# Module 1 — Peer Education
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 1.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m01-peer-education.html",
 "module_code": "M1",
 "module_slug": "peer-education",
 "lesson_slug": "m01-peer-education",
 "module_label": "Peer Educator · Module 1 of 19",
 "title": "Peer Education",
 "icon": "🤝",
 "duration": 60,

 "objectives": [
  ("Explain the concept and roles of peer education",
   "Eleza dhana na majukumu ya elimu ya rika",
   "Explain concept na roles za peer education"),
  ("Describe the qualities of an effective peer educator",
   "Eleza sifa za mwelimishaji rika bora",
   "Describe qualities za peer educator poa"),
  ("Apply communication skills for effective health education",
   "Tumia ujuzi wa mawasiliano kwa elimu bora ya afya",
   "Tumia communication skills kwa health education poa"),
  ("Select appropriate methods and tools for a peer session",
   "Chagua mbinu na zana zinazofaa kwa kipindi cha rika",
   "Chagua methods na tools sahihi kwa peer session"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Why would a young person believe you when they did not believe the nurse, the teacher or their parent?",
  "<strong>🔍 Swali Kubwa:</strong> Kwa nini kijana akuamini wewe wakati hakumwamini muuguzi, mwalimu au mzazi wake?",
  "<strong>🔍 Big Question:</strong> Kwa nini msee angekuamini wewe wakati hakuamini nurse, teacher ama mzazi wake?"),

 "slides": [

  # ── 1. Terminology ────────────────────────────────────────────────
  {"icon": "📖",
   "head": ("The Words We Use", "Maneno Tunayotumia", "Maneno Tunazotumia"),
   "blocks": [
    {"type": "p", "text": (
     "Peer education has a precise meaning. Before you can do it, you need to be clear what each part of it means.",
     "Elimu ya rika ina maana mahususi. Kabla ya kuifanya, unahitaji kuelewa kila sehemu yake inamaanisha nini.",
     "Peer education ina maana specific. Kabla ufanye, lazima uelewe kila part inamaanisha nini.")},
    {"type": "key_term", "term": ("🔑 Peer", "🔑 Rika", "🔑 Peer"), "text": (
     "A person who belongs to the same social group as another — similar age, background or experience.",
     "Mtu anayetoka kundi moja la kijamii na mwingine — umri, asili au uzoefu unaofanana.",
     "Msee wa group moja na wewe — same age, background ama experience.")},
    {"type": "key_term", "term": ("🔑 Education", "🔑 Elimu", "🔑 Education"), "text": (
     "The development of a person's knowledge, attitudes, beliefs or behaviour as a result of learning.",
     "Ukuzaji wa maarifa, mitazamo, imani au tabia ya mtu kutokana na kujifunza.",
     "Ku-develop knowledge, attitude, imani ama behaviour ya msee kutokana na kujifunza.")},
    {"type": "key_term", "term": ("🔑 Peer Education", "🔑 Elimu ya Rika", "🔑 Peer Education"), "text": (
     "The transfer of knowledge and skills to members of a social group by others within that same group.",
     "Uhamishaji wa maarifa na ujuzi kwa wanachama wa kundi la kijamii na wengine ndani ya kundi hilo hilo.",
     "Ku-transfer knowledge na skills kwa wasee wa group yako na wasee wengine wa group hiyo hiyo.")},
    {"type": "key_term", "term": ("🔑 Peer Educator", "🔑 Mwelimishaji Rika", "🔑 Peer Educator"), "text": (
     "A trained young person who gives information, guidance and support on health, rights and life skills to their peers in a way those peers can relate to.",
     "Kijana aliyefunzwa anayetoa taarifa, mwongozo na msaada kuhusu afya, haki na ujuzi wa maisha kwa wenzake kwa njia wanayoweza kuielewa.",
     "Kijana aliye-trained anayetoa info, guidance na support kuhusu health, rights na life skills kwa wasee wenzake kwa njia wanaweza ku-relate.")},
    {"type": "tip", "title": ("💡 Remember", "💡 Kumbuka", "💡 Remember"), "text": (
     " Peer educators are usually volunteers. You do this because you chose to, which is exactly why your peers trust it.",
     " Waelimishaji rika kwa kawaida ni wa kujitolea. Unafanya hivi kwa sababu ulichagua, na ndiyo maana wenzako wanaamini.",
     " Peer educators ni volunteers mostly. Unafanya hii kwa sababu ulichagua — na ndio maana wasee wanatrust.")},
   ]},

  # ── 2. Why it works ───────────────────────────────────────────────
  {"icon": "💡",
   "head": ("Why Peer Education Works", "Kwa Nini Elimu ya Rika Inafanya Kazi", "Kwa Nini Peer Education Inawork"),
   "blocks": [
    {"type": "p", "text": (
     "A young person will often tell a peer what they would never tell an adult. That is not a weakness in the health system — it is the opening peer education is built on.",
     "Kijana mara nyingi atamwambia rika kile ambacho hangemwambia mtu mzima kamwe. Hilo si udhaifu wa mfumo wa afya — ni mwanya ambao elimu ya rika imejengwa juu yake.",
     "Kijana atamwambia peer wake kitu ambacho hangemwambia mtu mzima. Hiyo si weakness ya health system — ni opening ambayo peer education imejengwa juu yake."),},
    {"type": "list", "items": [
     ("You speak the same language — including the words adults get wrong",
      "Mnazungumza lugha moja — pamoja na maneno ambayo watu wazima huyakosea",
      "Mnaspeak lugha moja — pamoja na maneno ambazo watu wazima huzikosea"),
     ("You are trusted because you are not in authority over anyone",
      "Unaaminika kwa sababu huna mamlaka juu ya mtu yeyote",
      "Unatrustiwa kwa sababu huna authority juu ya mtu"),
     ("You reach young people that clinics and schools never see",
      "Unawafikia vijana ambao kliniki na shule hazioni kamwe",
      "Unareach vijana ambao clinics na shule hawawaoni"),
     ("You are there on the day it happens, not at the next appointment",
      "Upo siku inapotokea, si kwenye miadi ijayo",
      "Uko siku inapohappen, si kwa appointment ijayo"),
    ]},
    {"type": "sheng", "text": (
     "Watu hawabadiliki kwa sababu wameambiwa ukweli. Wanabadilika wanapoona mtu wanayemwamini akiishi ule ukweli. Ndiyo kazi yako.",
     "Watu hawabadiliki kwa sababu wameambiwa ukweli. Hubadilika wanapomwona mtu wanayemwamini akiishi ukweli huo. Hiyo ndiyo kazi yako.",
     "Wasee hawachange kwa sababu wameambiwa ukweli. Wanachange wakiona msee wanamtrust akiishi huo ukweli. Hiyo ndio job yako.")},
   ]},

  # ── 3. Roles ──────────────────────────────────────────────────────
  {"icon": "🎯",
   "head": ("Your Roles and Responsibilities", "Majukumu Yako", "Roles na Responsibilities Zako"),
   "blocks": [
    {"type": "p", "text": (
     "A peer educator does six distinct jobs. Knowing which one you are doing at any moment keeps you inside your role.",
     "Mwelimishaji rika hufanya kazi sita tofauti. Kujua unayofanya wakati wowote kunakuweka ndani ya jukumu lako.",
     "Peer educator anafanya jobs sita tofauti. Kujua unafanya ipi kwa wakati wowote kunakuweka ndani ya role yako.")},
    {"type": "table",
     "headers": [("Role", "Jukumu", "Role"), ("What it looks like in practice", "Inavyoonekana kivitendo", "Inavyoonekana practically")],
     "rows": [
      [("Role model", "Mfano wa kuigwa", "Role model"),
       ("Live the behaviour you teach — peers watch what you do, not what you say",
        "Ishi tabia unayofundisha — wenzako huangalia unachofanya, si unachosema",
        "Ishi behaviour unayofundisha — wasee wanaangalia unachofanya, si unachosema")],
      [("Share accurate information", "Toa taarifa sahihi", "Share info sahihi"),
       ("Give correct adolescent health facts — and say 'I don't know' when you don't",
        "Toa ukweli sahihi wa afya ya vijana — na sema 'sijui' usipojua",
        "Toa facts sahihi za adolescent health — na useme 'sijui' usipojua")],
      [("Facilitate discussion", "Wezesha majadiliano", "Facilitate discussion"),
       ("Run one-to-one or group conversations on health issues",
        "Endesha mazungumzo ya mtu mmoja mmoja au ya kikundi kuhusu masuala ya afya",
        "Run one-on-one ama group conversations kuhusu health")],
      [("Support risk assessment", "Saidia kutathmini hatari", "Support risk assessment"),
       ("Help peers see their own risk and choose a safer path",
        "Wasaidie wenzako kuona hatari yao na kuchagua njia salama zaidi",
        "Saidia wasee waone risk yao na wachague njia safer")],
      [("Make referrals", "Toa rufaa", "Fanya referrals"),
       ("Connect peers to health services — and follow up that they arrived",
        "Waunganishe wenzako na huduma za afya — na fuatilia kwamba walifika",
        "Connect wasee na health services — na follow up kama walifika")],
      [("Record and report", "Rekodi na ripoti", "Record na report"),
       ("Document your sessions and referrals using the correct tools and channels",
        "Andika vipindi na rufaa zako kwa kutumia zana na njia sahihi",
        "Document sessions na referrals zako ukitumia tools na channels sahihi")],
     ]},
    {"type": "facilitator", "minutes": 10, "text": (
     "Ask the group: which of these six do you think you will find hardest? Most will say referral or record-keeping. Note their answers — you return to both in Module 16 and Module 18.",
     "Uliza kundi: ni lipi kati ya haya sita unadhani litakuwa gumu zaidi? Wengi watasema rufaa au kutunza kumbukumbu. Andika majibu yao — utarudi kwa yote mawili katika Moduli 16 na 18.",
     "Uliza group: ni ipi kati ya hizi sita unafikiri itakuwa ngumu zaidi? Wengi watasema referral ama record-keeping. Note majibu yao — utarudi kwa zote mbili kwa Module 16 na 18.")},
   ]},

  # ── 4. Qualities ──────────────────────────────────────────────────
  {"icon": "⭐",
   "head": ("Qualities of a Peer Educator", "Sifa za Mwelimishaji Rika", "Qualities za Peer Educator"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Confident and friendly</strong> — approachable, with a positive attitude",
      "<strong>Mwenye kujiamini na urafiki</strong> — anayefikika, mwenye mtazamo chanya",
      "<strong>Confident na friendly</strong> — approachable, na attitude poa"),
     ("<strong>Active and respected</strong> — trusted by peers and committed to the role",
      "<strong>Mwenye bidii na anayeheshimiwa</strong> — anayeaminika na wenzake na aliyejitolea",
      "<strong>Active na respected</strong> — anatrustiwa na wasee na amecommit kwa role"),
     ("<strong>Good listener and communicator</strong> — clear, engaging and empathetic",
      "<strong>Msikilizaji na mwasilianaji mzuri</strong> — wazi, mvutiaji na mwenye huruma",
      "<strong>Good listener na communicator</strong> — clear, engaging na empathetic"),
     ("<strong>Non-judgemental and open-minded</strong> — creates a safe, inclusive space",
      "<strong>Asiyehukumu na mwenye akili wazi</strong> — huunda nafasi salama, jumuishi",
      "<strong>Non-judgemental na open-minded</strong> — anacreate safe space kwa kila mtu"),
     ("<strong>A leader peers relate to</strong> — natural leader who speaks their language",
      "<strong>Kiongozi wenzake wanaomwelewa</strong> — kiongozi wa asili anayezungumza lugha yao",
      "<strong>Leader ambaye wasee wanamrelate</strong> — natural leader anaye-speak lugha yao"),
     ("<strong>Confidential</strong> — trustworthy with sensitive information",
      "<strong>Mwenye siri</strong> — anayeaminika na taarifa nyeti",
      "<strong>Confidential</strong> — anatrustiwa na sensitive info"),
    ]},
    {"type": "warn", "title": ("⚠️ The one that ends your work", "⚠️ Ile inayomaliza kazi yako", "⚠️ Ile inayoisha job yako"), "text": (
     " Break confidentiality once and it is over. Word travels faster than you do, and no peer will bring you anything real again. Confidentiality is not a nice quality — it is the licence to operate.",
     " Vunja usiri mara moja na imekwisha. Habari husafiri haraka kuliko wewe, na hakuna rika atakayekuletea jambo la kweli tena. Usiri si sifa nzuri tu — ni leseni ya kufanya kazi.",
     " Vunja confidentiality mara moja na imeisha. Story inatravel faster kuliko wewe, na hakuna msee atakuletea kitu real tena. Confidentiality si quality nzuri tu — ni licence ya kufanya hii job.")},
   ]},

  # ── 5. Communication ──────────────────────────────────────────────
  {"icon": "💬",
   "head": ("Communication That Helps — and Harms", "Mawasiliano Yanayosaidia na Yanayodhuru", "Communication Inayosaidia na Inayoharibu"),
   "blocks": [
    {"type": "table",
     "headers": [("✅ Improves communication", "✅ Huboresha mawasiliano", "✅ Inaboost communication"),
                 ("⚠️ Hinders communication", "⚠️ Huzuia mawasiliano", "⚠️ Inaharibu communication")],
     "rows": [
      [("Come prepared, warm and genuine", "Njoo umejiandaa, kwa ukarimu na ukweli", "Kuja umeprepare, warm na genuine"),
       ("Shouting, bad temper, lecturing", "Kupiga kelele, hasira, kuhubiri", "Kupiga kelele, temper mbaya, kulecture")],
      [("Listen actively — do not interrupt", "Sikiliza kwa makini — usikatize", "Listen actively — usiinterrupt"),
       ("Interrupting or looking bored", "Kukatiza au kuonekana umechoka", "Ku-interrupt ama kuonekana bored")],
      [("Be patient and non-judgmental", "Kuwa mvumilivu na usihukumu", "Kuwa patient na usijudge"),
       ("Checking your phone mid-conversation", "Kuangalia simu katikati ya mazungumzo", "Kucheki phone katikati ya story")],
      [("Use shared purpose and humour", "Tumia lengo la pamoja na ucheshi", "Tumia shared purpose na humour"),
       ("Talking too fast or using hard words", "Kuzungumza haraka mno au kutumia maneno magumu", "Ku-talk fast sana ama kutumia maneno ngumu")],
      [("Choose the right moment", "Chagua wakati mwafaka", "Chagua moment sahihi"),
       ("Body language that shuts people down", "Lugha ya mwili inayowafunga watu", "Body language inayoshut wasee down")],
     ]},
    {"type": "example", "title": ("🇰🇪 Wanjiru — Nakuru", "🇰🇪 Wanjiru — Nakuru", "🇰🇪 Wanjiru — Nakuru"), "text": (
     "Wanjiru, 19, is a peer educator. A girl started telling her about a problem at home, then stopped. Wanjiru realised she had been glancing at her phone. She put it face down, said 'sorry — I'm listening properly now', and waited. The girl started again, and that conversation ended in a referral that mattered.",
     "Wanjiru, miaka 19, ni mwelimishaji rika. Msichana alianza kumweleza tatizo la nyumbani, kisha akaacha. Wanjiru aligundua alikuwa akiangalia simu yake. Aliiweka chini, akasema 'samahani — sasa ninasikiliza vizuri', na akasubiri. Msichana alianza tena, na mazungumzo yale yalimalizika kwa rufaa ya maana.",
     "Wanjiru, 19, ni peer educator. Dem mmoja alianza kumwambia shida ya nyumbani, kisha akastop. Wanjiru aligundua alikuwa anacheki phone yake. Aliiweka chini, akasema 'pole — saa hii nasikiliza properly', na akangoja. Yule dem alianza tena, na hiyo story iliisha na referral ya maana.")},
   ]},

  # ── 6. Methods ────────────────────────────────────────────────────
  {"icon": "🧰",
   "head": ("Methods and Tools", "Mbinu na Zana", "Methods na Tools"),
   "blocks": [
    {"type": "p", "text": (
     "These are the four methods you use in a one-to-one meeting or a small group session.",
     "Hizi ni mbinu nne unazotumia katika mkutano wa mtu mmoja mmoja au kipindi cha kikundi kidogo.",
     "Hizi ndio methods nne unazotumia kwa one-on-one meeting ama small group session.")},
    {"type": "table",
     "headers": [("Method", "Mbinu", "Method"), ("Use it when", "Itumie wakati", "Itumie wakati")],
     "rows": [
      [("Illustrations", "Michoro", "Illustrations"),
       ("Pictures and visual aids — best where literacy varies",
        "Picha na vielelezo — bora pale kusoma kunatofautiana",
        "Pictures na visual aids — poa pale literacy inatofautiana")],
      [("Demonstration", "Maonyesho", "Demonstration"),
       ("Showing how something is done, such as correct condom use",
        "Kuonyesha jinsi kitu kinavyofanyika, kama matumizi sahihi ya kondomu",
        "Kuonyesha jinsi kitu kinafanywa, kama correct condom use")],
      [("Group discussion", "Majadiliano ya kikundi", "Group discussion"),
       ("Talking an issue through together — good for norms and attitudes",
        "Kujadili suala pamoja — nzuri kwa kanuni na mitazamo",
        "Ku-discuss issue pamoja — poa kwa norms na attitudes")],
      [("Role play", "Uigizaji", "Role play"),
       ("Acting out a scenario to rehearse a response before it is needed",
        "Kuigiza hali ili kufanya mazoezi ya jibu kabla halijahitajika",
        "Ku-act scenario ili u-rehearse response kabla ihitajike")],
     ]},
    {"type": "facilitator", "minutes": 15, "text": (
     "Split into pairs. Each pair picks one method and prepares a two-minute demonstration on any topic from this curriculum. Watch for the commonest error: turning a group discussion into a lecture.",
     "Gawanyeni katika jozi. Kila jozi ichague mbinu moja na iandae onyesho la dakika mbili kuhusu mada yoyote ya mtaala huu. Angalia kosa la kawaida zaidi: kugeuza majadiliano ya kikundi kuwa hotuba.",
     "Gawanyikeni pairs. Kila pair ichague method moja na i-prepare demo ya dakika mbili kuhusu topic yoyote ya hii curriculum. Angalia error ya kawaida: ku-turn group discussion kuwa lecture.")},
   ]},

  # ── 7. Boundaries ─────────────────────────────────────────────────
  {"icon": "🚧",
   "head": ("Know Where Your Role Ends", "Jua Jukumu Lako Linapoishia", "Jua Role Yako Inaishia Wapi"),
   "blocks": [
    {"type": "p", "text": (
     "The most damaging mistake a peer educator makes is not giving wrong information. It is trying to handle something that should have been referred.",
     "Kosa linalodhuru zaidi ambalo mwelimishaji rika hufanya si kutoa taarifa isiyo sahihi. Ni kujaribu kushughulikia jambo lililopaswa kupelekwa kwa mtaalamu.",
     "Mistake mbaya zaidi ambayo peer educator anafanya si kutoa info mbaya. Ni ku-try kuhandle kitu ambacho kilifaa ku-referiwa.")},
    {"type": "list", "items": [
     ("You are <strong>not</strong> a counsellor, a clinician or a police officer",
      "Wewe <strong>si</strong> mshauri, daktari au afisa wa polisi",
      "Wewe <strong>si</strong> counsellor, clinician ama polisi"),
     ("You do not diagnose, prescribe, or promise an outcome",
      "Hutambui ugonjwa, huagizi dawa, wala huahidi matokeo",
      "Hu-diagnose, hu-prescribe, wala huahidi outcome"),
     ("You refer, and you follow up that the referral landed",
      "Unatoa rufaa, na unafuatilia kwamba rufaa ilifika",
      "Una-refer, na una-follow up kama referral ilifika"),
     ("You never keep a disclosure of abuse or suicide to yourself",
      "Hutunzi siri ya ufichuzi wa unyanyasaji au kujiua",
      "Huwezi keep disclosure ya abuse ama suicide kwako"),
    ]},
    {"type": "warn", "title": ("⚠️ Escalate immediately", "⚠️ Peleka juu mara moja", "⚠️ Escalate immediately"), "text": (
     " Any mention of suicide, sexual abuse, or violence at home goes to your supervising adult the same day. Confidentiality protects private matters — it does not cover situations where someone is in danger.",
     " Kutajwa kwa kujiua, unyanyasaji wa kingono, au vurugu nyumbani kunaenda kwa mtu mzima anayekusimamia siku hiyo hiyo. Usiri hulinda mambo binafsi — haufuniki hali ambapo mtu yuko hatarini.",
     " Kutajwa kwa suicide, sexual abuse, ama violence nyumbani inaenda kwa msimamizi wako siku hiyo hiyo. Confidentiality inalinda private matters — haicovers situation ambapo mtu yuko hatarini.")},
   ]},

  # ── 8. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "Otieno, 17, is running his first group session in Kisumu. A boy asks a question about emergency contraception and Otieno is not sure of the answer.",
      "Otieno, miaka 17, anaendesha kipindi chake cha kwanza cha kikundi Kisumu. Mvulana anauliza swali kuhusu uzazi wa dharura na Otieno hana uhakika wa jibu.",
      "Otieno, 17, anarun first group session yake Kisumu. Mse mmoja anauliza question kuhusu emergency contraception na Otieno hana uhakika wa jibu."),
     "question": ("What should Otieno do?", "Otieno afanye nini?", "Otieno afanye nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Give his best guess so the group does not lose confidence in him",
                "Atoe kisio lake bora ili kikundi kisipoteze imani kwake",
                "Atoe guess yake bora ili group isipoteze confidence kwake"),
       "outcome": ("A confident wrong answer spreads further than a quiet correct one. If a peer acts on it and is harmed, that is on the session. Guessing also teaches the group that certainty matters more than accuracy.",
                   "Jibu lisilo sahihi lililotolewa kwa kujiamini husambaa mbali zaidi kuliko jibu sahihi la kimya. Rika akitenda kulingana nalo na akadhurika, hilo ni kosa la kipindi. Kubahatisha pia hufundisha kikundi kwamba kujiamini ni muhimu kuliko usahihi.",
                   "Wrong answer iliyotolewa kwa confidence inaspread mbali zaidi kuliko correct answer ya kimya. Msee akifanya kulingana nayo na adhurike, hiyo ni kosa la session. Ku-guess pia inafundisha group ati confidence ni muhimu kuliko accuracy.")},
      {"kind": "good",
       "text": ("Say he will find out and come back with the correct answer",
                "Aseme atatafuta na arudi na jibu sahihi",
                "Aseme ata-find out na arudi na jibu sahihi"),
       "outcome": ("Otieno said: 'Good question — I want to give you the right answer, not a guess. Let me check with the nurse and I'll bring it to the next session.' He did. The group trusted him more afterwards, not less. ✅",
                   "Otieno alisema: 'Swali zuri — nataka kukupa jibu sahihi, si kisio. Niulize muuguzi na nitaleta kipindi kijacho.' Alifanya hivyo. Kikundi kilimwamini zaidi baadaye, si kidogo. ✅",
                   "Otieno alisema: 'Question poa — nataka kukupa jibu sahihi, si guess. Niulize nurse na nitaleta next session.' Alifanya hivyo. Group ilimtrust more baadaye, si less. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "During a one-to-one, Faith tells her peer educator that her uncle has been touching her. She begs her not to tell anyone.",
      "Wakati wa mazungumzo ya faragha, Faith anamwambia mwelimishaji rika wake kwamba mjomba wake amekuwa akimgusa. Anamsihi asimwambie mtu yeyote.",
      "Wakati wa one-on-one, Faith anamwambia peer educator wake ati uncle wake amekuwa akimgusa. Anamplead asimwambie mtu."),
     "question": ("What must the peer educator do?", "Mwelimishaji rika lazima afanye nini?", "Peer educator lazima afanye nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Keep the promise — confidentiality is the peer educator's first rule",
                "Atimize ahadi — usiri ni sheria ya kwanza ya mwelimishaji rika",
                "A-keep promise — confidentiality ni rule ya kwanza ya peer educator"),
       "outcome": ("This is the mistake that causes the most harm. Confidentiality protects private information; it does not cover ongoing abuse. Staying silent leaves a child in danger and leaves the peer educator carrying something they cannot carry.",
                   "Hili ndilo kosa linalosababisha madhara makubwa zaidi. Usiri hulinda taarifa binafsi; haufuniki unyanyasaji unaoendelea. Kukaa kimya humwacha mtoto hatarini na humwacha mwelimishaji rika akibeba jambo asiloweza kubeba.",
                   "Hii ndio mistake inayosababisha harm kubwa zaidi. Confidentiality inalinda private info; haicovers abuse inayoendelea. Kukaa kimya inamwacha mtoto hatarini na inamwacha peer educator akibeba kitu hawezi kubeba.")},
      {"kind": "good",
       "text": ("Tell Faith gently that this one must be reported, and go with her to a trusted adult",
                "Amwambie Faith kwa upole kwamba hili lazima liripotiwe, na aende naye kwa mtu mzima anayeaminika",
                "Amwambie Faith kwa upole ati hii lazima i-reportiwe, na aende naye kwa mtu mzima wa kutrust"),
       "outcome": ("The peer educator said: 'I'm not going to gossip about this. But I can't keep this one to myself either, because you're not safe. I'll come with you.' Faith was angry at first — and safe afterwards. Going with her is the part that matters. ✅",
                   "Mwelimishaji rika alisema: 'Sitasengenya kuhusu hili. Lakini pia siwezi kulificha, kwa sababu hauko salama. Nitakuja nawe.' Faith alikasirika mwanzoni — na alikuwa salama baadaye. Kwenda naye ndiyo sehemu ya maana. ✅",
                   "Peer educator alisema: 'Sitagossip kuhusu hii. Lakini pia siwezi kuificha, kwa sababu hauko safe. Nitakuja na wewe.' Faith alikasirika mwanzoni — na akakuwa safe baadaye. Kwenda naye ndio part ya maana. ✅")},
     ]},
   ]},

  # ── 9. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Peer education builds trust, empowers peers and reaches hard-to-reach groups.",
      "Elimu ya rika hujenga imani, huwawezesha wenzako na hufikia makundi magumu kufikiwa.",
      "Peer education inajenga trust, ina-empower wasee na inareach groups ngumu kureach."),
     ("Peer educators are role models who share accurate information and link peers to services.",
      "Waelimishaji rika ni mifano ya kuigwa wanaotoa taarifa sahihi na kuwaunganisha wenzao na huduma.",
      "Peer educators ni role models wanaoshare info sahihi na ku-link wasee na services."),
     ("Effective peer educators are confident, approachable, non-judgmental and keep confidentiality.",
      "Waelimishaji rika bora wanajiamini, wanafikika, hawahukumu na wanatunza siri.",
      "Peer educators poa ni confident, approachable, non-judgmental na wanakeep confidentiality."),
     ("Knowing where your role ends is as important as knowing what it covers.",
      "Kujua jukumu lako linapoishia ni muhimu kama kujua linahusu nini.",
      "Kujua role yako inaishia wapi ni muhimu kama kujua inacover nini."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Hujaajiriwa kuwa daktari. Umeaminiwa kuwa daraja. Jua unachojua, kiri usichokijua, na uwafikishe watu upande wa pili.",
     "Hujaajiriwa kuwa daktari. Umeaminiwa kuwa daraja. Jua unachojua, kiri usichokijua, na uwafikishe watu upande wa pili.",
     "Haujahired kuwa daktari. Umetrustiwa kuwa bridge. Jua unachojua, admit usichojua, na uwafikishe wasee upande wa pili.")},
   ]},
 ],

 "quiz": [
  {"q": "Which of these best defines a 'peer' in peer education?",
   "options": ["Anyone younger than you",
               "A person from the same social group — similar age, background or experience",
               "A trained health worker assigned to your area",
               "A teacher who supervises youth activities"],
   "answer": "B",
   "explain": "A peer shares the social cohort — age, background or experience. That shared position is what makes the education work."},

  {"q": "Grace is asked a question in a session and does not know the answer. What should she do?",
   "options": ["Give her most likely guess confidently",
               "Change the subject to something she knows",
               "Say she will find out and return with the correct answer",
               "Tell the person to ask a nurse and move on"],
   "answer": "C",
   "explain": "Admitting the gap and following up builds trust. A confident wrong answer travels further than a quiet correct one."},

  {"q": "Which of the following are roles of a peer educator? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Serving as a role model",
               "Diagnosing illnesses and prescribing treatment",
               "Making referrals to health services",
               "Recording and reporting activity through the correct channels",
               "Facilitating discussion in one-to-one or group settings"],
   "answer": ["A", "C", "D", "E"],
   "explain": "Diagnosing and prescribing are clinical acts and sit outside the peer educator role."},

  {"q": "A peer discloses that she is being sexually abused at home and asks you to tell no one. What must you do?",
   "options": ["Keep it confidential — you promised",
               "Tell her gently it must be reported, and go with her to a trusted adult",
               "Tell the other peer educators so they can watch out for her",
               "Wait to see whether she mentions it again"],
   "answer": "B",
   "explain": "Confidentiality protects private information. It does not cover ongoing abuse, where a young person is in danger."},

  {"q": "Which method is most appropriate for rehearsing how to refuse an offer of alcohol?",
   "options": ["Illustration", "Role play", "A written test", "A lecture"],
   "answer": "B",
   "explain": "Role play rehearses the response before it is needed, which is exactly what refusal skills require."},

  {"q": "Which of these HINDER communication in a peer session? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Checking your phone while someone is speaking",
               "Allowing silence while a person gathers their thoughts",
               "Using difficult technical words",
               "Interrupting to correct a small detail",
               "Talking very fast to fit everything in"],
   "answer": ["A", "C", "D", "E"],
   "explain": "Silence is a tool, not a fault — it gives people room to speak. The other four all close a conversation down."},

  {"q": "Why are peer educators usually volunteers?",
   "options": ["Because the work requires no skill",
               "Because organisations cannot afford to pay them",
               "Because choosing the role freely is part of why peers trust it",
               "Because it is a legal requirement in Kenya"],
   "answer": "C",
   "explain": "The voluntary nature signals genuine commitment rather than obligation, which is part of the credibility."},

  {"q": "Which quality, if broken even once, most damages a peer educator's ability to work?",
   "options": ["Punctuality", "Confidentiality", "Public speaking skill", "Knowledge of anatomy"],
   "answer": "B",
   "explain": "Break confidentiality once and peers stop bringing you anything real. It is the licence to operate."},

  {"q": "Which of these are true of a good referral? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["It is recorded",
               "It ends the moment you hand over the phone number",
               "It is followed up to confirm the service was received",
               "It can be escalated or re-referred if the first attempt fails"],
   "answer": ["A", "C", "D"],
   "explain": "A referral is a deliberate hand-off with follow-up — not a phone number handed over."},

  {"q": "A peer educator notices a friend copying their healthy habits without being told to. Which role is at work?",
   "options": ["Record and report", "Role model", "Risk assessment", "Referral"],
   "answer": "B",
   "explain": "Peers watch what you do more closely than they listen to what you say. Modelling is the quietest and most powerful role."},
 ],
}
