# Module 2 — Adolescent Rights
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 2.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m02-adolescent-rights.html",
 "module_code": "M2",
 "module_slug": "adolescent-rights",
 "lesson_slug": "m02-adolescent-rights",
 "module_label": "Peer Educator · Module 2 of 19",
 "title": "Adolescent Rights",
 "icon": "⚖️",
 "duration": 60,

 "objectives": [
  ("Define rights in the context of adolescents",
   "Fafanua haki katika muktadha wa vijana",
   "Define rights kwa context ya vijana"),
  ("Identify the main national and international laws protecting adolescent rights in Kenya",
   "Tambua sheria kuu za kitaifa na kimataifa zinazolinda haki za vijana Kenya",
   "Tambua main national na international laws zinazolinda adolescent rights Kenya"),
  ("Explain the key rights and what they mean in everyday life",
   "Eleza haki kuu na maana yake katika maisha ya kila siku",
   "Explain key rights na maana yake kwa maisha ya kila siku"),
  ("Recognise common violations and know how to address them",
   "Tambua ukiukaji wa kawaida na ujue jinsi ya kuushughulikia",
   "Tambua common violations na ujue jinsi ya kuzi-address"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> A right you have never heard of protects you exactly as much as one you do not have. So whose job is it to tell you?",
  "<strong>🔍 Swali Kubwa:</strong> Haki ambayo hujawahi kuisikia inakulinda kwa kiasi kile kile cha ile usiyokuwa nayo. Basi ni kazi ya nani kukuambia?",
  "<strong>🔍 Big Question:</strong> Right ambayo hujawahi kuisikia inakulinda kwa kiasi kile kile cha ile usiyo nayo. So ni job ya nani kukuambia?"),

 "slides": [

  {"icon": "📖",
   "head": ("What Rights Actually Are", "Haki ni Nini Hasa", "Rights ni Nini Hasa"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Adolescent rights", "🔑 Haki za vijana", "🔑 Adolescent rights"), "text": (
     "The legal, social and ethical entitlements that protect and empower adolescents aged 10 to 19. They help young people grow, participate and thrive, while safeguarding them from harm.",
     "Stahili za kisheria, kijamii na kimaadili zinazolinda na kuwawezesha vijana wa miaka 10 hadi 19. Husaidia vijana kukua, kushiriki na kustawi, huku wakilindwa dhidi ya madhara.",
     "Legal, social na ethical entitlements zinazolinda na ku-empower vijana wa miaka 10 hadi 19. Zinasaidia vijana kukua, ku-participate na ku-thrive, huku wakilindwa dhidi ya harm.")},
    {"type": "p", "text": (
     "They are <strong>entitlements guaranteed by law</strong> — not favours granted by adults, and not privileges that can be withdrawn for bad behaviour. They rest on three principles: equality, dignity, and the best interests of the child.",
     "Ni <strong>stahili zinazohakikishwa na sheria</strong> — si upendeleo unaotolewa na watu wazima, wala si vibali vinavyoweza kuondolewa kwa tabia mbaya. Zinasimama kwenye kanuni tatu: usawa, hadhi, na maslahi bora ya mtoto.",
     "Ni <strong>entitlements zinazo-guaranteewa na sheria</strong> — si favours zinazotolewa na watu wazima, wala si privileges zinazoweza ku-withdrawiwa kwa bad behaviour. Zinasimama kwa principles tatu: equality, dignity, na best interests za mtoto.")},
    {"type": "warn", "title": ("⚠️ The distinction to hold onto", "⚠️ Tofauti ya kushikilia", "⚠️ Tofauti ya kushikilia"), "text": (
     " A privilege is something you earn and can lose. A right is something you have because you exist. If an adult ever frames a young person's health care, education or safety as something they must deserve, they have described a privilege — and that is not what the law says.",
     " Kibali ni kitu unachokipata na unaweza kukipoteza. Haki ni kitu unacho kwa sababu upo. Mtu mzima akiwahi kueleza huduma ya afya, elimu au usalama wa kijana kama kitu anachopaswa kustahili, ameeleza kibali — na si hivyo sheria inavyosema.",
     " Privilege ni kitu unachoi-earn na unaweza kuipoteza. Right ni kitu ulicho nacho kwa sababu upo. Mtu mzima akiwahi ku-frame health care, education ama safety ya kijana kama kitu anachofaa ku-deserve, ame-describe privilege — na si hivyo sheria inavyosema.")},
   ]},

  {"icon": "📜",
   "head": ("Where These Rights Come From", "Haki Hizi Zinatoka Wapi", "Hizi Rights Zinatoka Wapi"),
   "blocks": [
    {"type": "table",
     "headers": [("Framework", "Mfumo", "Framework"), ("What it does", "Inafanya nini", "Inafanya nini")],
     "rows": [
      [("<strong>Constitution of Kenya (2010)</strong>", "<strong>Katiba ya Kenya (2010)</strong>", "<strong>Constitution of Kenya (2010)</strong>"),
       ("The supreme law of Kenya. Sets out the rights every person holds, with specific protections for children.",
        "Sheria kuu ya Kenya. Inaainisha haki alizonazo kila mtu, na ulinzi mahususi kwa watoto.",
        "Supreme law ya Kenya. Ina-set out rights ambazo kila msee anazo, na specific protections kwa watoto.")],
      [("<strong>Children's Act (2022)</strong>", "<strong>Sheria ya Watoto (2022)</strong>", "<strong>Children's Act (2022)</strong>"),
       ("Kenya's national law on the care, protection and welfare of children — anyone under 18.",
        "Sheria ya kitaifa ya Kenya kuhusu malezi, ulinzi na ustawi wa watoto — yeyote chini ya miaka 18.",
        "National law ya Kenya kuhusu care, protection na welfare ya watoto — yeyote chini ya 18.")],
      [("<strong>UN Convention on the Rights of the Child (CRC, 1989)</strong>", "<strong>Mkataba wa UN wa Haki za Mtoto (CRC, 1989)</strong>", "<strong>UN Convention on the Rights of the Child (CRC, 1989)</strong>"),
       ("A global treaty covering children's civil, political, economic, social and cultural rights. <strong>Kenya has ratified it.</strong>",
        "Mkataba wa kimataifa unaohusu haki za kiraia, kisiasa, kiuchumi, kijamii na kitamaduni za watoto. <strong>Kenya imeuidhinisha.</strong>",
        "Global treaty inayocover civil, political, economic, social na cultural rights za watoto. <strong>Kenya ime-ratify.</strong>")],
      [("<strong>African Charter on the Rights and Welfare of the Child (ACRWC, 1990)</strong>", "<strong>Mkataba wa Afrika wa Haki na Ustawi wa Mtoto (ACRWC, 1990)</strong>", "<strong>African Charter on the Rights and Welfare of the Child (ACRWC, 1990)</strong>"),
       ("A regional treaty protecting African children, written for the African cultural context and <strong>expressly prohibiting harmful practices such as child marriage and FGM</strong>.",
        "Mkataba wa kikanda unaolinda watoto wa Afrika, ulioandikwa kwa muktadha wa kitamaduni wa Afrika na <strong>unaokataza waziwazi mila hatari kama ndoa za utotoni na ukeketaji</strong>.",
        "Regional treaty inayolinda watoto wa Afrika, iliyoandikwa kwa African cultural context na <strong>inayo-prohibit expressly harmful practices kama child marriage na FGM</strong>.")],
     ]},
    {"type": "tip", "title": ("💡 Why the African Charter matters in this conversation", "💡 Kwa nini Mkataba wa Afrika ni muhimu hapa", "💡 Kwa nini African Charter ni muhimu hapa"), "text": (
     " When someone defends FGM or child marriage as African tradition, the strongest answer is not a Western treaty — it is that African states wrote their own charter, in their own cultural context, and prohibited those practices themselves. That is a much harder argument to dismiss as foreign.",
     " Mtu anapotetea ukeketaji au ndoa za utotoni kama mila ya Kiafrika, jibu lenye nguvu zaidi si mkataba wa Magharibi — ni kwamba mataifa ya Afrika yaliandika mkataba wao wenyewe, katika muktadha wao wa kitamaduni, na yakakataza mila hizo wenyewe. Hiyo ni hoja ngumu zaidi kuipuuza kama ya kigeni.",
     " Msee anapo-defend FGM ama child marriage kama African tradition, answer yenye nguvu zaidi si Western treaty — ni ati African states ziliandika charter yao wenyewe, kwa cultural context yao, na zika-prohibit hizo practices wenyewe. Hiyo ni argument ngumu zaidi kui-dismiss kama ya kigeni.")},
   ]},

  {"icon": "🛡️",
   "head": ("The Seven Core Rights", "Haki Saba Kuu", "Rights Saba Kuu"),
   "blocks": [
    {"type": "table",
     "headers": [("Right", "Haki", "Right"), ("What it means day to day", "Maana yake kila siku", "Maana yake kila siku")],
     "rows": [
      [("Education", "Elimu", "Education"),
       ("Free and compulsory basic education, with support to keep adolescents in school.",
        "Elimu ya msingi bila malipo na ya lazima, pamoja na msaada wa kuwaweka vijana shuleni.",
        "Free na compulsory basic education, na support ya ku-keep vijana shuleni.")],
      [("Health", "Afya", "Health"),
       ("Access to general <em>and reproductive</em> health care, <strong>with privacy and confidentiality assured</strong>.",
        "Kupata huduma za afya kwa jumla <em>na za uzazi</em>, <strong>huku faragha na usiri vikihakikishwa</strong>.",
        "Access kwa general <em>na reproductive</em> health care, <strong>na privacy na confidentiality assured</strong>.")],
      [("Protection", "Ulinzi", "Protection"),
       ("Safety from abuse, neglect, exploitation, child marriage, FGM and hazardous work.",
        "Usalama dhidi ya unyanyasaji, kutelekezwa, unyonyaji, ndoa za utotoni, ukeketaji na kazi hatari.",
        "Safety kutoka abuse, neglect, exploitation, child marriage, FGM na hazardous work.")],
      [("Participation", "Ushiriki", "Participation"),
       ("Freedom to express views and take part in decisions that affect their own lives.",
        "Uhuru wa kutoa maoni na kushiriki katika maamuzi yanayoathiri maisha yao.",
        "Freedom ya ku-express views na ku-participate kwa decisions zinazoathiri maisha yao.")],
      [("Information", "Taarifa", "Information"),
       ("Access to accurate, age-appropriate and timely information — including about their own bodies.",
        "Kupata taarifa sahihi, zinazofaa umri na kwa wakati — ikiwemo kuhusu miili yao.",
        "Access kwa accurate, age-appropriate na timely info — ikiwemo kuhusu miili yao.")],
      [("Privacy", "Faragha", "Privacy"),
       ("Protection of personal information, dignity and personal space.",
        "Ulinzi wa taarifa binafsi, hadhi na nafasi binafsi.",
        "Protection ya personal info, dignity na personal space.")],
      [("Non-discrimination and parental care", "Kutobaguliwa na malezi", "Non-discrimination na parental care"),
       ("Equal treatment regardless of gender, disability, ethnicity or social status — and the right to parental care and guidance.",
        "Kutendewa sawa bila kujali jinsia, ulemavu, kabila au hadhi ya kijamii — na haki ya malezi na mwongozo wa wazazi.",
        "Equal treatment bila kujali gender, disability, ethnicity ama social status — na right ya parental care na guidance.")],
     ]},
    {"type": "sheng", "text": (
     "Angalia haki ya afya tena. Inasema 'faragha na usiri vimehakikishwa'. Hiyo si nyongeza — imeandikwa kwenye haki yenyewe.",
     "Angalia haki ya afya tena. Inasema 'faragha na usiri vimehakikishwa'. Hiyo si nyongeza — imeandikwa ndani ya haki yenyewe.",
     "Angalia right ya health tena. Inasema 'privacy na confidentiality assured'. Hiyo si add-on — imeandikwa ndani ya right yenyewe.")},
   ]},

  {"icon": "⚖️",
   "head": ("Rights Come With Responsibilities", "Haki Huja na Majukumu", "Rights Zinakuja na Responsibilities"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Respect the rights and dignity of others</strong> — your right ends where someone else's begins",
      "<strong>Heshimu haki na hadhi za wengine</strong> — haki yako inaishia pale ya mwingine inapoanza",
      "<strong>Respect rights na dignity za wengine</strong> — right yako inaishia pale ya mwingine inapoanza"),
     ("<strong>Use information and freedoms responsibly</strong>",
      "<strong>Tumia taarifa na uhuru kwa uwajibikaji</strong>",
      "<strong>Tumia info na freedoms responsibly</strong>"),
     ("<strong>Participate constructively</strong> in school, family and community life",
      "<strong>Shiriki kwa kujenga</strong> katika shule, familia na jamii",
      "<strong>Participate constructively</strong> kwa shule, family na community"),
     ("<strong>Avoid actions that harm yourself or others</strong>",
      "<strong>Epuka vitendo vinavyokudhuru wewe au wengine</strong>",
      "<strong>Avoid actions zinazokudhuru wewe ama wengine</strong>"),
     ("<strong>Know the laws and how to report violations</strong> — child protection offices, helplines",
      "<strong>Jua sheria na jinsi ya kuripoti ukiukaji</strong> — ofisi za ulinzi wa mtoto, simu za msaada",
      "<strong>Jua sheria na jinsi ya ku-report violations</strong> — child protection offices, helplines"),
     ("<strong>Engage in peer education and advocacy</strong> — which is exactly what you are training for",
      "<strong>Shiriki katika elimu ya rika na utetezi</strong> — ambayo ndiyo hasa unayofunzwa",
      "<strong>Engage kwa peer education na advocacy</strong> — ambayo ndio hasa unayo-trainiwa"),
     ("<strong>Work with parents, teachers and community leaders</strong> to promote rights",
      "<strong>Fanya kazi na wazazi, walimu na viongozi wa jamii</strong> kukuza haki",
      "<strong>Work na wazazi, teachers na community leaders</strong> ku-promote rights"),
    ]},
   ]},

  {"icon": "🚧",
   "head": ("Why Rights Fail in Practice", "Kwa Nini Haki Hushindwa Kivitendo", "Kwa Nini Rights Zina-fail Practically"),
   "blocks": [
    {"type": "p", "text": (
     "Every right listed above already exists in Kenyan law. These are the reasons that is not enough.",
     "Kila haki iliyoorodheshwa hapo juu tayari ipo katika sheria za Kenya. Hizi ndizo sababu hiyo haitoshi.",
     "Kila right iliyo-listiwa hapo juu tayari iko kwa sheria za Kenya. Hizi ndio sababu hiyo haitoshi.")},
    {"type": "list", "items": [
     ("<strong>Harmful practices</strong> such as child marriage and FGM continue despite being illegal",
      "<strong>Mila hatari</strong> kama ndoa za utotoni na ukeketaji zinaendelea licha ya kuwa haramu",
      "<strong>Harmful practices</strong> kama child marriage na FGM zinaendelea despite kuwa illegal"),
     ("<strong>Lack of awareness</strong> among adolescents and communities — the gap this module exists to close",
      "<strong>Ukosefu wa uelewa</strong> miongoni mwa vijana na jamii — pengo ambalo moduli hii ipo kulifunga",
      "<strong>Lack ya awareness</strong> kwa vijana na communities — gap ambayo hii module iko ku-close"),
     ("<strong>Barriers to services</strong> — stigma, cost, distance, and parental consent requirements",
      "<strong>Vizuizi vya huduma</strong> — unyanyapaa, gharama, umbali, na mahitaji ya ridhaa ya wazazi",
      "<strong>Barriers kwa services</strong> — stigma, cost, distance, na parental consent requirements"),
     ("<strong>Weak enforcement</strong> from limited resources and capacity",
      "<strong>Utekelezaji dhaifu</strong> kutokana na rasilimali na uwezo mdogo",
      "<strong>Weak enforcement</strong> kutokana na limited resources na capacity"),
     ("<strong>Poverty and inequality</strong> affecting access to education and health",
      "<strong>Umaskini na ukosefu wa usawa</strong> vinavyoathiri upatikanaji wa elimu na afya",
      "<strong>Poverty na inequality</strong> zinazoathiri access kwa education na health"),
     ("<strong>School dropout</strong> due to pregnancy or economic hardship",
      "<strong>Kuacha shule</strong> kutokana na ujauzito au ugumu wa kiuchumi",
      "<strong>School dropout</strong> kutokana na pregnancy ama economic hardship"),
     ("<strong>Peer pressure, exploitation, online abuse and cyberbullying</strong>",
      "<strong>Shinikizo la rika, unyonyaji, unyanyasaji mtandaoni na uonevu wa kimtandao</strong>",
      "<strong>Peer pressure, exploitation, online abuse na cyberbullying</strong>"),
    ]},
    {"type": "facilitator", "minutes": 12, "text": (
     "Take the seven rights and ask the group, for each one, whether it is actually available where they live — and if not, what specifically blocks it. Expect the health right to generate the most discussion, and expect 'they will tell my mother' to come up. That is a confidentiality failure, and it is nameable as one.",
     "Chukua haki saba na uulize kundi, kwa kila moja, kama inapatikana kweli wanakoishi — na kama hapana, ni nini hasa kinachoizuia. Tarajia haki ya afya kuzua majadiliano mengi zaidi, na tarajia 'watamwambia mama yangu' kujitokeza. Hiyo ni kushindwa kwa usiri, na inaweza kutajwa hivyo.",
     "Chukua rights saba na uulize group, kwa kila moja, kama inapatikana kweli wanakoishi — na kama hapana, ni nini hasa kinachoi-block. Expect health right i-generate discussion nyingi zaidi, na expect 'watamwambia mama yangu' kujitokeza. Hiyo ni confidentiality failure, na inaweza ku-namiwa hivyo.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A 16-year-old tells you she will not go to the clinic because the nurse knows her aunt and will tell the family what she came for.",
      "Msichana wa miaka 16 anakuambia hataenda kliniki kwa sababu muuguzi anamjua shangazi yake na atawaambia familia alichokuja kufanya.",
      "Dem wa miaka 16 anakuambia hataenda clinic kwa sababu nurse anamjua aunt wake na atawaambia family alichokuja kufanya."),
     "question": ("What is the right framing?", "Mfumo sahihi ni upi?", "Framing sahihi ni ipi?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell her she is probably imagining it and should go anyway",
                "Mwambie pengine anawaza tu na aende hata hivyo",
                "Mwambie pengine ana-imagine tu na aende anyway"),
       "outcome": ("Her fear is not imaginary — confidentiality failures are one of the listed barriers to services, and she has likely seen it happen to someone. Dismissing it teaches her that her concern is unserious, and she still does not go.",
                   "Hofu yake si ya kuwaza — kushindwa kwa usiri ni kimoja cha vizuizi vilivyoorodheshwa vya huduma, na huenda ameona likitokea kwa mtu. Kuipuuza kunamfundisha kwamba wasiwasi wake si wa dhati, na bado haendi.",
                   "Fear yake si ya ku-imagine — confidentiality failures ni moja ya listed barriers kwa services, na huenda ameona ikihappen kwa msee. Ku-dismiss kunamfundisha ati concern yake si serious, na bado haendi.")},
      {"kind": "good",
       "text": ("Name it as a rights violation, and help her find a service that will honour confidentiality",
                "Itaje kama ukiukaji wa haki, na umsaidie kupata huduma itakayoheshimu usiri",
                "I-name kama rights violation, na umsaidie kupata service itakayo-honour confidentiality"),
       "outcome": ("You said: 'What you're describing would be against the law, not just unkind — the right to health says privacy and confidentiality are guaranteed. Let's find you somewhere that keeps it, and I'll come.' Knowing it was a violation, rather than just bad luck, changed how she spoke about it. ✅",
                   "Ulisema: 'Unachoeleza kingekuwa kinyume cha sheria, si ukosefu wa fadhila tu — haki ya afya inasema faragha na usiri vimehakikishwa. Tutafute mahali panapoheshimu hilo, na nitakuja.' Kujua ni ukiukaji, si bahati mbaya tu, kulibadilisha jinsi alivyozungumza. ✅",
                   "Ulisema: 'Unachoi-describe kingekuwa kinyume cha sheria, si unkindness tu — right ya health inasema privacy na confidentiality zime-guaranteewa. Tutafute mahali panapoi-keep, na nitakuja.' Kujua ni violation, si bad luck tu, kuli-change jinsi alivyoongea.✅")},
     ]},
    {"type": "scenario",
     "context": (
      "An elder argues in a community meeting that talk of adolescent rights is a foreign idea being imposed on African families.",
      "Mzee anahoji katika mkutano wa jamii kwamba mazungumzo ya haki za vijana ni wazo la kigeni linalolazimishwa kwa familia za Kiafrika.",
      "Elder anaargue kwa community meeting ati story ya adolescent rights ni foreign idea inayo-imposiwa kwa African families."),
     "question": ("How do you answer?", "Unajibu vipi?", "Una-answer aje?"),
     "choices": [
      {"kind": "bad",
       "text": ("Cite the UN Convention and point out that Kenya ratified it",
                "Taja Mkataba wa UN na uonyeshe kwamba Kenya iliuidhinisha",
                "Cite UN Convention na uonyeshe ati Kenya ili-ratify"),
       "outcome": ("Answering 'this is foreign' with a UN treaty confirms his point in his own ears. He is not disputing the law's existence — he is disputing whose idea it was. You have to answer the actual objection.",
                   "Kujibu 'hii ni ya kigeni' kwa mkataba wa UN kunathibitisha hoja yake masikioni mwake. Hapingi kuwepo kwa sheria — anapinga wazo hilo lilikuwa la nani. Lazima ujibu pingamizi halisi.",
                   "Ku-answer 'hii ni ya kigeni' na UN treaty ina-confirm point yake kwa masikio yake. Hana-dispute existence ya sheria — ana-dispute wazo hilo lilikuwa la nani. Lazima u-answer objection halisi.")},
      {"kind": "good",
       "text": ("Point to the African Charter — African states wrote it themselves, in their own cultural context",
                "Onyesha Mkataba wa Afrika — mataifa ya Afrika yaliuandika wenyewe, katika muktadha wao wa kitamaduni",
                "Onyesha African Charter — African states ziliuandika wenyewe, kwa cultural context yao"),
       "outcome": ("You said: 'The African Charter on the Rights and Welfare of the Child was written by African states, for the African context, in 1990 — and they are the ones who prohibited child marriage and FGM in it. This is not something being brought here. It was written here.' He had not known that. ✅",
                   "Ulisema: 'Mkataba wa Afrika wa Haki na Ustawi wa Mtoto uliandikwa na mataifa ya Afrika, kwa muktadha wa Afrika, mwaka 1990 — na ndio waliokataza ndoa za utotoni na ukeketaji ndani yake. Hii si kitu kinacholetwa hapa. Kiliandikwa hapa.' Hakuwa amejua hilo. ✅",
                   "Ulisema: 'African Charter on the Rights and Welfare of the Child iliandikwa na African states, kwa African context, 1990 — na ndio waliokataza child marriage na FGM ndani yake. Hii si kitu kinacholetwa hapa. Iliandikwa hapa.' Hakuwa amejua hiyo. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Adolescent rights are enshrined in the Kenyan Constitution, national policy, and regional and international treaties Kenya has signed.",
      "Haki za vijana zimo katika Katiba ya Kenya, sera za kitaifa, na mikataba ya kikanda na kimataifa Kenya imetia saini.",
      "Adolescent rights ziko kwa Constitution ya Kenya, national policy, na regional na international treaties Kenya ime-sign."),
     ("Adolescents have rights to health, education, information, and privacy and confidentiality.",
      "Vijana wana haki za afya, elimu, taarifa, na faragha na usiri.",
      "Vijana wana rights za health, education, information, na privacy na confidentiality."),
     ("Rights, information and freedoms should be exercised responsibly.",
      "Haki, taarifa na uhuru vinapaswa kutumiwa kwa uwajibikaji.",
      "Rights, information na freedoms zinafaa kutumiwa responsibly."),
     ("Child marriage, FGM and hazardous work are violations, not traditions.",
      "Ndoa za utotoni, ukeketaji na kazi hatari ni ukiukaji, si mila.",
      "Child marriage, FGM na hazardous work ni violations, si traditions."),
     ("Knowing where to report a violation is part of knowing your rights.",
      "Kujua wapi kuripoti ukiukaji ni sehemu ya kujua haki zako.",
      "Kujua wapi ku-report violation ni part ya kujua rights zako."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Haki isiyojulikana ni haki isiyotumika. Kazi yako si kutunga sheria — ni kuhakikisha watu wanajua zilizopo tayari.",
     "Haki isiyojulikana ni haki isiyotumika. Kazi yako si kutunga sheria — ni kuhakikisha watu wanajua zilizopo tayari.",
     "Right isiyojulikana ni right isiyotumika. Job yako si ku-make sheria — ni kuhakikisha wasee wanajua zilizopo tayari.")},
   ]},
 ],

 "quiz": [
  {"q": "What is the difference between a right and a privilege?",
   "options": ["There is none",
               "A privilege is earned and can be lost; a right is held because you exist",
               "Rights apply only to adults",
               "Privileges are protected by law, rights are not"],
   "answer": "B",
   "explain": "If an adult frames health care, education or safety as something a young person must deserve, they have described a privilege — and that is not what the law says."},

  {"q": "Which age range does the curriculum define as adolescent for the purposes of these rights?",
   "options": ["10 to 19", "15 to 24", "12 to 18", "10 to 24"],
   "answer": "A",
   "explain": "10–19 is adolescent, 15–24 is youth, and 10–24 together is 'adolescents and young people'."},

  {"q": "Which frameworks protect adolescent rights in Kenya? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["The Constitution of Kenya (2010)",
               "The Children's Act (2022)",
               "The UN Convention on the Rights of the Child (1989)",
               "The African Charter on the Rights and Welfare of the Child (1990)",
               "The Kenyan Highway Code"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Kenya has ratified the CRC, and the African Charter was written specifically for the African cultural context."},

  {"q": "The right to health specifically guarantees what alongside access to care?",
   "options": ["Free transport", "Privacy and confidentiality",
               "Parental attendance", "A choice of clinician"],
   "answer": "B",
   "explain": "It is written into the right itself, not added on — which is why a clinic that tells a young person's family is committing a violation."},

  {"q": "An elder says adolescent rights are a foreign idea. What is the strongest answer?",
   "options": ["Cite the UN Convention",
               "Point to the African Charter, written by African states for the African context in 1990",
               "Say tradition does not matter",
               "Avoid the argument"],
   "answer": "B",
   "explain": "Answering 'this is foreign' with a UN treaty confirms his point. African states prohibited child marriage and FGM in their own charter."},

  {"q": "Which are responsibilities that accompany adolescent rights? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Respect the rights and dignity of others",
               "Use information and freedoms responsibly",
               "Know the laws and how to report violations",
               "Engage in peer education and advocacy",
               "Obey any instruction from an adult"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Rights are not conditional on obedience. Your right ends where someone else's begins — that is the actual limit."},

  {"q": "Which are barriers to adolescents accessing services? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Stigma", "Cost", "Distance", "Parental consent requirements", "The law forbidding it"],
   "answer": ["A", "B", "C", "D"],
   "explain": "The law grants the right — these four are what stop it working in practice."},

  {"q": "Which right covers freedom to express views and take part in decisions affecting one's own life?",
   "options": ["Right to Information", "Right to Participation", "Right to Privacy", "Right to Protection"],
   "answer": "B",
   "explain": "It is the right most often overlooked, and the one M18's 'nothing for us, without us' depends on."},

  {"q": "A girl fears the nurse will tell her aunt what she came for. What should a peer educator do?",
   "options": ["Tell her she is imagining it",
               "Name it as a rights violation and help her find a service that honours confidentiality",
               "Advise her not to go",
               "Tell her family first"],
   "answer": "B",
   "explain": "Her fear is not imaginary — confidentiality failure is a listed barrier. Knowing it is a violation rather than bad luck changes how she can speak about it."},

  {"q": "What does the curriculum say about child marriage and FGM?",
   "options": ["They are cultural matters outside the law",
               "They are violations, expressly prohibited — including by the African Charter",
               "They are permitted with parental consent",
               "They only concern girls over 16"],
   "answer": "B",
   "explain": "The African Charter prohibits them specifically, and the right to protection covers abuse, neglect, exploitation, child marriage, FGM and hazardous work."},
 ],
}
