# Module 3 — Growth and Development
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 3.
# Trilingual: English / Kiswahili / Sheng.
#
# Anatomy and puberty content is kept clinical and factual, as the deck does.

LESSON = {
 "file": "m03-growth-and-development.html",
 "module_code": "M3",
 "module_slug": "growth-and-development",
 "lesson_slug": "m03-growth-and-development",
 "module_label": "Peer Educator · Module 3 of 19",
 "title": "Growth and Development",
 "icon": "🌱",
 "duration": 60,

 "objectives": [
  ("Describe the stages of adolescence and the age categories used",
   "Eleza hatua za ujana na makundi ya umri yanayotumika",
   "Describe stages za adolescence na age categories zinazotumika"),
  ("Explain the physical and biological changes of puberty in boys and girls",
   "Eleza mabadiliko ya kimwili na kibiolojia ya ubalehe kwa wavulana na wasichana",
   "Explain physical na biological changes za puberty kwa wavulana na wasichana"),
  ("Describe the social and emotional changes at each stage",
   "Eleza mabadiliko ya kijamii na kihisia katika kila hatua",
   "Describe social na emotional changes kwa kila stage"),
  ("Explain menstruation and how to manage it safely",
   "Eleza hedhi na jinsi ya kuidhibiti kwa usalama",
   "Explain menstruation na jinsi ya kui-manage safely"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Nearly every young person believes their own body is developing wrongly. Where does that belief come from, if the changes are universal?",
  "<strong>🔍 Swali Kubwa:</strong> Karibu kila kijana anaamini mwili wake unakua vibaya. Imani hiyo inatoka wapi, kama mabadiliko ni ya kila mtu?",
  "<strong>🔍 Big Question:</strong> Karibu kila kijana anaamini mwili wake unakua vibaya. Hiyo belief inatoka wapi, kama changes ni za kila msee?"),

 "slides": [

  {"icon": "📖",
   "head": ("The Stages and the Words", "Hatua na Maneno", "Stages na Maneno"),
   "blocks": [
    {"type": "p", "text": (
     "Adolescence is the transition from childhood to adulthood. It involves physical, psychological and social maturity — three processes that do not run at the same speed, which is where most of the confusion comes from.",
     "Ujana ni mpito kutoka utotoni hadi utu uzima. Unahusisha ukomavu wa kimwili, kisaikolojia na kijamii — michakato mitatu isiyokwenda kwa kasi moja, ndipo mkanganyiko mwingi unapotoka.",
     "Adolescence ni transition kutoka utotoni hadi utu uzima. Ina-involve physical, psychological na social maturity — processes tatu zisizoenda kwa speed moja, ndipo confusion nyingi inapotoka.")},
    {"type": "table",
     "headers": [("Category", "Kundi", "Category"), ("Ages", "Umri", "Ages")],
     "rows": [
      [("Adolescent", "Kijana (balehe)", "Adolescent"), ("10–19", "10–19", "10–19")],
      [("Youth", "Kijana (vijana)", "Youth"), ("15–24", "15–24", "15–24")],
      [("Adolescents and Young People (AYP)", "Vijana na Watu Wazima Vijana", "Adolescents and Young People (AYP)"), ("10–24", "10–24", "10–24")],
     ]},
    {"type": "table",
     "headers": [("Stage", "Hatua", "Stage"), ("Ages", "Umri", "Ages"), ("Character of the stage", "Sifa ya hatua", "Character ya stage")],
     "rows": [
      [("Early adolescence", "Ujana wa mapema", "Early adolescence"), ("10–13", "10–13", "10–13"),
       ("Growth spurt begins; sexual maturation starts; increased interest in one's own anatomy; anxieties about size and normality begin.",
        "Ukuaji wa haraka huanza; ukomavu wa kingono huanza; hamu ya kujua mwili wako huongezeka; wasiwasi kuhusu ukubwa na ukawaida huanza.",
        "Growth spurt inaanza; sexual maturation inaanza; interest kwa anatomy yako inaongezeka; anxieties kuhusu size na normality zinaanza.")],
      [("Middle adolescence", "Ujana wa kati", "Middle adolescence"), ("14–16", "14–16", "14–16"),
       ("Stronger sense of identity; relates more strongly to the peer group; more reflective thought; transitioning between dependence and independence.",
        "Hisia imara zaidi ya utambulisho; huhusiana zaidi na kundi la rika; fikra za kutafakari zaidi; kuvuka kati ya kutegemea na kujitegemea.",
        "Stronger sense ya identity; ana-relate zaidi na peer group; more reflective thought; ku-transition kati ya dependence na independence.")],
      [("Late adolescence", "Ujana wa mwisho", "Late adolescence"), ("17–19", "17–19", "17–19"),
       ("The body fills out into adult form; ideas and opinions settle into a distinct identity; focus shifts to intimacy, stable relationships, plans and commitments.",
        "Mwili hukamilika katika umbo la utu uzima; mawazo na maoni hutulia katika utambulisho tofauti; umakini huhamia kwenye ukaribu, mahusiano thabiti, mipango na ahadi.",
        "Mwili unakamilika kwa adult form; ideas na opinions zinatulia kwa distinct identity; focus inahamia kwa intimacy, stable relationships, plans na commitments.")],
     ]},
   ]},

  {"icon": "🧬",
   "head": ("Physical and Biological Changes", "Mabadiliko ya Kimwili na Kibiolojia", "Physical na Biological Changes"),
   "blocks": [
    {"type": "table",
     "headers": [("In boys", "Kwa wavulana", "Kwa wavulana"), ("In girls", "Kwa wasichana", "Kwa wasichana"), ("In both", "Kwa wote", "Kwa wote")],
     "rows": [
      [("Shoulders broaden", "Mabega hupanuka", "Shoulders zinapanuka"),
       ("Body becomes rounder and more womanly", "Mwili huwa wa mviringo zaidi na wa kike", "Mwili unakuwa rounder na more womanly"),
       ("Voice changes — boys' voices 'break', girls' deepen", "Sauti hubadilika — sauti za wavulana 'huvunjika', za wasichana huzidi kuwa nzito", "Voice ina-change — voices za wavulana zina-'break', za wasichana zinakuwa deeper")],
      [("Facial hair appears", "Nywele za uso hujitokeza", "Facial hair inajitokeza"),
       ("Breast enlargement", "Kukua kwa matiti", "Breast enlargement"),
       ("Hair growth in the armpits and around the sex organs", "Ukuaji wa nywele kwapani na kuzunguka viungo vya uzazi", "Hair growth kwapani na kuzunguka sex organs")],
      [("Some parts — especially hands and feet — grow faster than others", "Baadhi ya sehemu — hasa mikono na miguu — hukua haraka kuliko nyingine", "Baadhi ya parts — hasa mikono na miguu — zinakua faster kuliko zingine"),
       ("Hip enlargement", "Kupanuka kwa nyonga", "Hip enlargement"),
       ("Skin problems such as acne may develop", "Matatizo ya ngozi kama chunusi yanaweza kujitokeza", "Skin problems kama acne zinaweza ku-develop")],
      [("Muscular and skeletal growth", "Ukuaji wa misuli na mifupa", "Muscular na skeletal growth"),
       ("Menarche — the onset of menstruation — and increased vaginal moisture", "Hedhi ya kwanza — kuanza kwa hedhi — na unyevu ulioongezeka ukeni", "Menarche — kuanza kwa periods — na increased vaginal moisture"),
       ("Growth in height and weight — the adolescent growth spurt", "Ukuaji wa urefu na uzito — ukuaji wa haraka wa ujana", "Growth ya height na weight — adolescent growth spurt")],
      [("Lengthening and widening of the penis; enlargement of the testicles; sperm production, ejaculation, erections and wet dreams", "Kurefuka na kupanuka kwa uume; kukua kwa korodani; utengenezaji wa mbegu, kumwaga, kusimama na ndoto za usiku", "Kurefuka na kupanuka kwa penis; kukua kwa testicles; sperm production, ejaculation, erections na wet dreams"),
       ("", "", ""),
       ("Genital organs enlarge; perspiration increases and body odour may appear", "Viungo vya uzazi hukua; jasho huongezeka na harufu ya mwili inaweza kujitokeza", "Genital organs zinakua; perspiration inaongezeka na body odour inaweza kujitokeza")],
     ]},
    {"type": "warn", "title": ("⚠️ The answer to the Big Question", "⚠️ Jibu la Swali Kubwa", "⚠️ Jibu la Big Question"), "text": (
     " Every one of these changes arrives at a <strong>different age for every person</strong>, and each young person only ever sees their own body from the inside while seeing everyone else's from the outside. That asymmetry — not any real abnormality — is what convinces almost every adolescent that something is wrong with them. Saying so out loud is one of the most useful things a peer educator does.",
     " Kila moja ya mabadiliko haya hufika kwa <strong>umri tofauti kwa kila mtu</strong>, na kila kijana huuona mwili wake kutoka ndani tu huku akiwaona wengine kutoka nje. Tofauti hiyo — si kasoro yoyote halisi — ndiyo inayomshawishi karibu kila kijana kwamba kuna kitu kibaya kwake. Kusema hivyo kwa sauti ni kimoja cha vitu vyenye manufaa zaidi anavyofanya mwelimishaji rika.",
     " Kila moja ya hizi changes inafika kwa <strong>age tofauti kwa kila msee</strong>, na kila kijana anauona mwili wake kutoka ndani tu huku akiwaona wengine kutoka nje. Hiyo asymmetry — si abnormality yoyote real — ndio inayo-convince karibu kila kijana ati kuna kitu kibaya kwake. Kusema hivyo kwa sauti ni kimoja cha vitu vyenye manufaa zaidi anavyofanya peer educator.")},
   ]},

  {"icon": "💭",
   "head": ("Social and Emotional Changes", "Mabadiliko ya Kijamii na Kihisia", "Social na Emotional Changes"),
   "blocks": [
    {"type": "p", "text": (
     "The mind changes as much as the body, and on its own timetable. Knowing which stage a peer is in tells you what will actually reach them.",
     "Akili hubadilika kama mwili, na kwa ratiba yake. Kujua kijana yuko hatua ipi kunakuambia ni nini kitakachomfikia kweli.",
     "Akili ina-change kama mwili, na kwa timetable yake. Kujua msee yuko stage ipi kunakuambia ni nini kitakachomfikia kweli.")},
    {"type": "table",
     "headers": [("10–13 Early", "10–13 Mapema", "10–13 Early"), ("14–16 Middle", "14–16 Kati", "14–16 Middle"), ("17–19 Late", "17–19 Mwisho", "17–19 Late")],
     "rows": [
      [("Self-exploration and self-evaluation begins",
        "Kujichunguza na kujitathmini huanza",
        "Self-exploration na self-evaluation inaanza"),
       ("Relates more strongly to the peer group than to family",
        "Huhusiana zaidi na kundi la rika kuliko familia",
        "Ana-relate zaidi na peer group kuliko family"),
       ("Ideas and opinions become settled — a distinct identity",
        "Mawazo na maoni hutulia — utambulisho tofauti",
        "Ideas na opinions zinatulia — distinct identity")],
      [("Anxieties and questions about the size and normality of one's own body",
        "Wasiwasi na maswali kuhusu ukubwa na ukawaida wa mwili wake",
        "Anxieties na questions kuhusu size na normality ya mwili wake"),
       ("More reflective thought — able to consider consequences",
        "Fikra za kutafakari zaidi — anaweza kuzingatia matokeo",
        "More reflective thought — anaweza ku-consider consequences"),
       ("Focus on intimacy and forming stable relationships",
        "Umakini kwenye ukaribu na kuunda mahusiano thabiti",
        "Focus kwa intimacy na kuunda stable relationships")],
      [("Increased interest in sexual anatomy",
        "Hamu iliyoongezeka kuhusu viungo vya uzazi",
        "Increased interest kwa sexual anatomy"),
       ("Transitioning between dependence and independence — the source of most conflict at home",
        "Kuvuka kati ya kutegemea na kujitegemea — chanzo cha migogoro mingi nyumbani",
        "Ku-transition kati ya dependence na independence — source ya conflict nyingi nyumbani"),
       ("Plans for the future, and commitments",
        "Mipango ya baadaye, na ahadi",
        "Plans za future, na commitments")],
     ]},
    {"type": "tip", "title": ("💡 Use the stage to choose the approach", "💡 Tumia hatua kuchagua mbinu", "💡 Tumia stage ku-choose approach"), "text": (
     " A 12-year-old wants to know whether they are normal. A 15-year-old wants to know what their friends think. An 18-year-old wants to know how this fits their plans. The same information, delivered without regard to the stage, lands on only one of them.",
     " Mwenye miaka 12 anataka kujua kama yuko sawa. Mwenye miaka 15 anataka kujua marafiki zake wanafikiri nini. Mwenye miaka 18 anataka kujua hili linaendanaje na mipango yake. Taarifa ile ile, ikitolewa bila kujali hatua, humfikia mmoja tu kati yao.",
     " Msee wa 12 anataka kujua kama yuko normal. Msee wa 15 anataka kujua friends wake wanafikiri nini. Msee wa 18 anataka kujua hii ina-fit aje plans zake. Info ile ile, ikitolewa bila kujali stage, ina-land kwa mmoja tu kati yao.")},
   ]},

  {"icon": "♂️",
   "head": ("Sperm Production and Semenarche", "Utengenezaji wa Mbegu na Semenarche", "Sperm Production na Semenarche"),
   "blocks": [
    {"type": "list", "items": [
     ("Sperm production begins in the testes when a boy reaches puberty, helped by the hormone testosterone",
      "Utengenezaji wa mbegu huanza kwenye korodani mvulana anapofikia ubalehe, kwa msaada wa homoni ya testosterone",
      "Sperm production inaanza kwa testes mvulana anapofika puberty, kwa msaada wa hormone testosterone"),
     ("Once ready, sperm is stored in the <strong>epididymis</strong> for further maturation",
      "Ikiwa tayari, mbegu huhifadhiwa kwenye <strong>epididymis</strong> kwa ukomavu zaidi",
      "Ikiwa ready, sperm ina-storiwa kwa <strong>epididymis</strong> kwa maturation zaidi"),
     ("<strong>Ejaculation</strong> is the release of semen, occurring during sexual arousal or in wet dreams",
      "<strong>Kumwaga</strong> ni kutolewa kwa shahawa, kunakotokea wakati wa msisimko wa kingono au katika ndoto za usiku",
      "<strong>Ejaculation</strong> ni ku-release semen, inayohappen wakati wa sexual arousal ama kwa wet dreams"),
     ("<strong>Semenarche</strong> — the first ejaculation — happens between about ages 11 and 15. It is a normal puberty milestone.",
      "<strong>Semenarche</strong> — kumwaga kwa kwanza — hutokea kati ya takriban miaka 11 na 15. Ni hatua ya kawaida ya ubalehe.",
      "<strong>Semenarche</strong> — first ejaculation — inahappen kati ya karibu miaka 11 na 15. Ni normal puberty milestone."),
     ("Eating healthily and staying active supports healthy sperm production",
      "Kula vizuri na kuwa na shughuli huunga mkono utengenezaji bora wa mbegu",
      "Kukula healthy na kuwa active kuna-support healthy sperm production"),
    ]},
    {"type": "warn", "title": ("⚠️ Wet dreams are not a problem to be solved", "⚠️ Ndoto za usiku si tatizo la kutatuliwa", "⚠️ Wet dreams si problem ya ku-solviwa"), "text": (
     " Boys often arrive believing a wet dream means something is wrong, or that they have done something shameful. It is a normal, involuntary milestone — say so directly. The shame around it is what stops boys asking any question about their bodies at all.",
     " Wavulana mara nyingi hufika wakiamini ndoto ya usiku inamaanisha kuna kitu kibaya, au kwamba wamefanya jambo la aibu. Ni hatua ya kawaida, isiyo ya hiari — sema hivyo moja kwa moja. Aibu kuihusu ndiyo inayozuia wavulana kuuliza swali lolote kuhusu miili yao.",
     " Wavulana mara nyingi wanafika wakiamini wet dream inamaanisha kuna kitu kibaya, ama ati wamefanya kitu cha aibu. Ni normal, involuntary milestone — sema hivyo directly. Aibu kuihusu ndio inayozuia wavulana kuuliza question yoyote kuhusu miili yao.")},
   ]},

  {"icon": "♀️",
   "head": ("Menarche and Menstruation", "Hedhi ya Kwanza na Hedhi", "Menarche na Menstruation"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Menarche", "🔑 Hedhi ya kwanza", "🔑 Menarche"), "text": (
     "The first menstrual period, usually occurring between ages 9 and 17.",
     "Hedhi ya kwanza, kwa kawaida hutokea kati ya miaka 9 na 17.",
     "First period, kwa kawaida inahappen kati ya miaka 9 na 17.")},
    {"type": "key_term", "term": ("🔑 Menstruation", "🔑 Hedhi", "🔑 Menstruation"), "text": (
     "The monthly shedding of blood and tissue from the womb, through the vagina.",
     "Kumwagika kwa kila mwezi kwa damu na tishu kutoka tumbo la uzazi, kupitia uke.",
     "Monthly shedding ya damu na tissue kutoka womb, kupitia vagina.")},
    {"type": "p", "text": (
     "<strong>Common problems during menstruation:</strong> weakness, dizziness, nausea, abdominal cramps, headaches, backache, breast pain, pimples, mood swings, irritability and tiredness.",
     "<strong>Matatizo ya kawaida wakati wa hedhi:</strong> udhaifu, kizunguzungu, kichefuchefu, maumivu ya tumbo, maumivu ya kichwa, maumivu ya mgongo, maumivu ya matiti, chunusi, mabadiliko ya hisia, kukasirika haraka na uchovu.",
     "<strong>Common problems wakati wa periods:</strong> udhaifu, dizziness, nausea, abdominal cramps, headaches, backache, breast pain, pimples, mood swings, irritability na tiredness.")},
    {"type": "table",
     "headers": [("Managing cramps", "Kudhibiti maumivu", "Ku-manage cramps"), ("Using and disposing of sanitary products", "Kutumia na kutupa bidhaa za usafi", "Kutumia na kutupa sanitary products")],
     "rows": [
      [("Use a hot water bottle on the lower abdomen — making sure the water is not hot enough to burn",
        "Tumia chupa ya maji moto kwenye tumbo la chini — ukihakikisha maji si moto wa kuunguza",
        "Tumia hot water bottle kwa lower abdomen — ukihakikisha maji si moto wa kuunguza"),
       ("Change pads or cloths every few hours",
        "Badilisha pedi au vitambaa kila baada ya saa chache",
        "Badilisha pads ama vitambaa kila baada ya masaa machache")],
      [("Keep the body active with some exercise",
        "Weka mwili na shughuli kwa mazoezi kidogo",
        "Weka mwili active na exercise kidogo"),
       ("Wrap and dispose in bins, or wash reusable cloths and sun-dry them",
        "Funga na utupe kwenye vyombo, au osha vitambaa vinavyotumika tena na uvikaushe juani",
        "Wrap na u-dispose kwa bins, ama osha reusable cloths na u-sun-dry")],
      [("On the most painful days, painkillers as advised by a clinician",
        "Siku za maumivu makali zaidi, dawa za maumivu kama zilivyoshauriwa na daktari",
        "Siku za pain kali zaidi, painkillers kama zilivyo-advisiwa na daktari"),
       ("<strong>Safe disposal prevents both infection and pollution</strong>",
        "<strong>Kutupa kwa usalama huzuia maambukizi na uchafuzi</strong>",
        "<strong>Safe disposal ina-prevent infection na pollution</strong>")],
      [("Regular check-ups, to monitor blood levels",
        "Vipimo vya kawaida, kufuatilia viwango vya damu",
        "Regular check-ups, ku-monitor blood levels"),
       ("<strong>Seek medical help if pain is persistent</strong>",
        "<strong>Tafuta msaada wa daktari kama maumivu yanaendelea</strong>",
        "<strong>Tafuta medical help kama pain inaendelea</strong>")],
     ]},
    {"type": "facilitator", "minutes": 10, "text": (
     "Teach this to mixed groups, not girls only. Boys who understand menstruation stop making it a source of teasing, and that single change does more for girls' school attendance than any supply of pads. If the group is uncomfortable, name that too — discomfort is what the silence is made of.",
     "Fundisha hili kwa makundi mchanganyiko, si wasichana peke yao. Wavulana wanaoelewa hedhi huacha kuifanya chanzo cha kuchekwa, na mabadiliko hayo moja hufanya zaidi kwa mahudhurio ya wasichana shuleni kuliko ugavi wowote wa pedi. Kama kundi lina wasiwasi, litaje hilo pia — wasiwasi ndicho ukimya umeundwa nacho.",
     "Fundisha hii kwa mixed groups, si wasichana peke yao. Wavulana wanaoelewa periods wanaacha kuifanya source ya teasing, na hiyo change moja inafanya zaidi kwa school attendance ya wasichana kuliko supply yoyote ya pads. Kama group ina discomfort, i-name pia — discomfort ndio silence ime-madiwa nacho.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A 13-year-old boy tells you quietly that he thinks something is wrong with him because his friends are taller and their voices have changed and his have not.",
      "Mvulana wa miaka 13 anakuambia kwa utulivu kwamba anadhani kuna kitu kibaya kwake kwa sababu marafiki zake ni warefu na sauti zao zimebadilika na yake haijabadilika.",
      "Mse wa miaka 13 anakuambia kwa utulivu ati anafikiri kuna kitu kibaya kwake kwa sababu friends wake ni warefu na voices zao zime-change na yake haija-change."),
     "question": ("What do you tell him?", "Unamwambia nini?", "Unamwambia nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell him not to compare himself to others and he will be fine",
                "Mwambie asijilinganishe na wengine na atakuwa sawa",
                "Mwambie asijilinganishe na wengine na atakuwa poa"),
       "outcome": ("Sound advice that answers nothing. He asked a factual question about his body and received an instruction about his attitude. He will not ask again — and the actual fact, that puberty starts anywhere between 10 and 15, would have settled it in one sentence.",
                   "Ushauri mzuri usiojibu chochote. Aliuliza swali la ukweli kuhusu mwili wake na akapokea agizo kuhusu mtazamo wake. Hatauliza tena — na ukweli halisi, kwamba ubalehe huanza mahali popote kati ya miaka 10 na 15, ungelimaliza kwa sentensi moja.",
                   "Advice nzuri isiyo-answer kitu. Aliuliza factual question kuhusu mwili wake na aka-receive instruction kuhusu attitude yake. Hatauliza tena — na fact halisi, ati puberty inaanza mahali popote kati ya miaka 10 na 15, ingeli-settle kwa sentence moja.")},
      {"kind": "good",
       "text": ("Give him the actual timings, and name the comparison trap explicitly",
                "Mpe nyakati halisi, na utaje mtego wa kulinganisha waziwazi",
                "Mpe timings halisi, na u-name comparison trap explicitly"),
       "outcome": ("You said: 'Puberty starts anywhere from about ten to fifteen — your friends started earlier, that's all. And here's the thing nobody tells you: you only see your own body from the inside and everyone else's from the outside, so it always looks like you're the odd one. You're not.' He visibly relaxed. ✅",
                   "Ulisema: 'Ubalehe huanza kutoka takriban miaka kumi hadi kumi na tano — marafiki zako walianza mapema, ndiyo yote. Na hili ndilo hakuna anayekuambia: unauona mwili wako kutoka ndani tu na wa wengine kutoka nje, kwa hivyo daima inaonekana wewe ndiye tofauti. Sio.' Alitulia dhahiri. ✅",
                   "Ulisema: 'Puberty inaanza kutoka karibu miaka kumi hadi fifteen — friends wako walianza mapema, ndio yote. Na hii ndio hakuna msee anakuambia: unauona mwili wako kutoka ndani tu na wa wengine kutoka nje, so daima inaonekana wewe ndio odd one. Hauko.' Ali-relax dhahiri. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "In a mixed session, boys start laughing when menstruation is mentioned. Two girls go quiet and look down.",
      "Katika kipindi mchanganyiko, wavulana wanaanza kucheka hedhi inapotajwa. Wasichana wawili wananyamaza na kuinamisha vichwa.",
      "Kwa mixed session, wavulana wanaanza kucheka periods zinapotajwa. Madem wawili wana-quiet na kuinamisha vichwa."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Split the group and teach menstruation to the girls separately",
                "Gawanya kundi na uwafundishe wasichana hedhi peke yao",
                "Split group na uwafundishe madem periods peke yao"),
       "outcome": ("Separating confirms that this is a shameful, female-only subject — which is the belief that made them laugh. The boys leave never having learned it, and go on teasing. Girls miss school over exactly this.",
                   "Kutenganisha kunathibitisha kwamba hili ni suala la aibu, la wanawake peke yao — ambayo ndiyo imani iliyowafanya wacheke. Wavulana huondoka bila kujifunza, na wanaendelea kuchekesha. Wasichana hukosa shule kwa sababu hii hasa.",
                   "Ku-separate kuna-confirm ati hii ni shameful, female-only subject — ambayo ndio belief iliyowafanya wacheke. Wavulana wanaondoka bila kujifunza, na wanaendelea ku-tease. Madem wana-miss shule kwa sababu hii hasa.")},
      {"kind": "good",
       "text": ("Keep the group together, name the laughter, and teach it as ordinary biology",
                "Weka kundi pamoja, taja kicheko, na ufundishe kama biolojia ya kawaida",
                "Weka group pamoja, name hicho kicheko, na ufundishe kama ordinary biology"),
       "outcome": ("You said: 'That laugh is why girls miss school. Half this room will menstruate and the other half will have daughters, sisters and wives who do. This is biology, same as the voice breaking we just covered.' The laughing stopped, and a boy asked a real question. ✅",
                   "Ulisema: 'Kicheko hicho ndiyo sababu wasichana hukosa shule. Nusu ya chumba hiki watapata hedhi na nusu nyingine watakuwa na mabinti, dada na wake watakaopata. Hii ni biolojia, sawa na sauti kuvunjika tuliyoieleza sasa hivi.' Kicheko kilikoma, na mvulana akauliza swali halisi. ✅",
                   "Ulisema: 'Hicho kicheko ndio sababu madem wana-miss shule. Nusu ya hii room watapata periods na nusu nyingine watakuwa na madem, sisters na wake watakaopata. Hii ni biology, sawa na voice kuvunjika tuliyo-cover saa hii.' Kicheko kili-stop, na mse akauliza real question. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Adolescence is the transition from childhood to adulthood, ages 10 to 19, with physical, emotional and social change.",
      "Ujana ni mpito kutoka utotoni hadi utu uzima, miaka 10 hadi 19, wenye mabadiliko ya kimwili, kihisia na kijamii.",
      "Adolescence ni transition kutoka utotoni hadi utu uzima, miaka 10 hadi 19, na physical, emotional na social change."),
     ("Physical changes include growth spurts, body shape change, hair growth, acne, body odour and sexual maturity — menarche in girls, sperm production and semenarche in boys.",
      "Mabadiliko ya kimwili ni pamoja na ukuaji wa haraka, mabadiliko ya umbo, ukuaji wa nywele, chunusi, harufu ya mwili na ukomavu wa kingono — hedhi ya kwanza kwa wasichana, utengenezaji wa mbegu na semenarche kwa wavulana.",
      "Physical changes ni pamoja na growth spurts, body shape change, hair growth, acne, body odour na sexual maturity — menarche kwa wasichana, sperm production na semenarche kwa wavulana."),
     ("Social and emotional changes include mood swings, desire for independence, peer influence, curiosity and questioning authority.",
      "Mabadiliko ya kijamii na kihisia ni pamoja na mabadiliko ya hisia, hamu ya kujitegemea, ushawishi wa rika, udadisi na kuhoji mamlaka.",
      "Social na emotional changes ni pamoja na mood swings, hamu ya independence, peer influence, curiosity na ku-question authority."),
     ("There is no single normal. Every change arrives at a different age for every person.",
      "Hakuna ukawaida mmoja. Kila badiliko hufika kwa umri tofauti kwa kila mtu.",
      "Hakuna normal moja. Kila change inafika kwa age tofauti kwa kila msee."),
     ("Good menstrual hygiene means clean pads or cloths, changing regularly, washing daily and safe disposal.",
      "Usafi mzuri wa hedhi ni pedi au vitambaa safi, kubadilisha mara kwa mara, kuosha kila siku na kutupa kwa usalama.",
      "Good menstrual hygiene ni clean pads ama cloths, kubadilisha regularly, kuosha kila siku na safe disposal."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Hakuna kijana anayeamini yuko wa kawaida. Kazi yako ni kuwaambia ukweli mmoja rahisi: hakuna ratiba moja, na wote wanahisi hivyo hivyo.",
     "Hakuna kijana anayeamini yuko wa kawaida. Kazi yako ni kuwaambia ukweli mmoja rahisi: hakuna ratiba moja, na wote wanahisi hivyo hivyo.",
     "Hakuna kijana anayeamini yuko normal. Job yako ni kuwaambia ukweli mmoja rahisi: hakuna timetable moja, na wote wanafeel hivyo hivyo.")},
   ]},
 ],

 "quiz": [
  {"q": "Which ages does the curriculum define as 'adolescent'?",
   "options": ["10–19", "15–24", "10–24", "13–18"],
   "answer": "A",
   "explain": "15–24 is youth, and 10–24 together is 'adolescents and young people' (AYP)."},

  {"q": "What are the three stages of adolescence?",
   "options": ["Early 10–13, middle 14–16, late 17–19",
               "Early 10–12, middle 13–15, late 16–19",
               "Early 12–14, middle 15–17, late 18–20",
               "There are only two stages"],
   "answer": "A",
   "explain": "Knowing the stage tells you what will actually reach a peer — a 12-year-old asks whether they are normal, an 18-year-old asks how it fits their plans."},

  {"q": "Which changes happen in BOTH boys and girls? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Voice changes", "Hair growth in armpits and around sex organs",
               "Acne may develop", "Increased perspiration and body odour", "Breast enlargement"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Boys' voices 'break' and girls' deepen — both change. Breast enlargement is listed under girls."},

  {"q": "What is semenarche?",
   "options": ["The start of sperm production",
               "The first ejaculation, usually between ages 11 and 15 — a normal puberty milestone",
               "A medical condition requiring treatment",
               "The male equivalent of menopause"],
   "answer": "B",
   "explain": "Boys often arrive believing a wet dream means something is wrong. Saying directly that it is normal and involuntary is what allows them to ask anything else."},

  {"q": "Where is sperm stored after it is produced?",
   "options": ["The testes", "The epididymis", "The prostate", "The bladder"],
   "answer": "B",
   "explain": "It is produced in the testes with the help of testosterone, then stored in the epididymis for further maturation."},

  {"q": "At what ages does menarche usually occur?",
   "options": ["Between 5 and 9", "Between 9 and 17", "Between 15 and 20", "Always at 12"],
   "answer": "B",
   "explain": "The wide range is the point — there is no single normal, which is exactly what most adolescents need to hear."},

  {"q": "Which are ways to manage menstrual cramps per the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["A hot water bottle on the lower abdomen, not hot enough to burn",
               "Some exercise to keep the body active",
               "Painkillers as advised by a clinician on the most painful days",
               "Regular check-ups to monitor blood levels",
               "Avoiding all food during the period"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Persistent pain should be seen by a clinician rather than endured as normal."},

  {"q": "Why does nearly every adolescent believe their body is developing wrongly?",
   "options": ["Most bodies do develop abnormally",
               "They see their own body from the inside and everyone else's from the outside, while every change arrives at a different age",
               "Because of poor nutrition",
               "Because puberty is unpredictable in Kenya specifically"],
   "answer": "B",
   "explain": "That asymmetry, not any real abnormality, is the source — and saying so out loud is one of the most useful things a peer educator does."},

  {"q": "Boys laugh when menstruation is mentioned in a mixed session. What is the best response?",
   "options": ["Split the group and teach the girls separately",
               "Keep the group together, name the laughter, and teach it as ordinary biology",
               "Skip the topic",
               "Ask the boys to leave"],
   "answer": "B",
   "explain": "Separating confirms it is a shameful, female-only subject — the very belief that caused the laughing. Girls miss school over exactly this."},

  {"q": "What characterises middle adolescence (14–16)?",
   "options": ["The body fills out into adult form",
               "Stronger identity, relating strongly to the peer group, and transitioning between dependence and independence",
               "Sexual maturation begins",
               "Plans for the future and commitments"],
   "answer": "B",
   "explain": "That dependence–independence transition is the source of most conflict at home during these years."},
 ],
}
