# Module 4 — Personal Hygiene and Sanitation
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 4.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m04-personal-hygiene.html",
 "module_code": "M4",
 "module_slug": "personal-hygiene",
 "lesson_slug": "m04-personal-hygiene",
 "module_label": "Peer Educator · Module 4 of 19",
 "title": "Personal Hygiene and Sanitation",
 "icon": "🧼",
 "duration": 45,

 "objectives": [
  ("Define personal hygiene and sanitation",
   "Fafanua usafi wa mwili na mazingira",
   "Define personal hygiene na sanitation"),
  ("Identify daily hygiene practices and their benefits",
   "Tambua mazoea ya usafi ya kila siku na faida zake",
   "Tambua daily hygiene practices na benefits zake"),
  ("Demonstrate correct bathing, brushing and handwashing",
   "Onyesha kuoga, kupiga mswaki na kunawa mikono kwa usahihi",
   "Onyesha correct bathing, brushing na handwashing"),
  ("Identify common conditions linked to poor hygiene",
   "Tambua hali za kawaida zinazohusiana na usafi duni",
   "Tambua conditions za kawaida zinazohusiana na poor hygiene"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Handwashing is free, takes twenty seconds, and everyone already knows about it. So why does it still not happen?",
  "<strong>🔍 Swali Kubwa:</strong> Kunawa mikono ni bure, kunachukua sekunde ishirini, na kila mtu tayari anajua. Basi kwa nini bado hakufanyiki?",
  "<strong>🔍 Big Question:</strong> Ku-wash hands ni free, inachukua seconds ishirini, na kila msee tayari anajua. So kwa nini bado hai-happen?"),

 "slides": [

  {"icon": "📖",
   "head": ("What Hygiene Is, and Why It Matters", "Usafi ni Nini, na Kwa Nini ni Muhimu", "Hygiene ni Nini, na Kwa Nini ni Muhimu"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Personal hygiene", "🔑 Usafi wa mwili", "🔑 Personal hygiene"), "text": (
     "The daily practices that keep the body clean and healthy.",
     "Mazoea ya kila siku yanayoweka mwili safi na wenye afya.",
     "Daily practices zinazoweka mwili safi na wenye afya.")},
    {"type": "list", "items": [
     ("<strong>It shows respect</strong> — for yourself and for the people around you",
      "<strong>Huonyesha heshima</strong> — kwako na kwa watu waliokuzunguka",
      "<strong>Inaonyesha respect</strong> — kwako na kwa wasee waliokuzunguka"),
     ("<strong>It boosts confidence and self-esteem</strong> — which matters more at this age than at any other",
      "<strong>Huongeza kujiamini na kujithamini</strong> — jambo muhimu zaidi katika umri huu kuliko mwingine wowote",
      "<strong>Inaboost confidence na self-esteem</strong> — kitu muhimu zaidi kwa hii age kuliko nyingine yoyote"),
     ("<strong>It helps build better relationships</strong>",
      "<strong>Husaidia kujenga mahusiano bora</strong>",
      "<strong>Inasaidia kujenga better relationships</strong>"),
     ("<strong>It prevents illness and the spread of germs</strong>",
      "<strong>Huzuia magonjwa na kuenea kwa vijidudu</strong>",
      "<strong>Ina-prevent illness na kuenea kwa germs</strong>"),
     ("<strong>It protects community health</strong> — hygiene is never only a private matter",
      "<strong>Hulinda afya ya jamii</strong> — usafi si jambo binafsi peke yake kamwe",
      "<strong>Inalinda community health</strong> — hygiene si private matter peke yake kamwe"),
    ]},
    {"type": "tip", "title": ("💡 Puberty changes the requirement", "💡 Ubalehe hubadilisha hitaji", "💡 Puberty inabadilisha requirement"), "text": (
     " Sweat glands become active, skin becomes oilier, and body odour appears where it did not exist before. A young person is not being careless — their body genuinely changed, and nobody told them the routine had to change with it. Say that plainly; it removes a lot of embarrassment.",
     " Tezi za jasho huanza kufanya kazi, ngozi huwa na mafuta zaidi, na harufu ya mwili hujitokeza pasipokuwepo awali. Kijana si mzembe — mwili wake ulibadilika kweli, na hakuna aliyemwambia kwamba utaratibu nao ulipaswa kubadilika. Sema hivyo wazi; kunaondoa aibu nyingi.",
     " Sweat glands zinaanza kufanya kazi, ngozi inakuwa na mafuta zaidi, na body odour inajitokeza pasipokuwepo awali. Kijana si careless — mwili wake uli-change kweli, na hakuna aliyemwambia ati routine nayo ilifaa ku-change. Sema hivyo wazi; inaondoa aibu nyingi.")},
   ]},

  {"icon": "🚿",
   "head": ("The Daily Routine", "Utaratibu wa Kila Siku", "Daily Routine"),
   "blocks": [
    {"type": "table",
     "headers": [("Practice", "Zoezi", "Practice"), ("How to do it properly", "Jinsi ya kufanya vizuri", "Jinsi ya kufanya vizuri")],
     "rows": [
      [("Bathing", "Kuoga", "Bathing"),
       ("Daily, with soap, paying attention to armpits, groin and feet — the areas where sweat and bacteria collect. Change into clean underwear afterwards.",
        "Kila siku, kwa sabuni, ukizingatia kwapa, sehemu za siri na miguu — maeneo ambapo jasho na bakteria hukusanyika. Vaa chupi safi baadaye.",
        "Kila siku, na sabuni, ukizingatia kwapa, groin na miguu — areas ambapo jasho na bacteria zinakusanyika. Vaa chupi safi baadaye.")],
      [("Brushing teeth", "Kupiga mswaki", "Brushing teeth"),
       ("Twice a day, morning and before bed, for about two minutes. Brush the gum line and the tongue, not just the front surfaces.",
        "Mara mbili kwa siku, asubuhi na kabla ya kulala, kwa takriban dakika mbili. Piga mswaki mstari wa fizi na ulimi, si nyuso za mbele tu.",
        "Mara mbili kwa siku, asubuhi na kabla ya kulala, kwa karibu dakika mbili. Piga mswaki gum line na ulimi, si front surfaces tu.")],
      [("Handwashing", "Kunawa mikono", "Handwashing"),
       ("With soap and running water, rubbing all surfaces — palms, backs, between fingers, thumbs and nails — for about twenty seconds.",
        "Kwa sabuni na maji yanayotiririka, ukisugua nyuso zote — viganja, migongo, kati ya vidole, gumba na kucha — kwa takriban sekunde ishirini.",
        "Na sabuni na running water, ukisugua surfaces zote — palms, backs, kati ya vidole, thumbs na nails — kwa karibu seconds ishirini.")],
     ]},
    {"type": "warn", "title": ("⚠️ Water alone is not handwashing", "⚠️ Maji peke yake si kunawa mikono", "⚠️ Maji peke yake si handwashing"), "text": (
     " Rinsing with water shifts visible dirt and leaves most germs in place. Soap is what lifts them off the skin so the water can carry them away. If soap is genuinely unavailable, ash works — but water alone does not.",
     " Kusuuza kwa maji huondoa uchafu unaoonekana na huacha vijidudu vingi mahali pake. Sabuni ndiyo inayoviondoa kwenye ngozi ili maji yaviondoe. Kama sabuni haipatikani kabisa, jivu hufanya kazi — lakini maji peke yake hayafanyi.",
     " Ku-rinse na maji inaondoa uchafu unaoonekana na inaacha germs nyingi mahali pake. Sabuni ndio inayo-lift kutoka ngozi ili maji yaziondoe. Kama sabuni haipatikani kabisa, jivu inawork — lakini maji peke yake hai-work.")},
   ]},

  {"icon": "🖐️",
   "head": ("The Five Critical Handwashing Times", "Nyakati Tano Muhimu za Kunawa Mikono", "Times Tano Muhimu za Handwashing"),
   "blocks": [
    {"type": "p", "text": (
     "Washing at random moments achieves little. These five are where transmission actually happens — which is why the curriculum names them specifically.",
     "Kunawa nyakati zisizo maalum hakusaidii sana. Hizi tano ndipo maambukizi hutokea hasa — ndiyo maana mtaala unazitaja hasa.",
     "Ku-wash kwa random moments haisaidii sana. Hizi tano ndio mahali transmission inahappen hasa — ndio maana curriculum inazi-name specifically.")},
    {"type": "list", "ordered": True, "items": [
     ("<strong>After defecation</strong>", "<strong>Baada ya kwenda haja kubwa</strong>", "<strong>Baada ya kwenda haja kubwa</strong>"),
     ("<strong>After handling faeces</strong> — including cleaning a child",
      "<strong>Baada ya kushika kinyesi</strong> — ikiwemo kumsafisha mtoto",
      "<strong>Baada ya kushika kinyesi</strong> — ikiwemo kum-clean mtoto"),
     ("<strong>After cleaning the environment</strong>",
      "<strong>Baada ya kusafisha mazingira</strong>",
      "<strong>Baada ya ku-clean environment</strong>"),
     ("<strong>Before preparing food</strong>",
      "<strong>Kabla ya kuandaa chakula</strong>",
      "<strong>Kabla ya ku-prepare chakula</strong>"),
     ("<strong>Before eating food</strong>",
      "<strong>Kabla ya kula chakula</strong>",
      "<strong>Kabla ya kukula chakula</strong>"),
    ]},
    {"type": "tip", "title": ("💡 The answer to the Big Question", "💡 Jibu la Swali Kubwa", "💡 Jibu la Big Question"), "text": (
     " Handwashing fails not from ignorance but from friction — no soap at the latrine, no water point near the kitchen, no habit attached to the moment. Fixing the place is more effective than repeating the message. Ask your group where the soap actually is in their school.",
     " Kunawa mikono hushindwa si kwa ujinga bali kwa ugumu — hakuna sabuni chooni, hakuna maji karibu na jikoni, hakuna mazoea yaliyoshikamana na wakati huo. Kurekebisha mahali kuna ufanisi zaidi kuliko kurudia ujumbe. Uliza kundi lako sabuni iko wapi hasa shuleni kwao.",
     " Handwashing ina-fail si kwa ignorance ni kwa friction — hakuna sabuni chooni, hakuna water point karibu na jikoni, hakuna habit iliyo-attachiwa kwa huo moment. Ku-fix mahali ina effectiveness zaidi kuliko kurudia message. Uliza group yako sabuni iko wapi hasa shuleni kwao.")},
    {"type": "facilitator", "minutes": 10, "text": (
     "Run the three demonstrations — bathing (over clothes or with a diagram), brushing, and handwashing. For handwashing, have everyone do it with you and count the twenty seconds aloud. Watching is not learning; doing it once with the group is.",
     "Endesha maonyesho matatu — kuoga (juu ya nguo au kwa mchoro), kupiga mswaki, na kunawa mikono. Kwa kunawa mikono, waache wote wafanye nawe na uhesabu sekunde ishirini kwa sauti. Kuangalia si kujifunza; kufanya mara moja na kundi ndiko.",
     "Run demos tatu — bathing (juu ya nguo ama na diagram), brushing, na handwashing. Kwa handwashing, wacha wote wafanye na wewe na u-count seconds ishirini kwa sauti. Ku-watch si kujifunza; kufanya mara moja na group ndio.")},
   ]},

  {"icon": "🦠",
   "head": ("What Poor Hygiene Causes", "Usafi Duni Husababisha Nini", "Poor Hygiene Inasababisha Nini"),
   "blocks": [
    {"type": "table",
     "headers": [("Area", "Eneo", "Area"), ("Common conditions", "Hali za kawaida", "Common conditions")],
     "rows": [
      [("Hands and food", "Mikono na chakula", "Hands na chakula"),
       ("Diarrhoeal illness, typhoid, cholera, and intestinal worms — all spread by the faecal-oral route the five critical times are designed to break.",
        "Magonjwa ya kuhara, homa ya matumbo, kipindupindu, na minyoo — yote huenea kwa njia ya kinyesi-mdomo ambayo nyakati tano muhimu zimeundwa kuikatiza.",
        "Diarrhoeal illness, typhoid, cholera, na intestinal worms — zote zinaspread kwa faecal-oral route ambayo times tano muhimu zime-designiwa kui-break.")],
      [("Skin", "Ngozi", "Skin"),
       ("Scabies, ringworm, boils and other skin infections — often spread by sharing towels, bedding or clothing.",
        "Upele, choano, majipu na maambukizi mengine ya ngozi — mara nyingi huenea kwa kushiriki taulo, matandiko au nguo.",
        "Scabies, ringworm, boils na skin infections zingine — mara nyingi zinaspread kwa kushare towels, bedding ama nguo.")],
      [("Mouth", "Mdomo", "Mouth"),
       ("Tooth decay, gum disease and persistent bad breath.",
        "Kuoza kwa meno, ugonjwa wa fizi na harufu mbaya ya kinywa inayoendelea.",
        "Tooth decay, gum disease na persistent bad breath.")],
      [("Eyes", "Macho", "Eyes"),
       ("Conjunctivitis and trachoma, where face-washing is infrequent.",
        "Ugonjwa wa macho na trakoma, pale kuosha uso kunapokuwa nadra.",
        "Conjunctivitis na trachoma, pale kuosha uso kunapokuwa rare.")],
     ]},
    {"type": "warn", "title": ("⚠️ Seek care early", "⚠️ Tafuta huduma mapema", "⚠️ Tafuta care early"), "text": (
     " Any sign of infection — a spreading rash, a wound that will not close, persistent diarrhoea, an inflamed eye — should be seen at a health facility at the earliest opportunity. Most of these are simple to treat early and difficult later.",
     " Dalili yoyote ya maambukizi — upele unaosambaa, jeraha lisilofunga, kuhara kunakoendelea, jicho lililovimba — inapaswa kuonwa kituoni cha afya haraka iwezekanavyo. Mengi ya haya ni rahisi kutibu mapema na magumu baadaye.",
     " Sign yoyote ya infection — rash inayo-spread, wound isiyo-close, persistent diarrhoea, jicho lililovimba — inafaa kuonwa kwa health facility haraka iwezekanavyo. Mengi ya haya ni rahisi ku-treat early na ngumu baadaye.")},
   ]},

  {"icon": "🩸",
   "head": ("Menstrual Hygiene", "Usafi Wakati wa Hedhi", "Menstrual Hygiene"),
   "blocks": [
    {"type": "p", "text": (
     "Menstrual hygiene is a health and dignity issue, not a private embarrassment. A peer educator who can discuss it calmly, in a mixed group, changes what is sayable in that school.",
     "Usafi wakati wa hedhi ni suala la afya na hadhi, si aibu ya faragha. Mwelimishaji rika anayeweza kulijadili kwa utulivu, katika kundi mchanganyiko, hubadilisha kinachoweza kusemwa shuleni humo.",
     "Menstrual hygiene ni health na dignity issue, si private embarrassment. Peer educator anayeweza kui-discuss kwa utulivu, kwa mixed group, ana-change kinachoweza kusemwa kwa hiyo shule.")},
    {"type": "list", "items": [
     ("Change pads or cloths every four to six hours, or more often on heavy days",
      "Badilisha pedi au vitambaa kila saa nne hadi sita, au mara nyingi zaidi siku za wingi",
      "Badilisha pads ama vitambaa kila masaa manne hadi sita, ama mara nyingi zaidi siku za wingi"),
     ("Wash the genital area with clean water; there is no need for scented soaps or douching, which can cause irritation and infection",
      "Osha sehemu za siri kwa maji safi; hakuna haja ya sabuni zenye harufu au kusafisha ndani, ambavyo vinaweza kusababisha muwasho na maambukizi",
      "Osha genital area na maji safi; hakuna haja ya scented soaps ama douching, ambazo zinaweza kusababisha irritation na infection"),
     ("If cloth is used, wash it with soap, dry it fully in direct sunlight, and store it clean and dry",
      "Kitambaa kikitumika, kioshe kwa sabuni, kikaushe kikamilifu kwenye jua, na kihifadhi kikiwa safi na kikavu",
      "Kama cloth inatumika, i-wash na sabuni, i-dry fully kwa jua, na i-store ikiwa safi na kavu"),
     ("Wash hands before and after changing — this is a handwashing moment too",
      "Nawa mikono kabla na baada ya kubadilisha — huu pia ni wakati wa kunawa mikono",
      "Wash hands kabla na baada ya kubadilisha — huu pia ni handwashing moment"),
     ("Missing school during a period is a hygiene-and-supplies problem, not an inevitability — raise it with your supervisor if it is happening",
      "Kukosa shule wakati wa hedhi ni tatizo la usafi na vifaa, si jambo lisiloepukika — liibue kwa msimamizi wako likitokea",
      "Kukosa shule wakati wa periods ni hygiene-na-supplies problem, si kitu kisichoepukika — i-raise kwa supervisor wako ikihappen"),
    ]},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A boy in your group is being teased about body odour. He looks humiliated and says nothing.",
      "Mvulana katika kundi lako anachekwa kuhusu harufu ya mwili. Anaonekana amefedheheka na hasemi chochote.",
      "Mse kwa group yako ana-teasiwa kuhusu body odour. Anaonekana humiliated na hasemi kitu."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell the group off, then move on with the session",
                "Karipia kundi, kisha uendelee na kipindi",
                "Karipia group, kisha uendelee na session"),
       "outcome": ("The teasing stops in front of you and continues after. He has been marked out twice now — once by them, once by your intervention. Nothing has changed about the thing he was teased for, and he will not come to you about it.",
                   "Kuchekwa kunakoma mbele yako na kunaendelea baadaye. Sasa ametengwa mara mbili — mara moja na wao, mara moja na uingiliaji wako. Hakuna kilichobadilika kuhusu jambo alilochekwa, na hatakuja kwako kulihusu.",
                   "Teasing ina-stop mbele yako na inaendelea baadaye. Saa hii ame-markiwa mara mbili — mara moja na wao, mara moja na intervention yako. Hakuna kilicho-change kuhusu kitu alichochekwa, na hatakuja kwako kuhusu hiyo.")},
      {"kind": "good",
       "text": ("Teach the whole group why puberty changes hygiene needs, then follow up with him privately",
                "Fundisha kundi zima kwa nini ubalehe hubadilisha mahitaji ya usafi, kisha umfuatilie faraghani",
                "Fundisha group nzima kwa nini puberty inabadilisha hygiene needs, kisha um-follow up privately"),
       "outcome": ("You told the room that sweat glands switch on at puberty and everyone's routine has to change with them — no names, no glances. Afterwards you asked him quietly whether he had soap at home. He did not. That was the actual problem. ✅",
                   "Uliambia chumba kwamba tezi za jasho huanza kufanya kazi wakati wa ubalehe na utaratibu wa kila mtu unapaswa kubadilika nazo — bila majina, bila kumtazama. Baadaye ulimuuliza kwa utulivu kama alikuwa na sabuni nyumbani. Hakuwa nayo. Hilo ndilo lilikuwa tatizo hasa. ✅",
                   "Uliambia room ati sweat glands zinaanza kufanya kazi wakati wa puberty na routine ya kila msee inafaa ku-change nazo — bila majina, bila kum-glance. Baadaye ulimuuliza kwa utulivu kama alikuwa na sabuni nyumbani. Hakuwa nayo. Hiyo ndio ilikuwa problem hasa. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "At your school the latrines have water but no soap, and there has been no soap for weeks. Learners wash with water only.",
      "Shuleni kwako vyoo vina maji lakini hakuna sabuni, na hakujakuwa na sabuni kwa wiki. Wanafunzi hunawa kwa maji tu.",
      "Shuleni kwako choo kina maji lakini hakuna sabuni, na hakujakuwa na sabuni kwa wiki. Learners wana-wash na maji tu."),
     "question": ("What is the most useful thing you can do?", "Ni kitu gani chenye manufaa zaidi unaweza kufanya?", "Ni kitu gani chenye manufaa zaidi unaweza kufanya?"),
     "choices": [
      {"kind": "bad",
       "text": ("Run another session reminding everyone to wash their hands properly",
                "Endesha kipindi kingine kuwakumbusha wote kunawa mikono vizuri",
                "Run session ingine kuwa-remind wote ku-wash hands properly"),
       "outcome": ("They already know. Repeating the message where the soap is missing teaches learners that the message is not serious — and teaches you nothing about why behaviour is not following knowledge.",
                   "Tayari wanajua. Kurudia ujumbe pale sabuni haipo kunawafundisha wanafunzi kwamba ujumbe si wa dhati — na hakukufundishi chochote kuhusu kwa nini tabia haifuati maarifa.",
                   "Tayari wanajua. Kurudia message pale sabuni haiko kunawafundisha learners ati message si serious — na haikufundishi kitu kuhusu kwa nini behaviour hai-follow knowledge.")},
      {"kind": "good",
       "text": ("Report the missing soap through your supervisor, and propose an ash station meanwhile",
                "Ripoti sabuni inayokosekana kupitia msimamizi wako, na upendekeze kituo cha jivu wakati huo huo",
                "Report sabuni inayokosekana kupitia supervisor wako, na u-propose ash station wakati huo"),
       "outcome": ("You raised it with the teacher on duty and set up a bucket with ash beside the latrine in the meantime. Handwashing rates changed the same week — because the barrier was never knowledge. ✅",
                   "Ulilileta kwa mwalimu wa zamu na ukaweka ndoo yenye jivu kando ya choo wakati huo. Viwango vya kunawa mikono vilibadilika wiki hiyo hiyo — kwa sababu kizuizi hakikuwa maarifa kamwe. ✅",
                   "Uli-raise na teacher wa duty na ukaweka bucket yenye jivu kando ya choo wakati huo. Handwashing rates zili-change wiki hiyo hiyo — kwa sababu barrier haikuwa knowledge kamwe. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Hygiene and sanitation prevent illness.",
      "Usafi wa mwili na mazingira huzuia magonjwa.",
      "Hygiene na sanitation zina-prevent illness."),
     ("Cleanliness shows respect for yourself and for others.",
      "Usafi huonyesha heshima kwako na kwa wengine.",
      "Cleanliness inaonyesha respect kwako na kwa wengine."),
     ("Good habits built early last a lifetime.",
      "Tabia nzuri zilizojengwa mapema hudumu maisha yote.",
      "Good habits zilizojengwa early zinadumu maisha yote."),
     ("Seek care early if you see any sign of infection.",
      "Tafuta huduma mapema ukiona dalili yoyote ya maambukizi.",
      "Tafuta care early ukiona sign yoyote ya infection."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Watu hawakosi kunawa mikono kwa sababu hawajui. Hukosa kwa sababu sabuni haiko pale. Rekebisha mahali, si ujumbe.",
     "Watu hawakosi kunawa mikono kwa sababu hawajui. Hukosa kwa sababu sabuni haipo pale. Rekebisha mahali, si ujumbe.",
     "Wasee hawa-miss ku-wash hands kwa sababu hawajui. Wana-miss kwa sababu sabuni haiko pale. Fix mahali, si message.")},
   ]},
 ],

 "quiz": [
  {"q": "How does the curriculum define personal hygiene?",
   "options": ["Bathing once a week", "Daily practices that keep the body clean and healthy",
               "Using perfume and deodorant", "Cleaning your home environment"],
   "answer": "B",
   "explain": "Sanitation covers the environment; personal hygiene is the daily body-care routine."},

  {"q": "Which are the five critical handwashing times? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["After defecation", "After handling faeces, including cleaning a child",
               "Before preparing food", "Before eating food", "After playing sport"],
   "answer": ["A", "B", "C", "D"],
   "explain": "The fifth is after cleaning the environment. Sport is not on the list — these five target the faecal-oral route specifically."},

  {"q": "Is washing with water alone enough?",
   "options": ["Yes, if you wash for long enough",
               "No — soap lifts germs off the skin so water can carry them away; ash works if soap is unavailable",
               "Yes, water removes all germs",
               "Only if the water is hot"],
   "answer": "B",
   "explain": "Rinsing shifts visible dirt and leaves most germs in place."},

  {"q": "Why does hygiene need change at puberty?",
   "options": ["It does not change",
               "Sweat glands become active, skin becomes oilier, and body odour appears where it did not before",
               "Only girls' needs change",
               "Because of school rules"],
   "answer": "B",
   "explain": "Saying this plainly removes a lot of embarrassment — the young person is not careless, their body genuinely changed."},

  {"q": "Which conditions are linked to poor hand and food hygiene? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Diarrhoeal illness", "Typhoid", "Intestinal worms", "Asthma"],
   "answer": ["A", "B", "C"],
   "explain": "Asthma is not hygiene-related. The others spread by the faecal-oral route."},

  {"q": "How often should menstrual pads or cloths be changed?",
   "options": ["Once a day", "Every four to six hours, or more often on heavy days",
               "Only when visibly full", "Every twelve hours"],
   "answer": "B",
   "explain": "If cloth is used, it should be washed with soap, dried fully in direct sunlight, and stored clean and dry."},

  {"q": "What is the correct advice about washing the genital area during menstruation?",
   "options": ["Use scented soap daily",
               "Clean water is sufficient; scented soaps and douching can cause irritation and infection",
               "Avoid washing during a period",
               "Use antiseptic solution"],
   "answer": "B",
   "explain": "Douching disturbs the natural balance and can cause the very infections it is meant to prevent."},

  {"q": "A boy is teased about body odour. What is the best response?",
   "options": ["Tell the group off and move on",
               "Teach the whole group why puberty changes hygiene needs, then follow up with him privately",
               "Ignore it",
               "Ask him publicly whether he bathes"],
   "answer": "B",
   "explain": "Telling the group off marks him out twice and changes nothing about the underlying problem — which in his case was having no soap at home."},

  {"q": "Learners at a school wash with water only because there has been no soap for weeks. What helps most?",
   "options": ["Another session reminding them to wash properly",
               "Reporting the missing soap and setting up an ash station meanwhile",
               "Telling them to bring soap from home",
               "Nothing can be done"],
   "answer": "B",
   "explain": "The barrier was never knowledge. Fixing the place is more effective than repeating the message."},

  {"q": "Which is TRUE about hygiene and the community?",
   "options": ["Hygiene is purely a private matter",
               "It protects community health — germs spread beyond the individual",
               "Only food handlers affect others",
               "Community health is unrelated to personal habits"],
   "answer": "B",
   "explain": "Preventing the spread of germs and ensuring community wellbeing are both listed among the reasons hygiene matters."},
 ],
}
