# Module 5 (part 1 of 2) — Life Skills: Skills for Yourself
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 5.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m05a-skills-for-yourself.html",
 "module_code": "M5",
 "module_slug": "life-skills",
 "lesson_slug": "m05a-skills-for-yourself",
 "module_label": "Peer Educator · M5 · Part 1 of 2",
 "title": "Life Skills — Skills for Yourself",
 "icon": "🧠",
 "duration": 45,

 "objectives": [
  ("Define life skills and explain why they matter in the transition to adulthood",
   "Fafanua ujuzi wa maisha na ueleze kwa nini ni muhimu katika kuvuka kuelekea utu uzima",
   "Define life skills na explain kwa nini ni muhimu kwa transition kuelekea utu uzima"),
  ("Describe the three categories of life skill",
   "Eleza makundi matatu ya ujuzi wa maisha",
   "Describe categories tatu za life skills"),
  ("Apply self-awareness, and manage strong emotions and stress",
   "Tumia kujitambua, na udhibiti hisia kali na msongo",
   "Tumia self-awareness, na u-manage hisia kali na stress"),
  ("Build resilience and set goals that carry a young person forward",
   "Jenga uthabiti na uweke malengo yanayomsonga kijana mbele",
   "Jenga resilience na uweke goals zinazomsonga kijana mbele"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Two young people face the same disappointment. One recovers in a week, the other never quite does. What is the difference actually made of?",
  "<strong>🔍 Swali Kubwa:</strong> Vijana wawili wanakabiliwa na kukatishwa tamaa sawa. Mmoja anapona kwa wiki, mwingine hapati nafuu kabisa. Tofauti hiyo imetengenezwa na nini hasa?",
  "<strong>🔍 Big Question:</strong> Vijana wawili wanaface disappointment moja. Mmoja anarecover kwa wiki, mwingine harecover kabisa. Hiyo tofauti ime-madiwa na nini hasa?"),

 "slides": [

  # ── 1. Definition ─────────────────────────────────────────────────
  {"icon": "📖",
   "head": ("What Life Skills Are", "Ujuzi wa Maisha ni Nini", "Life Skills ni Nini"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Skills", "🔑 Ujuzi", "🔑 Skills"), "text": (
     "Expertise or talent needed in order to do a job or a task.",
     "Utaalamu au kipaji kinachohitajika ili kufanya kazi au jukumu.",
     "Expertise ama talent inayohitajika ili kufanya job ama task.")},
    {"type": "key_term", "term": ("🔑 Life skills", "🔑 Ujuzi wa maisha", "🔑 Life skills"), "text": (
     "A set of basic skills acquired through learning and direct life experience, that let a person handle the issues and problems commonly met in daily life — and carry a young person successfully from childhood into adulthood.",
     "Seti ya ujuzi wa msingi unaopatikana kwa kujifunza na uzoefu wa moja kwa moja wa maisha, unaomwezesha mtu kushughulikia masuala na matatizo yanayokutwa kila siku — na kumvusha kijana kwa mafanikio kutoka utotoni hadi utu uzima.",
     "Set ya basic skills unaopatikana kwa kujifunza na direct life experience, unaomwezesha msee ku-handle issues na problems zinazokutwa kila siku — na ku-carry kijana successfully kutoka utotoni hadi utu uzima.")},
    {"type": "warn", "title": ("⚠️ The word that matters is 'acquired'", "⚠️ Neno muhimu ni 'unaopatikana'", "⚠️ Neno muhimu ni 'acquired'"), "text": (
     " Life skills are learned, not inherited. Nobody is simply born assertive or resilient. That is the whole reason this module exists — and the reason a peer educator can genuinely change someone's trajectory.",
     " Ujuzi wa maisha hujifunzwa, haurithiwi. Hakuna anayezaliwa tu akiwa mjasiri au mthabiti. Hiyo ndiyo sababu yote ya moduli hii kuwepo — na sababu mwelimishaji rika anaweza kubadilisha mwelekeo wa mtu kweli.",
     " Life skills zina-learniwa, hazi-inheritiwi. Hakuna msee anazaliwa tu akiwa assertive ama resilient. Hiyo ndio sababu yote ya hii module kuwepo — na sababu peer educator anaweza ku-change trajectory ya msee kweli.")},
   ]},

  # ── 2. Three categories ───────────────────────────────────────────
  {"icon": "🗂️",
   "head": ("The Three Categories", "Makundi Matatu", "Categories Tatu"),
   "blocks": [
    {"type": "table",
     "headers": [("Dealing with yourself", "Kujishughulikia", "Dealing na wewe mwenyewe"),
                 ("Dealing with others", "Kushughulika na wengine", "Dealing na wengine"),
                 ("Making decisions", "Kufanya maamuzi", "Ku-make decisions")],
     "rows": [
      [("Self-awareness", "Kujitambua", "Self-awareness"),
       ("Interpersonal relationships", "Mahusiano na watu", "Interpersonal relationships"),
       ("Critical thinking", "Fikra makini", "Critical thinking")],
      [("Self-esteem", "Kujithamini", "Self-esteem"),
       ("Friendship formation", "Kuunda urafiki", "Friendship formation"),
       ("Creative thinking", "Fikra bunifu", "Creative thinking")],
      [("Coping with emotions", "Kukabiliana na hisia", "Ku-cope na emotions"),
       ("Conflict resolution", "Kutatua migogoro", "Conflict resolution"),
       ("Decision making", "Kufanya maamuzi", "Decision making")],
      [("Coping with stress", "Kukabiliana na msongo", "Ku-cope na stress"),
       ("Empathy", "Huruma", "Empathy"),
       ("Problem solving", "Kutatua matatizo", "Problem solving")],
      [("Goal setting", "Kuweka malengo", "Goal setting"),
       ("Effective communication", "Mawasiliano bora", "Effective communication"),
       ("Economic empowerment", "Uwezeshaji kiuchumi", "Economic empowerment")],
      [("Time management", "Kudhibiti muda", "Time management"),
       ("Dealing with peer pressure; assertiveness; negotiation",
        "Kukabiliana na shinikizo la rika; ujasiri; majadiliano",
        "Ku-deal na peer pressure; assertiveness; negotiation"),
       ("Social and educational empowerment", "Uwezeshaji kijamii na kielimu", "Social na educational empowerment")],
     ]},
    {"type": "p", "text": (
     "This part covers the first column. Part 2 covers the other two.",
     "Sehemu hii inahusu safu ya kwanza. Sehemu ya 2 inahusu zile mbili nyingine.",
     "Hii part inacover column ya kwanza. Part 2 inacover zile mbili zingine.")},
   ]},

  # ── 3. Self-awareness ─────────────────────────────────────────────
  {"icon": "🪞",
   "head": ("Self-Awareness", "Kujitambua", "Self-Awareness"),
   "blocks": [
    {"type": "p", "text": (
     "Self-awareness is the ability to recognise your own strengths and weaknesses, what you want and what you do not. It is what lets an adolescent notice they are under stress or being pressured — before the decision is already made.",
     "Kujitambua ni uwezo wa kutambua nguvu na udhaifu wako, unachotaka na usichotaka. Ndiko kunakomwezesha kijana kutambua yuko na msongo au anashinikizwa — kabla uamuzi haujafanywa tayari.",
     "Self-awareness ni uwezo wa ku-recognise strengths na weaknesses zako, unachotaka na usichotaka. Ndio inamwezesha kijana ku-notice ana stress ama ana-pressuriwa — kabla decision ishafanywa.")},
    {"type": "list", "items": [
     ("Be mindful of your strengths, and of what you struggle with",
      "Kuwa makini na nguvu zako, na unachohangaika nacho",
      "Kuwa mindful na strengths zako, na unachohangaika nacho"),
     ("Know your emotional triggers — what reliably sets you off",
      "Jua vichochezi vyako vya hisia — kinachokuchochea daima",
      "Jua emotional triggers zako — kinachokutrigger daima"),
     ("Set boundaries, and stay focused on what you decided matters",
      "Weka mipaka, na ubaki umezingatia uliyoamua ni muhimu",
      "Weka boundaries, na ubaki umefocus kwa uliyo-decide ni muhimu"),
     ("Trust your instincts in decision-making",
      "Amini hisia zako katika kufanya maamuzi",
      "Trust instincts zako kwa decision-making"),
     ("Practise self-discipline",
      "Fanya mazoezi ya kujidhibiti",
      "Practise self-discipline"),
    ]},
    {"type": "tip", "title": ("💡 Why this one comes first", "💡 Kwa nini hii inakuja kwanza", "💡 Kwa nini hii inakuja kwanza"), "text": (
     " Every other skill in this module depends on it. You cannot refuse pressure you have not noticed, or manage an emotion you cannot name. Self-awareness is not the soft skill — it is the one that switches the others on.",
     " Kila ujuzi mwingine katika moduli hii unautegemea. Huwezi kukataa shinikizo usilolitambua, wala kudhibiti hisia usiyoiweza kuitaja. Kujitambua si ujuzi laini — ndio unaowasha vingine.",
     " Kila skill nyingine kwa hii module inai-depend. Huwezi ku-refuse pressure usiyoi-notice, wala ku-manage emotion usiyoweza kui-name. Self-awareness si soft skill — ndio inayo-switch on zingine.")},
   ]},

  # ── 4. Coping with emotions ───────────────────────────────────────
  {"icon": "💛",
   "head": ("Coping With Strong Emotions", "Kukabiliana na Hisia Kali", "Ku-cope na Hisia Kali"),
   "blocks": [
    {"type": "p", "text": (
     "This skill lets a young person manage intense emotion — anger, sadness — which harms health if it is not handled. The curriculum gives two different sets of advice, and it is worth keeping them apart.",
     "Ujuzi huu humwezesha kijana kudhibiti hisia kali — hasira, huzuni — ambazo hudhuru afya zisiposhughulikiwa. Mtaala unatoa seti mbili tofauti za ushauri, na inafaa kuzitenganisha.",
     "Hii skill inamwezesha kijana ku-manage intense emotion — hasira, huzuni — ambazo zinadhuru health zisiposhughulikiwa. Curriculum inatoa sets mbili tofauti za advice, na inafaa kuzi-separate.")},
    {"type": "table",
     "headers": [("For yourself", "Kwa nafsi yako", "Kwa nafsi yako"),
                 ("When supporting someone else", "Unapomsaidia mwingine", "Unapom-support mwingine")],
     "rows": [
      [("Write about how you feel",
        "Andika kuhusu unavyohisi",
        "Andika kuhusu unavyofeel"),
       ("Use non-judgemental language",
        "Tumia lugha isiyohukumu",
        "Tumia non-judgemental language")],
      [("Express feelings through art or music",
        "Eleza hisia kupitia sanaa au muziki",
        "Express feelings kupitia art ama music")],
      [("Use physical activity to release what has built up",
        "Tumia mazoezi ya mwili kutoa kilichojirundika",
        "Tumia physical activity kutoa kilichojirundika"),
       ("Avoid all-or-nothing thinking — accept there is often a grey area",
        "Epuka fikra za yote-au-hakuna — kubali mara nyingi kuna eneo la kijivu",
        "Avoid all-or-nothing thinking — accept mara nyingi kuna grey area")],
      [("<strong>Cry.</strong> It genuinely helps, and it is okay to.",
        "<strong>Lia.</strong> Kunasaidia kweli, na ni sawa kufanya hivyo.",
        "<strong>Lia.</strong> Inasaidia kweli, na ni poa kufanya hivyo."),
       ("Give choices and limits; be willing to renegotiate priorities",
        "Toa chaguo na mipaka; kuwa tayari kujadili upya vipaumbele",
        "Toa choices na limits; kuwa willing ku-renegotiate priorities")],
      [("Talk it through with someone you trust — both to release it and to gain perspective",
        "Zungumza na mtu unayemwamini — kutoa na kupata mtazamo",
        "Ongea na msee unayemtrust — kutoa na kupata perspective"),
       ("Be firm and gentle at once; show acceptance and hope; validate by paying attention",
        "Kuwa imara na mpole kwa pamoja; onyesha kukubali na matumaini; thibitisha kwa kuzingatia",
        "Kuwa firm na gentle kwa pamoja; onyesha acceptance na hope; validate kwa ku-pay attention")],
     ]},
    {"type": "sheng", "text": (
     "Hisia haziondoki kwa kupuuzwa. Zinasubiri. Na zikisubiri kwa muda wa kutosha, hutoka kwa njia usiyoichagua wewe.",
     "Hisia haziondoki kwa kupuuzwa. Husubiri. Na zikisubiri kwa muda wa kutosha, hutoka kwa njia usiyoichagua wewe.",
     "Feelings haziondoki kwa ku-ignoriwa. Zinangoja. Na zikingoja kwa muda wa kutosha, zinatoka kwa njia usiyoi-choose wewe.")},
   ]},

  # ── 5. Stress & resilience ────────────────────────────────────────
  {"icon": "🌱",
   "head": ("Coping With Stress, and Bouncing Back", "Kukabiliana na Msongo, na Kurudi", "Ku-cope na Stress, na Ku-bounce Back"),
   "blocks": [
    {"type": "p", "text": (
     "Young people meet stress constantly — schoolwork, exams, family conflict. Supporting someone through it is a specific skill.",
     "Vijana hukutana na msongo kila mara — kazi za shule, mitihani, migogoro ya familia. Kumsaidia mtu kupitia huo ni ujuzi mahususi.",
     "Vijana wanakutana na stress kila mara — schoolwork, exams, family conflict. Ku-support msee kupitia hiyo ni specific skill.")},
    {"type": "list", "items": [
     ("Let them know you have noticed, and that you support them",
      "Wafahamishe kwamba umeona, na kwamba unawaunga mkono",
      "Wafahamishe ati umeona, na ati unawa-support"),
     ("Help them identify the source — work out what is actually causing it",
      "Wasaidie kutambua chanzo — tambua ni nini hasa kinachosababisha",
      "Wasaidie ku-identify source — figure out ni nini hasa kinachosababisha"),
     ("Encourage a healthy lifestyle, especially physical activity",
      "Himiza mtindo bora wa maisha, hasa mazoezi ya mwili",
      "Encourage healthy lifestyle, hasa physical activity"),
     ("<strong>If the stress gets too much, seek help</strong> — a school counsellor, a psychologist or a spiritual leader",
      "<strong>Msongo ukizidi, tafuta msaada</strong> — mshauri wa shule, mwanasaikolojia au kiongozi wa kiroho",
      "<strong>Stress ikizidi, tafuta msaada</strong> — school counsellor, psychologist ama spiritual leader"),
    ]},
    {"type": "key_term", "term": ("🔑 Resilience", "🔑 Uthabiti", "🔑 Resilience"), "text": (
     "The ability to adapt well in the face of difficult times — also called 'bounce back'. Young people face arguments with friends, disappointing exam results and sporting losses, and need resilience to recover and learn from them.",
     "Uwezo wa kubadilika vizuri katika nyakati ngumu — pia huitwa 'kurudi'. Vijana hukabiliwa na mabishano na marafiki, matokeo mabaya ya mitihani na kushindwa michezoni, na wanahitaji uthabiti kupona na kujifunza kutokana nayo.",
     "Uwezo wa ku-adapt vizuri kwa difficult times — pia inaitwa 'bounce back'. Vijana wanaface arguments na friends, disappointing exam results na sporting losses, na wanahitaji resilience ku-recover na kujifunza kutokana nazo.")},
    {"type": "list", "items": [
     ("<strong>Self-respect and self-compassion</strong> — being as fair to yourself as you would be to a friend",
      "<strong>Kujiheshimu na kujihurumia</strong> — kuwa mwadilifu kwako kama ungekuwa kwa rafiki",
      "<strong>Self-respect na self-compassion</strong> — kuwa fair kwako kama ungekuwa kwa friend"),
     ("<strong>Social skills</strong> — making and keeping friends, sorting out conflict, working in a team",
      "<strong>Ujuzi wa kijamii</strong> — kupata na kuweka marafiki, kutatua migogoro, kufanya kazi kwa timu",
      "<strong>Social skills</strong> — kupata na ku-keep friends, ku-sort conflict, kufanya kazi kwa team"),
     ("<strong>Positive thinking habits</strong> — realistic and rational, finding the positives, expecting things to go well, and moving forward even when they seem bad",
      "<strong>Tabia za fikra chanya</strong> — halisi na za busara, kupata mazuri, kutarajia mambo yaende vyema, na kusonga mbele hata yanapoonekana mabaya",
      "<strong>Positive thinking habits</strong> — realistic na rational, kupata positives, ku-expect mambo yaende poa, na kusonga mbele hata yanapoonekana mabaya"),
     ("<strong>Skills for getting things done</strong> — goal-setting, planning, being organised and self-disciplined, resourceful, and prepared to work hard",
      "<strong>Ujuzi wa kutimiza mambo</strong> — kuweka malengo, kupanga, kuwa na mpangilio na nidhamu, mbunifu, na tayari kufanya kazi kwa bidii",
      "<strong>Skills za ku-get things done</strong> — goal-setting, planning, kuwa organised na self-disciplined, resourceful, na ready kufanya kazi kwa bidii"),
    ]},
   ]},

  # ── 6. Goal setting ───────────────────────────────────────────────
  {"icon": "🎯",
   "head": ("Goal Setting", "Kuweka Malengo", "Goal Setting"),
   "blocks": [
    {"type": "p", "text": (
     "Goals are ideas of the future a person plans and commits to. Young people should dream big — but start with small, manageable steps. <strong>A short-term goal is how a long-term goal actually gets reached.</strong>",
     "Malengo ni mawazo ya baadaye ambayo mtu hupanga na kujitolea kwayo. Vijana wanapaswa kuota ndoto kubwa — lakini waanze na hatua ndogo zinazoweza kutekelezwa. <strong>Lengo la muda mfupi ndilo linalofanya lengo la muda mrefu lifikiwe.</strong>",
     "Goals ni ideas za future ambazo msee ana-plan na ku-commit. Vijana wanafaa ku-dream big — lakini waanze na small, manageable steps. <strong>Short-term goal ndio inafanya long-term goal i-reachiwe.</strong>")},
    {"type": "table",
     "headers": [("General health goals", "Malengo ya afya kwa jumla", "General health goals"),
                 ("School and career goals", "Malengo ya shule na kazi", "School na career goals")],
     "rows": [
      [("Eating a healthy diet and exercising",
        "Kula lishe bora na kufanya mazoezi",
        "Kukula healthy diet na kufanya exercise"),
       ("Getting a better grade at school",
        "Kupata alama bora shuleni",
        "Kupata better grade shuleni")],
      [("Keeping away from drugs and substance abuse",
        "Kujiepusha na dawa za kulevya",
        "Kujiepusha na drugs na substance abuse"),
       ("Transitioning to high school",
        "Kuvuka hadi shule ya sekondari",
        "Ku-transition hadi high school")],
      [("Understanding your body and setting your own limits",
        "Kuelewa mwili wako na kuweka mipaka yako",
        "Kuelewa mwili wako na kuweka limits zako"),
       ("Joining college, university or vocational training",
        "Kujiunga na chuo, chuo kikuu au mafunzo ya ufundi",
        "Kujoin college, university ama vocational training")],
      [("Being prepared to refuse sex, or to consent at the right time",
        "Kuwa tayari kukataa ngono, au kukubali wakati sahihi",
        "Kuwa ready ku-refuse sex, ama ku-consent wakati sahihi"),
       ("Supporting yourself and your future family through your skills",
        "Kujikimu wewe na familia yako ya baadaye kupitia ujuzi wako",
        "Ku-support wewe na family yako ya baadaye kupitia skills zako")],
      [("Planning for the future — a healthy family, a loving partner",
        "Kupanga kwa ajili ya baadaye — familia yenye afya, mwenzi mpendwa",
        "Ku-plan kwa future — healthy family, loving partner"),
       ("Becoming self-sufficient through a job or self-employment",
        "Kujitegemea kupitia kazi au kujiajiri",
        "Kuwa self-sufficient kupitia job ama self-employment")],
     ]},
    {"type": "list", "items": [
     ("<strong>Why goals matter:</strong> they keep you focused, push you out of your comfort zone, give you control over your own activities, keep you motivated, and make you grow",
      "<strong>Kwa nini malengo ni muhimu:</strong> hukuweka umezingatia, hukusukuma nje ya eneo lako la faraja, hukupa udhibiti wa shughuli zako, hukuhamasisha, na hukukuza",
      "<strong>Kwa nini goals ni muhimu:</strong> zinaku-keep focused, zinaku-push nje ya comfort zone yako, zinakupa control ya activities zako, zinaku-motivate, na zinakukuza"),
    ]},
    {"type": "facilitator", "minutes": 12, "text": (
     "Have each participant write one long-term goal, then one short-term goal that serves it and can be started this week. Collect the short-term ones and read a few aloud without names. The gap between 'be a doctor' and 'pass this term's biology' is the lesson.",
     "Waache kila mshiriki aandike lengo moja la muda mrefu, kisha lengo moja la muda mfupi linaloliendeleza na linaloweza kuanzwa wiki hii. Kusanya yale ya muda mfupi na usome machache kwa sauti bila majina. Pengo kati ya 'kuwa daktari' na 'kufaulu biolojia ya muhula huu' ndilo somo.",
     "Wacha kila participant aandike long-term goal moja, kisha short-term goal moja inayoi-serve na inayoweza kuanzwa wiki hii. Collect zile za short-term na usome chache kwa sauti bila majina. Gap kati ya 'kuwa daktari' na 'ku-pass biology ya term hii' ndio lesson.")},
   ]},

  # ── 7. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "Kiptoo failed his mock exams badly. He tells you there is no point trying now, since he has already ruined everything.",
      "Kiptoo alishindwa vibaya mitihani yake ya majaribio. Anakuambia hakuna maana ya kujaribu sasa, kwa kuwa tayari ameharibu kila kitu.",
      "Kiptoo ali-fail mock exams zake vibaya. Anakuambia hakuna point ya ku-try saa hii, kwa kuwa tayari ameharibu kila kitu."),
     "question": ("Which life skill is missing here?", "Ni ujuzi upi wa maisha unaokosekana hapa?", "Ni life skill ipi inayo-miss hapa?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell him the mocks do not count and he should not worry about them",
                "Mwambie mitihani ya majaribio haihesabiki na asijali",
                "Mwambie mocks hazi-count na asi-worry"),
       "outcome": ("Dismissing the result also dismisses him. He knows they matter; being told otherwise just tells him you are not taking this seriously. What is missing is not reassurance — it is resilience, and the all-or-nothing thinking the curriculum specifically warns about.",
                   "Kupuuza matokeo pia ni kumpuuza yeye. Anajua yana maana; kuambiwa vinginevyo kunamwambia tu huchukui hili kwa uzito. Kinachokosekana si faraja — ni uthabiti, na fikra za yote-au-hakuna ambazo mtaala unaonya dhidi yake hasa.",
                   "Ku-dismiss result pia ni kum-dismiss yeye. Anajua zina maana; kuambiwa vinginevyo kunamwambia tu hu-take hii seriously. Kinachomiss si reassurance — ni resilience, na all-or-nothing thinking ambayo curriculum inaonya dhidi yake hasa.")},
      {"kind": "good",
       "text": ("Name the all-or-nothing thinking, and break the goal into something startable this week",
                "Taja fikra za yote-au-hakuna, na ugawanye lengo kuwa kitu kinachoweza kuanzwa wiki hii",
                "Name hiyo all-or-nothing thinking, na u-break goal kuwa kitu kinachoweza kuanzwa wiki hii"),
       "outcome": ("You said: 'You didn't ruin everything — you did badly in one set of exams. Those are different sentences. What's one subject you could move by one grade before the finals?' He picked chemistry. Starting somewhere is what resilience is actually made of. ✅",
                   "Ulisema: 'Hukuharibu kila kitu — ulifanya vibaya katika seti moja ya mitihani. Hizo ni sentensi tofauti. Ni somo lipi moja ungeweza kulipandisha alama moja kabla ya mitihani ya mwisho?' Alichagua kemia. Kuanza mahali fulani ndicho uthabiti umetengenezwa nacho hasa. ✅",
                   "Ulisema: 'Hukuharibu kila kitu — ulifanya vibaya kwa set moja ya exams. Hizo ni sentences tofauti. Ni subject ipi moja ungeweza ku-move kwa grade moja kabla ya finals?' Alichagua chemistry. Kuanza mahali fulani ndio resilience ime-madiwa nacho hasa. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A peer says she gets so angry she says things she regrets, and she has decided the answer is to stop feeling angry altogether.",
      "Rika anasema hukasirika sana hadi husema mambo anayoyajutia, na ameamua jibu ni kuacha kuhisi hasira kabisa.",
      "Msee anasema anakasirika sana hadi anasema vitu anavyo-regret, na ame-decide answer ni kuacha kufeel hasira kabisa."),
     "question": ("What do you tell her?", "Unamwambia nini?", "Unamwambia nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Agree — controlling anger means not letting yourself feel it",
                "Kubaliana — kudhibiti hasira maana yake ni kutojiruhusu kuihisi",
                "Agree — ku-control hasira maana yake ni kutojiruhusu kuifeel"),
       "outcome": ("Suppressed emotion does not disappear; it waits. The curriculum's advice is about releasing and processing feeling — writing, art, physical activity, crying, talking it through — not about not having it. Teaching her to bury it guarantees it comes out somewhere she did not choose.",
                   "Hisia iliyokandamizwa haitoweki; husubiri. Ushauri wa mtaala unahusu kutoa na kuchakata hisia — kuandika, sanaa, mazoezi, kulia, kuzungumza — si kutokuwa nayo. Kumfundisha kuizika kunahakikisha inatoka mahali asipochagua.",
                   "Suppressed emotion haiondoki; inangoja. Advice ya curriculum ni kuhusu ku-release na ku-process feeling — kuandika, art, physical activity, kulia, kuongea — si kutokuwa nayo. Kumfundisha kuizika kuna-guarantee inatoka mahali asipo-choose.")},
      {"kind": "good",
       "text": ("Separate feeling the anger from acting on it, and give her ways to release it",
                "Tenganisha kuhisi hasira na kutenda kutokana nayo, na umpe njia za kuitoa",
                "Separate kufeel hasira na ku-act kutokana nayo, na umpe njia za kui-release"),
       "outcome": ("You said: 'The anger isn't the problem — what happens in the ten seconds after it is. You can't stop feeling it, but you can put it somewhere: write it, run it, cry it out, or bring it to me before you bring it to them.' She started running. ✅",
                   "Ulisema: 'Hasira si tatizo — kinachotokea sekunde kumi baada yake ndicho. Huwezi kuacha kuihisi, lakini unaweza kuiweka mahali: iandike, ikimbie, ililie, au unililete kwangu kabla ya kuwapelekea wao.' Alianza kukimbia. ✅",
                   "Ulisema: 'Hasira si problem — kinachohappen kwa seconds kumi baada yake ndio. Huwezi kuacha kuifeel, lakini unaweza kuiweka mahali: iandike, ikimbie, ilie, ama uilete kwangu kabla uipeleke kwao.' Alianza kukimbia. ✅")},
     ]},
   ]},

  # ── 8. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Life skills are acquired through learning and experience — nobody is born with them.",
      "Ujuzi wa maisha hupatikana kwa kujifunza na uzoefu — hakuna anayezaliwa nao.",
      "Life skills zinapatikana kwa kujifunza na experience — hakuna msee anazaliwa nazo."),
     ("Knowing yourself is a powerful skill — it helps you understand your strengths and your emotions.",
      "Kujijua ni ujuzi wenye nguvu — hukusaidia kuelewa nguvu zako na hisia zako.",
      "Kujijua ni skill yenye nguvu — inakusaidia kuelewa strengths zako na emotions zako."),
     ("Emotions do not disappear when ignored. Release them deliberately, or they surface where you did not choose.",
      "Hisia haziondoki zikipuuzwa. Zitoe kwa makusudi, la sivyo zitajitokeza mahali usipochagua.",
      "Emotions haziondoki ziki-ignoriwa. Zi-release kwa makusudi, ama zitajitokeza mahali usipo-choose."),
     ("Resilience is bouncing back — and it is built from self-compassion, social skills, realistic thinking and getting things done.",
      "Uthabiti ni kurudi — na hujengwa kutokana na kujihurumia, ujuzi wa kijamii, fikra halisi na kutimiza mambo.",
      "Resilience ni ku-bounce back — na inajengwa kutokana na self-compassion, social skills, realistic thinking na ku-get things done."),
     ("A short-term goal is how a long-term goal actually gets reached.",
      "Lengo la muda mfupi ndilo linalofanya lengo la muda mrefu lifikiwe.",
      "Short-term goal ndio inafanya long-term goal i-reachiwe."),
    ]},
   ]},
 ],

 "quiz": [
  {"q": "How does the curriculum define life skills?",
   "options": ["Talents a person is born with",
               "Basic skills acquired through learning and life experience, enabling a person to handle everyday problems and transition to adulthood",
               "Practical trade skills taught at vocational college",
               "Skills only needed after leaving school"],
   "answer": "B",
   "explain": "The key word is 'acquired'. Nobody is born assertive or resilient — which is exactly why a peer educator can change someone's trajectory."},

  {"q": "Which category does self-awareness belong to?",
   "options": ["Skills for dealing with others",
               "Skills for dealing with and coping with oneself",
               "Skills for making effective decisions",
               "None of the above"],
   "answer": "B",
   "explain": "It sits alongside self-esteem, coping with emotions and stress, goal setting and time management."},

  {"q": "Why is self-awareness described as the skill that switches the others on?",
   "options": ["Because it is the easiest to learn",
               "Because you cannot refuse pressure you have not noticed, or manage an emotion you cannot name",
               "Because it is listed first alphabetically",
               "Because it requires no practice"],
   "answer": "B",
   "explain": "Every other skill depends on noticing your own state first."},

  {"q": "Which are ways of coping with strong emotions FOR YOURSELF? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Writing about how you feel",
               "Expressing feelings through art or music",
               "Physical activity",
               "Crying",
               "Using non-judgemental language"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Non-judgemental language is advice for supporting someone else, not for managing your own feelings."},

  {"q": "A peer decides the answer to her anger is to stop feeling angry. What is wrong with that?",
   "options": ["Nothing — emotional control means not feeling it",
               "Suppressed emotion does not disappear; it waits and surfaces where she did not choose",
               "Anger is always healthy and should be expressed freely",
               "She should feel angry more often"],
   "answer": "B",
   "explain": "The skill separates feeling the emotion from acting on it, and gives the feeling somewhere to go."},

  {"q": "What is resilience?",
   "options": ["Never feeling upset",
               "The ability to adapt well in difficult times — bouncing back",
               "Avoiding all challenges",
               "Physical strength"],
   "answer": "B",
   "explain": "Young people face arguments, disappointing results and losses, and need resilience to recover and learn from them."},

  {"q": "Which build resilience per the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Self-respect and self-compassion",
               "Social skills — making friends, resolving conflict, teamwork",
               "Positive thinking habits that stay realistic",
               "Goal-setting, planning and self-discipline",
               "Avoiding situations where you might fail"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Avoidance prevents the very experiences resilience is built from."},

  {"q": "Kiptoo says he failed his mocks so there is no point trying. Which thinking pattern is that?",
   "options": ["Realistic assessment",
               "All-or-nothing thinking, which the curriculum warns against",
               "Creative thinking",
               "Self-awareness"],
   "answer": "B",
   "explain": "'I did badly in one set of exams' and 'I ruined everything' are different sentences. Breaking the goal into something startable is the way back."},

  {"q": "What is the relationship between short-term and long-term goals?",
   "options": ["They are alternatives — choose one",
               "Creating a short-term goal is how a long-term goal actually gets reached",
               "Long-term goals should be set first and short-term ones ignored",
               "Only long-term goals matter"],
   "answer": "B",
   "explain": "Dream big, but start with small, manageable steps. The gap between 'be a doctor' and 'pass this term's biology' is where goals succeed or fail."},

  {"q": "When stress becomes too much, who does the curriculum say to seek help from?",
   "options": ["Nobody — it will pass",
               "A school counsellor, psychologist or spiritual leader",
               "Only a medical doctor",
               "Only your parents"],
   "answer": "B",
   "explain": "Supporting someone through stress is a specific skill — notice, name the source, encourage healthy habits, and escalate when it exceeds those."},
 ],
}
