# Module 5 (part 2 of 2) — Life Skills: Skills With Others and for Decisions
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 5.
# The communication-styles contrast (assertive/aggressive/passive/manipulative)
# is drawn from ARISE's own life-skills lesson, which develops the deck's
# assertiveness section usefully.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m05b-skills-with-others.html",
 "module_code": "M5",
 "module_slug": "life-skills",
 "lesson_slug": "m05b-skills-with-others",
 "module_label": "Peer Educator · M5 · Part 2 of 2",
 "title": "Life Skills — Others and Decisions",
 "icon": "🤝",
 "duration": 45,

 "objectives": [
  ("Apply effective communication and interpersonal relationship skills",
   "Tumia mawasiliano bora na ujuzi wa mahusiano na watu",
   "Tumia effective communication na interpersonal relationship skills"),
  ("Distinguish assertive communication from aggressive and passive",
   "Tofautisha mawasiliano ya ujasiri na ya ushambuliaji na ya unyenyekevu",
   "Tofautisha assertive communication na aggressive na passive"),
  ("Deal with peer pressure and apply empathy in relationships",
   "Kabiliana na shinikizo la rika na utumie huruma katika mahusiano",
   "Deal na peer pressure na utumie empathy kwa relationships"),
  ("Use the problem-solving and decision-making models step by step",
   "Tumia mfano wa kutatua matatizo na wa kufanya maamuzi hatua kwa hatua",
   "Tumia problem-solving na decision-making models step by step"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Saying no costs you something every time. So what makes some young people able to pay that price and others not?",
  "<strong>🔍 Swali Kubwa:</strong> Kusema hapana kunakugharimu kitu kila mara. Basi ni nini kinachowafanya baadhi ya vijana waweze kulipa gharama hiyo na wengine wasiweze?",
  "<strong>🔍 Big Question:</strong> Kusema no kunakugharimu kitu kila time. So ni nini kinachofanya baadhi ya vijana waweze ku-pay hiyo price na wengine wasiweze?"),

 "slides": [

  # ── 1. Interpersonal ──────────────────────────────────────────────
  {"icon": "🤝",
   "head": ("Getting On With People", "Kuelewana na Watu", "Kuelewana na Wasee"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Interpersonal relationship skills", "🔑 Ujuzi wa mahusiano", "🔑 Interpersonal relationship skills"), "text": (
     "The ability to communicate, interact and work effectively with individuals and groups.",
     "Uwezo wa kuwasiliana, kushirikiana na kufanya kazi kwa ufanisi na watu binafsi na makundi.",
     "Uwezo wa ku-communicate, ku-interact na kufanya kazi effectively na watu binafsi na groups.")},
    {"type": "list", "items": [
     ("<strong>Be a good listener</strong> — the skill most people think they already have",
      "<strong>Kuwa msikilizaji mzuri</strong> — ujuzi ambao watu wengi hudhani tayari wanao",
      "<strong>Kuwa good listener</strong> — skill ambayo wasee wengi wanafikiri tayari wanayo"),
     ("<strong>Be honest</strong>",
      "<strong>Kuwa mkweli</strong>",
      "<strong>Kuwa honest</strong>"),
     ("<strong>Be okay with disagreements</strong> — a relationship that cannot survive disagreement is not a strong one",
      "<strong>Kubali kutoelewana</strong> — uhusiano usioweza kuvumilia kutoelewana si imara",
      "<strong>Kuwa okay na disagreements</strong> — relationship isiyoweza ku-survive disagreement si strong"),
     ("<strong>Learn to apologise when you are wrong</strong> — owning up to your mistakes",
      "<strong>Jifunze kuomba msamaha ukikosea</strong> — kukiri makosa yako",
      "<strong>Jifunze ku-apologise ukikosea</strong> — ku-own up makosa yako"),
     ("<strong>Communicate well and regularly</strong> with the people you interact with",
      "<strong>Wasiliana vizuri na mara kwa mara</strong> na watu unaoshirikiana nao",
      "<strong>Communicate vizuri na regularly</strong> na wasee unaoshirikiana nao"),
    ]},
    {"type": "key_term", "term": ("🔑 Empathy", "🔑 Huruma", "🔑 Empathy"), "text": (
     "The ability to imagine what life is like for another person. It makes helping others more likely, and it is central to any successful relationship — with loved ones and with society at large.",
     "Uwezo wa kuwazia maisha yalivyo kwa mtu mwingine. Hufanya kuwasaidia wengine kuwezekane zaidi, na ni msingi wa uhusiano wowote wenye mafanikio — na wapendwa na jamii kwa ujumla.",
     "Uwezo wa ku-imagine maisha yalivyo kwa msee mwingine. Inafanya kusaidia wengine kuwezekane zaidi, na ni central kwa relationship yoyote successful — na wapendwa na society kwa ujumla.")},
   ]},

  # ── 2. Communication ──────────────────────────────────────────────
  {"icon": "💬",
   "head": ("Effective Communication", "Mawasiliano Bora", "Effective Communication"),
   "blocks": [
    {"type": "p", "text": (
     "The ability to express yourself, in words and without them, in ways appropriate to the culture and the situation — opinions, desires, needs and fears.",
     "Uwezo wa kujieleza, kwa maneno na bila maneno, kwa njia zinazofaa utamaduni na hali — maoni, matakwa, mahitaji na hofu.",
     "Uwezo wa kujieleza, kwa maneno na bila maneno, kwa njia zinazofaa culture na situation — opinions, desires, needs na fears.")},
    {"type": "list", "items": [
     ("<strong>Listen actively</strong> — use 'I see', 'tell me more about it', and do not interrupt",
      "<strong>Sikiliza kwa makini</strong> — tumia 'naona', 'nieleze zaidi', na usikatize",
      "<strong>Listen actively</strong> — tumia 'naona', 'nieleze zaidi', na usi-interrupt"),
     ("<strong>Who you are talking to matters</strong> — keep the person in mind as you shape the message",
      "<strong>Unayemzungumzia ni muhimu</strong> — mkumbuke mtu unapounda ujumbe",
      "<strong>Unayem-talk ni muhimu</strong> — m-keep in mind unapo-shape message"),
     ("<strong>Body language matters</strong> — posture, facial expression, gestures, eye movement",
      "<strong>Lugha ya mwili ni muhimu</strong> — mkao, sura, ishara, mwendo wa macho",
      "<strong>Body language ni muhimu</strong> — posture, facial expression, gestures, eye movement"),
     ("<strong>Be brief, yet specific</strong>",
      "<strong>Kuwa mfupi, lakini mahususi</strong>",
      "<strong>Kuwa brief, lakini specific</strong>"),
     ("<strong>Think before you speak</strong>",
      "<strong>Fikiri kabla ya kusema</strong>",
      "<strong>Fikiri kabla u-speak</strong>"),
    ]},
    {"type": "table",
     "headers": [("Style", "Mtindo", "Style"), ("What it sounds like", "Inavyosikika", "Inavyosikika"), ("What it produces", "Inachozalisha", "Inachozalisha")],
     "rows": [
      [("<strong>Assertive</strong>", "<strong>Ujasiri</strong>", "<strong>Assertive</strong>"),
       ("Clear and respectful: 'I feel X when Y happens'",
        "Wazi na kwa heshima: 'Nahisi X Y inapotokea'",
        "Clear na respectful: 'Nahisi X Y inapohappen'"),
       ("Mutual respect; the problem actually gets solved",
        "Heshima ya pande zote; tatizo linatatuliwa kweli",
        "Mutual respect; problem inasolviwa kweli")],
      [("Aggressive", "Ushambuliaji", "Aggressive"),
       ("Dominates, threatens, blames",
        "Hutawala, hutishia, hulaumu",
        "Ina-dominate, ina-threaten, ina-blame"),
       ("Fear, and damaged relationships",
        "Hofu, na mahusiano yaliyoharibika",
        "Fear, na damaged relationships")],
      [("Passive", "Unyenyekevu", "Passive"),
       ("Avoids the conflict, says nothing",
        "Huepuka mgogoro, husema kitu",
        "Ina-avoid conflict, haisemi kitu"),
       ("Resentment builds; needs go unmet",
        "Chuki hujilimbikiza; mahitaji hayatimizwi",
        "Resentment inajilimbikiza; needs hazi-metiwi")],
      [("Manipulative", "Udanganyifu", "Manipulative"),
       ("Uses guilt, tricks or lies",
        "Hutumia hatia, hila au uongo",
        "Ina-use guilt, tricks ama uongo"),
       ("Broken trust",
        "Imani iliyovunjika",
        "Broken trust")],
     ]},
   ]},

  # ── 3. Assertiveness ──────────────────────────────────────────────
  {"icon": "🗣️",
   "head": ("Assertiveness", "Ujasiri", "Assertiveness"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Assertiveness", "🔑 Ujasiri", "🔑 Assertiveness"), "text": (
     "Conveying information and ideas openly and directly, while maintaining respect for the person you are speaking to. It is not aggression with better manners — it is the middle path between attacking and disappearing.",
     "Kufikisha taarifa na mawazo kwa uwazi na moja kwa moja, huku ukidumisha heshima kwa unayemzungumzia. Si ushambuliaji wenye adabu bora — ni njia ya kati kati ya kushambulia na kutoweka.",
     "Ku-convey info na ideas openly na directly, huku uki-maintain respect kwa unayem-speak. Si aggression yenye better manners — ni middle path kati ya ku-attack na kutoweka.")},
    {"type": "list", "items": [
     ("Express your needs, feelings or beliefs clearly and directly, <strong>without feeling guilty</strong>",
      "Eleza mahitaji, hisia au imani yako wazi na moja kwa moja, <strong>bila kujihisi na hatia</strong>",
      "Express needs, feelings ama beliefs zako clearly na directly, <strong>bila kujiskia guilty</strong>"),
     ("Be confident about sharing your opinions and feelings",
      "Jiamini kushiriki maoni na hisia zako",
      "Kuwa confident ku-share opinions na feelings zako"),
     ("Stand up for your beliefs even when others disagree",
      "Simama kwa imani zako hata wengine wasipokubaliana",
      "Simama kwa beliefs zako hata wengine wasi-agree"),
     ("Avoid sounding unsure or unclear when expressing yourself",
      "Epuka kusikika huna uhakika au si wazi unapojieleza",
      "Avoid kusikika huna uhakika ama si clear unapojieleza"),
     ("Do not let yourself be easily led or swayed by others",
      "Usijiruhusu kuongozwa au kuyumbishwa kwa urahisi na wengine",
      "Usijiruhusu ku-lediwa ama ku-swayiwa easily na wengine"),
     ("Do not concede in the face of unexpected difficulties",
      "Usikubali kushindwa unapokabiliwa na ugumu usiotarajiwa",
      "Usi-concede unapoface unexpected difficulties"),
    ]},
    {"type": "tip", "title": ("💡 The I-statement", "💡 Sentensi ya 'Mimi'", "💡 I-statement"), "text": (
     " 'I feel hurt when you ignore me' works where 'you always ignore me' does not. The first states a feeling and invites a response; the second states a verdict and invites a fight. Teach the swap — it is the single most portable communication tool in this module.",
     " 'Nahisi kuumizwa unaponipuuza' hufanya kazi pale 'wewe daima hunipuuza' isipofanya. Ya kwanza inaeleza hisia na kualika jibu; ya pili inaeleza hukumu na kualika ugomvi. Fundisha ubadilishaji huo — ni kifaa cha mawasiliano kinachohamishika zaidi katika moduli hii.",
     " 'Nahisi kuumizwa unaponi-ignore' inawork pale 'wewe daima huni-ignore' isipowork. Ya kwanza ina-state feeling na ku-invite response; ya pili ina-state verdict na ku-invite fight. Fundisha hiyo swap — ni tool ya communication inayo-portable zaidi kwa hii module.")},
   ]},

  # ── 4. Peer pressure ──────────────────────────────────────────────
  {"icon": "👥",
   "head": ("Dealing With Peer Pressure", "Kukabiliana na Shinikizo la Rika", "Ku-deal na Peer Pressure"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Peer pressure", "🔑 Shinikizo la rika", "🔑 Peer pressure"), "text": (
     "The influence of friends, classmates or people your own age to do something you would not otherwise do, because you want to feel accepted and valued. <strong>It can be positive or negative.</strong>",
     "Ushawishi wa marafiki, wanafunzi wenzako au watu wa rika lako kufanya jambo ambalo usingelifanya vinginevyo, kwa sababu unataka kujihisi umekubaliwa na kuthaminiwa. <strong>Linaweza kuwa chanya au hasi.</strong>",
     "Influence ya friends, classmates ama wasee wa age yako kufanya kitu ambacho usingekifanya otherwise, kwa sababu unataka kujiskia accepted na valued. <strong>Inaweza kuwa positive ama negative.</strong>")},
    {"type": "warn", "title": ("⚠️ Do not teach it as only negative", "⚠️ Usifundishe kama hasi tu", "⚠️ Usifundishe kama negative tu"), "text": (
     " Peer pressure is the mechanism peer education itself runs on. The same force that gets a young person to try a cigarette is the one that gets them to test for HIV because their friend did. Your job is not to remove peer influence — it is to become a source of the useful kind.",
     " Shinikizo la rika ndio mbinu ambayo elimu ya rika yenyewe hufanya kazi kwayo. Nguvu ile ile inayomfanya kijana ajaribu sigara ndiyo inayomfanya apime VVU kwa sababu rafiki yake alifanya. Kazi yako si kuondoa ushawishi wa rika — ni kuwa chanzo cha ule wa manufaa.",
     " Peer pressure ndio mechanism ambayo peer education yenyewe inafanya kazi kwayo. Force ile ile inayomfanya kijana a-try cigarette ndio inayomfanya a-test HIV kwa sababu friend wake alifanya. Job yako si kuondoa peer influence — ni kuwa source ya ile ya manufaa.")},
    {"type": "list", "items": [
     ("<strong>Know what is right</strong> — decide before you are in the room, not during",
      "<strong>Jua lililo sahihi</strong> — amua kabla hujawa chumbani, si wakati huo",
      "<strong>Jua kilicho sahihi</strong> — decide kabla uwe kwa room, si wakati huo"),
     ("<strong>Have a friend who will stand with you</strong> — one ally changes the arithmetic completely",
      "<strong>Kuwa na rafiki atakayesimama nawe</strong> — mshirika mmoja hubadilisha hesabu kabisa",
      "<strong>Kuwa na friend atakayesimama na wewe</strong> — ally mmoja inabadilisha arithmetic kabisa"),
     ("<strong>Choose good friends</strong> — this is a decision, made repeatedly, not an accident",
      "<strong>Chagua marafiki wazuri</strong> — huu ni uamuzi, unaofanywa mara kwa mara, si ajali",
      "<strong>Chagua friends wazuri</strong> — hii ni decision, inayofanywa repeatedly, si accident"),
     ("<strong>Walk away</strong> when you are faced with pressure",
      "<strong>Ondoka</strong> unapokabiliwa na shinikizo",
      "<strong>Walk away</strong> unapoface pressure"),
     ("<strong>Get advice from a trusted adult</strong>",
      "<strong>Pata ushauri kutoka kwa mtu mzima unayemwamini</strong>",
      "<strong>Pata advice kutoka kwa mtu mzima unayemtrust</strong>"),
    ]},
   ]},

  # ── 5. Thinking & problem solving ─────────────────────────────────
  {"icon": "🧩",
   "head": ("Thinking, Problem Solving and Deciding", "Kufikiri, Kutatua na Kuamua", "Kufikiri, Ku-solve na Ku-decide"),
   "blocks": [
    {"type": "table",
     "headers": [("Critical thinking", "Fikra makini", "Critical thinking"), ("Creative thinking", "Fikra bunifu", "Creative thinking")],
     "rows": [
      [("Analysing information and experience objectively — working out what is right and what is wrong in the world around you.",
        "Kuchambua taarifa na uzoefu kwa uwazi — kutambua lililo sahihi na lisilo sahihi katika ulimwengu unaokuzunguka.",
        "Ku-analyse info na experience objectively — ku-work out kilicho sahihi na kisicho sahihi kwa world inayokuzunguka."),
       ("Coming up with new ideas and new approaches to a problem. Adolescents need it to deal with peer pressure effectively.",
        "Kubuni mawazo mapya na mbinu mpya za tatizo. Vijana wanahitaji hii kukabiliana na shinikizo la rika kwa ufanisi.",
        "Ku-come up na ideas mpya na approaches mpya za problem. Vijana wanahitaji hii ku-deal na peer pressure effectively.")],
     ]},
    {"type": "table",
     "headers": [("Problem solving — 6 steps", "Kutatua matatizo — hatua 6", "Problem solving — steps 6"),
                 ("Decision making — 6 steps", "Kufanya maamuzi — hatua 6", "Decision making — steps 6")],
     "rows": [
      [("1. Identify and define the problem", "1. Tambua na fafanua tatizo", "1. Identify na define problem"),
       ("1. Identify the problem", "1. Tambua tatizo", "1. Identify problem")],
      [("2. Come up with possible solutions", "2. Buni suluhisho zinazowezekana", "2. Come up na possible solutions"),
       ("2. Get more information on the situation", "2. Pata taarifa zaidi kuhusu hali", "2. Pata info zaidi kuhusu situation")],
      [("3. Evaluate the options", "3. Tathmini chaguo", "3. Evaluate options"),
       ("3. Explore the possible consequences of each course of action", "3. Chunguza matokeo yanayowezekana ya kila njia", "3. Explore possible consequences za kila course of action")],
      [("4. Choose the best solution", "4. Chagua suluhisho bora", "4. Chagua best solution"),
       ("4. Consider the effects on personal and family values", "4. Zingatia athari kwa maadili binafsi na ya familia", "4. Consider effects kwa personal na family values")],
      [("5. Implement it", "5. Itekeleze", "5. I-implement"),
       ("5. Evaluate how the decision may affect other people", "5. Tathmini jinsi uamuzi unavyoweza kuwaathiri wengine", "5. Evaluate jinsi decision inavyoweza ku-affect wengine")],
      [("6. Evaluate the outcome", "6. Tathmini matokeo", "6. Evaluate outcome"),
       ("6. Choose based on your knowledge and your values", "6. Chagua kulingana na maarifa na maadili yako", "6. Chagua kulingana na knowledge na values zako")],
     ]},
    {"type": "facilitator", "minutes": 12, "text": (
     "Give the group one real dilemma — a friend asking them to lie to a parent, say — and walk it through all six decision-making steps out loud. The value is in step 3 and step 5, which almost nobody does naturally: exploring consequences before deciding, and asking who else this lands on.",
     "Lipe kundi tatizo moja halisi — rafiki akiwaomba wamdanganye mzazi, kwa mfano — na lipitishe kwenye hatua zote sita za kufanya maamuzi kwa sauti. Thamani iko katika hatua ya 3 na ya 5, ambazo karibu hakuna anayefanya kwa asili: kuchunguza matokeo kabla ya kuamua, na kuuliza ni nani mwingine anaathirika.",
     "Ipe group dilemma moja real — friend akiwaomba wa-lie kwa mzazi, kwa mfano — na i-walk through steps zote sita za decision-making kwa sauti. Value iko kwa step 3 na step 5, ambazo karibu hakuna msee anafanya naturally: ku-explore consequences kabla ya ku-decide, na kuuliza ni nani mwingine ina-land kwake.")},
   ]},

  # ── 6. Acquiring skills ───────────────────────────────────────────
  {"icon": "📚",
   "head": ("Why They Matter, and How to Get Them", "Kwa Nini Ni Muhimu, na Jinsi ya Kuupata", "Kwa Nini Ni Muhimu, na Jinsi ya Kuzipata"),
   "blocks": [
    {"type": "table",
     "headers": [("Life skills help you", "Ujuzi wa maisha hukusaidia", "Life skills zinakusaidia"),
                 ("You acquire them by", "Unaupata kwa", "Unazipata kwa")],
     "rows": [
      [("Make informed decisions and solve problems",
        "Kufanya maamuzi sahihi na kutatua matatizo",
        "Ku-make informed decisions na ku-solve problems"),
       ("Reading relevant information — books, articles",
        "Kusoma taarifa muhimu — vitabu, makala",
        "Kusoma relevant info — books, articles")],
      [("Think critically and creatively",
        "Kufikiri kwa makini na kwa ubunifu",
        "Kufikiri critically na creatively"),
       ("Seeking advice or counselling from experienced people",
        "Kutafuta ushauri kutoka kwa watu wenye uzoefu",
        "Kutafuta advice ama counselling kutoka kwa wasee wenye experience")],
      [("Communicate effectively and build healthy relationships",
        "Kuwasiliana kwa ufanisi na kujenga mahusiano bora",
        "Ku-communicate effectively na kujenga healthy relationships"),
       ("Interacting with peers",
        "Kushirikiana na wenzako",
        "Ku-interact na wasee wenzako")],
      [("Cope with and manage life",
        "Kukabiliana na kudhibiti maisha",
        "Ku-cope na ku-manage maisha"),
       ("<strong>Accepting correction and criticism</strong>",
        "<strong>Kukubali kusahihishwa na kukosolewa</strong>",
        "<strong>Ku-accept correction na criticism</strong>")],
     ]},
    {"type": "sheng", "text": (
     "Ujuzi wa maisha haufundishwi kwa hotuba moja. Unajengwa kwa mazungumzo mia moja madogo — na wewe ndiye mtu anayeyafanya.",
     "Ujuzi wa maisha haufundishwi kwa hotuba moja. Hujengwa kwa mazungumzo mia moja madogo — na wewe ndiye mtu anayeyafanya.",
     "Life skills hazifundishwi kwa speech moja. Zinajengwa kwa conversations mia moja ndogo — na wewe ndio msee anayezifanya.")},
   ]},

  # ── 7. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "Njoki is upset that her friend keeps reading her messages and not replying. She tells you she is going to confront her with 'you never care about anyone but yourself'.",
      "Njoki amekasirika kwamba rafiki yake anaendelea kusoma ujumbe wake bila kujibu. Anakuambia atamkabili kwa 'wewe hujali mtu yeyote ila nafsi yako'.",
      "Njoki amekasirika ati friend wake anaendelea kusoma messages zake bila ku-reply. Anakuambia atam-confront na 'wewe hu-care mtu yeyote ila wewe mwenyewe'."),
     "question": ("What do you suggest?", "Unapendekeza nini?", "Una-suggest nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell her to say nothing and let it go, to protect the friendship",
                "Mwambie asiseme kitu na aachilie, kulinda urafiki",
                "Mwambie asiseme kitu na a-let go, ku-protect friendship"),
       "outcome": ("That is passive communication, and the curriculum is clear about where it leads — resentment builds and the need goes unmet. Protecting a friendship by never raising anything is how friendships quietly end instead of loudly recovering.",
                   "Hayo ni mawasiliano ya unyenyekevu, na mtaala uko wazi kuhusu yanakoelekea — chuki hujilimbikiza na hitaji halitimizwi. Kulinda urafiki kwa kutoibua chochote ndiyo jinsi urafiki huisha kimya badala ya kupona kwa kelele.",
                   "Hiyo ni passive communication, na curriculum iko wazi kuhusu inakoelekea — resentment inajilimbikiza na need hai-metiwi. Ku-protect friendship kwa kutoi-raise kitu ndio jinsi friendships zinaisha kimya badala ya ku-recover kwa kelele.")},
      {"kind": "good",
       "text": ("Swap the accusation for an I-statement about how it makes her feel",
                "Badilisha shtaka kuwa sentensi ya 'mimi' kuhusu jinsi inavyomfanya ahisi",
                "Swap accusation kuwa I-statement kuhusu jinsi inavyomfanya afeel"),
       "outcome": ("You said: 'Try \"I feel ignored when you read and don't reply\" instead. The first one describes what she does; yours describes what happens to you — and she can answer that without defending herself.' They talked it out that evening. ✅",
                   "Ulisema: 'Jaribu \"Nahisi kupuuzwa unaposoma na usijibu\" badala yake. Ile ya kwanza inaeleza anachofanya; yako inaeleza kinachokutokea — na anaweza kujibu hilo bila kujitetea.' Walizungumza jioni ile. ✅",
                   "Ulisema: 'Try \"Nahisi ku-ignoriwa unaposoma na usi-reply\" badala yake. Ya kwanza ina-describe anachofanya; yako ina-describe kinachokuhappen — na anaweza ku-answer hiyo bila kujitetea.' Waliongea jioni ile. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A peer educator says peer pressure is always bad and should be eliminated from young people's lives entirely.",
      "Mwelimishaji rika anasema shinikizo la rika ni baya daima na linapaswa kuondolewa kabisa maishani mwa vijana.",
      "Peer educator anasema peer pressure ni mbaya daima na inafaa ku-eliminatiwa kabisa kwa maisha ya vijana."),
     "question": ("Is that right?", "Je, ni sahihi?", "Je, ni sahihi?"),
     "choices": [
      {"kind": "bad",
       "text": ("Yes — the whole point of refusal skills is removing peer influence",
                "Ndiyo — lengo lote la ujuzi wa kukataa ni kuondoa ushawishi wa rika",
                "Ndio — point yote ya refusal skills ni kuondoa peer influence"),
       "outcome": ("If peer influence were removed, peer education would stop working — because it is the same mechanism. The curriculum states plainly that peer pressure can be positive or negative. Treating it as only negative undercuts the entire role you are being trained for.",
                   "Ushawishi wa rika ukiondolewa, elimu ya rika ingekoma kufanya kazi — kwa sababu ni mbinu ile ile. Mtaala unasema wazi kwamba shinikizo la rika linaweza kuwa chanya au hasi. Kulichukulia kama hasi tu kunadhoofisha jukumu lote unalofunzwa.",
                   "Peer influence ikiondolewa, peer education ingeacha ku-work — kwa sababu ni mechanism ile ile. Curriculum inasema wazi ati peer pressure inaweza kuwa positive ama negative. Kui-treat kama negative tu kuna-undercut role yote unayo-trainiwa.")},
      {"kind": "good",
       "text": ("No — the goal is to become a source of the positive kind",
                "Hapana — lengo ni kuwa chanzo cha aina chanya",
                "Hapana — goal ni kuwa source ya aina positive"),
       "outcome": ("You said: 'The force that makes someone try a cigarette because their friend did is the same force that makes them go for a test because their friend did. We're not removing it — we're standing in it, on the right side.' That is the job, described in one sentence. ✅",
                   "Ulisema: 'Nguvu inayomfanya mtu ajaribu sigara kwa sababu rafiki yake alifanya ndiyo nguvu inayomfanya aende kupimwa kwa sababu rafiki yake alifanya. Hatuiondoi — tunasimama ndani yake, upande sahihi.' Hiyo ndiyo kazi, imeelezwa kwa sentensi moja. ✅",
                   "Ulisema: 'Force inayomfanya msee a-try cigarette kwa sababu friend wake alifanya ndio force inayomfanya aende ku-test kwa sababu friend wake alifanya. Hatui-remove — tunasimama ndani yake, upande sahihi.' Hiyo ndio job, ime-describiwa kwa sentence moja. ✅")},
     ]},
   ]},

  # ── 8. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Good relationships matter — they make navigating a complex society far easier.",
      "Mahusiano mazuri ni muhimu — hurahisisha sana kupitia jamii tata.",
      "Good relationships ni muhimu — zinarahisisha sana ku-navigate complex society."),
     ("Think before you act, so you can consider the effect on yourself and on others.",
      "Fikiri kabla ya kutenda, ili uweze kuzingatia athari kwako na kwa wengine.",
      "Fikiri kabla u-act, ili uweze ku-consider effect kwako na kwa wengine."),
     ("Stay strong under pressure — stand your ground on your opinions and morals.",
      "Baki imara chini ya shinikizo — simama kwa maoni na maadili yako.",
      "Baki strong chini ya pressure — simama kwa opinions na morals zako."),
     ("Peer pressure can be positive or negative. Your job is to be a source of the positive kind.",
      "Shinikizo la rika linaweza kuwa chanya au hasi. Kazi yako ni kuwa chanzo cha aina chanya.",
      "Peer pressure inaweza kuwa positive ama negative. Job yako ni kuwa source ya aina positive."),
     ("Keep learning life skills — through trusted friends, family, and accepting correction.",
      "Endelea kujifunza ujuzi wa maisha — kupitia marafiki wa kuaminika, familia, na kukubali kusahihishwa.",
      "Endelea kujifunza life skills — kupitia trusted friends, family, na ku-accept correction."),
    ]},
   ]},
 ],

 "quiz": [
  {"q": "Which communication style is 'I feel hurt when you ignore me'?",
   "options": ["Aggressive", "Assertive", "Passive", "Manipulative"],
   "answer": "B",
   "explain": "It states a feeling and invites a response. 'You always ignore me' states a verdict and invites a fight."},

  {"q": "What does passive communication produce?",
   "options": ["Mutual respect and solved problems",
               "Built-up resentment and unmet needs",
               "Fear and damaged relationships",
               "Broken trust"],
   "answer": "B",
   "explain": "Protecting a friendship by never raising anything is how friendships quietly end instead of loudly recovering."},

  {"q": "Is peer pressure always negative?",
   "options": ["Yes, by definition",
               "No — the curriculum states it can be positive or negative",
               "Only for adolescents under 15",
               "Only when it involves substances"],
   "answer": "B",
   "explain": "It is the same mechanism peer education itself runs on. The goal is not removing peer influence but becoming a source of the useful kind."},

  {"q": "Which are tips for dealing with peer pressure? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Knowing what is right, before you are in the room",
               "Having a friend who will stand with you",
               "Choosing good friends",
               "Walking away when faced with pressure",
               "Avoiding all social situations"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Withdrawal is not a life skill. One ally who will stand with you changes the arithmetic completely."},

  {"q": "What is critical thinking?",
   "options": ["Criticising other people's ideas",
               "Analysing information and experience objectively, to distinguish right from wrong",
               "Coming up with new ideas",
               "Making decisions quickly"],
   "answer": "B",
   "explain": "Creative thinking is the one about generating new ideas and approaches — the two work together."},

  {"q": "In the six-step decision-making model, what comes immediately after getting more information?",
   "options": ["Choose the decision",
               "Explore the possible consequences of each course of action",
               "Implement it",
               "Identify the problem"],
   "answer": "B",
   "explain": "Steps 3 and 5 — exploring consequences, and asking who else the decision lands on — are the ones almost nobody does naturally."},

  {"q": "Which are ways of acquiring life skills per the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Reading relevant information",
               "Seeking advice from experienced people",
               "Interacting with peers",
               "Accepting correction and criticism",
               "Waiting until adulthood"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Accepting correction is listed explicitly — and it is the hardest of the four."},

  {"q": "What is empathy?",
   "options": ["Feeling sorry for someone",
               "The ability to imagine what life is like for another person",
               "Agreeing with everyone",
               "Solving other people's problems"],
   "answer": "B",
   "explain": "It increases the likelihood of helping others and is central to successful relationships."},

  {"q": "Which is an interpersonal skill tip from the curriculum?",
   "options": ["Avoid disagreements at all costs",
               "Be okay with disagreements",
               "Never apologise, it shows weakness",
               "Communicate only when necessary"],
   "answer": "B",
   "explain": "A relationship that cannot survive disagreement is not a strong one. Learning to apologise when wrong is on the same list."},

  {"q": "Assertiveness is best described as:",
   "options": ["Aggression with better manners",
               "The middle path between attacking and disappearing — direct, but respectful",
               "Always getting your way",
               "Avoiding conflict"],
   "answer": "B",
   "explain": "Express your needs clearly and without guilt, while maintaining respect for the person you are speaking to."},
 ],
}
