# Module 6 — Nutrition
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 6.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m06-nutrition.html",
 "module_code": "M6",
 "module_slug": "nutrition",
 "lesson_slug": "m06-nutrition",
 "module_label": "Peer Educator · Module 6 of 19",
 "title": "Nutrition",
 "icon": "🥗",
 "duration": 60,

 "objectives": [
  ("Explain why good nutrition matters for adolescent growth and health",
   "Eleza kwa nini lishe bora ni muhimu kwa ukuaji na afya ya vijana",
   "Explain kwa nini good nutrition ni muhimu kwa growth na health ya vijana"),
  ("Identify the main food groups and what the body uses each for",
   "Tambua makundi makuu ya vyakula na mwili hutumia kila kimoja kwa nini",
   "Tambua main food groups na mwili unatumia kila moja kwa nini"),
  ("Describe common nutrition problems among young people",
   "Eleza matatizo ya kawaida ya lishe kwa vijana",
   "Describe common nutrition problems kwa vijana"),
  ("Apply practical healthy-eating choices at school, at home and with friends",
   "Tumia maamuzi ya vitendo ya ulaji bora shuleni, nyumbani na na marafiki",
   "Tumia practical healthy-eating choices shuleni, nyumbani na na friends"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Your body will never grow this fast again after infancy. So why is adolescence the age at which most people start skipping meals?",
  "<strong>🔍 Swali Kubwa:</strong> Mwili wako hautakua kwa kasi hii tena baada ya utoto wa mapema. Basi kwa nini ujana ndio umri ambao watu wengi huanza kuruka milo?",
  "<strong>🔍 Big Question:</strong> Mwili wako hautakua kwa speed hii tena baada ya infancy. So kwa nini adolescence ndio age ambayo wasee wengi wanaanza ku-skip meals?"),

 "slides": [

  {"icon": "📖",
   "head": ("Why This Age Especially", "Kwa Nini Umri Huu Hasa", "Kwa Nini Hii Age Hasa"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Nutrition", "🔑 Lishe", "🔑 Nutrition"), "text": (
     "The intake and use of food and nutrients that support the rapid physical growth, brain development, hormonal change and psychosocial transition of adolescence and early adulthood.",
     "Ulaji na matumizi ya chakula na virutubisho vinavyounga mkono ukuaji wa haraka wa mwili, ukuaji wa ubongo, mabadiliko ya homoni na mpito wa kisaikolojia wa ujana na utu uzima wa mapema.",
     "Intake na use ya chakula na nutrients zinazo-support rapid physical growth, brain development, hormonal change na psychosocial transition ya adolescence na early adulthood.")},
    {"type": "list", "items": [
     ("It provides the <strong>energy</strong> for daily activity, school and work",
      "Hutoa <strong>nguvu</strong> kwa shughuli za kila siku, shule na kazi",
      "Inatoa <strong>energy</strong> kwa daily activity, shule na kazi"),
     ("<strong>Macronutrients</strong> — carbohydrates, proteins, fats — build the body, develop muscle and support reproductive health",
      "<strong>Virutubisho vikuu</strong> — wanga, protini, mafuta — hujenga mwili, hukuza misuli na kuunga mkono afya ya uzazi",
      "<strong>Macronutrients</strong> — carbohydrates, proteins, fats — zinajenga mwili, zina-develop muscle na ku-support reproductive health"),
     ("<strong>Micronutrients</strong> — vitamins and minerals — run immunity, bones, mental wellbeing and disease prevention",
      "<strong>Virutubisho vidogo</strong> — vitamini na madini — huendesha kinga, mifupa, ustawi wa akili na kuzuia magonjwa",
      "<strong>Micronutrients</strong> — vitamins na minerals — zinaendesha immunity, mifupa, mental wellbeing na disease prevention"),
     ("Good nutrition now <strong>lowers the risk of non-communicable disease later</strong> — the diabetes, hypertension and cancers of Module 8",
      "Lishe bora sasa <strong>hupunguza hatari ya magonjwa yasiyoambukiza baadaye</strong> — kisukari, shinikizo la damu na saratani za Moduli 8",
      "Good nutrition saa hii <strong>inapunguza risk ya non-communicable diseases baadaye</strong> — diabetes, hypertension na cancers za Module 8"),
    ]},
    {"type": "tip", "title": ("💡 The line worth memorising", "💡 Sentensi inayostahili kukaririwa", "💡 Line inayostahili ku-memoriwa"), "text": (
     " Macronutrients build the body; micronutrients run it. You can be eating enough and still be undernourished if the second half is missing — which is exactly what a plate of only ugali looks like.",
     " Virutubisho vikuu hujenga mwili; virutubisho vidogo huuendesha. Unaweza kuwa unakula vya kutosha na bado ukawa na utapiamlo kama nusu ya pili haipo — ambayo ndivyo sahani ya ugali peke yake inavyokuwa.",
     " Macronutrients zinajenga mwili; micronutrients zinauendesha. Unaweza kuwa unakula vya kutosha na bado uwe undernourished kama half ya pili haiko — ambayo ndio sahani ya ugali peke yake inavyokuwa.")},
   ]},

  {"icon": "🍽️",
   "head": ("The Food Groups", "Makundi ya Vyakula", "Food Groups"),
   "blocks": [
    {"type": "table",
     "headers": [("Food group", "Kundi la chakula", "Food group"), ("Examples", "Mifano", "Examples"), ("What the body uses it for", "Mwili huitumia kwa nini", "Mwili unaitumia kwa nini")],
     "rows": [
      [("Carbohydrates", "Wanga", "Carbohydrates"),
       ("Rice, maize, bread, potatoes", "Wali, mahindi, mkate, viazi", "Rice, maize, mkate, viazi"),
       ("Energy for learning, sport and daily activity", "Nguvu kwa kujifunza, michezo na shughuli za kila siku", "Energy kwa kujifunza, sports na daily activity")],
      [("Proteins", "Protini", "Proteins"),
       ("Beans, meat, eggs, fish, milk", "Maharagwe, nyama, mayai, samaki, maziwa", "Beans, nyama, mayai, samaki, maziwa"),
       ("Build muscle, support growth, repair tissue", "Kujenga misuli, kuunga mkono ukuaji, kurekebisha tishu", "Kujenga muscle, ku-support growth, ku-repair tissue")],
      [("Fats and oils", "Mafuta", "Fats na oils"),
       ("Nuts, avocado, vegetable oil", "Karanga, parachichi, mafuta ya mimea", "Nuts, avocado, vegetable oil"),
       ("Provide energy and help absorb vitamins", "Kutoa nguvu na kusaidia kunyonya vitamini", "Kutoa energy na kusaidia ku-absorb vitamins")],
      [("Vitamins and minerals", "Vitamini na madini", "Vitamins na minerals"),
       ("Fruits, vegetables, fortified foods", "Matunda, mboga, vyakula vilivyoongezwa virutubisho", "Matunda, mboga, fortified foods"),
       ("Keep immunity strong, protect from illness, support bones and brain", "Kuweka kinga imara, kulinda dhidi ya magonjwa, kuunga mkono mifupa na ubongo", "Ku-keep immunity strong, kulinda dhidi ya illness, ku-support mifupa na brain")],
      [("Water", "Maji", "Water"),
       ("Clean drinking water", "Maji safi ya kunywa", "Maji safi ya kunywa"),
       ("Hydration, digestion, and removing waste", "Kuweka mwili na maji, kusaga chakula, na kuondoa taka", "Hydration, digestion, na kuondoa waste")],
     ]},
    {"type": "list", "items": [
     ("<strong>Eat breakfast every day</strong> — it is what lets you concentrate in class",
      "<strong>Kula kifungua kinywa kila siku</strong> — ndicho kinachokuwezesha kuzingatia darasani",
      "<strong>Kula breakfast kila siku</strong> — ndio inayokuwezesha ku-concentrate class"),
     ("<strong>Limit junk food</strong> — chips, smocha, soda. Too much causes weight gain and health problems",
      "<strong>Punguza vyakula visivyofaa</strong> — chipsi, smocha, soda. Vingi husababisha kuongezeka uzito na matatizo ya afya",
      "<strong>Limit junk food</strong> — chips, smocha, soda. Nyingi zinasababisha weight gain na health problems"),
     ("<strong>Eat colourful plates</strong> — mix greens, reds and yellows for the vitamins",
      "<strong>Kula sahani za rangi</strong> — changanya kijani, nyekundu na njano kwa vitamini",
      "<strong>Kula colourful plates</strong> — mix greens, reds na yellows kwa vitamins"),
     ("<strong>Do not skip meals</strong> — your body needs regular energy to grow and function",
      "<strong>Usiruke milo</strong> — mwili wako unahitaji nguvu za mara kwa mara kukua na kufanya kazi",
      "<strong>Usi-skip meals</strong> — mwili wako unahitaji regular energy kukua na ku-function"),
    ]},
   ]},

  {"icon": "📱",
   "head": ("Nutrition, Body Image and Social Media", "Lishe, Muonekano wa Mwili na Mitandao", "Nutrition, Body Image na Social Media"),
   "blocks": [
    {"type": "p", "text": (
     "Many young people feel pressured to look a certain way. That pressure now arrives every hour, from a screen, comparing them against edited images.",
     "Vijana wengi hujihisi wakishinikizwa kuonekana kwa namna fulani. Shinikizo hilo sasa hufika kila saa, kutoka kwenye skrini, likiwalinganisha na picha zilizohaririwa.",
     "Vijana wengi wanajiskia wame-pressuriwa kuonekana kwa namna fulani. Hiyo pressure saa hii inafika kila saa, kutoka screen, ikiwa-compare na edited images.")},
    {"type": "list", "items": [
     ("<strong>Crash diets and skipping meals harm your health</strong> — especially during the fastest growth years",
      "<strong>Lishe kali za ghafla na kuruka milo hudhuru afya yako</strong> — hasa katika miaka ya ukuaji wa kasi zaidi",
      "<strong>Crash diets na ku-skip meals zinadhuru health yako</strong> — hasa kwa miaka ya fastest growth"),
     ("<strong>Healthy is better than skinny or bulky.</strong> Those are shapes; health is a state.",
      "<strong>Mwenye afya ni bora kuliko mwembamba au mnene.</strong> Hizo ni maumbo; afya ni hali.",
      "<strong>Healthy ni better kuliko skinny ama bulky.</strong> Hizo ni shapes; health ni state."),
     ("Your body and brain are growing fast — <strong>food is your fuel</strong>",
      "Mwili na ubongo wako vinakua kwa kasi — <strong>chakula ni mafuta yako</strong>",
      "Mwili na brain yako zinakua fast — <strong>chakula ni fuel yako</strong>"),
     ("Good nutrition gives energy, strong immunity and better mood; poor nutrition causes weakness, sickness and stunted growth",
      "Lishe bora hutoa nguvu, kinga imara na hali nzuri ya moyo; lishe duni husababisha udhaifu, magonjwa na kudumaa",
      "Good nutrition inatoa energy, strong immunity na better mood; poor nutrition inasababisha udhaifu, magonjwa na stunted growth"),
    ]},
    {"type": "facilitator", "minutes": 10, "text": (
     "Run the deck's discussion question directly: how does social media affect the way you eat? Let it run. The answers usually surface both directions — the fitness content that got someone moving, and the diet content that got someone skipping lunch.",
     "Endesha swali la majadiliano la mtaala moja kwa moja: mitandao ya kijamii inaathiri vipi jinsi unavyokula? Liache liendelee. Majibu kwa kawaida huibua pande zote mbili — maudhui ya mazoezi yaliyomfanya mtu asogee, na maudhui ya lishe yaliyomfanya mtu aruke chakula cha mchana.",
     "Run discussion question ya deck directly: social media inaathiri aje jinsi unavyokula? Iache iendelee. Answers kwa kawaida zina-surface pande zote mbili — fitness content iliyomfanya msee a-move, na diet content iliyomfanya msee a-skip lunch.")},
   ]},

  {"icon": "🔄",
   "head": ("The Cycle That Repeats", "Mzunguko Unaojirudia", "Cycle Inayojirudia"),
   "blocks": [
    {"type": "p", "text": (
     "Nutrition affects every stage of life, and poor nutrition at any stage disrupts the ones that follow — including the next generation.",
     "Lishe huathiri kila hatua ya maisha, na lishe duni katika hatua yoyote huvuruga zinazofuata — ikiwemo kizazi kijacho.",
     "Nutrition inaathiri kila stage ya maisha, na poor nutrition kwa stage yoyote ina-disrupt zinazofuata — ikiwemo generation ijayo.")},
    {"type": "warn", "title": ("⚠️ The intergenerational cycle of undernutrition", "⚠️ Mzunguko wa vizazi wa utapiamlo", "⚠️ Intergenerational cycle ya undernutrition"), "text": (
     " A girl who is stunted is more likely to give birth to a low-birth-weight baby. If that baby is a girl, and nothing intervenes, the cycle continues into the generation after. This is why adolescent girls' nutrition is treated as a public health priority and not a personal preference.",
     " Msichana aliyedumaa ana uwezekano mkubwa wa kuzaa mtoto mwenye uzito mdogo. Mtoto huyo akiwa msichana, na hakuna kinachoingilia, mzunguko huendelea hadi kizazi kinachofuata. Ndiyo maana lishe ya wasichana vijana huchukuliwa kama kipaumbele cha afya ya umma na si upendeleo binafsi.",
     " Dem aliye-stunted ana uwezekano mkubwa wa kuzaa mtoto mwenye low birth weight. Huyo mtoto akiwa dem, na hakuna kinacho-intervene, cycle inaendelea hadi generation inayofuata. Ndio maana nutrition ya wasichana vijana ina-treatiwa kama public health priority si personal preference.")},
   ]},

  {"icon": "⚖️",
   "head": ("Overweight and Obesity", "Unene na Kunenepa Kupita Kiasi", "Overweight na Obesity"),
   "blocks": [
    {"type": "p", "text": (
     "These happen when the energy taken in from food and drink exceeds what the body uses, over a long period.",
     "Haya hutokea wakati nguvu zinazopatikana kutoka chakula na vinywaji zinapozidi anachotumia mwili, kwa muda mrefu.",
     "Hizi zinahappen wakati energy inayopatikana kutoka chakula na drinks inazidi anachotumia mwili, kwa muda mrefu.")},
    {"type": "table",
     "headers": [("Overweight", "Unene", "Overweight"), ("Obesity", "Kunenepa kupita kiasi", "Obesity")],
     "rows": [
      [("Having more body weight than is healthy for your height.",
        "Kuwa na uzito zaidi ya ulio na afya kwa urefu wako.",
        "Kuwa na body weight zaidi ya iliyo healthy kwa height yako."),
       ("When extra body fat builds up to a level that can harm your health.",
        "Pale mafuta ya ziada mwilini yanapojilimbikiza hadi kiwango kinachoweza kudhuru afya yako.",
        "Pale extra body fat inapojilimbikiza hadi level inayoweza kudhuru health yako.")],
     ]},
    {"type": "table",
     "headers": [("Signs to notice", "Dalili za kuona", "Signs za kuona"), ("Complications later", "Matatizo baadaye", "Complications baadaye")],
     "rows": [
      [("Increase in body weight or waist size; clothes feeling tighter",
        "Kuongezeka kwa uzito au ukubwa wa kiuno; nguo kubana zaidi",
        "Kuongezeka kwa weight ama waist size; nguo kubana zaidi"),
       ("Type 2 diabetes", "Kisukari aina ya 2", "Type 2 diabetes")],
      [("Tiring easily, or short of breath after light activity",
        "Kuchoka haraka, au kupumua kwa shida baada ya shughuli nyepesi",
        "Kuchoka haraka, ama shortness of breath baada ya light activity"),
       ("High blood pressure and heart disease", "Shinikizo la juu la damu na magonjwa ya moyo", "High blood pressure na heart disease")],
      [("Low self-esteem or body image concerns",
        "Kujithamini duni au wasiwasi kuhusu muonekano",
        "Low self-esteem ama body image concerns"),
       ("Joint problems, and breathing problems such as sleep apnoea",
        "Matatizo ya viungo, na matatizo ya kupumua kama kukoroma kwa kusimamisha pumzi",
        "Joint problems, na breathing problems kama sleep apnoea")],
      [("Joint pain, skin changes or snoring",
        "Maumivu ya viungo, mabadiliko ya ngozi au kukoroma",
        "Joint pain, skin changes ama kukoroma"),
       ("Low self-esteem and possible depression; certain cancers later in life",
        "Kujithamini duni na huenda msongo wa mawazo; saratani fulani baadaye maishani",
        "Low self-esteem na huenda depression; cancers fulani baadaye maishani")],
     ]},
    {"type": "tip", "title": ("💡 How to raise this without shaming", "💡 Jinsi ya kuibua bila kuaibisha", "💡 Jinsi ya ku-raise bila ku-shame"), "text": (
     " Talk about energy, breath and how someone feels — not about how they look. 'Are you getting tired faster than you used to?' opens a conversation. Anything about appearance closes it, and pushes a young person toward exactly the crash diets this module warns against.",
     " Zungumza kuhusu nguvu, pumzi na jinsi mtu anavyojisikia — si jinsi anavyoonekana. 'Je, unachoka haraka kuliko zamani?' hufungua mazungumzo. Chochote kuhusu muonekano hukifunga, na humsukuma kijana kuelekea hasa lishe kali za ghafla ambazo moduli hii inaonya dhidi yake.",
     " Ongea kuhusu energy, pumzi na jinsi msee anavyojiskia — si jinsi anavyoonekana. 'Je, unachoka haraka kuliko zamani?' inafungua conversation. Chochote kuhusu appearance inaifunga, na inamsukuma kijana kuelekea hasa crash diets ambazo hii module inaonya dhidi yake.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "Chebet, 16, has started skipping lunch every day. She says she saw a video about getting slim before the holidays and it is working.",
      "Chebet, miaka 16, ameanza kuruka chakula cha mchana kila siku. Anasema aliona video kuhusu kupungua uzito kabla ya likizo na inafanya kazi.",
      "Chebet, 16, ameanza ku-skip lunch kila siku. Anasema aliona video kuhusu kuwa slim kabla ya holidays na ina-work."),
     "question": ("What do you say?", "Unasema nini?", "Unasema nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell her she looks fine as she is and should stop worrying",
                "Mwambie anaonekana sawa jinsi alivyo na aache kuwa na wasiwasi",
                "Mwambie anaonekana poa jinsi alivyo na aache ku-worry"),
       "outcome": ("Reassurance about appearance keeps the conversation about appearance, which is the frame that got her here. She has also just been told her judgement is wrong without being given any reason — so she will simply stop mentioning it.",
                   "Faraja kuhusu muonekano huweka mazungumzo kuhusu muonekano, ambao ndio mfumo uliomfikisha hapa. Pia ameambiwa tu uamuzi wake si sahihi bila kupewa sababu yoyote — hivyo ataacha tu kulitaja.",
                   "Reassurance kuhusu appearance inaweka conversation kuhusu appearance, ambayo ndio frame iliyomfikisha hapa. Pia ameambiwa tu judgement yake si sahihi bila kupewa reason yoyote — so ata-stop tu kuitaja.")},
      {"kind": "good",
       "text": ("Move the frame from how she looks to what her body is doing right now",
                "Hamisha mfumo kutoka anavyoonekana hadi mwili wake unafanya nini sasa",
                "Move frame kutoka anavyoonekana hadi mwili wake unafanya nini saa hii"),
       "outcome": ("You said: 'Your body is growing faster now than it will again in your life. Skipping lunch doesn't take fat off — it takes fuel off, and you'll feel it in class by two o'clock. Healthy beats skinny, and you can't grow on an empty tank.' She started eating lunch again, and asked what to eat rather than whether to. ✅",
                   "Ulisema: 'Mwili wako unakua kwa kasi zaidi sasa kuliko utakavyokua tena maishani mwako. Kuruka chakula cha mchana hakuondoi mafuta — kunaondoa mafuta ya kuendesha, na utahisi darasani saa nane. Kuwa na afya kunashinda kuwa mwembamba, na huwezi kukua na tangi tupu.' Alianza kula tena, na akauliza ale nini badala ya kama ale. ✅",
                   "Ulisema: 'Mwili wako unakua faster saa hii kuliko utakavyokua tena maishani. Ku-skip lunch hai-take fat off — ina-take fuel off, na uta-feel class by two. Healthy inabeat skinny, na huwezi kukua na tank tupu.' Alianza kukula lunch tena, na akauliza akule nini badala ya kama akule. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A peer says he cannot eat well because his family can only afford ugali and sukuma most days.",
      "Rika anasema hawezi kula vizuri kwa sababu familia yake inaweza kumudu ugali na sukuma tu siku nyingi.",
      "Msee anasema hawezi kukula vizuri kwa sababu family yake inaweza ku-afford ugali na sukuma tu siku nyingi."),
     "question": ("What is the useful response?", "Jibu lenye manufaa ni lipi?", "Response yenye manufaa ni ipi?"),
     "choices": [
      {"kind": "bad",
       "text": ("List the food groups again and tell him he needs protein daily",
                "Orodhesha makundi ya vyakula tena na umwambie anahitaji protini kila siku",
                "List food groups tena na umwambie anahitaji protein kila siku"),
       "outcome": ("Repeating the ideal to someone who cannot afford it teaches them that nutrition advice is not for people like them. That is how a young person stops listening to health messaging altogether.",
                   "Kurudia lililo bora kwa mtu asiyeweza kulimudu kunamfundisha kwamba ushauri wa lishe si kwa watu kama yeye. Ndivyo kijana huacha kusikiliza ujumbe wa afya kabisa.",
                   "Kurudia ideal kwa msee asiyeweza kui-afford kunamfundisha ati nutrition advice si ya wasee kama yeye. Ndio jinsi kijana ana-stop kusikiliza health messaging kabisa.")},
      {"kind": "good",
       "text": ("Work with what is actually on the plate — and find the cheapest thing that improves it",
                "Fanya kazi na kilicho kwenye sahani hasa — na utafute kitu cha bei nafuu zaidi kinachoiboresha",
                "Work na kilicho kwa plate hasa — na utafute kitu cha bei nafuu zaidi kinachoi-improve"),
       "outcome": ("You said: 'Ugali and sukuma is already carbohydrate and vegetable — that's two groups. Beans are the cheapest protein there is, and even a small handful in the sukuma changes the plate. What does it cost at your shop?' He worked it out himself. ✅",
                   "Ulisema: 'Ugali na sukuma tayari ni wanga na mboga — hayo ni makundi mawili. Maharagwe ndiyo protini ya bei nafuu zaidi iliyopo, na hata konzi ndogo kwenye sukuma hubadilisha sahani. Yanagharimu kiasi gani dukani kwenu?' Alijifanyia hesabu mwenyewe. ✅",
                   "Ulisema: 'Ugali na sukuma tayari ni carbohydrate na vegetable — hayo ni groups mbili. Beans ndio protein ya bei nafuu zaidi iliyopo, na hata handful ndogo kwa sukuma inabadilisha plate. Zina-cost ngapi kwa duka lenu?' Ali-work out mwenyewe. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Adolescence is a period of rapid growth — nutrition demand peaks here.",
      "Ujana ni kipindi cha ukuaji wa haraka — mahitaji ya lishe hufikia kilele hapa.",
      "Adolescence ni period ya rapid growth — nutrition demand ina-peak hapa."),
     ("Macronutrients build the body; micronutrients run it.",
      "Virutubisho vikuu hujenga mwili; virutubisho vidogo huuendesha.",
      "Macronutrients zinajenga mwili; micronutrients zinauendesha."),
     ("Healthy is better than skinny or bulky. Crash diets harm a growing body.",
      "Kuwa na afya ni bora kuliko kuwa mwembamba au mnene. Lishe kali za ghafla hudhuru mwili unaokua.",
      "Healthy ni better kuliko skinny ama bulky. Crash diets zinadhuru mwili unaokua."),
     ("Overweight and obesity are a growing threat — and largely preventable through everyday choices.",
      "Unene na kunenepa kupita kiasi ni tishio linaloongezeka — na linaweza kuzuiwa kwa kiasi kikubwa kupitia maamuzi ya kila siku.",
      "Overweight na obesity ni threat inayoongezeka — na inaweza ku-preventiwa kwa kiasi kikubwa kupitia everyday choices."),
     ("Healthy habits today mean healthier generations tomorrow.",
      "Tabia bora leo maana yake vizazi vyenye afya zaidi kesho.",
      "Healthy habits leo inamaanisha healthier generations kesho."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Chakula si suala la muonekano. Ni mafuta ya kuendesha mwili unaokua kwa kasi zaidi utakavyokua maishani mwako.",
     "Chakula si suala la muonekano. Ni mafuta ya kuendesha mwili unaokua kwa kasi zaidi utakavyokua maishani mwako.",
     "Chakula si issue ya appearance. Ni fuel ya mwili unaokua faster zaidi utakavyokua maishani mwako.")},
   ]},
 ],

 "quiz": [
  {"q": "Which statement best captures the role of the two nutrient types?",
   "options": ["Macronutrients and micronutrients do the same job",
               "Macronutrients build the body; micronutrients run it",
               "Only macronutrients matter for adolescents",
               "Micronutrients provide most of the body's energy"],
   "answer": "B",
   "explain": "You can eat enough and still be undernourished if the micronutrients are missing — which is what a plate of only ugali looks like."},

  {"q": "Which food group does the body use mainly to build muscle and repair tissue?",
   "options": ["Carbohydrates", "Proteins", "Fats and oils", "Water"],
   "answer": "B",
   "explain": "Beans, meat, eggs, fish and milk. Beans are the cheapest protein available in most Kenyan markets."},

  {"q": "What do fats and oils do besides providing energy?",
   "options": ["Build muscle", "Help the body absorb vitamins", "Remove waste", "Strengthen bones directly"],
   "answer": "B",
   "explain": "Which is why a completely fat-free diet undermines the vitamins in an otherwise good plate."},

  {"q": "Which are healthy eating tips from the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Eat breakfast every day", "Limit junk food like chips, smocha and soda",
               "Eat colourful plates", "Skip meals to control weight", "Do not skip meals"],
   "answer": ["A", "B", "C", "E"],
   "explain": "Skipping meals removes fuel, not fat — and does most damage during the fastest growth years."},

  {"q": "What is the intergenerational cycle of undernutrition?",
   "options": ["Undernutrition only affects the person experiencing it",
               "A stunted girl is more likely to give birth to a low-birth-weight baby, and if that baby is a girl the cycle continues",
               "It refers to families sharing meals",
               "It only occurs in famine conditions"],
   "answer": "B",
   "explain": "This is why adolescent girls' nutrition is a public health priority rather than a personal preference."},

  {"q": "What causes overweight and obesity?",
   "options": ["Eating any fat at all",
               "Energy taken in exceeding energy the body uses, over a long period",
               "Genetics alone",
               "Eating carbohydrates"],
   "answer": "B",
   "explain": "Overweight means more weight than is healthy for your height; obesity is when extra fat reaches a level that can harm health."},

  {"q": "Which are complications of obesity named in the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Type 2 diabetes", "High blood pressure and heart disease",
               "Joint problems and sleep apnoea", "Certain cancers later in life", "Improved endurance"],
   "answer": ["A", "B", "C", "D"],
   "explain": "These connect directly to Module 8 — the non-communicable diseases now rising among young Kenyans."},

  {"q": "Chebet is skipping lunch after seeing a video about getting slim. What is the best response?",
   "options": ["Tell her she looks fine as she is",
               "Move the frame from how she looks to what her body is doing right now",
               "Agree it will work short-term",
               "Tell her to eat more instead"],
   "answer": "B",
   "explain": "Reassurance about appearance keeps the conversation about appearance — which is the frame that got her there."},

  {"q": "A peer's family can only afford ugali and sukuma most days. What helps most?",
   "options": ["List the food groups again",
               "Work with what is on the plate and find the cheapest thing that improves it",
               "Tell him nutrition is not important for him",
               "Suggest he eat at friends' houses"],
   "answer": "B",
   "explain": "Repeating the ideal to someone who cannot afford it teaches them health advice is not for people like them."},

  {"q": "How should a peer educator raise weight concerns without shaming?",
   "options": ["Comment on how the person looks",
               "Talk about energy, breath and how they feel — not appearance",
               "Suggest a diet plan",
               "Compare them to others in the group"],
   "answer": "B",
   "explain": "Anything about appearance closes the conversation and pushes a young person toward the crash diets this module warns against."},
 ],
}
