# Module 7 — Physical Activity
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 7.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m07-physical-activity.html",
 "module_code": "M7",
 "module_slug": "physical-activity",
 "lesson_slug": "m07-physical-activity",
 "module_label": "Peer Educator · Module 7 of 19",
 "title": "Physical Activity",
 "icon": "🏃",
 "duration": 60,

 "objectives": [
  ("Explain the benefits of physical activity for health, mental well-being and peer connectedness",
   "Eleza faida za mazoezi kwa afya, ustawi wa akili na uhusiano na wenzako",
   "Explain benefits za physical activity kwa health, mental well-being na peer connectedness"),
  ("Demonstrate and guide peers in safe, age-appropriate activities",
   "Onyesha na uwaongoze wenzako katika shughuli salama zinazofaa umri",
   "Onyesha na u-guide wasee kwa safe, age-appropriate activities"),
  ("Use inclusive approaches for peers of differing abilities and fitness levels",
   "Tumia mbinu jumuishi kwa wenzako wenye uwezo na viwango tofauti vya siha",
   "Tumia inclusive approaches kwa wasee wenye abilities na fitness levels tofauti"),
  ("Organise, lead and sustain a peer-led activity session",
   "Panga, ongoza na udumishe kipindi cha mazoezi kinachoongozwa na rika",
   "Organise, lead na u-sustain peer-led activity session"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> The peers who most need to move are usually the ones least likely to join in. How do you design a session for the person standing at the edge?",
  "<strong>🔍 Swali Kubwa:</strong> Wenzako wanaohitaji zaidi kusogea kwa kawaida ndio wasio na uwezekano wa kujiunga. Unabuni vipi kipindi kwa ajili ya aliyesimama pembeni?",
  "<strong>🔍 Big Question:</strong> Wasee wanaohitaji zaidi ku-move kwa kawaida ndio wasio na uwezekano wa kujoin. Una-design aje session kwa ajili ya msee aliyesimama pembeni?"),

 "slides": [

  {"icon": "📖",
   "head": ("The Words", "Maneno", "Maneno"),
   "blocks": [
    {"type": "table",
     "headers": [("Term", "Neno", "Term"), ("Meaning", "Maana", "Maana")],
     "rows": [
      [("Physical activity", "Mazoezi ya mwili", "Physical activity"),
       ("Any movement of the body that uses energy — walking, running, dancing, playing games.",
        "Mwendo wowote wa mwili unaotumia nguvu — kutembea, kukimbia, kucheza dansi, kucheza michezo.",
        "Movement yoyote ya mwili inayotumia energy — kutembea, kukimbia, kucheza dance, kucheza games.")],
      [("Exercise", "Zoezi", "Exercise"),
       ("A planned, structured form of physical activity done to improve fitness and health.",
        "Aina iliyopangwa na yenye mpangilio ya mazoezi inayofanywa kuboresha siha na afya.",
        "Planned, structured form ya physical activity inayofanywa ku-improve fitness na health.")],
      [("Fitness", "Siha", "Fitness"),
       ("The ability of the body to perform daily tasks with energy, strength and endurance.",
        "Uwezo wa mwili kufanya kazi za kila siku kwa nguvu, imara na uvumilivu.",
        "Uwezo wa mwili kufanya daily tasks kwa energy, strength na endurance.")],
      [("Well-being", "Ustawi", "Well-being"),
       ("A state of feeling healthy, balanced and positive in body, mind and social life.",
        "Hali ya kujisikia mwenye afya, uwiano na chanya kimwili, kiakili na kijamii.",
        "State ya kujiskia healthy, balanced na positive kimwili, kiakili na kijamii.")],
      [("Warm-up", "Kujipasha moto", "Warm-up"),
       ("Light movements or stretches before activity, to prepare the body and prevent injury.",
        "Mienendo mepesi au kunyoosha kabla ya mazoezi, kuandaa mwili na kuzuia majeraha.",
        "Light movements ama stretches kabla ya activity, ku-prepare mwili na ku-prevent injury.")],
      [("Cool-down", "Kupoa", "Cool-down"),
       ("Gentle activity and stretching after exercise, to help the body recover.",
        "Shughuli nyepesi na kunyoosha baada ya mazoezi, kusaidia mwili kupona.",
        "Gentle activity na stretching baada ya exercise, kusaidia mwili ku-recover.")],
      [("Endurance / flexibility", "Uvumilivu / unyumbufu", "Endurance / flexibility"),
       ("Endurance is keeping going without tiring quickly. Flexibility is muscles and joints moving freely.",
        "Uvumilivu ni kuendelea bila kuchoka haraka. Unyumbufu ni misuli na viungo kusogea kwa uhuru.",
        "Endurance ni kuendelea bila kuchoka haraka. Flexibility ni muscles na joints ku-move freely.")],
     ]},
    {"type": "warn", "title": ("⚠️ Warm-up and cool-down are not optional extras", "⚠️ Kujipasha moto na kupoa si vya ziada", "⚠️ Warm-up na cool-down si optional extras"), "text": (
     " Most avoidable injuries in a peer-led session happen because someone went straight from sitting to sprinting. If you are leading, you lead the warm-up too — and you do not let anyone skip it because they arrived late.",
     " Majeraha mengi yanayoweza kuepukwa katika kipindi kinachoongozwa na rika hutokea kwa sababu mtu alitoka kukaa moja kwa moja hadi kukimbia. Ukiwa unaongoza, unaongoza pia kujipasha moto — na huruhusu yeyote kuruka kwa sababu amechelewa.",
     " Injuries nyingi zinazoweza ku-avoidiwa kwa peer-led session zinahappen kwa sababu msee alitoka kukaa directly hadi kukimbia. Ukiwa una-lead, una-lead pia warm-up — na huruhusu yeyote ku-skip kwa sababu amechelewa.")},
   ]},

  {"icon": "💪",
   "head": ("What Movement Actually Does", "Mwendo Hufanya Nini Hasa", "Movement Inafanya Nini Hasa"),
   "blocks": [
    {"type": "table",
     "headers": [("Benefit", "Faida", "Benefit"), ("How", "Jinsi gani", "Jinsi gani")],
     "rows": [
      [("Healthy growth and development", "Ukuaji na maendeleo bora", "Healthy growth na development"),
       ("Strengthens muscles, bones and joints, and supports proper posture.",
        "Huimarisha misuli, mifupa na viungo, na huunga mkono mkao sahihi.",
        "Ina-strengthen muscles, mifupa na joints, na ina-support proper posture.")],
      [("Improves mental well-being", "Huboresha ustawi wa akili", "Ina-improve mental well-being"),
       ("Releases endorphins that reduce stress, anxiety and depression, while boosting confidence.",
        "Hutoa endorfini zinazopunguza msongo, wasiwasi na huzuni, huku zikiongeza kujiamini.",
        "Ina-release endorphins zinazopunguza stress, anxiety na depression, huku zikiboost confidence.")],
      [("Prevents lifestyle diseases", "Huzuia magonjwa ya mtindo wa maisha", "Ina-prevent lifestyle diseases"),
       ("Active teens are less likely to develop obesity, type 2 diabetes and heart problems later in life.",
        "Vijana wenye shughuli wana uwezekano mdogo wa kupata unene, kisukari aina ya 2 na matatizo ya moyo baadaye.",
        "Active teens wana uwezekano mdogo wa ku-develop obesity, type 2 diabetes na heart problems baadaye.")],
      [("Enhances academic performance", "Huboresha ufaulu wa masomo", "Ina-improve academic performance"),
       ("Studies show active students often have better focus, memory and problem-solving.",
        "Tafiti zinaonyesha wanafunzi wenye shughuli mara nyingi wana umakini, kumbukumbu na utatuzi bora.",
        "Studies zinaonyesha active students mara nyingi wana better focus, memory na problem-solving.")],
     ]},
    {"type": "tip", "title": ("💡 The argument that actually persuades", "💡 Hoja inayoshawishi kweli", "💡 Argument inayo-persuade kweli"), "text": (
     " Telling a young person exercise prevents heart disease in forty years persuades nobody. Telling them it improves concentration before an exam, and lifts mood the same day, is a benefit they can verify this week. Lead with the immediate one.",
     " Kumwambia kijana mazoezi huzuia ugonjwa wa moyo baada ya miaka arobaini hakumshawishi mtu. Kumwambia huboresha umakini kabla ya mtihani, na huinua hali ya moyo siku hiyo hiyo, ni faida anayoweza kuithibitisha wiki hii. Anza na ile ya papo hapo.",
     " Kumwambia kijana exercise ina-prevent heart disease baada ya miaka arobaini hai-persuade mtu. Kumwambia ina-improve concentration kabla ya exam, na ina-lift mood siku hiyo hiyo, ni benefit anayoweza kui-verify wiki hii. Anza na ile ya immediate.")},
   ]},

  {"icon": "🚧",
   "head": ("Why Peers Do Not Take Part", "Kwa Nini Wenzako Hawashiriki", "Kwa Nini Wasee Hawa-participate"),
   "blocks": [
    {"type": "p", "text": (
     "Before you design a session, know what you are designing around. These are the real barriers — and only one of them is about motivation.",
     "Kabla ya kubuni kipindi, jua unabuni kuzunguka nini. Hivi ndivyo vizuizi halisi — na kimoja tu kati yake kinahusu hamasa.",
     "Kabla u-design session, jua una-design kuzunguka nini. Hizi ndio real barriers — na moja tu kati yake ni kuhusu motivation.")},
    {"type": "list", "items": [
     ("Busy school, work or household schedules leave little room for regular exercise",
      "Ratiba zenye shughuli za shule, kazi au nyumbani huacha nafasi ndogo ya mazoezi ya kawaida",
      "Busy school, work ama household schedules zinaacha nafasi ndogo ya regular exercise"),
     ("Few safe spaces, little equipment, and no organised opportunities",
      "Maeneo machache salama, vifaa vichache, na hakuna fursa zilizopangwa",
      "Safe spaces chache, equipment kidogo, na hakuna organised opportunities"),
     ("Some peers are disinterested, or have never been encouraged to be active",
      "Baadhi ya wenzako hawana hamu, au hawajawahi kuhimizwa kuwa na shughuli",
      "Baadhi ya wasee hawana interest, ama hawajawahi ku-encouragiwa kuwa active"),
     ("<strong>Chronic illness, disability, or fear of injury</strong> discourage participation",
      "<strong>Magonjwa sugu, ulemavu, au hofu ya kujeruhiwa</strong> huvunja moyo wa kushiriki",
      "<strong>Chronic illness, disability, ama fear ya injury</strong> zinavunja moyo wa kushiriki"),
     ("Unsafe neighbourhoods, poor infrastructure or insecurity limit outdoor activity",
      "Mitaa isiyo salama, miundombinu duni au ukosefu wa usalama hupunguza shughuli za nje",
      "Unsafe neighbourhoods, poor infrastructure ama insecurity zinapunguza outdoor activity"),
     ("Limited money for gym fees, sports gear or transport",
      "Pesa kidogo za ada za mazoezi, vifaa vya michezo au usafiri",
      "Pesa kidogo za gym fees, sports gear ama transport"),
     ("Excessive phone, video game and social media use reduces active time",
      "Matumizi ya kupita kiasi ya simu, michezo ya video na mitandao hupunguza muda wa shughuli",
      "Excessive phone, video game na social media use inapunguza active time"),
    ]},
    {"type": "sheng", "text": (
     "Mtu anayesimama pembeni mara nyingi si mvivu. Hana viatu, au anaogopa kuchekwa, au anaumwa na hakuna aliyeuliza.",
     "Mtu anayesimama pembeni mara nyingi si mvivu. Hana viatu, au anaogopa kuchekwa, au anaumwa na hakuna aliyeuliza.",
     "Msee anayesimama pembeni mara nyingi si lazy. Hana viatu, ama anaogopa kuchekwa, ama anaumwa na hakuna aliyeuliza.")},
   ]},

  {"icon": "🤲",
   "head": ("Running an Inclusive Session", "Kuendesha Kipindi Jumuishi", "Ku-run Inclusive Session"),
   "blocks": [
    {"type": "p", "text": (
     "An inclusive session is one where the least confident person present still takes part. That is the test — not how much fun the most athletic people had.",
     "Kipindi jumuishi ni kile ambapo mtu asiye na ujasiri zaidi aliyepo bado hushiriki. Hicho ndicho kipimo — si furaha kiasi gani watu wenye siha zaidi walipata.",
     "Inclusive session ni ile ambapo msee asiye na confidence zaidi aliyepo bado ana-participate. Hicho ndio test — si fun kiasi gani wasee wenye fitness zaidi walipata.")},
    {"type": "list", "items": [
     ("<strong>Offer levels, not one standard.</strong> Walk, jog or run — same activity, three entry points.",
      "<strong>Toa viwango, si kiwango kimoja.</strong> Tembea, kimbia polepole au kimbia — shughuli ile ile, njia tatu za kuingia.",
      "<strong>Toa levels, si standard moja.</strong> Tembea, jog ama run — activity ile ile, entry points tatu."),
     ("<strong>Avoid picking teams by captains.</strong> It publicly ranks everyone, and the same people are chosen last every time.",
      "<strong>Epuka kuchagua timu kwa manahodha.</strong> Hupanga kila mtu hadharani, na watu wale wale huchaguliwa mwisho kila mara.",
      "<strong>Avoid ku-pick teams na captains.</strong> Ina-rank kila msee publicly, na wasee wale wale wana-choosiwa last kila time."),
     ("<strong>Adapt rather than exclude.</strong> Someone who cannot run can keep score, throw, or play a seated version.",
      "<strong>Rekebisha badala ya kuwatenga.</strong> Asiyeweza kukimbia anaweza kuhesabu alama, kurusha, au kucheza toleo la kukaa.",
      "<strong>Adapt badala ya ku-exclude.</strong> Asiyeweza kukimbia anaweza ku-keep score, ku-throw, ama kucheza seated version."),
     ("<strong>Ask about health conditions quietly before you start</strong> — asthma, sickle cell, an old injury. Never in front of the group.",
      "<strong>Uliza kuhusu hali za afya kwa utulivu kabla ya kuanza</strong> — pumu, selimundu, jeraha la zamani. Kamwe si mbele ya kundi.",
      "<strong>Uliza kuhusu health conditions kwa utulivu kabla uanze</strong> — asthma, sickle cell, injury ya zamani. Kamwe si mbele ya group."),
     ("<strong>Make it free.</strong> If a session needs shoes, gear or fees, it excludes exactly the peers who benefit most.",
      "<strong>Ifanye bure.</strong> Kipindi kikihitaji viatu, vifaa au ada, kinawatenga hasa wenzako wanaonufaika zaidi.",
      "<strong>Ifanye free.</strong> Session ikihitaji viatu, gear ama fees, ina-exclude hasa wasee wanao-benefit zaidi."),
    ]},
    {"type": "table",
     "headers": [("Active games to try", "Michezo ya kujaribu", "Active games za ku-try"),
                 ("Mind-body activities", "Shughuli za mwili na akili", "Mind-body activities")],
     "rows": [
      [("Simple football or kickball drills", "Mazoezi rahisi ya mpira", "Simple football ama kickball drills"),
       ("Yoga-inspired stretches for balance and calm", "Kunyoosha kwa mtindo wa yoga kwa uwiano na utulivu", "Yoga-inspired stretches kwa balance na calm")],
      [("Skipping rope competitions", "Mashindano ya kamba", "Skipping rope competitions"),
       ("Mindful walking — walk slowly in silence, focusing on breathing", "Kutembea kwa umakini — tembea polepole kimya, ukizingatia kupumua", "Mindful walking — tembea polepole kimya, uki-focus kwa kupumua")],
      [("Tug-of-war with a rope or cloth", "Kuvutana kamba au kitambaa", "Tug-of-war na rope ama cloth"),
       ("Relaxation circle — sit or lie comfortably, short guided meditation", "Duara la kupumzika — kaa au lala kwa raha, tafakuri fupi", "Relaxation circle — kaa ama lala comfortably, short guided meditation")],
      [("Frisbee or ball toss in pairs or groups", "Kurushiana mpira kwa jozi au vikundi", "Frisbee ama ball toss kwa pairs ama groups"),
       ("", "", "")],
     ]},
    {"type": "facilitator", "minutes": 20, "text": (
     "Actually run one. Warm up for five minutes, play one game for ten, cool down for five. Then ask the group who did not take part and why — and fix that for next week. A session you discussed is worth less than a session you ran badly and improved.",
     "Kiendeshe kweli. Jipasheni moto kwa dakika tano, chezeni mchezo mmoja kwa dakika kumi, poeni kwa dakika tano. Kisha uliza kundi ni nani hakushiriki na kwa nini — na urekebishe hilo kwa wiki ijayo. Kipindi ulichojadili kina thamani ndogo kuliko kipindi ulichoendesha vibaya na ukakiboresha.",
     "I-run kweli. Warm up kwa dakika tano, chezeni game moja kwa dakika kumi, cool down kwa dakika tano. Kisha uliza group ni nani hakushiriki na kwa nini — na u-fix hiyo kwa wiki ijayo. Session uliyoi-discuss ina value ndogo kuliko session uliyoi-run vibaya na uka-improve.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "You are running a session. One girl stands at the edge every week and never joins. Today someone shouts at her to stop being lazy.",
      "Unaendesha kipindi. Msichana mmoja husimama pembeni kila wiki na hajiungi kamwe. Leo mtu anampigia kelele aache uvivu.",
      "Una-run session. Dem mmoja anasimama pembeni kila wiki na hajoin kamwe. Leo msee anampigia kelele aache uvivu."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Encourage her publicly to join in — a bit of pressure will get her started",
                "Mhimize hadharani ajiunge — shinikizo kidogo litamfanya aanze",
                "M-encourage publicly a-join — pressure kidogo itamfanya aanze"),
       "outcome": ("Public encouragement is still public attention on the thing she is avoiding. The curriculum lists chronic illness, disability and fear of injury as real barriers — and she has now been called lazy in front of everyone and then singled out by you.",
                   "Kuhimiza hadharani bado ni umakini wa hadharani kwa jambo analoliepuka. Mtaala unaorodhesha magonjwa sugu, ulemavu na hofu ya kujeruhiwa kama vizuizi halisi — na sasa ameitwa mvivu mbele ya kila mtu kisha ukamtenga wewe.",
                   "Public encouragement bado ni public attention kwa kitu anachoi-avoid. Curriculum ina-list chronic illness, disability na fear ya injury kama real barriers — na saa hii ameitwa lazy mbele ya kila msee kisha uka-single her out.")},
      {"kind": "good",
       "text": ("Stop the name-calling, then ask her privately afterwards what would make it possible",
                "Simamisha matusi, kisha umuulize faraghani baadaye ni nini kingefanya iwezekane",
                "Stop hiyo name-calling, kisha umuulize privately baadaye ni nini kingefanya iwezekane"),
       "outcome": ("You said to the group that nobody gets called lazy in your session, and moved on quickly. Afterwards you asked her quietly. She had asthma and had never told anyone. The following week you built in a walking option and she took part. ✅",
                   "Uliambia kundi kwamba hakuna anayeitwa mvivu katika kipindi chako, na ukaendelea haraka. Baadaye ulimuuliza kwa utulivu. Alikuwa na pumu na hakuwahi kumwambia mtu. Wiki iliyofuata uliweka chaguo la kutembea na akashiriki. ✅",
                   "Uliambia group ati hakuna msee anaitwa lazy kwa session yako, na ukaendelea haraka. Baadaye ulimuuliza kwa utulivu. Alikuwa na asthma na hakuwahi kumwambia msee. Wiki iliyofuata uli-build in walking option na aka-participate. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "Your school has no equipment, no field markings, and no budget. Peers tell you a physical activity programme is impossible here.",
      "Shule yako haina vifaa, hakuna alama za uwanja, na hakuna bajeti. Wenzako wanakuambia programu ya mazoezi haiwezekani hapa.",
      "Shule yako haina equipment, hakuna field markings, na hakuna budget. Wasee wanakuambia physical activity programme haiwezekani hapa."),
     "question": ("What is the honest answer?", "Jibu la ukweli ni lipi?", "Honest answer ni ipi?"),
     "choices": [
      {"kind": "bad",
       "text": ("Agree — without equipment there is not much that can be done",
                "Kubaliana — bila vifaa hakuna mengi yanayoweza kufanyika",
                "Agree — bila equipment hakuna mengi yanayoweza kufanyika"),
       "outcome": ("Every activity in this curriculum needs at most a rope or a cloth. Agreeing that equipment is required accepts a barrier that is not actually there, and the peers who most need to move go on not moving.",
                   "Kila shughuli katika mtaala huu inahitaji zaidi kamba au kitambaa. Kukubali kwamba vifaa vinahitajika ni kukubali kizuizi ambacho hakipo hasa, na wenzako wanaohitaji zaidi kusogea wanaendelea kutosogea.",
                   "Kila activity kwa hii curriculum inahitaji zaidi rope ama cloth. Ku-agree ati equipment inahitajika ni ku-accept barrier ambayo haiko hasa, na wasee wanaohitaji zaidi ku-move wanaendelea kutosogea.")},
      {"kind": "good",
       "text": ("Point out that every activity on the list needs nothing but people and space",
                "Onyesha kwamba kila shughuli kwenye orodha haihitaji chochote ila watu na nafasi",
                "Onyesha ati kila activity kwa list haihitaji kitu ila wasee na space"),
       "outcome": ("You said: 'Tug-of-war needs a cloth. Skipping needs one rope. Mindful walking needs nothing at all. The gap here isn't equipment — it's that nobody has organised it, and that's the thing we can actually fix.' You ran the first session that Friday. ✅",
                   "Ulisema: 'Kuvutana kunahitaji kitambaa. Kuruka kamba kunahitaji kamba moja. Kutembea kwa umakini hakuhitaji chochote. Pengo hapa si vifaa — ni kwamba hakuna aliyepanga, na hilo ndilo tunaloweza kurekebisha kweli.' Uliendesha kipindi cha kwanza Ijumaa hiyo. ✅",
                   "Ulisema: 'Tug-of-war inahitaji cloth. Skipping inahitaji rope moja. Mindful walking haihitaji kitu. Gap hapa si equipment — ni ati hakuna msee ame-organise, na hiyo ndio tunaweza ku-fix kweli.' Uli-run session ya kwanza hiyo Friday. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Physical activity is a tool for social connection, not just fitness.",
      "Mazoezi ni chombo cha kuunganisha kijamii, si siha tu.",
      "Physical activity ni tool ya social connection, si fitness tu."),
     ("Any activity is better than none — all movement counts.",
      "Shughuli yoyote ni bora kuliko hakuna — kila mwendo unahesabika.",
      "Activity yoyote ni better kuliko hakuna — kila movement ina-count."),
     ("Design sessions that prioritise fun, interaction and emotional well-being alongside physical health.",
      "Buni vipindi vinavyopa kipaumbele furaha, mwingiliano na ustawi wa kihisia pamoja na afya ya mwili.",
      "Design sessions zinazo-prioritise fun, interaction na emotional well-being pamoja na physical health."),
     ("Use games and group challenges to break down barriers and build trust.",
      "Tumia michezo na changamoto za kikundi kuvunja vizuizi na kujenga imani.",
      "Tumia games na group challenges ku-break barriers na kujenga trust."),
     ("Shared movement reduces isolation and builds mental resilience.",
      "Mwendo wa pamoja hupunguza upweke na kujenga uthabiti wa akili.",
      "Shared movement inapunguza isolation na kujenga mental resilience."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Kipindi kizuri si kile ambapo wenye siha zaidi walifurahia. Ni kile ambapo aliyesimama pembeni alijiunga.",
     "Kipindi kizuri si kile ambapo wenye siha zaidi walifurahia. Ni kile ambapo aliyesimama pembeni alijiunga.",
     "Session poa si ile ambapo wenye fitness zaidi walienjoy. Ni ile ambapo msee aliyesimama pembeni ali-join.")},
   ]},
 ],

 "quiz": [
  {"q": "What is the difference between physical activity and exercise?",
   "options": ["They are the same thing",
               "Physical activity is any movement using energy; exercise is planned, structured activity to improve fitness",
               "Exercise is easier than physical activity",
               "Physical activity only happens in sport"],
   "answer": "B",
   "explain": "Walking, dancing and playing all count as physical activity — which matters, because 'all movement counts'."},

  {"q": "Why does the curriculum insist on warm-up and cool-down?",
   "options": ["They make sessions longer",
               "Warm-up prepares the body and prevents injury; cool-down helps it recover",
               "They are only needed for competitive sport",
               "They are optional for young people"],
   "answer": "B",
   "explain": "Most avoidable injuries in a peer-led session happen when someone goes straight from sitting to sprinting."},

  {"q": "Which benefit is most persuasive to an adolescent?",
   "options": ["Preventing heart disease in forty years",
               "Improved concentration before an exam and better mood the same day",
               "Living longer",
               "Reducing medical costs"],
   "answer": "B",
   "explain": "Lead with the benefit they can verify this week. The long-term ones are true but persuade nobody at fifteen."},

  {"q": "Which are barriers to physical activity named in the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Busy school, work or household schedules",
               "Few safe spaces or equipment",
               "Chronic illness, disability or fear of injury",
               "Limited money for gear or transport",
               "Simple laziness"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Only one listed barrier is about motivation at all. The person standing at the edge usually has a reason nobody asked about."},

  {"q": "What makes a session inclusive?",
   "options": ["Everyone does exactly the same thing",
               "The least confident person present still takes part",
               "The most athletic people enjoy it",
               "It follows official sports rules"],
   "answer": "B",
   "explain": "That is the test — not how much fun the fittest people had."},

  {"q": "Why should you avoid picking teams by captains?",
   "options": ["It takes too long",
               "It publicly ranks everyone, and the same people are chosen last every time",
               "Captains cannot be trusted",
               "It is against the rules"],
   "answer": "B",
   "explain": "Adapt rather than exclude — and never build a ritual that humiliates the same peers weekly."},

  {"q": "How should you ask about health conditions before a session?",
   "options": ["In front of the group so everyone knows",
               "Quietly and privately before you start",
               "Not at all — it is intrusive",
               "Only ask those who look unfit"],
   "answer": "B",
   "explain": "Asthma, sickle cell or an old injury all matter for what you plan — but never surface them publicly."},

  {"q": "A peer says a programme is impossible without equipment. What is the honest answer?",
   "options": ["They are right — equipment is essential",
               "Tug-of-war needs a cloth, skipping needs one rope, mindful walking needs nothing",
               "They should fundraise first",
               "Only schools with fields can run sessions"],
   "answer": "B",
   "explain": "The gap is usually organisation, not equipment — and organisation is the thing a peer educator can actually fix."},

  {"q": "Which are mind-body activities suggested in the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Yoga-inspired stretches", "Mindful walking in silence",
               "A guided relaxation circle", "Competitive sprinting"],
   "answer": ["A", "B", "C"],
   "explain": "Sessions should prioritise fun, interaction and emotional well-being alongside physical health."},

  {"q": "What does 'physical activity is a tool for social connection' mean for a peer educator?",
   "options": ["Fitness results are unimportant",
               "Shared movement reduces isolation and builds mental resilience — the session is also a mental health intervention",
               "Only group sports count",
               "Sessions should be competitive"],
   "answer": "B",
   "explain": "Use games and group challenges to break down barriers and build trust — which is why this module connects directly to Module 9."},
 ],
}
