# Module 9 (part 1 of 2) — Mental Health, Stress and Common Conditions
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 9.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m09a-mental-health-and-stress.html",
 "module_code": "M9",
 "module_slug": "mental-health",
 "lesson_slug": "m09a-mental-health-and-stress",
 "module_label": "Peer Educator · M9 · Part 1 of 2",
 "title": "Mental Health, Stress and Common Conditions",
 "icon": "💚",
 "duration": 45,

 "objectives": [
  ("Define mental health and explain its place in overall well-being",
   "Fafanua afya ya akili na ueleze nafasi yake katika ustawi wa jumla",
   "Define mental health na explain nafasi yake kwa overall well-being"),
  ("Distinguish healthy from unhealthy ways of coping with stress",
   "Tofautisha njia bora na mbaya za kukabiliana na msongo",
   "Tofautisha healthy na unhealthy ways za ku-cope na stress"),
  ("Describe the common mental health conditions among young people",
   "Eleza hali za kawaida za afya ya akili kwa vijana",
   "Describe common mental health conditions kwa vijana"),
  ("Recognise when a normal reaction has become something needing help",
   "Tambua wakati majibu ya kawaida yamekuwa jambo linalohitaji msaada",
   "Tambua wakati normal reaction imekuwa kitu kinachohitaji msaada"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Everyone feels sad and everyone gets stressed. So how does anyone tell the difference between a hard week and a condition?",
  "<strong>🔍 Swali Kubwa:</strong> Kila mtu huhisi huzuni na kila mtu hupata msongo. Basi mtu anajuaje tofauti kati ya wiki ngumu na hali ya ugonjwa?",
  "<strong>🔍 Big Question:</strong> Kila msee anafeel sad na kila msee anapata stress. So msee anajuaje tofauti kati ya wiki ngumu na condition?"),

 "slides": [

  # ── 1. Definition ─────────────────────────────────────────────────
  {"icon": "📖",
   "head": ("What Mental Health Actually Means", "Afya ya Akili Inamaanisha Nini Hasa", "Mental Health Inamaanisha Nini Hasa"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Mental health", "🔑 Afya ya akili", "🔑 Mental health"), "text": (
     "A state of mental well-being that enables people to cope with the stresses of life, realise their abilities, learn and work well, and contribute to their community.",
     "Hali ya ustawi wa akili inayomwezesha mtu kukabiliana na misongo ya maisha, kutambua uwezo wake, kujifunza na kufanya kazi vizuri, na kuchangia jamii yake.",
     "State ya mental well-being inayomwezesha msee ku-cope na stress za maisha, ku-realise abilities zake, kujifunza na kufanya kazi vizuri, na ku-contribute kwa community yake.")},
    {"type": "p", "text": (
     "Notice what that definition is not. It does not say 'the absence of problems' or 'being happy all the time'. Mental health is about capacity to cope — which means it goes up and down, for everyone.",
     "Angalia ufafanuzi huo si nini. Hausemi 'kutokuwa na matatizo' au 'kuwa na furaha kila wakati'. Afya ya akili inahusu uwezo wa kukabiliana — maana yake hupanda na kushuka, kwa kila mtu.",
     "Angalia hiyo definition si nini. Haisemi 'kutokuwa na problems' ama 'kuwa happy kila time'. Mental health ni kuhusu capacity ya ku-cope — meaning inapanda na kushuka, kwa kila msee.")},
    {"type": "table",
     "headers": [("Term", "Neno", "Term"), ("Meaning", "Maana", "Maana")],
     "rows": [
      [("Mental illness / disorder", "Ugonjwa wa akili", "Mental illness / disorder"),
       ("A condition affecting thinking, emotions, behaviour or mood in ways that disrupt daily life.",
        "Hali inayoathiri fikra, hisia, tabia au hali ya moyo kwa njia zinazovuruga maisha ya kila siku.",
        "Condition inayoathiri thinking, emotions, behaviour ama mood kwa njia zinazo-disrupt daily life.")],
      [("Well-being", "Ustawi", "Well-being"),
       ("The overall balance of physical, emotional and social health.",
        "Uwiano wa jumla wa afya ya kimwili, kihisia na kijamii.",
        "Overall balance ya physical, emotional na social health.")],
      [("Stigma", "Unyanyapaa", "Stigma"),
       ("Negative attitudes, discrimination or stereotypes toward people with mental health challenges.",
        "Mitazamo hasi, ubaguzi au dhana potofu dhidi ya watu wenye changamoto za afya ya akili.",
        "Negative attitudes, discrimination ama stereotypes dhidi ya wasee wenye mental health challenges.")],
      [("Suicidal ideation", "Mawazo ya kujiua", "Suicidal ideation"),
       ("Thinking about, considering or planning suicide.",
        "Kufikiria, kutafakari au kupanga kujiua.",
        "Kufikiria, ku-consider ama ku-plan suicide.")],
      [("Stress", "Msongo", "Stress"),
       ("A response to a perceived threat, caused by a hormonal surge — and it can help you respond to a problem.",
        "Majibu kwa tishio linaloonekana, yanayosababishwa na ongezeko la homoni — na yanaweza kukusaidia kukabiliana na tatizo.",
        "Response kwa perceived threat, inayosababishwa na hormonal surge — na inaweza kukusaidia ku-respond kwa problem.")],
     ]},
   ]},

  # ── 2. Continuum ──────────────────────────────────────────────────
  {"icon": "📊",
   "head": ("Mental Health Is a Continuum", "Afya ya Akili ni Mfululizo", "Mental Health ni Continuum"),
   "blocks": [
    {"type": "p", "text": (
     "There is no line with 'healthy' on one side and 'mentally ill' on the other. Everyone moves along a range, in both directions, throughout life.",
     "Hakuna mstari wenye 'mwenye afya' upande mmoja na 'mgonjwa wa akili' upande mwingine. Kila mtu husogea kwenye mfululizo, pande zote mbili, maisha yote.",
     "Hakuna line yenye 'healthy' upande mmoja na 'mentally ill' upande mwingine. Kila msee anasogea kwa range, pande zote mbili, maisha yote.")},
    {"type": "tip", "title": ("💡 Why the continuum matters to a peer educator", "💡 Kwa nini mfululizo ni muhimu kwa mwelimishaji rika", "💡 Kwa nini continuum ni muhimu kwa peer educator"), "text": (
     " If mental health is two boxes, then asking for help means admitting you are in the bad box — and almost nobody will. If it is a range everyone moves along, asking for help is just noticing which way you are moving. That single reframe removes more stigma than any speech.",
     " Kama afya ya akili ni masanduku mawili, basi kuomba msaada ni kukiri uko sanduku baya — na karibu hakuna atakayefanya. Kama ni mfululizo ambao kila mtu husogea, kuomba msaada ni kutambua tu unaelekea upande upi. Mabadiliko hayo moja ya mtazamo huondoa unyanyapaa kuliko hotuba yoyote.",
     " Kama mental health ni boxes mbili, basi kuomba msaada ni ku-admit uko kwa bad box — na karibu hakuna atakayefanya. Kama ni range ambayo kila msee anasogea, kuomba msaada ni ku-notice tu unaelekea upande upi. Hiyo reframe moja inaondoa stigma kuliko speech yoyote.")},
    {"type": "sheng", "text": (
     "Hakuna mtu 'mwenye afya ya akili' au 'mwenye kichaa'. Kuna watu walio karibu na upande mmoja wa mfululizo leo, na wanaweza kuwa upande mwingine mwaka ujao. Wewe pia.",
     "Hakuna mtu 'mwenye afya ya akili' au 'mwenye kichaa'. Kuna watu walio karibu na upande mmoja wa mfululizo leo, na wanaweza kuwa upande mwingine mwaka ujao. Wewe pia.",
     "Hakuna msee 'mwenye mental health' ama 'mwenye kichaa'. Kuna wasee walio karibu na upande mmoja wa continuum leo, na wanaweza kuwa upande mwingine next year. Wewe pia.")},
   ]},

  # ── 3. Stress ─────────────────────────────────────────────────────
  {"icon": "😰",
   "head": ("Stress — the Useful Kind and the Harmful Kind", "Msongo — Aina ya Manufaa na ya Madhara", "Stress — Aina ya Manufaa na ya Madhara"),
   "blocks": [
    {"type": "p", "text": (
     "Stress is the body reacting to a demanding situation. Depending on the situation, that reaction can be positive or negative.",
     "Msongo ni mwili kuitikia hali inayodai. Kulingana na hali, majibu hayo yanaweza kuwa chanya au hasi.",
     "Stress ni mwili ku-react kwa demanding situation. Kulingana na situation, hiyo reaction inaweza kuwa positive ama negative.")},
    {"type": "table",
     "headers": [("Eustress — positive", "Eustress — chanya", "Eustress — positive"),
                 ("Distress — negative", "Distress — hasi", "Distress — negative")],
     "rows": [
      [("Occurs when the occasion is positive — an exam you are ready for, a match, a performance. It sharpens you.",
        "Hutokea tukio linapokuwa chanya — mtihani uliojiandaa, mechi, onyesho. Hukunoa.",
        "Inahappen occasion inapokuwa positive — exam uliyo-prepare, match, performance. Inakunoa."),
       ("The reaction that overwhelms rather than sharpens — and if it stays, it starts doing damage.",
        "Majibu yanayozidi badala ya kunoa — na yakibaki, huanza kudhuru.",
        "Reaction inayo-overwhelm badala ya kunoa — na ikibaki, inaanza kudhuru.")],
     ]},
    {"type": "list", "items": [
     ("<strong>Signs of distress:</strong> isolation, disrupted sleep, little interest in normal duties, changed eating habits, fatigue, low self-worth, easy irritability, feeling rejected by family or friends",
      "<strong>Dalili za distress:</strong> kujitenga, usingizi uliovurugika, hamu ndogo ya kazi za kawaida, mabadiliko ya ulaji, uchovu, kujithamini duni, kukasirika haraka, kujihisi umekataliwa na familia au marafiki",
      "<strong>Signs za distress:</strong> kujitenga, disrupted sleep, interest ndogo kwa duties za kawaida, changed eating habits, fatigue, low self-worth, kukasirika haraka, kujiskia rejected na family ama friends"),
     ("<strong>And this one is never ordinary stress:</strong> negative thoughts of harming oneself, including suicide",
      "<strong>Na hii kamwe si msongo wa kawaida:</strong> mawazo hasi ya kujidhuru, ikiwemo kujiua",
      "<strong>Na hii kamwe si ordinary stress:</strong> negative thoughts za kujidhuru, ikiwemo suicide"),
    ]},
    {"type": "table",
     "headers": [("❌ Unhealthy coping", "❌ Kukabiliana vibaya", "❌ Unhealthy coping"),
                 ("✅ Healthy coping", "✅ Kukabiliana vizuri", "✅ Healthy coping")],
     "rows": [
      [("Withdrawal and isolation", "Kujitenga na upweke", "Withdrawal na isolation"),
       ("Talking to someone", "Kuzungumza na mtu", "Kuongea na msee")],
      [("Substance use", "Matumizi ya dawa za kulevya", "Substance use"),
       ("Physical activity", "Mazoezi ya mwili", "Physical activity")],
      [("Overworking, or avoidance", "Kufanya kazi kupita kiasi, au kuepuka", "Overworking, ama avoidance"),
       ("Rest and good sleep habits", "Kupumzika na tabia nzuri za usingizi", "Rest na good sleep habits")],
      [("Emotional eating or restrictive dieting", "Kula kwa hisia au kujizuia kula", "Emotional eating ama restrictive dieting"),
       ("Faith and spiritual practice", "Imani na mazoea ya kiroho", "Faith na spiritual practice")],
      [("Screen time addiction; negative thinking", "Uraibu wa skrini; fikra hasi", "Screen time addiction; negative thinking"),
       ("Structured problem-solving", "Kutatua matatizo kwa mpangilio", "Structured problem-solving")],
     ]},
    {"type": "warn", "title": ("⚠️ Notice the overlap with Module 10", "⚠️ Angalia mwingiliano na Moduli 10", "⚠️ Angalia overlap na Module 10"), "text": (
     " 'Substance use' sits at the top of the unhealthy coping list, and 'to cope with stress' sits on Module 10's list of why young people start. Those are the same young person, described twice. Treat mental health and substance use as one conversation, not two.",
     " 'Matumizi ya dawa' yapo juu ya orodha ya kukabiliana vibaya, na 'kukabiliana na msongo' yapo kwenye orodha ya Moduli 10 ya kwa nini vijana huanza. Huyo ni kijana yule yule, ameelezwa mara mbili. Chukulia afya ya akili na matumizi ya dawa kama mazungumzo moja, si mawili.",
     " 'Substance use' iko juu ya list ya unhealthy coping, na 'ku-cope na stress' iko kwa list ya Module 10 ya kwa nini vijana wanaanza. Huyo ni kijana yule yule, ame-describiwa mara mbili. Chukulia mental health na substance use kama conversation moja, si mbili.")},
   ]},

  # ── 4. Categories ─────────────────────────────────────────────────
  {"icon": "🗂️",
   "head": ("Two Categories of Condition", "Makundi Mawili ya Hali", "Categories Mbili za Condition"),
   "blocks": [
    {"type": "table",
     "headers": [("Neurodevelopmental", "Za kuzaliwa nazo", "Neurodevelopmental"),
                 ("Acquired", "Zinazopatikana", "Acquired")],
     "rows": [
      [("Present from birth or early development",
        "Zipo tangu kuzaliwa au ukuaji wa mapema",
        "Ziko tangu kuzaliwa ama early development"),
       ("Develop later in life, from varied circumstances",
        "Hukua baadaye maishani, kutokana na mazingira tofauti",
        "Zina-develop baadaye maishani, kutokana na circumstances tofauti")],
      [("Autism Spectrum Disorder, ADHD, learning disorders such as dyslexia, intellectual developmental disorder, cerebral palsy",
        "Ugonjwa wa Tawahudi, ADHD, matatizo ya kujifunza kama dyslexia, ulemavu wa akili, kupooza kwa ubongo",
        "Autism Spectrum Disorder, ADHD, learning disorders kama dyslexia, intellectual developmental disorder, cerebral palsy"),
       ("Depression, anxiety, bipolar disorder, PTSD, substance use disorders, schizophrenia, personality disorder, suicide",
        "Msongo wa mawazo, wasiwasi, bipolar, PTSD, matatizo ya matumizi ya dawa, skizofrenia, matatizo ya utu, kujiua",
        "Depression, anxiety, bipolar disorder, PTSD, substance use disorders, schizophrenia, personality disorder, suicide")],
     ]},
    {"type": "list", "items": [
     ("<strong>Signs of a neurodevelopmental condition:</strong> delayed milestones such as late walking; poor coordination and balance; inattention or hyperactivity; difficulty focusing, sitting still or following instructions",
      "<strong>Dalili za hali ya kuzaliwa nayo:</strong> kuchelewa hatua kama kutembea; uratibu duni na usawa; kutozingatia au kuhangaika; ugumu wa kuzingatia, kukaa tuli au kufuata maelekezo",
      "<strong>Signs za neurodevelopmental condition:</strong> delayed milestones kama kutembea late; poor coordination na balance; inattention ama hyperactivity; ugumu wa ku-focus, kukaa tuli ama kufuata instructions"),
     ("Also emotional regulation difficulty, social challenges such as avoiding eye contact, repetitive behaviour such as hand-flapping or rocking, and language delays",
      "Pia ugumu wa kudhibiti hisia, changamoto za kijamii kama kuepuka mawasiliano ya macho, tabia za kurudia kama kupiga mikono au kuyumba, na kuchelewa kwa lugha",
      "Pia ugumu wa emotional regulation, social challenges kama ku-avoid eye contact, repetitive behaviour kama hand-flapping ama rocking, na language delays"),
     ("<strong>Children born with these conditions grow into vulnerable young people needing care and protection</strong> — and many develop skills and live full lives when nurtured properly",
      "<strong>Watoto waliozaliwa na hali hizi hukua kuwa vijana walio hatarini wanaohitaji malezi na ulinzi</strong> — na wengi hukuza ujuzi na kuishi maisha kamili wakilelewa vizuri",
      "<strong>Watoto waliozaliwa na hizi conditions wanakua kuwa vulnerable young people wanaohitaji care na protection</strong> — na wengi wana-develop skills na kuishi full lives wakilelewa vizuri"),
    ]},
   ]},

  # ── 5. Anxiety, depression, PTSD ──────────────────────────────────
  {"icon": "🩺",
   "head": ("The Three You Will Meet Most", "Tatu Utakazokutana Nazo Zaidi", "Tatu Utakutana Nazo Zaidi"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Anxiety", "🔑 Wasiwasi", "🔑 Anxiety"), "text": (
     "Anxiety is a natural response to a stressful situation. Prolonged, it causes panic attacks and phobias. Signs: constant worrying, restlessness, fast heartbeat, sweating, trouble sleeping, avoiding friends and family. <strong>Seek help if it has gone on more than two weeks.</strong>",
     "Wasiwasi ni majibu ya asili kwa hali ya msongo. Ukiendelea, husababisha mashambulizi ya hofu na woga mkubwa. Dalili: kuwa na wasiwasi daima, kutotulia, mapigo ya haraka ya moyo, kutokwa jasho, ugumu wa kulala, kuepuka marafiki na familia. <strong>Tafuta msaada ukiendelea zaidi ya wiki mbili.</strong>",
     "Anxiety ni natural response kwa stressful situation. Ikiendelea, inasababisha panic attacks na phobias. Signs: kuwa na worry daima, restlessness, fast heartbeat, kutokwa jasho, ugumu wa kulala, ku-avoid friends na family. <strong>Tafuta msaada ikiendelea zaidi ya wiki mbili.</strong>")},
    {"type": "p", "text": (
     "<strong>Depression</strong> is persistent sadness lasting <strong>two weeks or more</strong>, with loss of interest, worthlessness, difficulty concentrating and changes in appetite and sleep. The signs group under seven headings:",
     "<strong>Msongo wa mawazo</strong> ni huzuni endelevu inayodumu <strong>wiki mbili au zaidi</strong>, na kupoteza hamu, kujiona huna thamani, ugumu wa kuzingatia na mabadiliko ya hamu ya kula na usingizi. Dalili hujipanga chini ya vichwa saba:",
     "<strong>Depression</strong> ni persistent sadness inayodumu <strong>wiki mbili ama zaidi</strong>, na kupoteza interest, kujiona huna value, ugumu wa ku-concentrate na changes za appetite na sleep. Signs zina-group chini ya headings saba:")},
    {"type": "table",
     "headers": [("Area", "Eneo", "Area"), ("What it looks like", "Inavyoonekana", "Inavyoonekana")],
     "rows": [
      [("Sleep", "Usingizi", "Sleep"), ("Insomnia, or sleeping far too much", "Kukosa usingizi, au kulala kupita kiasi", "Insomnia, ama kulala kupita kiasi")],
      [("Interest", "Hamu", "Interest"), ("Loss of interest or pleasure in activities once enjoyed", "Kupoteza hamu au furaha katika shughuli zilizokuwa zikifurahisha", "Kupoteza interest ama pleasure kwa activities zilizokuwa zikifurahisha")],
      [("Guilt", "Hatia", "Guilt"), ("Worthlessness, hopelessness or excessive regret", "Kujiona huna thamani, kukata tamaa au majuto makubwa", "Worthlessness, hopelessness ama excessive regret")],
      [("Energy", "Nguvu", "Energy"), ("Fatigue and exhaustion", "Uchovu na kuishiwa nguvu", "Fatigue na exhaustion")],
      [("Concentration", "Umakini", "Concentration"), ("Difficulty focusing, poor concentration, indecisiveness", "Ugumu wa kuzingatia, umakini duni, kutoamua", "Ugumu wa ku-focus, poor concentration, kutodecide")],
      [("Appetite", "Hamu ya kula", "Appetite"), ("Significant change in appetite or weight, up or down", "Mabadiliko makubwa ya hamu ya kula au uzito, juu au chini", "Significant change ya appetite ama weight, juu ama chini")],
      [("Psychomotor", "Mwendo", "Psychomotor"), ("Agitation and restlessness, or slowed movement and speech", "Kuhangaika na kutotulia, au mwendo na maongezi ya polepole", "Agitation na restlessness, ama slowed movement na speech")],
      [("Suicide", "Kujiua", "Suicide"), ("Recurrent thoughts of death, suicidal ideation, or attempts", "Mawazo ya mara kwa mara ya kifo, mawazo ya kujiua, au majaribio", "Recurrent thoughts za kifo, suicidal ideation, ama attempts")],
     ]},
    {"type": "key_term", "term": ("🔑 Post Traumatic Stress Disorder (PTSD)", "🔑 PTSD", "🔑 Post Traumatic Stress Disorder (PTSD)"), "text": (
     "Develops after experiencing a traumatic event — the death of a loved one, an accident, conflict or a natural disaster. Signs: flashbacks (reliving it as if it is happening again), nightmares, unwanted intrusive memories, and emotional or physical reactions when reminded of the trauma.",
     "Hukua baada ya kupitia tukio la kiwewe — kifo cha mpendwa, ajali, mgogoro au maafa ya asili. Dalili: kumbukumbu za ghafla (kuishi tena kana kwamba inatokea sasa), ndoto mbaya, kumbukumbu zisizotakikana, na majibu ya kihisia au kimwili unapokumbushwa kiwewe.",
     "Ina-develop baada ya ku-experience traumatic event — kifo cha mpendwa, accident, conflict ama natural disaster. Signs: flashbacks (kuishi tena kana kwamba inahappen saa hii), nightmares, unwanted intrusive memories, na emotional ama physical reactions unapokumbushwa trauma.")},
    {"type": "tip", "title": ("💡 The two-week rule answers the Big Question", "💡 Kanuni ya wiki mbili hujibu Swali Kubwa", "💡 Rule ya wiki mbili inajibu Big Question"), "text": (
     " A hard week is a hard week. When low mood, loss of interest or constant worry has lasted <strong>two weeks or more</strong> and is disrupting daily life, that is the point at which the curriculum says seek help. It is a simple, teachable line — and it is the one most peers have never been given.",
     " Wiki ngumu ni wiki ngumu. Huzuni, kupoteza hamu au wasiwasi wa daima ukidumu <strong>wiki mbili au zaidi</strong> na kuvuruga maisha ya kila siku, hapo ndipo mtaala unasema tafuta msaada. Ni mstari rahisi, unaofundishika — na ndio ambao wenzako wengi hawajawahi kupewa.",
     " Wiki ngumu ni wiki ngumu. Low mood, kupoteza interest ama constant worry ikidumu <strong>wiki mbili ama zaidi</strong> na iku-disrupt daily life, hapo ndio curriculum inasema tafuta msaada. Ni line rahisi, inayofundishika — na ndio ambayo wasee wengi hawajawahi kupewa.")},
   ]},

  # ── 6. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "Amina, 17, has not come to football for three weeks, sleeps most of the day, and says she just feels tired. She insists she is fine and that everyone gets tired.",
      "Amina, miaka 17, hajaja kwenye mpira kwa wiki tatu, hulala mchana mwingi, na anasema amechoka tu. Anasisitiza yuko sawa na kwamba kila mtu huchoka.",
      "Amina, 17, hajakuja football kwa wiki tatu, analala mchana mwingi, na anasema amechoka tu. Ana-insist yuko poa na ati kila msee anachoka."),
     "question": ("What do you notice?", "Unaona nini?", "Unaona nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Take her word for it — tiredness is normal for students",
                "Kubali anachosema — uchovu ni wa kawaida kwa wanafunzi",
                "Kubali anachosema — uchovu ni normal kwa students"),
       "outcome": ("Three of the seven depression headings are already present: sleep, interest and energy — and it has run past two weeks. 'Everyone gets tired' is true, and it is also the sentence that keeps depression undetected in adolescents for months.",
                   "Vichwa vitatu kati ya saba vya msongo wa mawazo tayari vipo: usingizi, hamu na nguvu — na imepita wiki mbili. 'Kila mtu huchoka' ni kweli, na pia ndiyo sentensi inayofanya msongo wa mawazo usigundulike kwa vijana kwa miezi.",
                   "Headings tatu kati ya saba za depression tayari ziko: sleep, interest na energy — na imepita wiki mbili. 'Kila msee anachoka' ni kweli, na pia ndio sentence inayofanya depression isigundulike kwa vijana kwa miezi.")},
      {"kind": "good",
       "text": ("Note that three depression signs have lasted beyond two weeks, and gently open a conversation",
                "Tambua kwamba dalili tatu za msongo zimedumu zaidi ya wiki mbili, na ufungue mazungumzo kwa upole",
                "Note ati signs tatu za depression zimedumu zaidi ya wiki mbili, na u-open conversation kwa upole"),
       "outcome": ("You said: 'You're allowed to be tired. But you've been tired for three weeks, you stopped the one thing you loved, and you're sleeping through the day. That's a bit more than tired. Can we talk to someone about it — I'll come.' She cried, and then she talked. ✅",
                   "Ulisema: 'Unaruhusiwa kuwa umechoka. Lakini umechoka kwa wiki tatu, umeacha kitu kimoja ulichokipenda, na unalala mchana mzima. Hiyo ni zaidi kidogo ya uchovu. Tunaweza kuzungumza na mtu kuhusu hilo — nitakuja.' Alilia, kisha akazungumza. ✅",
                   "Ulisema: 'Unaruhusiwa kuwa umechoka. Lakini umechoka kwa wiki tatu, umeacha kitu kimoja ulichopenda, na unalala mchana mzima. Hiyo ni zaidi kidogo ya uchovu. Tunaweza kuongea na msee kuhusu hiyo — nitakuja.' Alilia, kisha akaongea. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A group member says people with mental illness are 'just weak' and that in their day people simply got on with things.",
      "Mwanachama wa kundi anasema watu wenye magonjwa ya akili ni 'dhaifu tu' na kwamba zamani watu waliendelea tu na mambo.",
      "Member wa group anasema wasee wenye mental illness ni 'weak tu' na ati zamani wasee waliendelea tu na mambo."),
     "question": ("What is the strongest response?", "Jibu lenye nguvu zaidi ni lipi?", "Response yenye nguvu zaidi ni ipi?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell him that is an ignorant thing to say",
                "Mwambie hilo ni jambo la ujinga kusema",
                "Mwambie hiyo ni ignorant kusema"),
       "outcome": ("Calling him ignorant makes the point about him rather than about mental health, and everyone in the room who quietly agreed with him now just agrees with him more privately. Stigma does not lose arguments; it goes underground.",
                   "Kumwita mjinga hufanya hoja iwe kumhusu yeye badala ya afya ya akili, na kila aliyekubaliana naye kimya sasa anakubaliana naye kwa siri zaidi. Unyanyapaa haushindwi katika mabishano; huenda chini ya ardhi.",
                   "Ku-call ignorant inafanya point iwe kumhusu yeye badala ya mental health, na kila msee kwa room aliyekubaliana naye kimya saa hii anakubaliana naye privately zaidi. Stigma haishindwi kwa arguments; inaenda underground.")},
      {"kind": "good",
       "text": ("Use the continuum — everyone moves along it, including him",
                "Tumia mfululizo — kila mtu husogea juu yake, akiwemo yeye",
                "Tumia continuum — kila msee anasogea juu yake, akiwemo yeye"),
       "outcome": ("You said: 'Mental health isn't two boxes with strong people in one and weak people in the other. It's a range everyone moves along — you included, this year, next year. The only difference is whether someone gets help while they're moving.' He went quiet, and later asked a question about his brother. ✅",
                   "Ulisema: 'Afya ya akili si masanduku mawili yenye watu imara upande mmoja na dhaifu upande mwingine. Ni mfululizo ambao kila mtu husogea juu yake — wewe pia, mwaka huu, mwaka ujao. Tofauti pekee ni kama mtu anapata msaada akiwa anasogea.' Alinyamaza, na baadaye akauliza swali kuhusu kaka yake. ✅",
                   "Ulisema: 'Mental health si boxes mbili zenye wasee strong upande mmoja na weak upande mwingine. Ni range ambayo kila msee anasogea juu yake — wewe pia, mwaka huu, next year. Tofauti pekee ni kama msee anapata msaada akiwa anasogea.' Alinyamaza, na baadaye akauliza question kuhusu bro wake. ✅")},
     ]},
   ]},

  # ── 7. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Stress is a normal part of daily life — the useful kind sharpens you, the harmful kind overwhelms you.",
      "Msongo ni sehemu ya kawaida ya maisha — aina ya manufaa hukunoa, ya madhara hukuzidi.",
      "Stress ni normal part ya maisha — aina ya manufaa inakunoa, ya madhara inakuzidi."),
     ("Identify the trigger, and identify a positive way of coping with it.",
      "Tambua chanzo, na utambue njia chanya ya kukabiliana nacho.",
      "Tambua trigger, na utambue positive way ya ku-cope nayo."),
     ("Mental health is a continuum — everyone moves along it, in both directions.",
      "Afya ya akili ni mfululizo — kila mtu husogea juu yake, pande zote mbili.",
      "Mental health ni continuum — kila msee anasogea juu yake, pande zote mbili."),
     ("Two weeks or more, disrupting daily life, is the line at which to seek help.",
      "Wiki mbili au zaidi, ikivuruga maisha ya kila siku, ndio mstari wa kutafuta msaada.",
      "Wiki mbili ama zaidi, ikivuruga daily life, ndio line ya kutafuta msaada."),
     ("It is okay not to be okay. It is okay to seek help.",
      "Ni sawa kutokuwa sawa. Ni sawa kutafuta msaada.",
      "Ni poa kutokuwa poa. Ni poa kutafuta msaada."),
    ]},
    {"type": "p", "text": (
     "Part 2 covers recognising and responding to suicide risk, the pressures of social media and betting, and where to send someone in Kenya.",
     "Sehemu ya 2 inahusu kutambua na kukabiliana na hatari ya kujiua, shinikizo la mitandao ya kijamii na kamari, na wapi kumpeleka mtu Kenya.",
     "Part 2 inacover ku-recognise na ku-respond kwa suicide risk, pressure za social media na betting, na wapi kumpeleka msee Kenya.")},
   ]},
 ],

 "quiz": [
  {"q": "How does the curriculum define mental health?",
   "options": ["The absence of mental illness",
               "A state of well-being enabling people to cope with life's stresses, realise their abilities, learn and work well, and contribute to their community",
               "Being happy most of the time",
               "Never experiencing stress"],
   "answer": "B",
   "explain": "It is about capacity to cope — which means it moves up and down, for everyone."},

  {"q": "What is eustress?",
   "options": ["Stress that has lasted more than two weeks",
               "Positive stress, occurring when the occasion is positive",
               "Stress caused by illness",
               "Another word for anxiety"],
   "answer": "B",
   "explain": "Eustress sharpens you — an exam you are ready for, a match. Distress overwhelms rather than sharpens."},

  {"q": "After how long should someone seek help for anxiety or persistent low mood?",
   "options": ["Two days", "Two weeks or more", "Six months", "Only if they cannot work"],
   "answer": "B",
   "explain": "Two weeks, with disruption to daily life, is the teachable line — and the one most peers have never been given."},

  {"q": "Which are UNHEALTHY ways of coping listed in the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Withdrawal and isolation",
               "Substance use",
               "Physical activity",
               "Avoidance and overworking",
               "Screen time addiction"],
   "answer": ["A", "B", "D", "E"],
   "explain": "Physical activity is on the healthy list. Note that substance use appears here AND on Module 10's list of why young people start — the same person, described twice."},

  {"q": "Amina has slept excessively, lost interest in football and felt exhausted for three weeks. What does this suggest?",
   "options": ["Normal student tiredness",
               "Three depression signs — sleep, interest and energy — past the two-week mark",
               "PTSD",
               "A neurodevelopmental condition"],
   "answer": "B",
   "explain": "'Everyone gets tired' is true, and it is also the sentence that keeps adolescent depression undetected for months."},

  {"q": "Which are neurodevelopmental conditions? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Autism Spectrum Disorder",
               "ADHD",
               "Depression",
               "Dyslexia",
               "Intellectual developmental disorder"],
   "answer": ["A", "B", "D", "E"],
   "explain": "Depression is acquired — it develops later in life. Neurodevelopmental conditions are present from birth or early development."},

  {"q": "What distinguishes PTSD?",
   "options": ["It only affects soldiers",
               "It develops after a traumatic event, with flashbacks, nightmares and intrusive memories",
               "It lasts less than two weeks",
               "It is present from birth"],
   "answer": "B",
   "explain": "The triggering events named include the death of a loved one, an accident, conflict or natural disaster."},

  {"q": "A peer says people with mental illness are 'just weak'. What is the strongest response?",
   "options": ["Tell him that is ignorant",
               "Use the continuum — everyone moves along it, including him",
               "Ignore the comment",
               "Ask him to leave the session"],
   "answer": "B",
   "explain": "Calling someone ignorant makes the point about them. Stigma does not lose arguments — it goes underground."},

  {"q": "Which depression heading covers 'loss of interest or pleasure in activities'?",
   "options": ["Energy", "Interest", "Psychomotor", "Guilt"],
   "answer": "B",
   "explain": "Also called anhedonia. It is one of the seven headings — sleep, interest, guilt, energy, concentration, appetite, psychomotor, and suicide."},

  {"q": "Why does the continuum model reduce stigma?",
   "options": ["Because it hides the seriousness of illness",
               "Because asking for help becomes noticing which way you are moving, not admitting you are in a 'bad box'",
               "Because it means nobody is really ill",
               "Because it is easier to remember"],
   "answer": "B",
   "explain": "If mental health is two boxes, seeking help means admitting you are in the bad one — and almost nobody will."},
 ],
}
