# Module 9 (part 2 of 2) — Suicide Risk, Modern Pressures and Getting Help
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 9.
# Trilingual: English / Kiswahili / Sheng.
#
# SAFETY NOTE: this lesson covers suicide recognition and response. It teaches
# what to notice and what to do — never method detail. Every path leads to
# escalation and a named helpline. The opening slide warns the facilitator to
# have a plan before running it.

LESSON = {
 "file": "m09b-suicide-pressures-and-help.html",
 "module_code": "M9",
 "module_slug": "mental-health",
 "lesson_slug": "m09b-suicide-pressures-and-help",
 "module_label": "Peer Educator · M9 · Part 2 of 2",
 "title": "Suicide Risk, Modern Pressures and Getting Help",
 "icon": "🆘",
 "duration": 45,

 "objectives": [
  ("Recognise the warning signs that someone may be considering suicide",
   "Tambua dalili za onyo kwamba mtu anaweza kuwa anafikiria kujiua",
   "Tambua warning signs ati msee anaweza kuwa anafikiria suicide"),
  ("Respond safely and escalate without delay",
   "Itikia kwa usalama na upeleke juu bila kuchelewa",
   "Respond safely na escalate bila kuchelewa"),
  ("Explain how social media and betting affect mental health",
   "Eleza jinsi mitandao ya kijamii na kamari zinavyoathiri afya ya akili",
   "Explain jinsi social media na betting zinaathiri mental health"),
  ("Describe protective factors and name where to get help in Kenya",
   "Eleza mambo ya kinga na utaje wapi kupata msaada Kenya",
   "Describe protective factors na uname wapi kupata msaada Kenya"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> People worry that asking someone directly about suicide might put the idea in their head. What if the opposite is true?",
  "<strong>🔍 Swali Kubwa:</strong> Watu huhofia kwamba kumuuliza mtu moja kwa moja kuhusu kujiua kunaweza kumtia wazo kichwani. Je, ikiwa kinyume chake ndicho kweli?",
  "<strong>🔍 Big Question:</strong> Wasee wanaworry ati kumuuliza msee directly kuhusu suicide kunaweza kumtia wazo kichwani. Je, ikiwa opposite ndio kweli?"),

 "slides": [

  # ── 1. Before you begin ───────────────────────────────────────────
  {"icon": "⚠️",
   "head": ("Before You Run This Session", "Kabla Ya Kuendesha Kipindi Hiki", "Kabla Ya Ku-run Hii Session"),
   "blocks": [
    {"type": "facilitator", "minutes": 5, "text": (
     "This session can bring things to the surface. Before you start: know which adult you will take a disclosure to today, have the helpline numbers written down and in your pocket, and tell the group at the start that anyone can step out at any point without explaining. Do not ask anyone to share a personal experience in front of others.",
     "Kipindi hiki kinaweza kuibua mambo. Kabla ya kuanza: jua ni mtu mzima yupi utampelekea ufichuzi leo, kuwa na nambari za simu za msaada zimeandikwa mfukoni mwako, na waambie kundi mwanzoni kwamba yeyote anaweza kutoka wakati wowote bila kueleza. Usimwombe mtu kushiriki uzoefu binafsi mbele ya wengine.",
     "Hii session inaweza ku-bring vitu juu. Kabla uanze: jua ni mtu mzima yupi utampelekea disclosure leo, kuwa na helpline numbers zimeandikwa mfukoni, na uambie group mwanzoni ati yeyote anaweza kutoka wakati wowote bila ku-explain. Usimwombe msee kushare personal experience mbele ya wengine.")},
    {"type": "p", "text": (
     "Suicide is when someone ends their own life. It is often the result of feeling overwhelmed, hopeless, or believing there is no other way out. That last part matters most: what the person needs is not to be told they are wrong, but to be shown another way out exists.",
     "Kujiua ni pale mtu anapoyamaliza maisha yake. Mara nyingi ni matokeo ya kujihisi kuzidiwa, kukata tamaa, au kuamini hakuna njia nyingine ya kutoka. Sehemu hiyo ya mwisho ndiyo muhimu zaidi: anachohitaji mtu si kuambiwa amekosea, bali kuonyeshwa kwamba njia nyingine ipo.",
     "Suicide ni pale msee anapo-end maisha yake. Mara nyingi ni result ya kujiskia overwhelmed, hopeless, ama kuamini hakuna njia nyingine ya kutoka. Hiyo part ya mwisho ndio muhimu zaidi: anachohitaji msee si kuambiwa amekosea, ni kuonyeshwa ati njia nyingine iko.")},
   ]},

  # ── 2. Warning signs ──────────────────────────────────────────────
  {"icon": "🚩",
   "head": ("Warning Signs", "Dalili za Onyo", "Warning Signs"),
   "blocks": [
    {"type": "table",
     "headers": [("Emotional", "Kihisia", "Emotional"), ("Behavioural", "Kitabia", "Behavioural"), ("Physical", "Kimwili", "Physical")],
     "rows": [
      [("Feeling hopeless or worthless",
        "Kujihisi umekata tamaa au huna thamani",
        "Kujiskia hopeless ama worthless"),
       ("Talking or joking about wanting to die",
        "Kuzungumza au kutania kuhusu kutaka kufa",
        "Kuongea ama kutania kuhusu kutaka kufa"),
       ("Neglecting personal appearance",
        "Kutojali muonekano wa mwili",
        "Kutojali personal appearance")],
      [("Extreme sadness or emotional pain",
        "Huzuni kubwa au maumivu ya kihisia",
        "Extreme sadness ama emotional pain"),
       ("Withdrawing from friends and family",
        "Kujitenga na marafiki na familia",
        "Kujitenga na friends na family"),
       ("Constant tiredness or low energy",
        "Uchovu wa daima au nguvu kidogo",
        "Constant tiredness ama low energy")],
      [("", "", ""),
       ("Giving away belongings, or saying goodbye in unusual ways",
        "Kutoa mali zake, au kuaga kwa njia zisizo za kawaida",
        "Kutoa vitu vyake, ama kuaga kwa njia zisizo za kawaida"),
       ("", "", "")],
      [("", "", ""),
       ("Risk-taking behaviour — reckless driving, substance use",
        "Tabia za kuhatarisha — kuendesha bila uangalifu, matumizi ya dawa",
        "Risk-taking behaviour — reckless driving, substance use"),
       ("", "", "")],
     ]},
    {"type": "list", "items": [
     ("<strong>Clues in conversation and on social media:</strong> posts, messages or songs about death, hopelessness or being a burden",
      "<strong>Viashiria katika mazungumzo na mitandaoni:</strong> machapisho, ujumbe au nyimbo kuhusu kifo, kukata tamaa au kuwa mzigo",
      "<strong>Clues kwa conversation na social media:</strong> posts, messages ama nyimbo kuhusu kifo, hopelessness ama kuwa burden"),
     ("Writing or drawing about death or self-harm",
      "Kuandika au kuchora kuhusu kifo au kujidhuru",
      "Kuandika ama kuchora kuhusu kifo ama self-harm"),
     ("Questions like <em>'Would anyone care if I were gone?'</em>",
      "Maswali kama <em>'Je, mtu angejali kama ningeondoka?'</em>",
      "Questions kama <em>'Je, msee angecare kama ningeondoka?'</em>"),
    ]},
    {"type": "warn", "title": ("⚠️ Take the joke seriously", "⚠️ Chukua utani kwa uzito", "⚠️ Chukua joke seriously"), "text": (
     " 'Talking or joking about wanting to die' is on the list for a reason. Humour is how many young people test whether it is safe to say something real. Laughing along closes the door. Asking quietly afterwards opens it.",
     " 'Kuzungumza au kutania kuhusu kutaka kufa' iko kwenye orodha kwa sababu. Ucheshi ndiyo njia vijana wengi hujaribu kama ni salama kusema jambo halisi. Kucheka pamoja hufunga mlango. Kuuliza kwa utulivu baadaye hufungua.",
     " 'Kuongea ama kutania kuhusu kutaka kufa' iko kwa list kwa sababu. Humour ndio njia vijana wengi wana-test kama ni safe kusema kitu real. Kucheka pamoja inafunga door. Kuuliza kwa utulivu baadaye inafungua.")},
   ]},

  # ── 3. How to help ────────────────────────────────────────────────
  {"icon": "🤝",
   "head": ("How to Help", "Jinsi ya Kusaidia", "Jinsi ya Kusaidia"),
   "blocks": [
    {"type": "tip", "title": ("💡 The answer to the Big Question", "💡 Jibu la Swali Kubwa", "💡 Jibu la Big Question"), "text": (
     " Asking someone directly whether they are thinking about suicide does not put the idea there. For someone already carrying it, being asked is usually the first relief they have had — because it means somebody noticed, and somebody can hear the answer. Ask plainly: <em>'Are you thinking about ending your life?'</em>",
     " Kumuuliza mtu moja kwa moja kama anafikiria kujiua hakumtii wazo hilo. Kwa mtu ambaye tayari analibeba, kuulizwa mara nyingi ndiyo faraja ya kwanza aliyopata — kwa sababu inamaanisha mtu aliona, na mtu anaweza kusikia jibu. Uliza wazi: <em>'Je, unafikiria kuyamaliza maisha yako?'</em>",
     " Kumuuliza msee directly kama anafikiria suicide haimtii hilo wazo. Kwa msee ambaye tayari analibeba, kuulizwa mara nyingi ndio relief ya kwanza amepata — kwa sababu inamaanisha msee aliona, na msee anaweza kusikia jibu. Uliza wazi: <em>'Je, unafikiria ku-end maisha yako?'</em>")},
    {"type": "list", "ordered": True, "items": [
     ("<strong>Listen without judgement.</strong> Do not argue, do not minimise, do not rush to fix it.",
      "<strong>Sikiliza bila kuhukumu.</strong> Usibishane, usidharau, usikimbilie kurekebisha.",
      "<strong>Listen bila kujudge.</strong> Usi-argue, usi-minimise, usikimbilie ku-fix."),
     ("<strong>Seek help from an adult</strong> — a parent, guardian, community health promoter, church elder or mental health professional.",
      "<strong>Tafuta msaada kwa mtu mzima</strong> — mzazi, mlezi, mhudumu wa afya wa jamii, mzee wa kanisa au mtaalamu wa afya ya akili.",
      "<strong>Tafuta msaada kwa mtu mzima</strong> — mzazi, guardian, community health promoter, church elder ama mental health professional."),
     ("<strong>Encourage professional help — and offer to go with them.</strong> The offer to go is usually what makes it happen.",
      "<strong>Himiza msaada wa kitaalamu — na jitolee kwenda naye.</strong> Kujitolea kwenda ndiko kwa kawaida kunakofanya litokee.",
      "<strong>Encourage professional help — na offer kwenda naye.</strong> Hiyo offer ya kwenda ndio kwa kawaida inafanya i-happen."),
     ("<strong>Remove things that could be used</strong> — knives, pesticides and similar items should not be within reach.",
      "<strong>Ondoa vitu vinavyoweza kutumika</strong> — visu, dawa za wadudu na vitu kama hivyo visiwe karibu.",
      "<strong>Ondoa vitu vinavyoweza kutumika</strong> — visu, pesticides na vitu kama hivyo visiwe karibu."),
     ("<strong>Stay connected.</strong> Keep checking on them regularly — not once, and not only in a crisis.",
      "<strong>Endelea kuwasiliana.</strong> Endelea kumwangalia mara kwa mara — si mara moja, na si tu wakati wa dharura.",
      "<strong>Stay connected.</strong> Endelea kum-check regularly — si mara moja, na si tu wakati wa crisis."),
    ]},
    {"type": "warn", "title": ("⚠️ This is never a secret you keep", "⚠️ Hii kamwe si siri unayoiweka", "⚠️ Hii kamwe si secret unayo-keep"), "text": (
     " Any mention of suicide goes to your supervising adult the same day — as in Module 1 and Module 12. Confidentiality protects private information; it does not cover a life at risk. Tell the person you are doing it, and why, before you do it.",
     " Kutajwa kwa kujiua kunaenda kwa mtu mzima anayekusimamia siku hiyo hiyo — kama katika Moduli 1 na Moduli 12. Usiri hulinda taarifa binafsi; haufuniki maisha yaliyo hatarini. Mwambie mtu unafanya hivyo, na kwa nini, kabla ya kufanya.",
     " Kutajwa kwa suicide kunaenda kwa msimamizi wako siku hiyo hiyo — kama kwa Module 1 na Module 12. Confidentiality inalinda private info; haicovers maisha yaliyo hatarini. Mwambie msee unafanya hivyo, na kwa nini, kabla ufanye.")},
   ]},

  # ── 4. Social media ───────────────────────────────────────────────
  {"icon": "📱",
   "head": ("Social Media and Mental Health", "Mitandao ya Kijamii na Afya ya Akili", "Social Media na Mental Health"),
   "blocks": [
    {"type": "table",
     "headers": [("Pressure", "Shinikizo", "Pressure"), ("What it does", "Inafanya nini", "Inafanya nini")],
     "rows": [
      [("Comparison", "Kulinganisha", "Comparison"),
       ("You compare your ordinary day with everyone else's edited highlights, and conclude you are behind.",
        "Unalinganisha siku yako ya kawaida na vipande bora vilivyohaririwa vya wengine, na kuhitimisha umebaki nyuma.",
        "Una-compare siku yako ya kawaida na edited highlights za wasee wengine, na ku-conclude uko behind.")],
      [("Cyberbullying", "Uonevu mtandaoni", "Cyberbullying"),
       ("Harassment that follows a young person home, into their bedroom, at any hour.",
        "Unyanyasaji unaomfuata kijana nyumbani, chumbani mwake, saa yoyote.",
        "Harassment inayomfuata kijana nyumbani, kwa bedroom yake, saa yoyote.")],
      [("Addiction and screen overuse", "Uraibu na matumizi kupita kiasi", "Addiction na screen overuse"),
       ("Displaces sleep, movement and face-to-face contact — the three biggest protective factors there are.",
        "Huondoa usingizi, mwendo na mawasiliano ya ana kwa ana — mambo matatu makubwa zaidi ya kinga yaliyopo.",
        "Ina-displace sleep, movement na face-to-face contact — protective factors tatu kubwa zaidi zilizopo.")],
      [("Fear of missing out (FOMO)", "Hofu ya kukosa (FOMO)", "Fear of missing out (FOMO)"),
       ("Constant low-level anxiety that something better is happening without you.",
        "Wasiwasi wa kudumu wa kiwango cha chini kwamba kitu bora kinatokea bila wewe.",
        "Constant low-level anxiety ati kitu better kina-happen bila wewe.")],
      [("The positive side", "Upande chanya", "Positive side"),
       ("Awareness, support groups and finding others who understand — real, and worth naming.",
        "Uelewa, vikundi vya msaada na kupata wengine wanaoelewa — halisi, na inastahili kutajwa.",
        "Awareness, support groups na kupata wasee wanaoelewa — real, na inastahili kutajwa.")],
     ]},
   ]},

  # ── 5. Betting ────────────────────────────────────────────────────
  {"icon": "🎲",
   "head": ("Betting and Mental Health", "Kamari na Afya ya Akili", "Betting na Mental Health"),
   "blocks": [
    {"type": "p", "text": (
     "Betting is not a side issue in Kenya — it is among the most live mental health risks facing young men in particular. The curriculum treats it as a mental health topic, and so should you.",
     "Kamari si suala la pembeni Kenya — ni kati ya hatari kubwa zaidi za afya ya akili zinazowakabili vijana wa kiume hasa. Mtaala unaichukulia kama mada ya afya ya akili, na wewe pia unapaswa.",
     "Betting si side issue Kenya — ni kati ya mental health risks live zaidi zinazowakabili vijana wa kiume hasa. Curriculum inai-treat kama mental health topic, na wewe pia unafaa.")},
    {"type": "list", "ordered": True, "items": [
     ("<strong>The systems are designed to keep you hooked</strong> — they work directly on the brain's reward system.",
      "<strong>Mifumo imeundwa kukuweka umenaswa</strong> — hufanya kazi moja kwa moja kwenye mfumo wa zawadi wa ubongo.",
      "<strong>Systems zime-designiwa kuku-keep hooked</strong> — zinafanya kazi directly kwa reward system ya brain."),
     ("<strong>Occasional wins create a false sense of control</strong> — you remember the wins and forget the losses, which is exactly what the design intends.",
      "<strong>Ushindi wa mara chache huunda hisia potofu ya udhibiti</strong> — unakumbuka ushindi na kusahau hasara, ambayo ndiyo hasa muundo unakusudia.",
      "<strong>Occasional wins zina-create false sense ya control</strong> — unakumbuka wins na kusahau losses, ambayo ndio hasa design inakusudia."),
     ("<strong>Anxiety and depression follow</strong> — both from the losses and from hiding them.",
      "<strong>Wasiwasi na msongo wa mawazo hufuata</strong> — kutokana na hasara na kutokana na kuzificha.",
      "<strong>Anxiety na depression zina-follow</strong> — kutokana na losses na kutokana na kuzificha."),
     ("<strong>Financial stress worsens mental health</strong>, which drives more betting to recover the loss. That is the loop.",
      "<strong>Msongo wa kifedha huzidisha afya mbaya ya akili</strong>, ambayo husukuma kamari zaidi kurudisha hasara. Huo ndio mzunguko.",
      "<strong>Financial stress inazidisha mental health mbaya</strong>, ambayo ina-drive betting zaidi ku-recover loss. Hiyo ndio loop."),
     ("<strong>When betting starts controlling you, it is no longer entertainment.</strong> That is the sentence to give a peer.",
      "<strong>Kamari inapoanza kukudhibiti, si burudani tena.</strong> Hiyo ndiyo sentensi ya kumpa rika.",
      "<strong>Betting inapoanza kuku-control, si entertainment tena.</strong> Hiyo ndio sentence ya kumpa msee."),
    ]},
    {"type": "sheng", "text": (
     "Kampuni haihitaji ushinde ili urudi. Inahitaji ukaribie kushinda. Hilo ni jambo tofauti kabisa — na limejengwa ndani kwa makusudi.",
     "Kampuni haihitaji ushinde ili urudi. Inahitaji ukaribie kushinda. Hilo ni jambo tofauti kabisa — na limejengwa ndani kwa makusudi.",
     "Company haihitaji ushinde ili urudi. Inahitaji ukaribie kushinda. Hiyo ni kitu tofauti kabisa — na ime-buildiwa ndani kwa makusudi.")},
   ]},

  # ── 6. Protective factors ─────────────────────────────────────────
  {"icon": "🛡️",
   "head": ("Protective Factors", "Mambo ya Kinga", "Protective Factors"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Healthy lifestyle</strong> — regular exercise, balanced nutrition and enough sleep genuinely improve mental well-being",
      "<strong>Mtindo bora wa maisha</strong> — mazoezi ya kawaida, lishe bora na usingizi wa kutosha huboresha ustawi wa akili kweli",
      "<strong>Healthy lifestyle</strong> — regular exercise, balanced nutrition na sleep ya kutosha zina-improve mental well-being kweli"),
     ("<strong>Social support</strong> — talking with friends, family or a support group reduces isolation and shares the load",
      "<strong>Msaada wa kijamii</strong> — kuzungumza na marafiki, familia au kikundi cha msaada hupunguza upweke na kugawana mzigo",
      "<strong>Social support</strong> — kuongea na friends, family ama support group inapunguza isolation na ku-share load"),
     ("<strong>Stress management</strong> — mindfulness, relaxation exercises, or simply doing something you enjoy",
      "<strong>Kudhibiti msongo</strong> — utulivu wa akili, mazoezi ya kupumzika, au kufanya tu kitu unachofurahia",
      "<strong>Stress management</strong> — mindfulness, relaxation exercises, ama kufanya tu kitu unachoenjoy"),
     ("<strong>Professional help</strong> — a therapist, counsellor or doctor for proper diagnosis, treatment and support",
      "<strong>Msaada wa kitaalamu</strong> — mtaalamu wa tiba, mshauri au daktari kwa utambuzi sahihi, matibabu na msaada",
      "<strong>Professional help</strong> — therapist, counsellor ama daktari kwa proper diagnosis, treatment na support"),
     ("<strong>Medication when prescribed</strong> — antidepressants, mood stabilisers or antipsychotics, under medical supervision only",
      "<strong>Dawa zikiagizwa</strong> — dawa za msongo, za kutuliza hisia au za akili, chini ya usimamizi wa daktari pekee",
      "<strong>Medication ikiwa prescribed</strong> — antidepressants, mood stabilisers ama antipsychotics, chini ya medical supervision pekee"),
    ]},
    {"type": "warn", "title": ("⚠️ Do not advise on medication", "⚠️ Usishauri kuhusu dawa", "⚠️ Usi-advise kuhusu dawa"), "text": (
     " As with PrEP in Module 13B: naming that medication exists is your job. Deciding whether someone needs it, which one, or whether they should stop taking it, is not. Stopping psychiatric medication abruptly can be dangerous — always route that question to the prescriber.",
     " Kama ilivyo kwa PrEP katika Moduli 13B: kutaja kwamba dawa zipo ni kazi yako. Kuamua kama mtu anazihitaji, ipi, au kama aache kuzitumia, si kazi yako. Kuacha dawa za akili ghafla kunaweza kuwa hatari — daima peleka swali hilo kwa daktari aliyeagiza.",
     " Kama PrEP kwa Module 13B: ku-name ati medication iko ni job yako. Ku-decide kama msee anaihitaji, ipi, ama kama aache kuitumia, si job yako. Kuacha psychiatric medication ghafla inaweza kuwa hatari — daima route hiyo question kwa prescriber.")},
   ]},

  # ── 7. Where to get help ──────────────────────────────────────────
  {"icon": "📞",
   "head": ("Where to Get Help in Kenya", "Wapi Kupata Msaada Kenya", "Wapi Kupata Msaada Kenya"),
   "blocks": [
    {"type": "table",
     "headers": [("Service", "Huduma", "Service"), ("Number", "Nambari", "Number")],
     "rows": [
      [("Befrienders Kenya — 24/7 emotional support and suicide prevention",
        "Befrienders Kenya — msaada wa kihisia saa 24 na kuzuia kujiua",
        "Befrienders Kenya — 24/7 emotional support na suicide prevention"),
       ("<strong>0722 178 177</strong>", "<strong>0722 178 177</strong>", "<strong>0722 178 177</strong>")],
      [("Chiromo Hospital Group — 24/7 crisis line",
        "Chiromo Hospital Group — simu ya dharura saa 24",
        "Chiromo Hospital Group — 24/7 crisis line"),
       ("<strong>0722 529 714</strong>", "<strong>0722 529 714</strong>", "<strong>0722 529 714</strong>")],
      [("Kenya Red Cross — toll free",
        "Msalaba Mwekundu Kenya — bila malipo",
        "Kenya Red Cross — toll free"),
       ("<strong>1199</strong>", "<strong>1199</strong>", "<strong>1199</strong>")],
      [("National emergency lines",
        "Simu za dharura za kitaifa",
        "National emergency lines"),
       ("<strong>719</strong> · <strong>0729 471 414</strong> · <strong>0732 353 535</strong>",
        "<strong>719</strong> · <strong>0729 471 414</strong> · <strong>0732 353 535</strong>",
        "<strong>719</strong> · <strong>0729 471 414</strong> · <strong>0732 353 535</strong>")],
      [("Childline Kenya — anyone under 18",
        "Childline Kenya — yeyote chini ya miaka 18",
        "Childline Kenya — yeyote chini ya 18"),
       ("<strong>116</strong>", "<strong>116</strong>", "<strong>116</strong>")],
     ]},
    {"type": "tip", "title": ("💡 Carry these, do not look them up", "💡 Zibebe, usizitafute", "💡 Zibebe, usizi-look up"), "text": (
     " Write these on a card and keep it on you. In the moment someone tells you they want to die, you will not be searching a phone. Module 16 applies here in full: issue the referral, record it, follow up, and re-refer if it did not land.",
     " Ziandike kwenye kadi na uibebe. Wakati mtu anapokuambia anataka kufa, hutakuwa unatafuta kwenye simu. Moduli 16 inatumika hapa kikamilifu: toa rufaa, iandike, fuatilia, na utoe tena kama haikufika.",
     " Ziandike kwa card na uibebe. Wakati msee anakuambia anataka kufa, hutakuwa una-search kwa phone. Module 16 inatumika hapa fully: issue referral, i-record, follow up, na u-re-refer kama haiku-land.")},
   ]},

  # ── 8. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A friend posts a song about being a burden, then jokes in the group chat that everyone would be better off without him. Others laugh.",
      "Rafiki anachapisha wimbo kuhusu kuwa mzigo, kisha anatania kwenye gumzo la kundi kwamba kila mtu angekuwa bora bila yeye. Wengine wanacheka.",
      "Friend ana-post wimbo kuhusu kuwa burden, kisha anatania kwa group chat ati kila msee angekuwa better bila yeye. Wengine wanacheka."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Laugh along so he does not feel singled out, and watch him for a while",
                "Cheka pamoja ili asijihisi ametengwa, na umwangalie kwa muda",
                "Cheka pamoja ili asijiskie singled out, na um-watch kwa muda"),
       "outcome": ("Two clues from the list are already present — a song about being a burden, and joking about wanting to die. Laughing along tells him the group cannot hold this. Watching quietly is not a plan; it is a delay.",
                   "Viashiria viwili kutoka orodha tayari vipo — wimbo kuhusu kuwa mzigo, na kutania kuhusu kutaka kufa. Kucheka pamoja kunamwambia kundi haliwezi kubeba hili. Kuangalia kimya si mpango; ni kuchelewesha.",
                   "Clues mbili kutoka list tayari ziko — wimbo kuhusu kuwa burden, na kutania kuhusu kutaka kufa. Kucheka pamoja inamwambia group haiwezi kubeba hii. Ku-watch kimya si plan; ni delay.")},
      {"kind": "good",
       "text": ("Message him privately, ask directly, and take it to your supervising adult today",
                "Mtumie ujumbe faraghani, muulize moja kwa moja, na upeleke kwa msimamizi wako leo",
                "M-message privately, muulize directly, na upeleke kwa msimamizi wako leo"),
       "outcome": ("You messaged: 'That song, and what you said in the group — are you actually thinking about ending your life?' He said yes. You stayed on the phone, told him you were telling one adult and why, and went with him the next morning. Asking directly is what let him answer. ✅",
                   "Ulituma ujumbe: 'Wimbo ule, na uliyosema kwenye kundi — je, kwa kweli unafikiria kuyamaliza maisha yako?' Alisema ndiyo. Ulibaki kwenye simu, ukamwambia unamwambia mtu mzima mmoja na kwa nini, na ukaenda naye asubuhi iliyofuata. Kuuliza moja kwa moja ndiko kulikomwezesha kujibu. ✅",
                   "Uli-message: 'Ule wimbo, na uliyosema kwa group — je, kweli unafikiria ku-end maisha yako?' Alisema ndio. Ulibaki kwa phone, ukamwambia unamwambia mtu mzima mmoja na kwa nini, na ukaenda naye asubuhi iliyofuata. Kuuliza directly ndio kulikomwezesha ku-answer. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A peer has been betting daily for months. He tells you he is close to winning it all back and just needs one more good weekend.",
      "Rika amekuwa akicheza kamari kila siku kwa miezi. Anakuambia yuko karibu kurudisha yote na anahitaji tu wikendi moja nzuri zaidi.",
      "Msee amekuwa aki-bet kila siku kwa miezi. Anakuambia yuko karibu ku-win yote back na anahitaji tu weekend moja nzuri zaidi."),
     "question": ("What is actually happening here?", "Ni nini kinachotokea hasa hapa?", "Ni nini kina-happen hasa hapa?"),
     "choices": [
      {"kind": "bad",
       "text": ("Help him work out a smarter betting strategy to limit his losses",
                "Msaidie atengeneze mkakati bora wa kamari kupunguza hasara",
                "Msaidie a-work out smarter betting strategy ku-limit losses"),
       "outcome": ("There is no strategy that beats a system built to keep him playing. Helping him bet 'better' joins him inside the false sense of control — which the curriculum names as the exact mechanism that keeps people hooked.",
                   "Hakuna mkakati unaoshinda mfumo uliojengwa kumweka akicheza. Kumsaidia acheze 'vizuri zaidi' kunakuunganisha naye ndani ya hisia potofu ya udhibiti — ambayo mtaala unaitaja kama mbinu hasa inayowaweka watu wamenaswa.",
                   "Hakuna strategy inayo-beat system iliyojengwa kum-keep akicheza. Kumsaidia a-bet 'better' inakuunganisha naye ndani ya false sense ya control — ambayo curriculum inai-name kama exact mechanism inayowaweka wasee hooked.")},
      {"kind": "good",
       "text": ("Name the loop — losses, stress, more betting — and treat it as a mental health referral",
                "Taja mzunguko — hasara, msongo, kamari zaidi — na uichukulie kama rufaa ya afya ya akili",
                "Name hiyo loop — losses, stress, betting zaidi — na uitreat kama mental health referral"),
       "outcome": ("You said: 'You're not one weekend away — that feeling is the product. Losing makes you stressed, being stressed makes you bet, and the stress is now the reason you can't stop. That's not a money problem any more.' He agreed to talk to someone. ✅",
                   "Ulisema: 'Hauko wikendi moja mbali — hisia hiyo ndiyo bidhaa. Kupoteza kunakufanya uwe na msongo, msongo unakufanya ucheze, na msongo sasa ndiyo sababu huwezi kuacha. Hilo si tatizo la pesa tena.' Alikubali kuzungumza na mtu. ✅",
                   "Ulisema: 'Hauko weekend moja mbali — hiyo feeling ndio product. Ku-lose kunakufanya uwe na stress, stress inakufanya u-bet, na stress saa hii ndio sababu huwezi kuacha. Hiyo si money problem tena.' Alikubali kuongea na msee. ✅")},
     ]},
   ]},

  # ── 9. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Asking someone directly about suicide does not plant the idea — it is often the first relief they have had.",
      "Kumuuliza mtu moja kwa moja kuhusu kujiua hakumtii wazo — mara nyingi ndiyo faraja ya kwanza aliyopata.",
      "Kumuuliza msee directly kuhusu suicide haimtii wazo — mara nyingi ndio relief ya kwanza amepata."),
     ("Joking about wanting to die is on the warning list. Take it seriously, quietly, afterwards.",
      "Kutania kuhusu kutaka kufa kuko kwenye orodha ya onyo. Kuchukue kwa uzito, kwa utulivu, baadaye.",
      "Kutania kuhusu kutaka kufa iko kwa warning list. I-chukue seriously, kwa utulivu, baadaye."),
     ("Any mention of suicide goes to a supervising adult the same day. It is never a secret you keep.",
      "Kutajwa kwa kujiua kunaenda kwa mtu mzima anayesimamia siku hiyo hiyo. Kamwe si siri unayoiweka.",
      "Kutajwa kwa suicide kunaenda kwa msimamizi siku hiyo hiyo. Kamwe si secret unayo-keep."),
     ("When betting starts controlling you, it is no longer entertainment.",
      "Kamari inapoanza kukudhibiti, si burudani tena.",
      "Betting inapoanza kuku-control, si entertainment tena."),
     ("Real change in mental health is only recognised when we intentionally pay attention.",
      "Mabadiliko halisi ya afya ya akili hutambulika tu tunapozingatia kwa makusudi.",
      "Real change ya mental health inatambulika tu tunapo-pay attention kwa makusudi."),
     ("It is okay not to be okay. It is okay to seek help.",
      "Ni sawa kutokuwa sawa. Ni sawa kutafuta msaada.",
      "Ni poa kutokuwa poa. Ni poa kutafuta msaada."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Hutahitaji kuwa mtaalamu. Unahitaji kuwa mtu anayeuliza swali gumu na kubaki hapo kusikiliza jibu.",
     "Hutahitaji kuwa mtaalamu. Unahitaji kuwa mtu anayeuliza swali gumu na kubaki hapo kusikiliza jibu.",
     "Huhitaji kuwa expert. Unahitaji kuwa msee anayeuliza question ngumu na kubaki hapo kusikiliza jibu.")},
   ]},
 ],

 "quiz": [
  {"q": "Does asking someone directly whether they are thinking about suicide put the idea in their head?",
   "options": ["Yes — it should always be avoided",
               "No — for someone already carrying it, being asked is often the first relief they have had",
               "Only if they are under 18",
               "Only if you are not a professional"],
   "answer": "B",
   "explain": "Asking plainly is what allows them to answer. Being asked means somebody noticed, and somebody can hear the answer."},

  {"q": "A peer jokes in a group chat about everyone being better off without him. What is that?",
   "options": ["Ordinary dark humour, best ignored",
               "A behavioural warning sign — joking about wanting to die is on the list",
               "Attention-seeking",
               "Only concerning if he repeats it"],
   "answer": "B",
   "explain": "Humour is how many young people test whether it is safe to say something real. Laughing along closes the door."},

  {"q": "Which are steps in helping someone at risk of suicide? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Listen without judgement",
               "Seek help from a trusted adult",
               "Offer to go with them to professional help",
               "Promise to keep it between the two of you",
               "Remove items that could be used, such as knives and pesticides"],
   "answer": ["A", "B", "C", "E"],
   "explain": "Any mention of suicide goes to a supervising adult the same day. Confidentiality protects private information; it does not cover a life at risk."},

  {"q": "Which clue should prompt concern on social media?",
   "options": ["Posting about a football match",
               "Posts, messages or songs about death, hopelessness or being a burden",
               "Posting less often than usual",
               "Changing a profile picture"],
   "answer": "B",
   "explain": "Also writing or drawing about death or self-harm, and questions like 'Would anyone care if I were gone?'"},

  {"q": "Why do occasional wins make betting more dangerous, not less?",
   "options": ["They encourage people to stop while ahead",
               "They create a false sense of control — you remember wins and forget losses",
               "They reduce the total amount lost",
               "They have no effect"],
   "answer": "B",
   "explain": "The system does not need you to win in order to come back. It needs you to come close — and that is built in deliberately."},

  {"q": "Which are ways social media affects mental health per the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Comparison and low self-esteem",
               "Cyberbullying and online harassment",
               "Fear of missing out",
               "Awareness and support — a positive impact",
               "Improved sleep quality"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Screen overuse displaces sleep rather than improving it. The positive impacts are real and worth naming alongside the risks."},

  {"q": "A peer says he is one good weekend away from winning back his betting losses. What is happening?",
   "options": ["He may well be right",
               "He is inside the false-sense-of-control loop, and it is now a mental health issue, not a money one",
               "He needs a better betting strategy",
               "He should bet larger amounts to recover faster"],
   "answer": "B",
   "explain": "Losses cause stress, stress drives more betting, and the stress becomes the reason he cannot stop. Helping him bet 'better' joins him inside the illusion."},

  {"q": "What should a peer educator NOT do regarding psychiatric medication?",
   "options": ["Mention that medication exists as an option",
               "Advise someone whether to take it, which one, or whether to stop",
               "Encourage them to see a professional",
               "Offer to go with them to an appointment"],
   "answer": "B",
   "explain": "As with PrEP in Module 13B — naming that it exists is your job; prescribing is not. Stopping psychiatric medication abruptly can be dangerous."},

  {"q": "Which are protective factors for mental health? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Regular exercise and adequate sleep",
               "Talking with friends, family or a support group",
               "Mindfulness and relaxation",
               "Keeping problems to yourself to avoid burdening others"],
   "answer": ["A", "B", "C"],
   "explain": "Isolation is on the unhealthy coping list in Part 1. Social support is precisely what reduces it."},

  {"q": "What does the curriculum say real change in mental health depends on?",
   "options": ["Medication alone",
               "Intentionally paying attention",
               "Waiting for symptoms to pass",
               "Professional diagnosis only"],
   "answer": "B",
   "explain": "'Real change in mental health is only recognised when we intentionally pay attention' — which is exactly the peer educator's function."},
 ],
}
