# Module 10 (part 1 of 2) — Understanding Drug and Substance Abuse
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 10.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m10a-understanding-drug-abuse.html",
 "module_code": "M10",
 "module_slug": "drug-substance-abuse",
 "lesson_slug": "m10a-understanding-drug-abuse",
 "module_label": "Peer Educator · M10 · Part 1 of 2",
 "title": "Understanding Drug and Substance Abuse",
 "icon": "🚭",
 "duration": 45,

 "objectives": [
  ("Define the key terms — use, abuse, tolerance, dependency, withdrawal and addiction",
   "Fafanua maneno muhimu — matumizi, matumizi mabaya, uvumilivu, utegemezi, dalili za kuachana na uraibu",
   "Define key terms — use, abuse, tolerance, dependency, withdrawal na addiction"),
  ("State the main classes of drug commonly abused by young people",
   "Taja makundi makuu ya dawa zinazotumiwa vibaya na vijana",
   "Taja classes kuu za drugs zinazotumiwa vibaya na vijana"),
  ("Explain the five stages from first use to dependence",
   "Eleza hatua tano kutoka matumizi ya kwanza hadi utegemezi",
   "Explain stages tano kutoka first use hadi dependence"),
  ("Identify the family, school and peer factors that lead to substance abuse",
   "Tambua sababu za kifamilia, kishule na kirika zinazosababisha matumizi mabaya",
   "Tambua family, school na peer factors zinazosababisha substance abuse"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Nobody sets out to become dependent. So at which point does a choice stop being a choice?",
  "<strong>🔍 Swali Kubwa:</strong> Hakuna anayeanza akikusudia kuwa mtegemezi. Basi ni wapi uchaguzi unapoacha kuwa uchaguzi?",
  "<strong>🔍 Big Question:</strong> Hakuna msee anayeanza akikusudia kuwa dependent. So ni wapi choice inaacha kuwa choice?"),

 "slides": [

  # ── 1. The words ──────────────────────────────────────────────────
  {"icon": "📖",
   "head": ("The Words That Get Confused", "Maneno Yanayochanganywa", "Maneno Yanayo-confusiwa"),
   "blocks": [
    {"type": "p", "text": (
     "'Use', 'abuse', 'dependence' and 'addiction' get used interchangeably in ordinary conversation. They are not the same, and mixing them up is how a real problem gets dismissed as ordinary behaviour.",
     "'Matumizi', 'matumizi mabaya', 'utegemezi' na 'uraibu' hutumiwa kwa kubadilishana katika mazungumzo ya kawaida. Si sawa, na kuyachanganya ndiko kunakofanya tatizo halisi lipuuzwe kama tabia ya kawaida.",
     "'Use', 'abuse', 'dependence' na 'addiction' zinatumiwa interchangeably kwa ordinary conversation. Si sawa, na kuzi-mix ndio inafanya real problem i-dismissiwe kama ordinary behaviour.")},
    {"type": "table",
     "headers": [("Term", "Neno", "Term"), ("What it means", "Maana yake", "Maana yake")],
     "rows": [
      [("Drug", "Dawa ya kulevya", "Drug"),
       ("Any substance that changes how the body or mind works.",
        "Kitu chochote kinachobadilisha jinsi mwili au akili inavyofanya kazi.",
        "Kitu chochote kinachobadilisha jinsi mwili ama akili inavyowork.")],
      [("Drug use vs abuse", "Matumizi dhidi ya matumizi mabaya", "Use dhidi ya abuse"),
       ("Use is taking a substance as intended or prescribed. Abuse is use that harms health, school, work or relationships.",
        "Matumizi ni kuchukua kitu kama ilivyokusudiwa au kuagizwa. Matumizi mabaya ni matumizi yanayodhuru afya, shule, kazi au mahusiano.",
        "Use ni kuchukua kitu kama ilivyokusudiwa ama ku-prescribiwa. Abuse ni use inayodhuru health, shule, kazi ama relationships.")],
      [("Tolerance", "Uvumilivu", "Tolerance"),
       ("Needing more of the substance to get the same effect it used to give.",
        "Kuhitaji kiasi kikubwa zaidi ili kupata athari ile ile iliyokuwa ikitolewa.",
        "Kuhitaji zaidi ya substance ili kupata effect ile ile iliyokuwa ikitolewa.")],
      [("Dependency", "Utegemezi", "Dependency"),
       ("Needing the substance in order to feel or function normally.",
        "Kuhitaji kitu hicho ili kujisikia au kufanya kazi kwa kawaida.",
        "Kuhitaji hiyo substance ili kujiskia ama ku-function normally.")],
      [("Withdrawal", "Dalili za kuachana", "Withdrawal"),
       ("The physical and mental symptoms that appear when a dependent person stops.",
        "Dalili za kimwili na kiakili zinazojitokeza mtegemezi anapoacha.",
        "Physical na mental symptoms zinazojitokeza dependent person anapoacha.")],
      [("Intoxication", "Kulewa", "Intoxication"),
       ("The immediate state after taking a substance — the 'high' and the loss of judgement with it.",
        "Hali ya papo hapo baada ya kuchukua kitu — 'kupanda' na kupoteza uamuzi pamoja nako.",
        "Immediate state baada ya kuchukua substance — 'high' na kupoteza judgement pamoja nayo.")],
      [("Addiction", "Uraibu", "Addiction"),
       ("Compulsive use that continues even when the person can see the harm it is doing.",
        "Matumizi ya kulazimishwa yanayoendelea hata mtu akiona madhara yanayosababishwa.",
        "Compulsive use inayoendelea hata msee akiona harm inayofanyika.")],
     ]},
   ]},

  # ── 2. Classification ─────────────────────────────────────────────
  {"icon": "🔬",
   "head": ("The Five Classes", "Makundi Matano", "Classes Tano"),
   "blocks": [
    {"type": "table",
     "headers": [("Class", "Kundi", "Class"), ("What it does", "Inafanya nini", "Inafanya nini"), ("Examples", "Mifano", "Examples")],
     "rows": [
      [("Stimulants", "Vichangamshi", "Stimulants"),
       ("Increase alertness, reduce sleep, lift mood; some suppress appetite",
        "Huongeza umakini, hupunguza usingizi, huinua hisia; zingine hupunguza hamu ya kula",
        "Zinaongeza alertness, zinapunguza usingizi, zinainua mood; zingine zinapunguza appetite"),
       ("Tobacco, shisha (flavoured tobacco), miraa", "Tumbaku, shisha (tumbaku yenye ladha), miraa", "Tobacco, shisha (flavoured tobacco), miraa")],
      [("Depressants", "Vituliza", "Depressants"),
       ("Reduce arousal and alertness, slow down reactions",
        "Hupunguza msisimko na umakini, hupunguza kasi ya majibu",
        "Zinapunguza arousal na alertness, zinapunguza speed ya reactions"),
       ("Alcohol, codeine, diazepam, heroin", "Pombe, kodeini, diazepam, heroini", "Pombe, codeine, diazepam, heroin")],
      [("Hallucinogens", "Vipotoshi", "Hallucinogens"),
       ("Modify brain function; distort and fragment perception, thought and emotion; cause illusions and delusions",
        "Hubadilisha utendaji wa ubongo; hupotosha na kuvunja mtazamo, fikra na hisia; husababisha njozi na imani potofu",
        "Zinabadilisha brain function; zinapotosha perception, thought na emotion; zinasababisha illusions na delusions"),
       ("Cannabis, hashish", "Bangi, hashish", "Bangi, hashish")],
      [("Steroids", "Steroidi", "Steroids"),
       ("Used to build muscle — common among young men",
        "Hutumiwa kujenga misuli — kawaida kwa vijana wa kiume",
        "Zinatumiwa kujenga muscle — common kwa vijana wa kiume"),
       ("Anabolic steroids", "Steroidi za anaboli", "Anabolic steroids")],
      [("Prescription medicine", "Dawa za daktari", "Prescription medicine"),
       ("Legitimate medicines taken without a prescription, or beyond it",
        "Dawa halali zinazochukuliwa bila agizo la daktari, au zaidi ya agizo",
        "Legitimate medicines zinazochukuliwa bila prescription, ama zaidi ya prescription"),
       ("Codeine, morphine, valium, pethidine", "Kodeini, morfini, valium, pethidine", "Codeine, morphine, valium, pethidine")],
     ]},
    {"type": "warn", "title": ("⚠️ Legal does not mean safe", "⚠️ Halali si salama", "⚠️ Legal si safe"), "text": (
     " Alcohol, tobacco and prescription medicine are all legal for someone, somewhere. Legality describes the law's position, not the drug's effect on a developing brain. The most damaging substances among Kenyan adolescents are mostly the legal ones.",
     " Pombe, tumbaku na dawa za daktari zote ni halali kwa mtu fulani, mahali fulani. Uhalali unaeleza msimamo wa sheria, si athari ya dawa kwenye ubongo unaokua. Vitu vinavyodhuru zaidi kwa vijana wa Kenya ni vile halali kwa wingi.",
     " Pombe, tobacco na prescription medicine zote ni legal kwa msee fulani, mahali fulani. Legality inaeleza position ya sheria, si effect ya drug kwa developing brain. Substances zinazodhuru zaidi kwa vijana wa Kenya ni zile legal mostly.")},
   ]},

  # ── 3. Why people start ───────────────────────────────────────────
  {"icon": "❓",
   "head": ("Why Young People Start", "Kwa Nini Vijana Huanza", "Kwa Nini Vijana Wanaanza"),
   "blocks": [
    {"type": "p", "text": (
     "Notice that not one of these reasons is 'to become addicted'. Every one of them is a need. If you only attack the drug and never address the need, the drug wins.",
     "Angalia kwamba hakuna hata sababu moja hapa ni 'kuwa mraibu'. Kila moja ni hitaji. Ukishambulia dawa tu na usishughulikie hitaji, dawa hushinda.",
     "Angalia ati hakuna hata reason moja hapa ni 'kuwa addicted'. Kila moja ni need. Uki-attack drug tu na usi-address need, drug inashinda.")},
    {"type": "list", "items": [
     ("To relax and feel calm", "Kupumzika na kujisikia mtulivu", "Ku-relax na kujiskia calm"),
     ("To feel happy", "Kujisikia furaha", "Kujiskia happy"),
     ("For pain relief", "Kupunguza maumivu", "Kwa pain relief"),
     ("To cope with stress", "Kukabiliana na msongo", "Ku-cope na stress"),
     ("Pressure from peers", "Shinikizo kutoka kwa wenzao", "Pressure kutoka kwa friends"),
     ("To help with sleep", "Kusaidia kulala", "Kusaidia kulala"),
     ("To feel more confident in social situations", "Kujisikia na ujasiri zaidi katika hali za kijamii", "Kujiskia confident zaidi kwa social situations"),
    ]},
    {"type": "facilitator", "minutes": 10, "text": (
     "Write the seven reasons on a board and ask the group which they have heard most often. Then ask: what else meets that same need? Every alternative they name themselves is worth more than one you supply.",
     "Andika sababu saba ubaoni na uulize kundi ni ipi wamesikia mara nyingi zaidi. Kisha uliza: ni nini kingine kinachotimiza hitaji hilo hilo? Kila mbadala wanaoutaja wenyewe una thamani zaidi ya ule unaoutoa wewe.",
     "Andika reasons saba kwa board na uulize group ni ipi wamesikia mara nyingi zaidi. Kisha uliza: ni nini kingine kinachomeet hiyo need? Kila alternative wanayo-name wenyewe ina value zaidi ya ile unayo-supply wewe.")},
   ]},

  # ── 4. The five stages ────────────────────────────────────────────
  {"icon": "🪜",
   "head": ("The Five Stages", "Hatua Tano", "Stages Tano"),
   "blocks": [
    {"type": "p", "text": (
     "This is the most useful framework in the module. Dependence is not an event — it is a slope, and each stage looks reasonable from inside the one before it.",
     "Huu ndio mfumo muhimu zaidi katika moduli hii. Utegemezi si tukio — ni mteremko, na kila hatua inaonekana ya busara ukiwa katika ile iliyotangulia.",
     "Hii ndio framework muhimu zaidi kwa module hii. Dependence si event — ni slope, na kila stage inaonekana reasonable ukiwa ndani ya ile iliyotangulia.")},
    {"type": "table",
     "headers": [("Stage", "Hatua", "Stage"), ("What it looks like", "Inavyoonekana", "Inavyoonekana")],
     "rows": [
      [("1. Experiential", "1. Kujaribu", "1. Experiential"),
       ("Trying it once, out of curiosity. 'Just to see.'",
        "Kujaribu mara moja, kwa udadisi. 'Kuona tu.'",
        "Ku-try mara moja, kwa curiosity. 'Kuona tu.'")],
      [("2. Social", "2. Kijamii", "2. Social"),
       ("Using with friends, at gatherings. Still tied to the occasion, not the substance.",
        "Kutumia na marafiki, kwenye mikusanyiko. Bado kunahusiana na tukio, si kitu chenyewe.",
        "Kutumia na friends, kwa gatherings. Bado inahusiana na occasion, si substance yenyewe.")],
      [("3. Instrumental", "3. Kutumia kwa kusudi", "3. Instrumental"),
       ("Using it <em>for</em> something — to sleep, to study, to cope, to feel confident.",
        "Kutumia <em>kwa</em> kitu — kulala, kusoma, kukabiliana, kujisikia ujasiri.",
        "Kutumia <em>kwa</em> kitu — kulala, kusoma, ku-cope, kujiskia confident.")],
      [("4. Habitual", "4. Kimazoea", "4. Habitual"),
       ("Now routine. It happens without a decision being made each time.",
        "Sasa ni kawaida. Hutokea bila uamuzi kufanywa kila mara.",
        "Saa hii ni routine. Inahappen bila decision kufanywa kila time.")],
      [("5. Compulsive", "5. Kulazimishwa", "5. Compulsive"),
       ("Dependence. Continuing despite clearly seeing the harm. Stopping now needs help.",
        "Utegemezi. Kuendelea licha ya kuona wazi madhara. Kuacha sasa kunahitaji msaada.",
        "Dependence. Kuendelea despite kuona wazi harm. Kuacha saa hii kunahitaji msaada.")],
     ]},
    {"type": "tip", "title": ("💡 Where a peer educator actually works", "💡 Mwelimishaji rika anafanya kazi wapi hasa", "💡 Peer educator anafanya kazi wapi hasa"), "text": (
     " Stages 1 to 3 are where a conversation can still change the direction. By stage 5 the person needs treatment, not persuasion — and your job shifts from talking to referring. Knowing which stage you are looking at tells you which job you are doing.",
     " Hatua 1 hadi 3 ndipo mazungumzo bado yanaweza kubadilisha mwelekeo. Kufikia hatua ya 5 mtu anahitaji matibabu, si ushawishi — na kazi yako hubadilika kutoka kuzungumza hadi kutoa rufaa. Kujua unaangalia hatua ipi kunakuambia unafanya kazi ipi.",
     " Stages 1 hadi 3 ndio mahali conversation bado inaweza ku-change direction. Kufika stage 5 msee anahitaji treatment, si persuasion — na job yako inabadilika kutoka kuongea hadi ku-refer. Kujua unaangalia stage ipi kunakuambia unafanya job ipi.")},
   ]},

  # ── 5. Factors ────────────────────────────────────────────────────
  {"icon": "🏠",
   "head": ("What Pushes Young People Toward It", "Kinachowasukuma Vijana Huko", "Kinachowa-push Vijana Huko"),
   "blocks": [
    {"type": "table",
     "headers": [("Family", "Familia", "Family"), ("School", "Shule", "School"), ("Peer", "Rika", "Peer")],
     "rows": [
      [("Ineffective parenting — absence, or a parent's death",
        "Malezi duni — kutokuwepo, au kifo cha mzazi",
        "Ineffective parenting — absence, ama kifo cha mzazi"),
       ("An inappropriate school environment",
        "Mazingira ya shule yasiyofaa",
        "Inappropriate school environment"),
       ("Early antisocial behaviour",
        "Tabia mbaya za mapema",
        "Early antisocial behaviour")],
      [("Inconsistent discipline",
        "Nidhamu isiyo thabiti",
        "Inconsistent discipline"),
       ("Poor school management",
        "Usimamizi duni wa shule",
        "Poor school management"),
       ("Spending most time with using peers",
        "Kutumia muda mwingi na wenzao wanaotumia",
        "Kutumia time nyingi na friends wanaotumia")],
      [("Parents using or abusing substances themselves",
        "Wazazi wenyewe wanaotumia au kutumia vibaya dawa",
        "Wazazi wenyewe wanaotumia ama ku-abuse substances"),
       ("Irresponsible staff — abusing or selling to students",
        "Wafanyakazi wasiowajibika — wanaotumia au kuuza kwa wanafunzi",
        "Irresponsible staff — wanaotumia ama kuuza kwa wanafunzi"),
       ("Low interest in education",
        "Hamu ndogo ya elimu",
        "Low interest kwa education")],
      [("A chaotic home — poor or absent communication",
        "Nyumba yenye vurugu — mawasiliano duni au yasiyokuwepo",
        "Chaotic home — poor ama absent communication"),
       ("Failure in school performance",
        "Kushindwa katika ufaulu wa shule",
        "Kushindwa kwa school performance"),
       ("Feeling different from everyone around them",
        "Kujihisi tofauti na kila mtu aliye karibu",
        "Kujiskia different na kila msee aliye karibu")],
      [("Lack of attachment; conflict between parents and adolescent",
        "Ukosefu wa uhusiano; migogoro kati ya wazazi na kijana",
        "Lack ya attachment; conflict kati ya wazazi na kijana"),
       ("", "", ""),
       ("", "", "")],
     ]},
    {"type": "sheng", "text": (
     "Angalia orodha hiyo tena. Karibu kila kitu ni jambo lililomtokea kijana, si alilochagua. Ndiyo maana kumlaumu ni kuchelewa, na kumsaidia ni mapema.",
     "Angalia orodha hiyo tena. Karibu kila kitu ni jambo lililomtokea kijana, si alilochagua. Ndiyo maana kumlaumu ni kuchelewa, na kumsaidia ni mapema.",
     "Angalia hiyo list tena. Karibu kila kitu ni kitu kilicho-happen kwa kijana, si alichochagua. Ndio maana ku-blame ni kuchelewa, na kusaidia ni mapema.")},
   ]},

  # ── 6. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "Otieno, 18, tells you he only drinks at weekends with friends, but recently he has started having one on Sunday nights 'to sleep before school'.",
      "Otieno, miaka 18, anakuambia hunywa wikendi tu na marafiki, lakini hivi karibuni ameanza kunywa moja Jumapili usiku 'ili alale kabla ya shule'.",
      "Otieno, 18, anakuambia hunywa weekend tu na friends, lakini recently ameanza kunywa moja Sunday usiku 'ili alale kabla ya shule'."),
     "question": ("What has actually changed?", "Nini kimebadilika hasa?", "Nini kime-change hasa?"),
     "choices": [
      {"kind": "bad",
       "text": ("Nothing much — one drink to sleep is not a problem at his age",
                "Si kitu kikubwa — kinywaji kimoja ili alale si tatizo katika umri wake",
                "Si kitu kikubwa — drink moja ili alale si problem kwa age yake"),
       "outcome": ("Something specific has changed: he has moved from social use to instrumental use — drinking FOR something. That is stage 2 to stage 3, and it is the point at which the substance starts doing a job that nothing else is doing. Missing it means meeting him again at stage 4.",
                   "Kitu mahususi kimebadilika: amehama kutoka matumizi ya kijamii hadi matumizi ya kusudi — kunywa KWA kitu. Hiyo ni hatua ya 2 hadi ya 3, na ndipo kitu hicho kinapoanza kufanya kazi ambayo hakuna kingine kinachofanya. Kukosa hilo kunamaanisha kukutana naye tena hatua ya 4.",
                   "Kitu specific kime-change: amehama kutoka social use hadi instrumental use — kunywa KWA kitu. Hiyo ni stage 2 hadi stage 3, na ndio point ambapo substance inaanza kufanya job ambayo hakuna kingine kinachofanya. Ku-miss hiyo inamaanisha kukutana naye tena stage 4.")},
      {"kind": "good",
       "text": ("Name the shift — from drinking with people to drinking for a reason — and ask what is keeping him awake",
                "Taja mabadiliko — kutoka kunywa na watu hadi kunywa kwa sababu — na uulize ni nini kinachomkosesha usingizi",
                "Name hiyo shift — kutoka kunywa na wasee hadi kunywa kwa reason — na uulize ni nini kinachomkosesha usingizi"),
       "outcome": ("You said: 'Weekends with friends is one thing. Sunday night on your own so you can sleep is a different thing — that's it doing a job for you now. What's actually keeping you awake?' It turned out to be exam pressure. That was the real conversation. ✅",
                   "Ulisema: 'Wikendi na marafiki ni jambo moja. Jumapili usiku peke yako ili ulale ni jambo tofauti — hiyo ni kufanya kazi kwa ajili yako sasa. Ni nini hasa kinachokukosesha usingizi?' Ilibainika ni shinikizo la mitihani. Hayo ndiyo yaliyokuwa mazungumzo halisi. ✅",
                   "Ulisema: 'Weekend na friends ni kitu kimoja. Sunday usiku peke yako ili ulale ni kitu tofauti — hiyo ni kufanya job kwa ajili yako saa hii. Ni nini hasa kinachokukosesha usingizi?' Ikabainika ni exam pressure. Hiyo ndio ilikuwa real conversation. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A group member argues that alcohol cannot be a real drug because it is legal, sold openly, and their parents drink it.",
      "Mwanachama wa kundi anahoji kwamba pombe haiwezi kuwa dawa halisi ya kulevya kwa sababu ni halali, inauzwa wazi, na wazazi wao hunywa.",
      "Member wa group anaargue ati pombe haiwezi kuwa real drug kwa sababu ni legal, inauzwa wazi, na wazazi wao hunywa."),
     "question": ("How do you answer?", "Unajibu vipi?", "Una-answer aje?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell him alcohol is worse than most illegal drugs",
                "Mwambie pombe ni mbaya kuliko dawa nyingi haramu",
                "Mwambie pombe ni mbaya kuliko drugs nyingi illegal"),
       "outcome": ("Overstating loses you the room, and anyone whose parent drinks now hears you calling their family the worst kind of user. Exaggeration is how peer educators lose credibility on the topics that matter most.",
                   "Kutia chumvi kunakupotezea chumba, na yeyote ambaye mzazi wake hunywa sasa anakusikia ukiiita familia yake watumiaji wabaya zaidi. Kutia chumvi ndiko waelimishaji rika hupoteza uaminifu kwenye mada muhimu zaidi.",
                   "Ku-overstate inakupotezea room, na yeyote ambaye mzazi wake hunywa saa hii anakusikia uki-call family yake worst kind ya users. Exaggeration ndio jinsi peer educators wanapoteza credibility kwa topics muhimu zaidi.")},
      {"kind": "good",
       "text": ("Separate what the law says from what the substance does",
                "Tenganisha sheria inachosema na kitu chenyewe kinachofanya",
                "Separate sheria inachosema na substance yenyewe inachofanya"),
       "outcome": ("You said: 'Legal is about the law, not about the effect. Alcohol is a depressant — it slows reactions and judgement whoever is drinking it. Being sold openly tells you about trade, not about what it does to a brain that's still developing.' The argument stopped because it was accurate, not because it was loud. ✅",
                   "Ulisema: 'Uhalali unahusu sheria, si athari. Pombe ni kituliza — hupunguza kasi ya majibu na uamuzi kwa yeyote anayeinywa. Kuuzwa wazi kunakuambia kuhusu biashara, si kuhusu inachofanya kwa ubongo bado unaokua.' Hoja ilikoma kwa sababu ilikuwa sahihi, si kwa sababu ilikuwa ya kelele. ✅",
                   "Ulisema: 'Legal ni kuhusu sheria, si kuhusu effect. Pombe ni depressant — inapunguza speed ya reactions na judgement kwa yeyote anayeinywa. Kuuzwa wazi kunakuambia kuhusu biashara, si kuhusu inachofanya kwa brain bado inayokua.' Argument ili-stop kwa sababu ilikuwa accurate, si kwa sababu ilikuwa ya kelele. ✅")},
     ]},
   ]},

  # ── 7. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Use, abuse, dependence and addiction are different things — precision matters.",
      "Matumizi, matumizi mabaya, utegemezi na uraibu ni vitu tofauti — usahihi ni muhimu.",
      "Use, abuse, dependence na addiction ni vitu tofauti — precision ni muhimu."),
     ("Legal does not mean safe. The most damaging substances among Kenyan adolescents are largely the legal ones.",
      "Halali si salama. Vitu vinavyodhuru zaidi kwa vijana wa Kenya ni vile halali kwa wingi.",
      "Legal si safe. Substances zinazodhuru zaidi kwa vijana wa Kenya ni zile legal mostly."),
     ("Dependence is a slope of five stages, not a single event.",
      "Utegemezi ni mteremko wa hatua tano, si tukio moja.",
      "Dependence ni slope ya stages tano, si event moja."),
     ("Almost every risk factor is something that happened to a young person, not something they chose.",
      "Karibu kila sababu ya hatari ni jambo lililomtokea kijana, si alilochagua.",
      "Karibu kila risk factor ni kitu kilicho-happen kwa kijana, si alichochagua."),
    ]},
    {"type": "p", "text": (
     "Part 2 covers how to recognise it, the substances common in Kenya that this curriculum does not name, and where to send someone for help.",
     "Sehemu ya 2 inahusu jinsi ya kuitambua, vitu vilivyo vya kawaida Kenya ambavyo mtaala huu hauvitaji, na wapi kumpeleka mtu kwa msaada.",
     "Part 2 inacover jinsi ya kui-recognise, substances common Kenya ambazo hii curriculum haizitaji, na wapi kumpeleka msee kwa msaada.")},
   ]},
 ],

 "quiz": [
  {"q": "What is tolerance?",
   "options": ["Being able to handle a drug better than others",
               "Needing more of the substance to get the same effect it used to give",
               "Not being affected by a drug at all",
               "The symptoms that appear when you stop"],
   "answer": "B",
   "explain": "Tolerance is the body adjusting, so the old amount no longer produces the old effect. It is often the first quiet sign of trouble."},

  {"q": "Which class of drug does alcohol belong to?",
   "options": ["Stimulant", "Depressant", "Hallucinogen", "Steroid"],
   "answer": "B",
   "explain": "Depressants reduce arousal and alertness and slow reactions. Alcohol, codeine, diazepam and heroin are all in this class."},

  {"q": "Otieno moves from drinking at weekends with friends to drinking alone on Sunday nights to sleep. What has changed?",
   "options": ["Nothing — the amount is the same",
               "He has moved from social use to instrumental use",
               "He has become physically dependent",
               "He has developed tolerance"],
   "answer": "B",
   "explain": "Stage 2 to stage 3. The substance is now doing a job — which is the point at which the conversation needs to be about the job, not the drink."},

  {"q": "Put in order, what are the five stages of substance abuse?",
   "options": ["Social, experiential, habitual, instrumental, compulsive",
               "Experiential, social, instrumental, habitual, compulsive",
               "Experiential, instrumental, social, compulsive, habitual",
               "Social, instrumental, experiential, habitual, compulsive"],
   "answer": "B",
   "explain": "Each stage looks reasonable from inside the one before it — which is exactly why the slope is hard to notice from the inside."},

  {"q": "Which are family-based risk factors named in the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Parents using or abusing substances themselves",
               "Inconsistent discipline",
               "A chaotic home with poor communication",
               "Conflict between parents and the adolescent",
               "Failure in school performance"],
   "answer": ["A", "B", "C", "D"],
   "explain": "School performance is a school-related factor, not a family one — though the two often travel together."},

  {"q": "A peer says alcohol is not a real drug because it is legal. What is the accurate response?",
   "options": ["Agree — legal substances are less harmful",
               "Tell him alcohol is worse than most illegal drugs",
               "Explain that legality describes the law's position, not the substance's effect",
               "Avoid the topic since his parents drink"],
   "answer": "C",
   "explain": "Overstating costs you credibility. Accuracy — legality is about trade and law, not about what it does to a developing brain — ends the argument properly."},

  {"q": "Which is TRUE of the reasons young people give for starting?",
   "options": ["Most are simply about rebellion",
               "Each one is a need — relaxation, sleep, confidence, coping",
               "Most young people intend to become dependent",
               "Peer pressure is the only real reason"],
   "answer": "B",
   "explain": "If you attack the drug and never address the need, the drug wins. That is why the useful question is what else meets the same need."},

  {"q": "Shisha is classified as which type of drug?",
   "options": ["A depressant", "A stimulant — it is flavoured tobacco", "A hallucinogen", "Not a drug at all"],
   "answer": "B",
   "explain": "The curriculum lists shisha under stimulants, as flavoured tobacco. The flavouring changes the taste, not the class."},

  {"q": "At which stages can a peer educator's conversation still change direction?",
   "options": ["Only stage 1",
               "Stages 1 to 3",
               "Stage 5 especially",
               "All stages equally"],
   "answer": "B",
   "explain": "By stage 5 the person needs treatment rather than persuasion, and your job shifts from talking to referring."},

  {"q": "What distinguishes dependency from addiction?",
   "options": ["They are identical",
               "Dependency is needing it to function normally; addiction is compulsive use continuing despite visible harm",
               "Dependency only applies to illegal drugs",
               "Addiction is purely physical, dependency purely mental"],
   "answer": "B",
   "explain": "The distinction matters because it changes what help is needed — and because using the words loosely lets a real problem be dismissed."},
 ],
}
