# Module 10 (part 2 of 2) — Recognising Substance Abuse and Responding
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 10.
# Local substance content (miraa/khat, shisha) cross-checked against ARISE's
# own lessons, since the national deck names shisha only in passing and does
# not mention miraa or khat at all.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m10b-recognising-and-responding.html",
 "module_code": "M10",
 "module_slug": "drug-substance-abuse",
 "lesson_slug": "m10b-recognising-and-responding",
 "module_label": "Peer Educator · M10 · Part 2 of 2",
 "title": "Recognising Substance Abuse and Responding",
 "icon": "🩺",
 "duration": 45,

 "objectives": [
  ("Describe the signs and symptoms of drug and substance abuse",
   "Eleza dalili za matumizi mabaya ya dawa za kulevya",
   "Describe signs na symptoms za drug na substance abuse"),
  ("Explain the health and social consequences for young people",
   "Eleza madhara ya kiafya na kijamii kwa vijana",
   "Explain health na social consequences kwa vijana"),
  ("Discuss the substances common in Kenya, including miraa and shisha",
   "Jadili vitu vilivyo vya kawaida Kenya, ikiwemo miraa na shisha",
   "Discuss substances common Kenya, ikiwemo miraa na shisha"),
  ("Describe prevention, harm reduction and where to send someone for help",
   "Eleza kuzuia, kupunguza madhara na wapi kumpeleka mtu kwa msaada",
   "Describe prevention, harm reduction na wapi kumpeleka msee kwa msaada"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> You notice a friend changing. Say something and you might be wrong and lose them. Say nothing and you might be right. Which risk do you take?",
  "<strong>🔍 Swali Kubwa:</strong> Unamwona rafiki akibadilika. Ukisema unaweza kuwa umekosea na umpoteze. Usiposema unaweza kuwa ulikuwa sahihi. Ni hatari ipi unachukua?",
  "<strong>🔍 Big Question:</strong> Unaona friend akibadilika. Ukisema unaweza kuwa umekosea na umpoteze. Usiposema unaweza kuwa ulikuwa sahihi. Ni risk ipi unachukua?"),

 "slides": [

  # ── 1. Signs ──────────────────────────────────────────────────────
  {"icon": "🔍",
   "head": ("Signs and Symptoms", "Dalili na Ishara", "Signs na Symptoms"),
   "blocks": [
    {"type": "p", "text": (
     "No single sign proves anything. It is the <strong>cluster</strong> and the <strong>change</strong> that matter — several of these appearing together, in someone who was not like that before.",
     "Hakuna dalili moja inayothibitisha chochote. Ni <strong>mkusanyiko</strong> na <strong>mabadiliko</strong> ndiyo muhimu — kadhaa kati ya hizi zikijitokeza pamoja, kwa mtu ambaye hakuwa hivyo awali.",
     "Hakuna sign moja inayothibitisha kitu. Ni <strong>cluster</strong> na <strong>change</strong> ndio muhimu — kadhaa kati ya hizi zikijitokeza pamoja, kwa msee ambaye hakuwa hivyo awali.")},
    {"type": "table",
     "headers": [("Behaviour", "Tabia", "Behaviour"), ("School or work", "Shule au kazi", "Shule ama kazi"), ("Body and mood", "Mwili na hisia", "Mwili na mood")],
     "rows": [
      [("Sudden personality change with no known cause",
        "Mabadiliko ya ghafla ya tabia bila sababu inayojulikana",
        "Sudden personality change bila sababu inayojulikana"),
       ("Sudden decline in performance or attendance",
        "Kushuka kwa ghafla kwa ufaulu au mahudhurio",
        "Sudden decline kwa performance ama attendance"),
       ("Poor personal hygiene and grooming",
        "Usafi duni wa mwili na mavazi",
        "Poor personal hygiene na grooming")],
      [("Changed friends, and reluctance to talk about them",
        "Marafiki waliobadilika, na kusita kuzungumza kuwahusu",
        "Friends waliobadilika, na kusita kuongea kuwahusu"),
       ("Frequent absence",
        "Kutokuwepo mara kwa mara",
        "Frequent absence"),
       ("Difficulty paying attention, or forgetfulness",
        "Ugumu wa kuzingatia, au usahaulifu",
        "Ugumu wa ku-pay attention, ama forgetfulness")],
      [("Increased secretiveness; sharp sensitivity to any question",
        "Kuongezeka kwa usiri; kuathirika sana na swali lolote",
        "Kuongezeka kwa secretiveness; sensitivity kali kwa question yoyote"),
       ("Low interest in education; inappropriate classroom behaviour",
        "Hamu ndogo ya elimu; tabia zisizofaa darasani",
        "Low interest kwa education; inappropriate classroom behaviour"),
       ("Sudden aggression, irritability, nervousness or giddiness",
        "Ukali wa ghafla, hasira, wasiwasi au kizunguzungu",
        "Sudden aggression, irritability, nervousness ama giddiness")],
      [("Stealing or selling personal items to fund use",
        "Kuiba au kuuza vitu binafsi kufadhili matumizi",
        "Kuiba ama kuuza personal items ku-fund use"),
       ("Bullying others; placement in special classes",
        "Kuwaonea wengine; kuwekwa katika madarasa maalum",
        "Ku-bully wengine; kuwekwa kwa special classes"),
       ("Loss of interest in hobbies and sport once enjoyed",
        "Kupoteza hamu ya vitu vya kupendeza na michezo vilivyokuwa vikifurahisha",
        "Kupoteza interest kwa hobbies na sport zilizokuwa zikifurahisha")],
      [("Withdrawal symptoms when unable to use",
        "Dalili za kuachana asipoweza kutumia",
        "Withdrawal symptoms asipoweza kutumia"),
       ("", "", ""), ("", "", "")],
     ]},
    {"type": "warn", "title": ("⚠️ Adolescence looks like this too", "⚠️ Ujana pia huonekana hivi", "⚠️ Adolescence pia inaonekana hivi"), "text": (
     " Mood swings, new friends, secrecy and dropping grades are also just being fifteen. That is why you never accuse — you ask, you stay close, and you notice whether the cluster grows.",
     " Mabadiliko ya hisia, marafiki wapya, usiri na alama kushuka pia ni kuwa na miaka kumi na mitano tu. Ndiyo maana husitushi kamwe — unauliza, unabaki karibu, na unaangalia kama mkusanyiko unakua.",
     " Mood swings, friends wapya, secrecy na grades kushuka pia ni kuwa na miaka fifteen tu. Ndio maana hu-accuse kamwe — unauliza, unabaki karibu, na unaangalia kama cluster inakua.")},
   ]},

  # ── 2. Consequences ───────────────────────────────────────────────
  {"icon": "📉",
   "head": ("What It Costs a Young Person", "Inavyomgharimu Kijana", "Inavyomgharimu Kijana"),
   "blocks": [
    {"type": "list", "items": [
     ("Early school dropout and failure in performance",
      "Kuacha shule mapema na kushindwa katika ufaulu",
      "Early school dropout na kushindwa kwa performance"),
     ("Delinquency and juvenile crime",
      "Utovu wa nidhamu na uhalifu wa vijana",
      "Delinquency na juvenile crime"),
     ("Risky sexual behaviour — and the infections and pregnancies that follow",
      "Tabia hatarishi za kingono — na maambukizi na mimba zinazofuata",
      "Risky sexual behaviour — na infections na pregnancies zinazofollow"),
     ("Indiscipline in schools, including riots and strikes",
      "Utovu wa nidhamu shuleni, ikiwemo vurugu na migomo",
      "Indiscipline shuleni, ikiwemo riots na strikes"),
     ("Bullying, and placement in special classes",
      "Kuwaonea wengine, na kuwekwa katika madarasa maalum",
      "Bullying, na kuwekwa kwa special classes"),
    ]},
    {"type": "example", "title": ("🇰🇪 The link peers underestimate", "🇰🇪 Uhusiano wenzako hawaupi uzito", "🇰🇪 Link ambayo wasee wanai-underestimate"), "text": (
     "Intoxication removes judgement before it removes anything else. Most of the risky sexual decisions in Module 13B, and a good share of the GBV in Module 12, happen after someone has been drinking. Substance use is not a separate topic from those — it is often the doorway into them.",
     "Kulewa huondoa uamuzi kabla ya kuondoa kitu kingine chochote. Maamuzi mengi hatarishi ya kingono katika Moduli 13B, na sehemu kubwa ya ukatili katika Moduli 12, hutokea baada ya mtu kunywa. Matumizi ya dawa si mada tofauti na hayo — mara nyingi ni mlango wa kuingia.",
     "Intoxication inaondoa judgement kabla ya kuondoa kitu kingine. Risky sexual decisions nyingi za Module 13B, na sehemu kubwa ya GBV ya Module 12, zinahappen baada ya msee kunywa. Substance use si topic tofauti na hizo — mara nyingi ni doorway ya kuingia.")},
   ]},

  # ── 3. Local substances ───────────────────────────────────────────
  {"icon": "🇰🇪",
   "head": ("What Young Kenyans Actually Use", "Vijana wa Kenya Hutumia Nini Hasa", "Vijana wa Kenya Wanatumia Nini Hasa"),
   "blocks": [
    {"type": "p", "text": (
     "The national curriculum names shisha only in passing, and does not mention miraa at all. In much of Kenya these are the two you will actually meet, so a peer educator needs the facts on both.",
     "Mtaala wa kitaifa unataja shisha kwa kupita tu, na hautaji miraa kabisa. Katika sehemu kubwa ya Kenya hivi ndivyo utakavyokutana navyo hasa, hivyo mwelimishaji rika anahitaji ukweli wa vyote viwili.",
     "National curriculum inataja shisha kwa kupita tu, na haitaji miraa kabisa. Kwa sehemu kubwa ya Kenya hizi ndio mbili utakutana nazo hasa, so peer educator anahitaji facts za zote mbili.")},
    {"type": "key_term", "term": ("🔑 Miraa (khat)", "🔑 Miraa (khat)", "🔑 Miraa (khat)"), "text": (
     "Catha edulis — a plant native to East Africa whose fresh leaves and stems are chewed as a stimulant. A major cash crop in Meru County. It contains cathinone and cathine; cathinone is the stronger and degrades quickly after harvest, which is why users want it fresh within 48 hours.",
     "Catha edulis — mmea wa Afrika Mashariki ambao majani na vikonyo vyake vibichi hutafunwa kama kichangamshi. Zao kuu la biashara katika Kaunti ya Meru. Una cathinone na cathine; cathinone ndiyo yenye nguvu zaidi na huharibika haraka baada ya kuvunwa, ndiyo maana watumiaji huitaka mbichi ndani ya saa 48.",
     "Catha edulis — mmea wa East Africa ambao majani na stems zake fresh zinatafunwa kama stimulant. Major cash crop kwa Meru County. Ina cathinone na cathine; cathinone ndio yenye nguvu zaidi na inaharibika haraka baada ya harvest, ndio maana users wanaitaka fresh ndani ya masaa 48.")},
    {"type": "list", "items": [
     ("Effects begin within <strong>15–30 minutes</strong> and last <strong>3–6 hours</strong>",
      "Athari huanza ndani ya <strong>dakika 15–30</strong> na hudumu <strong>saa 3–6</strong>",
      "Effects zinaanza ndani ya <strong>dakika 15–30</strong> na zinadumu <strong>masaa 3–6</strong>"),
     ("The <strong>WHO classifies khat as a drug of abuse</strong> that can produce mild-to-moderate psychological dependence",
      "<strong>WHO inaainisha khat kama dawa ya matumizi mabaya</strong> inayoweza kusababisha utegemezi wa kisaikolojia wa wastani",
      "<strong>WHO ina-classify khat kama drug of abuse</strong> inayoweza kusababisha mild-to-moderate psychological dependence"),
     ("It does not cause the severe physical withdrawal of heroin or alcohol — but users report being unable to work, socialise or feel normal without it",
      "Haisababishi dalili kali za kimwili za kuachana kama heroini au pombe — lakini watumiaji husema hawawezi kufanya kazi, kushirikiana au kujisikia kawaida bila yake",
      "Haisababishi severe physical withdrawal kama heroin ama pombe — lakini users wanasema hawawezi kufanya kazi, ku-socialise ama kujiskia normal bila yake"),
     ("Studies suggest up to <strong>30% of young people in miraa-growing regions</strong> chew regularly; mental health admissions linked to khat have risen in Meru and Nairobi",
      "Tafiti zinaonyesha hadi <strong>asilimia 30 ya vijana katika maeneo yanayolima miraa</strong> hutafuna mara kwa mara; kulazwa hospitalini kwa afya ya akili kuhusiana na khat kumeongezeka Meru na Nairobi",
      "Studies zinaonyesha hadi <strong>30% ya vijana kwa maeneo yanayolima miraa</strong> wanatafuna regularly; mental health admissions zinazohusiana na khat zimeongezeka Meru na Nairobi"),
    ]},
    {"type": "sheng", "label": "Culture and Health", "text": (
     "Unaweza kuheshimu utamaduni wako na bado ukalinda afya yako. Mila zinaweza kubadilika. Swali si 'je ni yetu?' — ni 'je inatudhuru?'",
     "Unaweza kuheshimu utamaduni wako na bado ukalinda afya yako. Mila zinaweza kubadilika. Swali si 'je ni yetu?' — ni 'je inatudhuru?'",
     "Unaweza ku-respect culture yako na bado u-protect health yako. Traditions zinaweza ku-evolve. Question si 'je ni yetu?' — ni 'je inatudhuru?'")},
   ]},

  # ── 4. Shisha ─────────────────────────────────────────────────────
  {"icon": "💨",
   "head": ("Shisha — The Myths That Keep It Going", "Shisha — Imani Potofu Zinazoiendeleza", "Shisha — Myths Zinazoi-keep Going"),
   "blocks": [
    {"type": "p", "text": (
     "Shisha (also called hookah, water pipe, narghile or hubble bubble) burns charcoal over <em>maassel</em> — tobacco soaked in molasses, honey, fruit flavouring and glycerine. The sweetness and fruit smell hide the tobacco and the nicotine.",
     "Shisha (pia huitwa hookah, kiko cha maji, narghile au hubble bubble) huchoma mkaa juu ya <em>maassel</em> — tumbaku iliyolowekwa katika molasi, asali, ladha za matunda na glycerine. Utamu na harufu ya matunda hufunika tumbaku na nikotini.",
     "Shisha (pia inaitwa hookah, water pipe, narghile ama hubble bubble) inachoma charcoal juu ya <em>maassel</em> — tobacco iliyolowekwa kwa molasses, asali, fruit flavouring na glycerine. Utamu na harufu ya matunda zinaficha tobacco na nicotine.")},
    {"type": "table",
     "headers": [("The myth", "Imani potofu", "Myth"), ("The fact", "Ukweli", "Fact")],
     "rows": [
      [("'The water filters out the harmful stuff'",
        "'Maji huchuja vitu vyenye madhara'",
        "'Maji zina-filter vitu vyenye madhara'"),
       ("<strong>The water does not filter harmful chemicals.</strong> It cools the smoke so it feels smoother — the toxins pass through unchanged. This is the biggest shisha myth.",
        "<strong>Maji hayachuji kemikali zenye madhara.</strong> Hupoza moshi ili uhisi laini — sumu hupita bila kubadilika. Hii ndiyo imani potofu kubwa zaidi ya shisha.",
        "<strong>Maji hazi-filter harmful chemicals.</strong> Zinapoza smoke ili ihisi smoother — toxins zinapita bila kubadilika. Hii ndio biggest shisha myth.")],
      [("'It is just flavoured steam, not a real drug'",
        "'Ni mvuke wenye ladha tu, si dawa halisi'",
        "'Ni flavoured steam tu, si real drug'"),
       ("It is tobacco. The flavouring changes the taste, not the class — the curriculum lists shisha under stimulants for exactly that reason.",
        "Ni tumbaku. Ladha hubadilisha onja, si kundi — mtaala unaorodhesha shisha chini ya vichangamshi kwa sababu hiyo hasa.",
        "Ni tobacco. Flavouring inabadilisha taste, si class — curriculum ina-list shisha chini ya stimulants kwa hiyo sababu hasa.")],
      [("'Sharing a pipe is harmless'",
        "'Kushiriki kiko hakuna madhara'",
        "'Kushare pipe hakuna madhara'"),
       ("Sharing directly transmits <strong>TB, herpes, hepatitis and other respiratory infections</strong>. New mouthpieces do not fully prevent it.",
        "Kushiriki huambukiza moja kwa moja <strong>kifua kikuu, herpes, homa ya ini na maambukizi mengine ya kupumua</strong>. Midomo mipya haizuii kabisa.",
        "Kushare kunaambukiza directly <strong>TB, herpes, hepatitis na respiratory infections zingine</strong>. Mouthpieces mpya hazi-prevent fully.")],
     ]},
   ]},

  # ── 5. Prevention ─────────────────────────────────────────────────
  {"icon": "🛡️",
   "head": ("Prevention — Build the Protective Side", "Kuzuia — Jenga Upande wa Ulinzi", "Prevention — Jenga Protective Side"),
   "blocks": [
    {"type": "p", "text": (
     "Prevention that only says 'don't' has a poor record. What works is strengthening the things that make a young person less likely to need it in the first place.",
     "Kuzuia kunakosema 'usifanye' tu kuna rekodi mbaya. Kinachofanya kazi ni kuimarisha mambo yanayomfanya kijana asihitaji tangu mwanzo.",
     "Prevention inayosema 'usifanye' tu ina record mbaya. Kinachowork ni ku-strengthen vitu vinavyomfanya kijana asi-need tangu mwanzo.")},
    {"type": "list", "items": [
     ("<strong>Protective factors:</strong> strong family bonds, parental monitoring and involvement, success at school, prosocial institutions, and clear community norms about drug use",
      "<strong>Mambo ya kinga:</strong> uhusiano imara wa kifamilia, ufuatiliaji na ushiriki wa wazazi, mafanikio shuleni, taasisi za kijamii, na kanuni wazi za jamii kuhusu matumizi",
      "<strong>Protective factors:</strong> strong family bonds, parental monitoring na involvement, success shuleni, prosocial institutions, na clear community norms kuhusu drug use"),
     ("<strong>Interactive skills training</strong> — resisting drugs, strengthening personal commitment, building social competence, reinforcing attitudes against use",
      "<strong>Mafunzo shirikishi ya ujuzi</strong> — kukataa dawa, kuimarisha dhamira binafsi, kujenga uwezo wa kijamii, kuimarisha mitazamo dhidi ya matumizi",
      "<strong>Interactive skills training</strong> — ku-resist drugs, ku-strengthen personal commitment, kujenga social competence, ku-reinforce attitudes dhidi ya use"),
     ("<strong>Family-focused programmes</strong> have greater impact than parent-only or child-only ones",
      "<strong>Programu zinazolenga familia</strong> zina athari kubwa kuliko za wazazi peke yao au watoto peke yao",
      "<strong>Family-focused programmes</strong> zina impact kubwa kuliko za wazazi peke yao ama watoto peke yao"),
     ("<strong>Address the local drug problem specifically</strong> — and be culturally sensitive about it",
      "<strong>Shughulikia tatizo la dawa la eneo hasa</strong> — na uwe mwangalifu kiutamaduni kulihusu",
      "<strong>Address local drug problem specifically</strong> — na uwe culturally sensitive kuihusu"),
    ]},
    {"type": "facilitator", "minutes": 8, "text": (
     "Ask the group to name the single most abused substance in their own community, then design a two-minute message aimed at it specifically. Generic 'say no to drugs' messaging is exactly what the curriculum warns against.",
     "Uliza kundi litaje kitu kinachotumiwa vibaya zaidi katika jamii yao, kisha waandae ujumbe wa dakika mbili unaokilenga hasa. Ujumbe wa jumla wa 'sema hapana kwa dawa' ndio hasa mtaala unaoonya dhidi yake.",
     "Uliza group i-name substance inayotumiwa vibaya zaidi kwa community yao, kisha wa-design message ya dakika mbili inayoi-target specifically. Generic 'say no to drugs' messaging ndio hasa curriculum inaonya dhidi yake.")},
   ]},

  # ── 6. Harm reduction ─────────────────────────────────────────────
  {"icon": "🤝",
   "head": ("Treatment and Harm Reduction", "Matibabu na Kupunguza Madhara", "Treatment na Harm Reduction"),
   "blocks": [
    {"type": "p", "text": (
     "Once someone is dependent, the question stops being how to persuade them and becomes how to keep them alive and connected until treatment works.",
     "Mtu akishakuwa mtegemezi, swali huacha kuwa jinsi ya kumshawishi na kuwa jinsi ya kumweka hai na ameunganishwa hadi matibabu yafanye kazi.",
     "Msee akishakuwa dependent, question inaacha kuwa jinsi ya kum-persuade na inakuwa jinsi ya kum-keep alive na connected mpaka treatment i-work.")},
    {"type": "list", "items": [
     ("<strong>Careful assessment first</strong> — the nature of the use, what underlies it, and what response capacity exists",
      "<strong>Tathmini makini kwanza</strong> — aina ya matumizi, kinachoyachochea, na uwezo wa kukabiliana uliopo",
      "<strong>Careful assessment kwanza</strong> — nature ya use, kinachoi-underlie, na response capacity iliyopo"),
     ("<strong>Community outreach</strong> — services delivered close to where people live, buy or use are far more effective",
      "<strong>Ufikiaji wa jamii</strong> — huduma zinazotolewa karibu na wanapoishi, kununua au kutumia zina ufanisi zaidi",
      "<strong>Community outreach</strong> — services zinazotolewa karibu na wanapoishi, kununua ama kutumia zina effectiveness zaidi"),
     ("<strong>Trusting relationships</strong> — positive relations between providers and people who use drugs increase uptake. Judgement reduces it.",
      "<strong>Mahusiano ya kuaminiana</strong> — uhusiano mzuri kati ya watoa huduma na watumiaji huongeza matumizi ya huduma. Kuhukumu hupunguza.",
      "<strong>Trusting relationships</strong> — positive relations kati ya providers na wasee wanaotumia drugs zinaongeza uptake. Judgement inapunguza."),
     ("<strong>Multiple targets</strong> — interventions should benefit the person, their partners and their family",
      "<strong>Malengo mengi</strong> — hatua zinapaswa kumnufaisha mtu, wenzi wake na familia yake",
      "<strong>Multiple targets</strong> — interventions zinafaa ku-benefit msee, partners wake na family yake"),
     ("<strong>Continuous monitoring and health education</strong> — services adjust as needs change, and every contact is a chance to reduce risk",
      "<strong>Ufuatiliaji na elimu ya afya endelevu</strong> — huduma hubadilika mahitaji yanapobadilika, na kila mkutano ni nafasi ya kupunguza hatari",
      "<strong>Continuous monitoring na health education</strong> — services zinabadilika needs zinapobadilika, na kila contact ni chance ya kupunguza risk"),
    ]},
   ]},

  # ── 7. Where to get help ──────────────────────────────────────────
  {"icon": "📞",
   "head": ("Where to Send Someone in Kenya", "Wapi Kumpeleka Mtu Kenya", "Wapi Kumpeleka Msee Kenya"),
   "blocks": [
    {"type": "p", "text": (
     "Start with the people already around them — a teacher, youth leader or community health volunteer — or the nearest health facility. Then these.",
     "Anza na watu waliopo karibu nao — mwalimu, kiongozi wa vijana au mhudumu wa afya wa jamii — au kituo cha afya cha karibu. Kisha hizi.",
     "Anza na wasee walio karibu nao — teacher, youth leader ama community health volunteer — ama health facility ya karibu. Kisha hizi.")},
    {"type": "table",
     "headers": [("Service", "Huduma", "Service"), ("Number", "Nambari", "Number")],
     "rows": [
      [("NACADA — free counselling and referral for drug dependence, countrywide",
        "NACADA — ushauri na rufaa bila malipo kwa utegemezi wa dawa, nchi nzima",
        "NACADA — free counselling na referral kwa drug dependence, nchi nzima"),
       ("<strong>1192</strong>", "<strong>1192</strong>", "<strong>1192</strong>")],
      [("Befrienders Kenya — 24/7 emotional support",
        "Befrienders Kenya — msaada wa kihisia saa 24",
        "Befrienders Kenya — 24/7 emotional support"),
       ("<strong>0722 178 177</strong>", "<strong>0722 178 177</strong>", "<strong>0722 178 177</strong>")],
      [("Chiromo Hospital Group — 24/7 crisis line",
        "Chiromo Hospital Group — simu ya dharura saa 24",
        "Chiromo Hospital Group — 24/7 crisis line"),
       ("<strong>0722 529 714</strong>", "<strong>0722 529 714</strong>", "<strong>0722 529 714</strong>")],
      [("Kenya Red Cross — toll free",
        "Msalaba Mwekundu Kenya — bila malipo",
        "Kenya Red Cross — toll free"),
       ("<strong>1199</strong>", "<strong>1199</strong>", "<strong>1199</strong>")],
      [("National emergency lines",
        "Simu za dharura za kitaifa",
        "National emergency lines"),
       ("<strong>719</strong> · <strong>0729 471 414</strong> · <strong>0732 353 535</strong>",
        "<strong>719</strong> · <strong>0729 471 414</strong> · <strong>0732 353 535</strong>",
        "<strong>719</strong> · <strong>0729 471 414</strong> · <strong>0732 353 535</strong>")],
     ]},
    {"type": "tip", "title": ("💡 Make it a referral, not a number", "💡 Ifanye rufaa, si nambari", "💡 Ifanye referral, si number"), "text": (
     " Module 16 applies here exactly as written: issue and record the referral, follow up until the service is received, re-refer if it did not land. Handing over 1192 and walking away is not a referral.",
     " Moduli 16 inatumika hapa kama ilivyoandikwa: toa na rekodi rufaa, fuatilia hadi huduma ipokewe, toa rufaa tena kama haikufika. Kutoa 1192 na kuondoka si rufaa.",
     " Module 16 inatumika hapa exactly kama ilivyoandikwa: issue na record referral, follow up mpaka service i-receiviwe, re-refer kama haiku-land. Kutoa 1192 na kuondoka si referral.")},
   ]},

  # ── 8. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "Over two months a friend's grades have dropped, he has new friends he will not discuss, he has stopped playing football, and his brother's phone went missing.",
      "Kwa miezi miwili alama za rafiki zimeshuka, ana marafiki wapya asiotaka kuwajadili, ameacha kucheza mpira, na simu ya kaka yake ilipotea.",
      "Kwa miezi miwili grades za friend zimeshuka, ana friends wapya asiotaka ku-discuss, ameacha kucheza mpira, na phone ya bro wake ilipotea."),
     "question": ("What is the right move?", "Hatua sahihi ni ipi?", "Move sahihi ni ipi?"),
     "choices": [
      {"kind": "bad",
       "text": ("Confront him with the pattern and ask him directly if he is using",
                "Mkabili na mchoro huo na umuulize moja kwa moja kama anatumia",
                "M-confront na hiyo pattern na umuulize directly kama anatumia"),
       "outcome": ("A direct accusation, backed by a list, produces denial almost every time — and now he knows he is being watched. Secretiveness and sharp sensitivity to questions are on the sign list precisely because confrontation triggers them.",
                   "Shtaka la moja kwa moja, likiungwa mkono na orodha, hutoa kukana karibu kila mara — na sasa anajua anachunguzwa. Usiri na kuathirika sana na maswali viko kwenye orodha ya dalili hasa kwa sababu makabiliano huviamsha.",
                   "Direct accusation, ikiwa-backed na list, inatoa denial karibu kila time — na saa hii anajua ana-watchiwa. Secretiveness na sharp sensitivity kwa questions ziko kwa sign list hasa kwa sababu confrontation inazi-trigger.")},
      {"kind": "good",
       "text": ("Say what you have noticed about him, not about drugs, and stay available",
                "Sema uliyoyaona kumhusu, si kuhusu dawa, na ubaki upo",
                "Sema uliyoyaona kumhusu, si kuhusu drugs, na ubaki available"),
       "outcome": ("You said: 'I'm not asking what you're doing. I've just noticed you stopped playing, and you don't seem like you. If something's going on I'm around — and I'm not going to lecture you.' He said nothing that day. He came back three weeks later. ✅",
                   "Ulisema: 'Sikuulizi unafanya nini. Nimeona tu umeacha kucheza, na huonekani kama wewe. Kama kuna kitu kinaendelea nipo — na sitakuhubiria.' Hakusema chochote siku ile. Alirudi wiki tatu baadaye. ✅",
                   "Ulisema: 'Sikuulizi unafanya nini. Nimeona tu umeacha kucheza, na huonekani kama wewe. Kama kuna kitu kinaendelea niko — na sitakulecture.' Hakusema kitu siku ile. Alirudi wiki tatu baadaye. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "In Meru, a peer says chewing miraa is part of their culture and that telling young people to stop is an attack on their community.",
      "Meru, rika anasema kutafuna miraa ni sehemu ya utamaduni wao na kwamba kuwaambia vijana waache ni shambulio dhidi ya jamii yao.",
      "Meru, msee anasema kutafuna miraa ni part ya culture yao na ati kuwaambia vijana waache ni attack dhidi ya community yao."),
     "question": ("How do you handle this well?", "Unashughulikia hili vizuri vipi?", "Una-handle hii vizuri aje?"),
     "choices": [
      {"kind": "bad",
       "text": ("Explain that culture is not a good reason to do something harmful",
                "Eleza kwamba utamaduni si sababu nzuri ya kufanya jambo lenye madhara",
                "Explain ati culture si reason nzuri ya kufanya kitu chenye madhara"),
       "outcome": ("True, and useless. He did not ask whether culture justifies harm — he heard an outsider criticising his community, which is what he expected. The curriculum specifically requires prevention to be culturally sensitive, and this is why.",
                   "Ni kweli, na haina msaada. Hakuuliza kama utamaduni unahalalisha madhara — alisikia mgeni akikosoa jamii yake, ambayo ndiyo aliyotarajia. Mtaala unahitaji hasa kuzuia kuwe na uangalifu wa kiutamaduni, na ndiyo maana.",
                   "Ni kweli, na haina msaada. Hakuuliza kama culture inahalalisha harm — alisikia outsider aki-criticise community yake, ambayo ndio alitarajia. Curriculum inahitaji hasa prevention iwe culturally sensitive, na ndio maana.")},
      {"kind": "good",
       "text": ("Accept the culture as real, and separate the crop and the trade from what daily chewing does to a body",
                "Kubali utamaduni kama halisi, na tenganisha zao na biashara na kile kutafuna kila siku kunafanya kwa mwili",
                "Accept culture kama real, na separate crop na biashara na kile kutafuna kila siku kunafanya kwa mwili"),
       "outcome": ("You said: 'Miraa built this county — I'm not arguing with that. What I'm asking is different: what does chewing every day do to you, specifically? You can honour where you're from and still look after your body. Traditions change all the time; that's how they survive.' He stayed in the conversation. ✅",
                   "Ulisema: 'Miraa imejenga kaunti hii — sibishani na hilo. Ninachouliza ni tofauti: kutafuna kila siku kunakufanyia nini, hasa? Unaweza kuheshimu unakotoka na bado ukalinda mwili wako. Mila hubadilika kila wakati; ndivyo zinavyoendelea kuishi.' Alibaki kwenye mazungumzo. ✅",
                   "Ulisema: 'Miraa imejenga hii county — sibishani na hiyo. Ninachouliza ni tofauti: kutafuna kila siku kunakufanyia nini, specifically? Unaweza ku-honour unakotoka na bado u-look after mwili wako. Traditions zina-change kila time; ndio jinsi zinavyo-survive.' Alibaki kwa conversation. ✅")},
     ]},
   ]},

  # ── 9. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("No single sign proves anything — look for a cluster, and for change from how someone was.",
      "Hakuna dalili moja inayothibitisha chochote — tafuta mkusanyiko, na mabadiliko kutoka alivyokuwa mtu.",
      "Hakuna sign moja inayothibitisha kitu — tafuta cluster, na change kutoka alivyokuwa msee."),
     ("Never accuse. Say what you have noticed about the person, and stay available.",
      "Usishtaki kamwe. Sema uliyoyaona kuhusu mtu, na ubaki upo.",
      "Usi-accuse kamwe. Sema uliyoyaona kuhusu msee, na ubaki available."),
     ("Miraa and shisha are what you will actually meet in much of Kenya — know the facts on both.",
      "Miraa na shisha ndivyo utakavyokutana navyo hasa katika sehemu kubwa ya Kenya — jua ukweli wa vyote.",
      "Miraa na shisha ndio utakutana nazo hasa kwa sehemu kubwa ya Kenya — jua facts za zote."),
     ("Dependence is a health condition, not a moral failure. Judgement reduces uptake of help.",
      "Utegemezi ni hali ya kiafya, si kushindwa kimaadili. Kuhukumu hupunguza matumizi ya msaada.",
      "Dependence ni health condition, si moral failure. Judgement inapunguza uptake ya msaada."),
     ("NACADA 1192 is free, countrywide — but hand it over as a recorded referral, not a phone number.",
      "NACADA 1192 ni bure, nchi nzima — lakini itoe kama rufaa iliyoandikwa, si nambari ya simu.",
      "NACADA 1192 ni free, nchi nzima — lakini itoe kama recorded referral, si number ya simu."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Hakuna anayeacha kwa sababu ameaibishwa. Watu huacha wanapokuwa na sababu ya kuacha na mtu wa kutembea naye. Wewe ni yule mtu.",
     "Hakuna anayeacha kwa sababu ameaibishwa. Watu huacha wanapokuwa na sababu ya kuacha na mtu wa kutembea naye. Wewe ni yule mtu.",
     "Hakuna msee anayeacha kwa sababu ame-shamewa. Wasee wanaacha wakiwa na reason ya kuacha na msee wa kutembea naye. Wewe ni huyo msee.")},
   ]},
 ],

 "quiz": [
  {"q": "A friend shows one of the warning signs. What does that prove?",
   "options": ["That they are using",
               "Nothing on its own — it is the cluster of signs and the change from before that matter",
               "That you should tell their parents",
               "That they are at stage 4"],
   "answer": "B",
   "explain": "Mood swings, new friends and dropping grades are also just being fifteen. Look for several together, in someone who was not like that before."},

  {"q": "What is the active chemical that makes fresh miraa preferred?",
   "options": ["Nicotine", "Cathinone", "Caffeine", "THC"],
   "answer": "B",
   "explain": "Cathinone is the more potent of miraa's two psychoactive chemicals and degrades rapidly after harvest — hence the preference for chewing within 48 hours."},

  {"q": "How does the WHO classify khat?",
   "options": ["A harmless traditional stimulant",
               "A drug of abuse that can produce mild-to-moderate psychological dependence",
               "A controlled narcotic equivalent to heroin",
               "A herbal medicine"],
   "answer": "B",
   "explain": "It does not cause heroin-like physical withdrawal, but users report being unable to work, socialise or feel normal without it."},

  {"q": "What is the biggest myth about shisha?",
   "options": ["That it is popular",
               "That the water filters out the harmful chemicals",
               "That it comes from the Middle East",
               "That it is expensive"],
   "answer": "B",
   "explain": "The water cools the smoke so it feels smoother, but the toxins pass through unchanged."},

  {"q": "Which infections can be transmitted by sharing a shisha pipe? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Tuberculosis", "Herpes", "Hepatitis", "Malaria"],
   "answer": ["A", "B", "C"],
   "explain": "Malaria is mosquito-borne. The others transmit directly through the shared mouthpiece — and new mouthpieces do not fully prevent it."},

  {"q": "Which are protective factors against substance abuse? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Strong family bonds",
               "Parental monitoring and involvement",
               "Success in school performance",
               "Clear community norms about drug use",
               "Keeping young people unaware that drugs exist"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Concealment is not protection. The curriculum calls for interactive, skills-based training rather than avoidance."},

  {"q": "A peer in Meru says miraa is part of their culture. What is the best approach?",
   "options": ["Explain that culture does not justify harm",
               "Accept the culture as real and separate it from what daily chewing does to a body",
               "Avoid the topic entirely",
               "Report the community to authorities"],
   "answer": "B",
   "explain": "The curriculum specifically requires prevention to be culturally sensitive. 'You can honour where you're from and still look after your body.'"},

  {"q": "Why do trusting relationships matter in harm reduction?",
   "options": ["They make the work more pleasant",
               "Positive relations between providers and people who use drugs increase uptake of services; judgement reduces it",
               "They are required by law",
               "They reduce the cost of treatment"],
   "answer": "B",
   "explain": "Someone who expects to be judged does not come back — which is why dependence must be treated as a health condition, not a moral failure."},

  {"q": "Your friend shows several warning signs. What is the right first move?",
   "options": ["Confront him with the pattern and ask directly if he is using",
               "Say what you have noticed about him, not about drugs, and stay available",
               "Tell his parents immediately",
               "Wait until you are certain"],
   "answer": "B",
   "explain": "A direct accusation backed by a list produces denial almost every time — and heightened sensitivity to questioning is itself on the sign list."},

  {"q": "What is the correct way to use the NACADA helpline with a peer?",
   "options": ["Give them the number 1192 and let them decide",
               "Issue and record it as a referral, then follow up until the service is received",
               "Call on their behalf without telling them",
               "Only use it if they ask"],
   "answer": "B",
   "explain": "Module 16 applies exactly as written. Handing over a number and walking away is not a referral."},
 ],
}
