# Module 11 (part 1 of 2) — Sex, Its Consequences, and Preventing Them
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 11.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m11a-sex-and-consequences.html",
 "module_code": "M11",
 "module_slug": "sexual-reproductive-health",
 "lesson_slug": "m11a-sex-and-consequences",
 "module_label": "Peer Educator · M11 · Part 1 of 2",
 "title": "Sex, Consequences and Prevention",
 "icon": "🌺",
 "duration": 45,

 "objectives": [
  ("Explain what sexual intercourse is and its possible physical, emotional and social consequences",
   "Eleza ngono ni nini na matokeo yake ya kimwili, kihisia na kijamii",
   "Explain sexual intercourse ni nini na consequences zake za kimwili, kihisia na kijamii"),
  ("List the methods of preventing those consequences",
   "Orodhesha njia za kuzuia matokeo hayo",
   "List methods za ku-prevent hizo consequences"),
  ("Distinguish decisions made from readiness from decisions made under pressure",
   "Tofautisha maamuzi yanayotokana na utayari na yale ya shinikizo",
   "Tofautisha decisions zinazotokana na readiness na zile za pressure"),
  ("Support a peer to make an informed and responsible decision",
   "Msaidie rika kufanya uamuzi wenye taarifa na uwajibikaji",
   "Support msee kufanya informed na responsible decision"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Two people can do exactly the same thing and one walks away fine while the other carries it for years. What actually makes the difference?",
  "<strong>🔍 Swali Kubwa:</strong> Watu wawili wanaweza kufanya jambo lile lile na mmoja aondoke akiwa sawa huku mwingine akilibeba kwa miaka. Ni nini hasa kinachofanya tofauti?",
  "<strong>🔍 Big Question:</strong> Wasee wawili wanaweza kufanya kitu kile kile na mmoja aondoke akiwa poa huku mwingine aki-carry kwa miaka. Ni nini hasa kinachofanya tofauti?"),

 "slides": [

  {"icon": "📖",
   "head": ("What We Are Talking About", "Tunachozungumzia", "Tunachoongelea"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Sexual intercourse", "🔑 Ngono", "🔑 Sexual intercourse"), "text": (
     "When two people engage in physical activity that can lead to sexual pleasure, and sometimes the exchange of body fluids such as semen or vaginal fluids.",
     "Pale watu wawili wanaposhiriki shughuli ya kimwili inayoweza kuleta raha ya kingono, na wakati mwingine kubadilishana majimaji ya mwili kama shahawa au majimaji ya uke.",
     "Pale wasee wawili wanaposhiriki physical activity inayoweza kuleta sexual pleasure, na wakati mwingine ku-exchange body fluids kama semen ama vaginal fluids.")},
    {"type": "p", "text": (
     "This happens in different ways. The most common is vaginal intercourse, which can result in <strong>pregnancy</strong> or in passing on <strong>sexually transmitted infections, including HIV</strong>.",
     "Hii hutokea kwa njia tofauti. Ya kawaida zaidi ni ngono ya uke, ambayo inaweza kusababisha <strong>ujauzito</strong> au kupitisha <strong>magonjwa ya zinaa, ikiwemo VVU</strong>.",
     "Hii inahappen kwa njia tofauti. Ya kawaida zaidi ni vaginal intercourse, ambayo inaweza kusababisha <strong>pregnancy</strong> ama ku-pass <strong>STIs, ikiwemo HIV</strong>.")},
    {"type": "warn", "title": ("⚠️ Outcomes can be positive or negative", "⚠️ Matokeo yanaweza kuwa chanya au hasi", "⚠️ Outcomes zinaweza kuwa positive ama negative"), "text": (
     " The curriculum is deliberate here: sex has physical, emotional and social outcomes, and they can go either way <strong>depending on the circumstances and the choices made</strong>. A peer educator who teaches only the disasters loses credibility with anyone who has experienced otherwise — and then loses the ability to warn them about anything.",
     " Mtaala ni wa makusudi hapa: ngono ina matokeo ya kimwili, kihisia na kijamii, na yanaweza kwenda upande wowote <strong>kutegemea mazingira na maamuzi yaliyofanywa</strong>. Mwelimishaji rika anayefundisha majanga tu hupoteza uaminifu kwa yeyote aliyepitia tofauti — kisha hupoteza uwezo wa kumwonya kuhusu chochote.",
     " Curriculum ni deliberate hapa: sex ina physical, emotional na social outcomes, na zinaweza kwenda upande wowote <strong>kutegemea circumstances na choices zilizofanywa</strong>. Peer educator anayefundisha disasters tu anapoteza credibility kwa yeyote aliye-experience otherwise — kisha anapoteza uwezo wa kum-warn kuhusu chochote.")},
   ]},

  {"icon": "🩺",
   "head": ("Physical Consequences", "Matokeo ya Kimwili", "Physical Consequences"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Unintended pregnancy</strong>",
      "<strong>Mimba isiyotarajiwa</strong>",
      "<strong>Unintended pregnancy</strong>"),
     ("<strong>Sexually transmitted infections</strong> — HIV, syphilis, gonorrhoea or chlamydia, if one or both partners has an infection",
      "<strong>Magonjwa ya zinaa</strong> — VVU, kaswende, kisonono au klamidia, kama mmoja au wote wana maambukizi",
      "<strong>STIs</strong> — HIV, syphilis, gonorrhea ama chlamydia, kama mmoja ama wote wana infection"),
     ("<strong>Physical injury or discomfort</strong> — especially where sex is forced or unsafe",
      "<strong>Jeraha la kimwili au usumbufu</strong> — hasa pale ngono inapolazimishwa au si salama",
      "<strong>Physical injury ama discomfort</strong> — hasa pale sex inapo-forciwa ama si safe"),
    ]},
    {"type": "tip", "title": ("💡 Where the other modules connect", "💡 Moduli nyingine zinapoungana", "💡 Modules zingine zinapo-connect"), "text": (
     " Every physical consequence here has a module of its own. STIs are Module 13B. Forced sex is Module 12, and carries a 72-hour window. Pregnancy is the second half of this one. A peer who arrives with one of these does not need a lecture — they need the right module and a referral.",
     " Kila matokeo ya kimwili hapa yana moduli yake. Magonjwa ya zinaa ni Moduli 13B. Ngono ya kulazimishwa ni Moduli 12, na ina muda wa saa 72. Ujauzito ni nusu ya pili ya hii. Rika anayefika na mojawapo hahitaji hotuba — anahitaji moduli sahihi na rufaa.",
     " Kila physical consequence hapa ina module yake. STIs ni Module 13B. Forced sex ni Module 12, na ina window ya masaa 72. Pregnancy ni half ya pili ya hii. Msee anayefika na mojawapo hahitaji lecture — anahitaji module sahihi na referral.")},
   ]},

  {"icon": "💭",
   "head": ("Emotional and Social Consequences", "Matokeo ya Kihisia na Kijamii", "Emotional na Social Consequences"),
   "blocks": [
    {"type": "table",
     "headers": [("Emotional and psychological", "Kihisia na kisaikolojia", "Emotional na psychological"),
                 ("Social", "Kijamii", "Social")],
     "rows": [
      [("Feelings of closeness and trust <strong>when sex is consensual and respectful</strong>",
        "Hisia za ukaribu na kuaminiana <strong>ngono inapokuwa ya ridhaa na heshima</strong>",
        "Feelings za closeness na trust <strong>sex inapokuwa consensual na respectful</strong>"),
       ("Changes in friendships or reputation, especially where cultural or religious views are strong",
        "Mabadiliko katika urafiki au sifa, hasa pale maoni ya kitamaduni au kidini ni imara",
        "Changes kwa friendships ama reputation, hasa pale cultural ama religious views ni strong")],
      [("Regret, guilt or distress <strong>if it happens without readiness, consent or protection</strong>",
        "Majuto, hatia au dhiki <strong>ikitokea bila utayari, ridhaa au kinga</strong>",
        "Regret, guilt ama distress <strong>ikihappen bila readiness, consent ama protection</strong>"),
       ("Possible discrimination or stigma if a pregnancy or an STI becomes known",
        "Uwezekano wa ubaguzi au unyanyapaa ikiwa ujauzito au ugonjwa wa zinaa unajulikana",
        "Possible discrimination ama stigma kama pregnancy ama STI inajulikana")],
      [("Stress or anxiety about pregnancy, infection, or how the relationship changes",
        "Msongo au wasiwasi kuhusu ujauzito, maambukizi, au jinsi uhusiano unavyobadilika",
        "Stress ama anxiety kuhusu pregnancy, infection, ama jinsi relationship inavyo-change")],
     ]},
    {"type": "sheng", "text": (
     "Angalia safu ya kushoto tena. Tofauti kati ya mstari wa kwanza na wa pili si kitendo. Ni ridhaa, utayari na kinga. Hiyo ndiyo jibu la swali kubwa.",
     "Angalia safu ya kushoto tena. Tofauti kati ya mstari wa kwanza na wa pili si kitendo. Ni ridhaa, utayari na kinga. Hilo ndilo jibu la swali kubwa.",
     "Angalia column ya kushoto tena. Tofauti kati ya line ya kwanza na ya pili si kitendo. Ni consent, readiness na protection. Hiyo ndio answer ya big question.")},
   ]},

  {"icon": "🛡️",
   "head": ("Preventing the Consequences — A, B, C", "Kuzuia Matokeo — A, B, C", "Ku-prevent Consequences — A, B, C"),
   "blocks": [
    {"type": "table",
     "headers": [("", "", ""), ("What it means", "Maana yake", "Maana yake")],
     "rows": [
      [("<strong>A — Abstinence</strong>", "<strong>A — Kujizuia</strong>", "<strong>A — Abstinence</strong>"),
       ("Choosing not to have sex. <strong>The only method that removes the risk of both pregnancy and STIs entirely.</strong>",
        "Kuchagua kutofanya ngono. <strong>Njia pekee inayoondoa kabisa hatari ya ujauzito na magonjwa ya zinaa.</strong>",
        "Kuchagua kutofanya sex. <strong>Method pekee inayoondoa kabisa risk ya pregnancy na STIs.</strong>")],
      [("<strong>B — Be faithful</strong>", "<strong>B — Kuwa mwaminifu</strong>", "<strong>B — Be faithful</strong>"),
       ("Having sex only with one partner who is also faithful to you. This reduces the risk of STIs.",
        "Kufanya ngono na mwenzi mmoja tu ambaye pia ni mwaminifu kwako. Hii hupunguza hatari ya magonjwa ya zinaa.",
        "Kufanya sex na partner mmoja tu ambaye pia ni faithful kwako. Hii inapunguza risk ya STIs.")],
      [("<strong>C — Contraceptives</strong>", "<strong>C — Uzazi wa mpango</strong>", "<strong>C — Contraceptives</strong>"),
       ("For those over 18: condoms or other approved methods, to prevent pregnancy and reduce STI risk if sexually active. The curriculum places this as the last option.",
        "Kwa walio zaidi ya miaka 18: kondomu au njia nyingine zilizoidhinishwa, kuzuia ujauzito na kupunguza hatari ya magonjwa ya zinaa kama unafanya ngono. Mtaala unaiweka hii kama chaguo la mwisho.",
        "Kwa walio zaidi ya 18: condoms ama methods zingine approved, ku-prevent pregnancy na kupunguza STI risk kama unafanya sex. Curriculum inai-weka hii kama last option.")],
     ]},
    {"type": "warn", "title": ("⚠️ Teach all three, in order, without editing", "⚠️ Fundisha zote tatu, kwa mpangilio, bila kuhariri", "⚠️ Fundisha zote tatu, kwa order, bila ku-edit"), "text": (
     " Some peer educators teach only A because it feels safest to say. But a young person who is already sexually active and hears only 'don't' concludes the whole session has nothing for them, and stops listening — including to the parts that would have protected them. Give the full sequence and let them locate themselves in it.",
     " Baadhi ya waelimishaji rika hufundisha A peke yake kwa sababu inaonekana salama zaidi kusema. Lakini kijana ambaye tayari anafanya ngono na anasikia 'usifanye' tu huhitimisha kipindi kizima hakina lolote kwake, na huacha kusikiliza — ikiwemo sehemu zingelizomlinda. Toa mfululizo mzima na uwaache wajipate ndani yake.",
     " Baadhi ya peer educators wanafundisha A peke yake kwa sababu inaonekana safest kusema. Lakini kijana ambaye tayari anafanya sex na anasikia 'usifanye' tu ana-conclude session nzima haina kitu kwake, na ana-stop kusikiliza — ikiwemo parts ambazo zingemlinda. Toa full sequence na uwache waji-locate ndani yake.")},
   ]},

  {"icon": "🧭",
   "head": ("Deciding, Rather Than Drifting", "Kuamua, Badala ya Kuyumba", "Ku-decide, Badala ya Ku-drift"),
   "blocks": [
    {"type": "p", "text": (
     "Most young people who regret a sexual decision did not decide anything — the situation decided for them. These four steps, from Module 13A, are how a decision gets made rather than arrived at.",
     "Vijana wengi wanaojutia uamuzi wa kingono hawakuamua chochote — hali iliwaamulia. Hatua hizi nne, kutoka Moduli 13A, ndizo jinsi uamuzi unavyofanywa badala ya kufikiwa.",
     "Vijana wengi wanao-regret sexual decision hawaku-decide kitu — situation iliwa-decide. Hizi steps nne, kutoka Module 13A, ndio jinsi decision inavyofanywa badala ya ku-arriviwa.")},
    {"type": "list", "ordered": True, "items": [
     ("<strong>Stop and think</strong> — what could actually happen here?",
      "<strong>Simama na ufikiri</strong> — ni nini kinaweza kutokea hapa hasa?",
      "<strong>Stop na ufikiri</strong> — ni nini kinaweza ku-happen hapa hasa?"),
     ("<strong>Get the facts</strong> — know the risks and the prevention",
      "<strong>Pata ukweli</strong> — jua hatari na kinga",
      "<strong>Pata facts</strong> — jua risks na prevention"),
     ("<strong>Check your values</strong> — does this align with what is right for you?",
      "<strong>Angalia maadili yako</strong> — je, hii inaendana na kilicho sahihi kwako?",
      "<strong>Check values zako</strong> — je, hii ina-align na kilicho sahihi kwako?"),
     ("<strong>Choose safety</strong> — protect your health now and in the future",
      "<strong>Chagua usalama</strong> — linda afya yako sasa na baadaye",
      "<strong>Chagua safety</strong> — linda health yako saa hii na baadaye"),
    ]},
    {"type": "facilitator", "minutes": 12, "text": (
     "Do not run this as a debate about whether young people should have sex — that argument has no winner and costs you the room. Run it as a decision-quality exercise: take a scenario the group supplies, and walk the four steps aloud. The skill transfers to every other decision in the curriculum.",
     "Usiiendeshe kama mjadala wa kama vijana wanapaswa kufanya ngono — hoja hiyo haina mshindi na inakugharimu chumba. Iendeshe kama zoezi la ubora wa uamuzi: chukua hali ambayo kundi limetoa, na upitie hatua nne kwa sauti. Ujuzi huo huhamia kwenye kila uamuzi mwingine katika mtaala.",
     "Usii-run kama debate ya kama vijana wanafaa kufanya sex — hiyo argument haina winner na inakugharimu room. I-run kama decision-quality exercise: chukua scenario ambayo group ime-supply, na u-walk steps nne kwa sauti. Hiyo skill ina-transfer kwa kila decision nyingine kwa curriculum.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A 17-year-old tells you she is already sexually active. She says the abstinence talk made her feel the session was not for her.",
      "Msichana wa miaka 17 anakuambia tayari anafanya ngono. Anasema mazungumzo ya kujizuia yalimfanya ahisi kipindi hakikuwa chake.",
      "Dem wa miaka 17 anakuambia tayari anafanya sex. Anasema abstinence talk ilimfanya afeel session haikuwa yake."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Encourage her to stop and start again with abstinence",
                "Mhimize aache na aanze upya na kujizuia",
                "M-encourage aache na aanze upya na abstinence"),
       "outcome": ("Whatever the merits, she has just been told again that the session is not about her situation. She is now less likely to come back for testing, contraception or a referral — and those are exactly what her actual risk requires.",
                   "Hata iweje, ameambiwa tena kwamba kipindi si kuhusu hali yake. Sasa ana uwezekano mdogo wa kurudi kwa kupimwa, uzazi wa mpango au rufaa — na hivyo ndivyo hasa hatari yake halisi inavyohitaji.",
                   "Whatever merits, ameambiwa tena ati session si kuhusu situation yake. Saa hii ana uwezekano mdogo wa kurudi kwa testing, contraception ama referral — na hizo ndio hasa real risk yake inavyohitaji.")},
      {"kind": "good",
       "text": ("Tell her the whole sequence exists precisely because people are in different places, and move to what protects her now",
                "Mwambie mfululizo mzima upo hasa kwa sababu watu wako sehemu tofauti, na uhamie kwa kinachomlinda sasa",
                "Mwambie sequence nzima iko hasa kwa sababu wasee wako places tofauti, na u-move kwa kinachom-protect saa hii"),
       "outcome": ("You said: 'A, B and C exist because people are in different places — you're at C, and that part is as much the lesson as the first part. Let's talk about testing, protection, and where you can go without being judged.' She asked three questions she had been carrying for months. ✅",
                   "Ulisema: 'A, B na C zipo kwa sababu watu wako sehemu tofauti — wewe uko C, na sehemu hiyo ni somo kama sehemu ya kwanza. Tuzungumze kuhusu kupimwa, kinga, na wapi unaweza kwenda bila kuhukumiwa.' Aliuliza maswali matatu aliyokuwa akiyabeba kwa miezi. ✅",
                   "Ulisema: 'A, B na C ziko kwa sababu wasee wako places tofauti — wewe uko C, na hiyo part ni lesson kama part ya kwanza. Tuongee kuhusu testing, protection, na wapi unaweza kuenda bila ku-judgiwa.' Aliuliza questions tatu alizokuwa aki-carry kwa miezi. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A boy says he does not need to think about any of this because 'it just happens in the moment — you can't plan it'.",
      "Mvulana anasema hahitaji kufikiria lolote kati ya haya kwa sababu 'hutokea tu wakati huo — huwezi kupanga'.",
      "Mse anasema hahitaji kufikiria kitu kati ya haya kwa sababu 'inahappen tu wakati huo — huwezi ku-plan'."),
     "question": ("How do you answer?", "Unajibu vipi?", "Una-answer aje?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell him that is irresponsible and he needs to grow up",
                "Mwambie hilo si la uwajibikaji na anahitaji kukomaa",
                "Mwambie hiyo si responsible na anahitaji kukua"),
       "outcome": ("He described how it actually feels, and was told off for describing it. The honest observation underneath — that decisions in the moment are hard — is correct, and it is the thing the four steps exist to solve. Dismissing it wastes the opening.",
                   "Alieleza jinsi inavyohisiwa hasa, na akakaripiwa kwa kuieleza. Uchunguzi wa kweli chini yake — kwamba maamuzi ya papo hapo ni magumu — ni sahihi, na ndicho hatua nne zilizopo kukitatua. Kuupuuza kunapoteza mwanya.",
                   "Ali-describe jinsi inavyofeeliwa hasa, na aka-karipiwa kwa kui-describe. Honest observation chini yake — ati decisions za wakati huo ni ngumu — ni sahihi, na ndio steps nne ziko ku-solve. Ku-dismiss kunapoteza opening.")},
      {"kind": "good",
       "text": ("Agree that in-the-moment decisions are hard — which is exactly why the decision is made beforehand",
                "Kubali kwamba maamuzi ya papo hapo ni magumu — ndiyo maana uamuzi hufanywa mapema",
                "Agree ati in-the-moment decisions ni ngumu — ndio maana decision inafanywa beforehand"),
       "outcome": ("You said: 'You're right that nobody thinks clearly in the moment. That's the whole point — you decide before you're in the room, not during. Same as refusal skills: you rehearse the line so you don't have to invent it under pressure.' He accepted that immediately. ✅",
                   "Ulisema: 'Uko sahihi kwamba hakuna anayefikiri wazi wakati huo. Hilo ndilo lengo lote — unaamua kabla hujawa chumbani, si wakati huo. Sawa na ujuzi wa kukataa: unafanya mazoezi ya sentensi ili usilazimike kuibuni chini ya shinikizo.' Alikubali mara moja. ✅",
                   "Ulisema: 'Uko sahihi ati hakuna msee anafikiri clearly wakati huo. Hiyo ndio point yote — una-decide kabla uwe kwa room, si wakati huo. Sawa na refusal skills: una-rehearse line ili usilazimike kui-invent chini ya pressure.' Ali-accept mara moja. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Sex has physical, emotional and social outcomes, and they depend on the circumstances and the choices made.",
      "Ngono ina matokeo ya kimwili, kihisia na kijamii, na yanategemea mazingira na maamuzi yaliyofanywa.",
      "Sex ina physical, emotional na social outcomes, na zinategemea circumstances na choices zilizofanywa."),
     ("Abstinence is the only method that removes the risk of both pregnancy and STIs entirely.",
      "Kujizuia ndiyo njia pekee inayoondoa kabisa hatari ya ujauzito na magonjwa ya zinaa.",
      "Abstinence ndio method pekee inayoondoa kabisa risk ya pregnancy na STIs."),
     ("Teach A, B and C in full — a young person who hears only 'don't' stops listening to everything else.",
      "Fundisha A, B na C kikamilifu — kijana anayesikia 'usifanye' tu huacha kusikiliza kila kitu kingine.",
      "Fundisha A, B na C fully — kijana anayesikia 'usifanye' tu ana-stop kusikiliza kila kitu kingine."),
     ("Decide before you are in the room. Nobody thinks clearly in the moment.",
      "Amua kabla hujawa chumbani. Hakuna anayefikiri wazi wakati huo.",
      "Decide kabla uwe kwa room. Hakuna msee anafikiri clearly wakati huo."),
    ]},
    {"type": "p", "text": (
     "Part 2 covers contraception, teenage pregnancy and unsafe abortion.",
     "Sehemu ya 2 inahusu uzazi wa mpango, mimba za utotoni na utoaji mimba usio salama.",
     "Part 2 inacover contraception, teenage pregnancy na unsafe abortion.")},
   ]},
 ],

 "quiz": [
  {"q": "According to the curriculum, sexual outcomes are:",
   "options": ["Always negative for adolescents",
               "Physical, emotional and social — and can be positive or negative depending on circumstances and choices",
               "Only physical",
               "Unpredictable and impossible to influence"],
   "answer": "B",
   "explain": "A peer educator who teaches only the disasters loses credibility with anyone who has experienced otherwise."},

  {"q": "Which physical consequences are listed? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Unintended pregnancy", "STIs including HIV, syphilis, gonorrhoea and chlamydia",
               "Physical injury, especially where sex is forced or unsafe", "Permanent infertility in all cases"],
   "answer": ["A", "B", "C"],
   "explain": "Some STIs can affect fertility if untreated, but that is not an automatic consequence of sex."},

  {"q": "What distinguishes closeness and trust from regret and guilt as emotional outcomes?",
   "options": ["The age of the people involved",
               "Whether it was consensual and respectful, versus without readiness, consent or protection",
               "Whether anyone found out",
               "Nothing — it is random"],
   "answer": "B",
   "explain": "That is the answer to the module's Big Question: the difference is not the act, it is consent, readiness and protection."},

  {"q": "What does the B in A-B-C stand for?",
   "options": ["Barrier methods", "Be faithful — one partner who is also faithful to you",
               "Birth control", "Be careful"],
   "answer": "B",
   "explain": "A is abstinence, B is being faithful, C is contraceptives — which the curriculum places as the last option, for those over 18."},

  {"q": "Why should a peer educator teach the whole A-B-C sequence rather than only abstinence?",
   "options": ["Because abstinence does not work",
               "Because a young person who is already sexually active and hears only 'don't' stops listening to everything else",
               "Because the curriculum is optional",
               "Because contraception is more effective"],
   "answer": "B",
   "explain": "They then miss the parts that would have protected them — and do not come back for testing or referral."},

  {"q": "What are the four decision-making steps?",
   "options": ["Ask, decide, act, review",
               "Stop and think; get the facts; check your values; choose safety",
               "Plan, prepare, protect, proceed",
               "Talk, test, treat, trace"],
   "answer": "B",
   "explain": "Most young people who regret a sexual decision did not decide anything — the situation decided for them."},

  {"q": "A peer says 'it just happens in the moment, you can't plan it'. What is the best response?",
   "options": ["Tell him that is irresponsible",
               "Agree that nobody thinks clearly in the moment — which is exactly why the decision is made beforehand",
               "Tell him he is right and move on",
               "Change the subject"],
   "answer": "B",
   "explain": "His observation is honest and correct. It is also the precise reason the four steps exist — same principle as rehearsing refusal skills."},

  {"q": "A 17-year-old says the abstinence talk made her feel the session was not for her. What should you do?",
   "options": ["Encourage her to stop and restart with abstinence",
               "Explain that A, B and C exist because people are in different places, and move to what protects her now",
               "Agree the session was not for her",
               "Report her to a teacher"],
   "answer": "B",
   "explain": "Her actual risk requires testing, protection and a referral — and she will only return for those if the session includes her."},

  {"q": "Which social consequence does the curriculum name?",
   "options": ["Improved popularity",
               "Possible discrimination or stigma if a pregnancy or STI becomes known",
               "Automatic exclusion from school",
               "Legal prosecution"],
   "answer": "B",
   "explain": "Alongside changes in friendships or reputation, especially where cultural or religious views are strong."},

  {"q": "Which method removes the risk of both pregnancy and STIs entirely?",
   "options": ["Condoms", "Abstinence", "The pill", "Being faithful"],
   "answer": "B",
   "explain": "Condoms give dual protection but not absolute protection; faithfulness reduces STI risk but not pregnancy risk."},
 ],
}
