# Module 11 (part 2 of 2) — Contraception, Teenage Pregnancy and Unsafe Abortion
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 11.
# Trilingual: English / Kiswahili / Sheng.
#
# SCOPE NOTE: contraceptive methods are named and described; choosing one is a
# clinical decision made at a facility. Same boundary as PrEP in M13B.

LESSON = {
 "file": "m11b-contraception-and-pregnancy.html",
 "module_code": "M11",
 "module_slug": "sexual-reproductive-health",
 "lesson_slug": "m11b-contraception-and-pregnancy",
 "module_label": "Peer Educator · M11 · Part 2 of 2",
 "title": "Contraception and Teenage Pregnancy",
 "icon": "🌺",
 "duration": 45,

 "objectives": [
  ("Describe what contraception is, who it is for, and its different types",
   "Eleza uzazi wa mpango ni nini, ni kwa nani, na aina zake tofauti",
   "Describe contraception ni nini, ni kwa nani, na types zake tofauti"),
  ("Explain the benefits of contraception and the barriers to using it",
   "Eleza faida za uzazi wa mpango na vizuizi vya kuutumia",
   "Explain benefits za contraception na barriers za kuitumia"),
  ("Discuss teenage pregnancy, its causes, signs and consequences",
   "Jadili mimba za utotoni, sababu zake, dalili na matokeo",
   "Discuss teenage pregnancy, causes zake, signs na consequences"),
  ("Explain why unsafe abortion happens and what drives it",
   "Eleza kwa nini utoaji mimba usio salama hutokea na nini kinachouchochea",
   "Explain kwa nini unsafe abortion inahappen na nini kinachoi-drive"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Contraception is legal, effective and available in Kenya. So why do so many young people still arrive pregnant?",
  "<strong>🔍 Swali Kubwa:</strong> Uzazi wa mpango ni halali, wenye ufanisi na unapatikana Kenya. Basi kwa nini vijana wengi bado wanafika wakiwa na mimba?",
  "<strong>🔍 Big Question:</strong> Contraception ni legal, effective na inapatikana Kenya. So kwa nini vijana wengi bado wanafika wakiwa na mimba?"),

 "slides": [

  {"icon": "📖",
   "head": ("What Contraception Is", "Uzazi wa Mpango ni Nini", "Contraception ni Nini"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Contraception", "🔑 Uzazi wa mpango", "🔑 Contraception"), "text": (
     "Using a method, pill or device to prevent pregnancy if you are sexually active.",
     "Kutumia njia, kidonge au kifaa kuzuia ujauzito ikiwa unafanya ngono.",
     "Kutumia method, pill ama device ku-prevent pregnancy kama unafanya sex.")},
    {"type": "table",
     "headers": [("Type", "Aina", "Type"), ("How it works", "Inavyofanya kazi", "Inavyowork")],
     "rows": [
      [("<strong>Barrier methods</strong>", "<strong>Njia za kizuizi</strong>", "<strong>Barrier methods</strong>"),
       ("Condoms. Prevent pregnancy <strong>and</strong> protect against STIs including HIV — dual protection, as in Module 13B.",
        "Kondomu. Huzuia ujauzito <strong>na</strong> hulinda dhidi ya magonjwa ya zinaa ikiwemo VVU — ulinzi maradufu, kama Moduli 13B.",
        "Condoms. Zinazuia pregnancy <strong>na</strong> zinalinda dhidi ya STIs ikiwemo HIV — dual protection, kama Module 13B.")],
      [("<strong>Hormonal methods</strong>", "<strong>Njia za homoni</strong>", "<strong>Hormonal methods</strong>"),
       ("Pills, injections, implants and IUDs. They work by stopping the release of eggs, or preventing a fertilised egg from growing in the womb. <strong>No protection against STIs.</strong>",
        "Vidonge, sindano, vipandikizi na IUD. Hufanya kazi kwa kuzuia kutolewa kwa mayai, au kuzuia yai lililorutubishwa kukua tumboni. <strong>Hakuna kinga dhidi ya magonjwa ya zinaa.</strong>",
        "Pills, injections, implants na IUDs. Zinawork kwa ku-stop release ya mayai, ama kuzuia fertilised egg kukua kwa womb. <strong>Hakuna protection dhidi ya STIs.</strong>")],
      [("<strong>Permanent methods</strong>", "<strong>Njia za kudumu</strong>", "<strong>Permanent methods</strong>"),
       ("Vasectomy and bilateral tubal ligation (BTL). Intended to be irreversible — not for adolescents.",
        "Vasektomi na kufunga mirija (BTL). Zimekusudiwa kutorudishwa — si kwa vijana.",
        "Vasectomy na bilateral tubal ligation (BTL). Zime-intendiwa kuwa irreversible — si kwa vijana.")],
      [("<strong>Natural methods</strong>", "<strong>Njia za asili</strong>", "<strong>Natural methods</strong>"),
       ("Avoiding sex during fertile days. Requires accurate cycle tracking, and is the least reliable for adolescents whose cycles are often irregular.",
        "Kuepuka ngono siku za rutuba. Inahitaji kufuatilia mzunguko kwa usahihi, na ndiyo isiyoaminika zaidi kwa vijana ambao mizunguko yao mara nyingi si ya kawaida.",
        "Ku-avoid sex siku za fertile. Inahitaji accurate cycle tracking, na ndio least reliable kwa vijana ambao cycles zao mara nyingi si regular.")],
     ]},
    {"type": "warn", "title": ("⚠️ Only one of these protects against infection", "⚠️ Moja tu kati ya hizi hulinda dhidi ya maambukizi", "⚠️ Moja tu kati ya hizi inalinda dhidi ya infection"), "text": (
     " A young person on an implant is protected from pregnancy and completely unprotected from HIV. This is one of the most consequential misunderstandings in the whole curriculum — say it explicitly every time contraception comes up.",
     " Kijana aliye na kipandikizi amelindwa dhidi ya ujauzito na hajalindwa kabisa dhidi ya VVU. Huu ni mmoja wa mkanganyiko wenye athari kubwa zaidi katika mtaala mzima — useme wazi kila mara uzazi wa mpango unapotajwa.",
     " Kijana aliye na implant ame-protectiwa dhidi ya pregnancy na hajalindwa kabisa dhidi ya HIV. Huu ni mmoja wa misunderstandings zenye consequence kubwa zaidi kwa curriculum nzima — sema wazi kila time contraception inatajwa.")},
    {"type": "p", "text": (
     "Choosing the right method depends on health, comfort and personal preference — <strong>and that choice is made at a health facility, not by a peer educator.</strong> Your job is to name that options exist and get someone through the door.",
     "Kuchagua njia sahihi kunategemea afya, faraja na mapendeleo binafsi — <strong>na uchaguzi huo hufanywa kituoni cha afya, si na mwelimishaji rika.</strong> Kazi yako ni kutaja kwamba chaguo zipo na kumfikisha mtu mlangoni.",
     "Ku-choose method sahihi kunategemea health, comfort na personal preference — <strong>na hiyo choice inafanywa kwa health facility, si na peer educator.</strong> Job yako ni ku-name ati options ziko na kumfikisha msee mlangoni.")},
   ]},

  {"icon": "✅",
   "head": ("Why It Matters", "Kwa Nini Ni Muhimu", "Kwa Nini Ni Muhimu"),
   "blocks": [
    {"type": "list", "items": [
     ("Prevents unintended pregnancies",
      "Huzuia mimba zisizotarajiwa",
      "Ina-prevent unintended pregnancies"),
     ("<strong>Reduces the risk of unsafe abortion</strong> — which is the deadliest consequence in this module",
      "<strong>Hupunguza hatari ya utoaji mimba usio salama</strong> — matokeo hatari zaidi katika moduli hii",
      "<strong>Inapunguza risk ya unsafe abortion</strong> — consequence hatari zaidi kwa hii module"),
     ("Promotes reproductive health by enabling informed choices about if and when to have children",
      "Hukuza afya ya uzazi kwa kuwezesha maamuzi yenye taarifa kuhusu kama na lini kupata watoto",
      "Ina-promote reproductive health kwa ku-enable informed choices kuhusu kama na lini kupata watoto"),
     ("Supports physical and mental wellbeing by reducing the stress and anxiety of unintended pregnancy",
      "Huunga mkono ustawi wa kimwili na kiakili kwa kupunguza msongo na wasiwasi wa mimba isiyotarajiwa",
      "Ina-support physical na mental wellbeing kwa kupunguza stress na anxiety ya unintended pregnancy"),
     ("Empowers young people to take control of their own reproductive lives",
      "Huwawezesha vijana kudhibiti maisha yao ya uzazi",
      "Ina-empower vijana ku-take control ya reproductive lives zao"),
     ("Can protect against certain STIs — <strong>but only when barrier methods are used</strong>",
      "Inaweza kulinda dhidi ya magonjwa fulani ya zinaa — <strong>lakini pale tu njia za kizuizi zinapotumika</strong>",
      "Inaweza kulinda dhidi ya STIs fulani — <strong>lakini pale tu barrier methods zinapotumika</strong>"),
    ]},
   ]},

  {"icon": "🚧",
   "head": ("Why Young People Do Not Use It", "Kwa Nini Vijana Hawautumii", "Kwa Nini Vijana Hawaitumii"),
   "blocks": [
    {"type": "p", "text": (
     "This slide answers the Big Question. Every barrier below is about access, information or fear — not one is about the method failing.",
     "Slaidi hii inajibu Swali Kubwa. Kila kizuizi hapa chini kinahusu upatikanaji, taarifa au hofu — hakuna hata kimoja kinachohusu njia kushindwa.",
     "Hii slide inajibu Big Question. Kila barrier hapa chini ni kuhusu access, information ama fear — hakuna hata moja ni kuhusu method ku-fail.")},
    {"type": "list", "items": [
     ("<strong>Lack of information</strong> — not knowing what exists or where to get it",
      "<strong>Ukosefu wa taarifa</strong> — kutojua kilichopo au wapi kukipata",
      "<strong>Lack ya information</strong> — kutojua kilichopo ama wapi kukipata"),
     ("<strong>Misconceptions and myths</strong> — that it causes infertility, or is only for married women",
      "<strong>Dhana potofu na imani za uongo</strong> — kwamba husababisha ugumba, au ni kwa wanawake walioolewa tu",
      "<strong>Misconceptions na myths</strong> — ati inasababisha infertility, ama ni kwa wanawake walioolewa tu"),
     ("<strong>Fear of medical procedures</strong>",
      "<strong>Hofu ya taratibu za kimatibabu</strong>",
      "<strong>Fear ya medical procedures</strong>"),
     ("<strong>Inability to pay</strong> for services",
      "<strong>Kutoweza kulipia</strong> huduma",
      "<strong>Kutoweza ku-pay</strong> services"),
     ("<strong>Shyness</strong> about discussing reproductive health at all",
      "<strong>Aibu</strong> ya kujadili afya ya uzazi kabisa",
      "<strong>Shyness</strong> ya ku-discuss reproductive health kabisa"),
     ("<strong>Fear of being judged</strong> — by a clinician, a parent, or the community",
      "<strong>Hofu ya kuhukumiwa</strong> — na daktari, mzazi, au jamii",
      "<strong>Fear ya ku-judgiwa</strong> — na clinician, mzazi, ama community"),
     ("<strong>Cultural and religious beliefs</strong>",
      "<strong>Imani za kitamaduni na kidini</strong>",
      "<strong>Cultural na religious beliefs</strong>"),
    ]},
    {"type": "tip", "title": ("💡 Four of these seven are yours to fix", "💡 Nne kati ya saba hizi ni zako kurekebisha", "💡 Nne kati ya hizi saba ni zako ku-fix"), "text": (
     " You cannot change someone's income or their family's beliefs. But lack of information, myths, shyness and fear of judgement are exactly what a trusted peer removes — by knowing the facts, saying them without embarrassment, and going with someone to the facility. That is more than half the barrier list.",
     " Huwezi kubadilisha kipato cha mtu au imani za familia yake. Lakini ukosefu wa taarifa, imani za uongo, aibu na hofu ya kuhukumiwa ndivyo hasa rika anayeaminika huviondoa — kwa kujua ukweli, kuusema bila aibu, na kwenda na mtu kituoni. Hiyo ni zaidi ya nusu ya orodha ya vizuizi.",
     " Huwezi ku-change income ya msee ama beliefs za family yake. Lakini lack ya info, myths, shyness na fear ya judgement ndio hasa trusted peer anazi-remove — kwa kujua facts, kuzisema bila aibu, na kwenda na msee facility. Hiyo ni zaidi ya half ya barrier list.")},
   ]},

  {"icon": "🤰",
   "head": ("Teenage Pregnancy", "Mimba za Utotoni", "Teenage Pregnancy"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Teenage pregnancy", "🔑 Mimba ya utotoni", "🔑 Teenage pregnancy"), "text": (
     "Where a girl between the ages of 10 and 19 becomes pregnant.",
     "Pale msichana kati ya miaka 10 na 19 anapopata mimba.",
     "Pale dem kati ya miaka 10 na 19 anapopata mimba.")},
    {"type": "p", "text": (
     "Early signs differ from person to person and between pregnancies. They include:",
     "Dalili za mapema hutofautiana kutoka mtu hadi mtu na kati ya mimba. Ni pamoja na:",
     "Early signs zinatofautiana kutoka msee hadi msee na kati ya pregnancies. Ni pamoja na:")},
    {"type": "table",
     "headers": [("Early signs", "Dalili za mapema", "Early signs"), ("Also", "Pia", "Pia")],
     "rows": [
      [("Missed periods", "Kukosa hedhi", "Kukosa periods"), ("Feeling bloated", "Kuhisi kuvimbiwa", "Kuhisi bloated")],
      [("Tender or swollen breasts", "Matiti yenye maumivu au kuvimba", "Matiti yenye pain ama kuvimba"), ("Changes in appetite", "Mabadiliko ya hamu ya kula", "Changes za appetite")],
      [("Frequent urination", "Kukojoa mara kwa mara", "Kukojoa mara kwa mara"), ("Feeling unusually emotional", "Kuhisi hisia zisizo za kawaida", "Kuhisi emotional isivyo kawaida")],
      [("Unusual fatigue", "Uchovu usio wa kawaida", "Unusual fatigue"), ("", "", "")],
      [("Nausea and vomiting", "Kichefuchefu na kutapika", "Nausea na kutapika"), ("", "", "")],
     ]},
    {"type": "p", "text": (
     "Pregnancy is confirmed with a <strong>pregnancy test</strong> — done by a health worker, or bought from a pharmacy and done at home using mid-stream urine.",
     "Ujauzito huthibitishwa kwa <strong>kipimo cha ujauzito</strong> — kinachofanywa na mhudumu wa afya, au kununuliwa duka la dawa na kufanywa nyumbani kwa mkojo wa katikati.",
     "Pregnancy ina-confirmiwa na <strong>pregnancy test</strong> — inayofanywa na health worker, ama kununuliwa pharmacy na kufanywa nyumbani na mid-stream urine.")},
    {"type": "warn", "title": ("⚠️ What a peer educator does with a suspected pregnancy", "⚠️ Mwelimishaji rika hufanya nini na mimba inayoshukiwa", "⚠️ Peer educator anafanya nini na suspected pregnancy"), "text": (
     " Do not diagnose, do not speculate, and do not tell anyone else. Get her to a test and a health worker quickly — early confirmation opens every option and protects her health, while delay closes options one by one. Module 16 applies: record the referral and follow it up.",
     " Usitambue ugonjwa, usidhanie, na usimwambie mtu mwingine. Mfikishe kwenye kipimo na mhudumu wa afya haraka — uthibitisho wa mapema hufungua kila chaguo na kulinda afya yake, huku kuchelewa kukifunga chaguo moja baada ya nyingine. Moduli 16 inatumika: rekodi rufaa na uifuatilie.",
     " Usi-diagnose, usi-speculate, na usimwambie msee mwingine. M-fikishe kwa test na health worker haraka — early confirmation inafungua kila option na kulinda health yake, huku delay ikifunga options moja baada ya nyingine. Module 16 inatumika: record referral na ui-follow up.")},
   ]},

  {"icon": "⚠️",
   "head": ("Unsafe Abortion", "Utoaji Mimba Usio Salama", "Unsafe Abortion"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Unsafe abortion", "🔑 Utoaji mimba usio salama", "🔑 Unsafe abortion"), "text": (
     "The termination of a pregnancy by someone lacking the necessary skills, or in an environment that does not meet minimum medical standards.",
     "Kukomesha ujauzito na mtu asiye na ujuzi unaohitajika, au katika mazingira yasiyofikia viwango vya chini vya kimatibabu.",
     "Ku-terminate pregnancy na msee asiye na skills zinazohitajika, ama kwa environment isiyo-meet minimum medical standards.")},
    {"type": "p", "text": (
     "The curriculum names it plainly: unsafe abortion is <strong>one of the major risks of teenage pregnancy, and a leading cause of maternal death among adolescents and youth</strong>.",
     "Mtaala unautaja wazi: utoaji mimba usio salama ni <strong>mojawapo ya hatari kubwa za mimba za utotoni, na sababu kuu ya vifo vya uzazi miongoni mwa vijana</strong>.",
     "Curriculum inai-name wazi: unsafe abortion ni <strong>mojawapo ya major risks za teenage pregnancy, na leading cause ya maternal death miongoni mwa vijana</strong>.")},
    {"type": "table",
     "headers": [("What drives it", "Kinachoichochea", "Kinachoi-drive"), ("Which is really about", "Ambayo kwa kweli inahusu", "Ambayo kwa kweli ni kuhusu")],
     "rows": [
      [("Unintended pregnancies — from lack of access to contraception, or contraceptive failure",
        "Mimba zisizotarajiwa — kutokana na kukosa uzazi wa mpango, au kushindwa kwake",
        "Unintended pregnancies — kutokana na kukosa access ya contraception, ama contraceptive failure"),
       ("The barriers on the previous slide", "Vizuizi vya slaidi iliyopita", "Barriers za slide iliyopita")],
      [("Social stigma — fear of judgement from family, community or health workers",
        "Unyanyapaa wa kijamii — hofu ya kuhukumiwa na familia, jamii au wahudumu wa afya",
        "Social stigma — fear ya judgement kutoka family, community ama health workers"),
       ("Why she did not come to anyone earlier", "Kwa nini hakuja kwa mtu mapema", "Kwa nini hakuja kwa msee mapema")],
      [("Limited reproductive health services, especially rural or marginalised",
        "Huduma chache za afya ya uzazi, hasa vijijini au maeneo yaliyotengwa",
        "Limited reproductive health services, hasa rural ama marginalised"),
       ("Distance and availability", "Umbali na upatikanaji", "Distance na availability")],
      [("Gender-based violence — pregnancies resulting from rape or coercion",
        "Ukatili wa kijinsia — mimba zinazotokana na ubakaji au kulazimishwa",
        "Gender-based violence — pregnancies zinazotokana na rape ama coercion"),
       ("Module 12, and the 72-hour window", "Moduli 12, na muda wa saa 72", "Module 12, na window ya masaa 72")],
      [("Economic barriers — inability to afford safe medical services",
        "Vizuizi vya kiuchumi — kutoweza kumudu huduma salama za kimatibabu",
        "Economic barriers — kutoweza ku-afford safe medical services")],
     ]},
    {"type": "warn", "title": ("⚠️ Stigma is the mechanism, not a side effect", "⚠️ Unyanyapaa ni mbinu, si athari ya pembeni", "⚠️ Stigma ni mechanism, si side effect"), "text": (
     " Read that middle row again. A girl reaches an unsafe provider because she was afraid of how she would be treated by a safe one. Every session where a peer educator lets shaming language pass unchallenged makes that outcome slightly more likely — which is why the tone of your sessions is itself a health intervention.",
     " Soma mstari wa kati tena. Msichana hufika kwa mtoa huduma asiye salama kwa sababu aliogopa jinsi angetendewa na aliye salama. Kila kipindi ambapo mwelimishaji rika huacha lugha ya kuaibisha ipite bila kupingwa hufanya matokeo hayo yawe na uwezekano zaidi kidogo — ndiyo maana sauti ya vipindi vyako yenyewe ni hatua ya kiafya.",
     " Soma hiyo middle row tena. Dem anafika kwa unsafe provider kwa sababu aliogopa jinsi angetendewa na safe one. Kila session ambapo peer educator anaacha shaming language ipite bila ku-challengiwa inafanya hiyo outcome iwe likely zaidi kidogo — ndio maana tone ya sessions zako yenyewe ni health intervention.")},
    {"type": "facilitator", "minutes": 10, "text": (
     "Do not stage a debate about the legality or morality of abortion — it will consume the session and help nobody in the room. Keep the focus on what the curriculum states: unsafe abortion kills adolescent girls, and every driver listed is something that could have been addressed earlier.",
     "Usiandae mjadala kuhusu uhalali au maadili ya utoaji mimba — utameza kipindi na hautamsaidia yeyote chumbani. Weka umakini kwa yale mtaala unayosema: utoaji mimba usio salama huua wasichana vijana, na kila kichocheo kilichoorodheshwa ni kitu ambacho kingeweza kushughulikiwa mapema.",
     "Usi-stage debate kuhusu legality ama morality ya abortion — ita-consume session na haitamsaidia msee kwa room. Keep focus kwa yale curriculum inasema: unsafe abortion inaua wasichana vijana, na kila driver iliyo-listiwa ni kitu ambacho kingeweza ku-addressiwa mapema.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A peer tells you she is on an implant so she does not need to worry about condoms any more.",
      "Rika anakuambia ana kipandikizi kwa hivyo hahitaji kuwa na wasiwasi kuhusu kondomu tena.",
      "Msee anakuambia ana implant so hahitaji ku-worry kuhusu condoms tena."),
     "question": ("What do you say?", "Unasema nini?", "Unasema nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Agree — the implant is one of the most effective methods there is",
                "Kubaliana — kipandikizi ni mojawapo ya njia zenye ufanisi zaidi zilizopo",
                "Agree — implant ni mojawapo ya methods effective zaidi zilizopo"),
       "outcome": ("It is highly effective — against pregnancy only. She now believes she is protected against HIV and STIs when she is completely unprotected. This is the single most consequential misunderstanding in the module, and agreeing confirmed it.",
                   "Ni yenye ufanisi mkubwa — dhidi ya ujauzito peke yake. Sasa anaamini amelindwa dhidi ya VVU na magonjwa ya zinaa ilhali hajalindwa kabisa. Huu ndio mkanganyiko wenye athari kubwa zaidi katika moduli, na kukubaliana kuliuthibitisha.",
                   "Ni highly effective — dhidi ya pregnancy peke yake. Saa hii anaamini ame-protectiwa dhidi ya HIV na STIs ilhali hajalindwa kabisa. Huu ndio misunderstanding wenye consequence kubwa zaidi kwa module, na ku-agree kuli-confirm.")},
      {"kind": "good",
       "text": ("Separate the two risks — the implant covers pregnancy, only condoms cover infection",
                "Tenganisha hatari mbili — kipandikizi kinashughulikia ujauzito, kondomu peke yake ndizo hushughulikia maambukizi",
                "Separate risks mbili — implant ina-cover pregnancy, condoms peke yake ndio zina-cover infection"),
       "outcome": ("You said: 'The implant is excellent — at stopping pregnancy. It does absolutely nothing about HIV or any other STI. Those are two different risks and only condoms cover both. That's what dual protection means.' She had genuinely not known. ✅",
                   "Ulisema: 'Kipandikizi ni bora — kwa kuzuia ujauzito. Hakifanyi lolote kuhusu VVU au ugonjwa mwingine wa zinaa. Hizo ni hatari mbili tofauti na kondomu peke yake ndizo hushughulikia zote. Ndiyo maana ya ulinzi maradufu.' Hakuwa amejua kweli. ✅",
                   "Ulisema: 'Implant ni excellent — kwa ku-stop pregnancy. Haifanyi kitu kuhusu HIV ama STI nyingine. Hizo ni risks mbili tofauti na condoms peke yake ndio zina-cover zote. Ndio maana ya dual protection.' Hakuwa amejua kweli. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A 16-year-old thinks she may be pregnant. She is terrified and asks you not to tell anyone, and says she has heard of someone who can 'sort it out' cheaply.",
      "Msichana wa miaka 16 anadhani huenda ana mimba. Ameogopa sana na anakuomba usimwambie mtu, na anasema amesikia kuhusu mtu anayeweza 'kulimaliza' kwa bei nafuu.",
      "Dem wa miaka 16 anafikiri huenda ana mimba. Ameogopa sana na anakuomba usimwambie msee, na anasema amesikia kuhusu msee anayeweza ku-'sort it out' cheap."),
     "question": ("What matters most here?", "Nini ni muhimu zaidi hapa?", "Nini ni muhimu zaidi hapa?"),
     "choices": [
      {"kind": "bad",
       "text": ("Promise to keep it secret and give her time to decide alone",
                "Ahidi kuiweka siri na umpe muda aamue peke yake",
                "Promise kui-keep secret na umpe time a-decide peke yake"),
       "outcome": ("She has just described the exact path to an unsafe provider — fear, secrecy, cost. Leaving her alone with it is how the leading cause of adolescent maternal death happens. This is a same-day escalation, and the promise you cannot make is secrecy.",
                   "Ameeleza tu njia hasa ya kufika kwa mtoa huduma asiye salama — hofu, siri, gharama. Kumwacha peke yake nayo ndiyo jinsi sababu kuu ya vifo vya uzazi kwa vijana hutokea. Hii ni kupeleka juu siku hiyo hiyo, na ahadi usiyoweza kuitoa ni ya siri.",
                   "Ame-describe exact path ya kufika kwa unsafe provider — fear, secrecy, cost. Kumwacha peke yake nayo ndio jinsi leading cause ya adolescent maternal death inahappen. Hii ni same-day escalation, na promise usiyoweza ku-make ni ya secrecy.")},
      {"kind": "good",
       "text": ("Be honest about what you can keep private, get her a test today, and escalate to your supervising adult",
                "Kuwa mkweli kuhusu unachoweza kuweka faragha, mpe kipimo leo, na upeleke kwa msimamizi wako",
                "Kuwa honest kuhusu unachoweza ku-keep private, m-get test leo, na u-escalate kwa msimamizi wako"),
       "outcome": ("You said: 'I'm not going to gossip about this. But I can't leave you with it alone, because what you just described is how girls get hurt. Let's find out for certain today, and I'll come with you.' She tested, and she was not pregnant. She also never went near the person she mentioned. ✅",
                   "Ulisema: 'Sitasengenya kuhusu hili. Lakini siwezi kukuacha nalo peke yako, kwa sababu ulichokieleza ndiyo jinsi wasichana wanavyodhurika. Tujue kwa uhakika leo, na nitakuja nawe.' Alipimwa, na hakuwa na mimba. Pia hakuenda karibu na yule mtu aliyemtaja. ✅",
                   "Ulisema: 'Sitagossip kuhusu hii. Lakini siwezi kukuacha nayo peke yako, kwa sababu ulichoi-describe ndio jinsi madem wanavyodhurika. Tujue kwa uhakika leo, na nitakuja na wewe.' Alipimwa, na hakuwa na mimba. Pia hakuenda karibu na yule msee aliyemtaja. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Adolescents face real risks — teenage pregnancy, unsafe abortion, STIs including HIV, and maternal death.",
      "Vijana wanakabiliwa na hatari halisi — mimba za utotoni, utoaji mimba usio salama, magonjwa ya zinaa ikiwemo VVU, na vifo vya uzazi.",
      "Vijana wanaface real risks — teenage pregnancy, unsafe abortion, STIs ikiwemo HIV, na maternal death."),
     ("Teenage pregnancy is driven by poverty, low education, peer pressure, sexual violence, drug use and poor access to services.",
      "Mimba za utotoni husababishwa na umaskini, elimu duni, shinikizo la rika, ukatili wa kingono, matumizi ya dawa na huduma duni.",
      "Teenage pregnancy ina-driviwa na poverty, low education, peer pressure, sexual violence, drug use na poor access ya services."),
     ("Contraceptives prevent unplanned pregnancy — but only barrier methods also prevent STIs.",
      "Uzazi wa mpango huzuia mimba zisizopangwa — lakini njia za kizuizi peke yake ndizo pia huzuia magonjwa ya zinaa.",
      "Contraceptives zina-prevent unplanned pregnancy — lakini barrier methods peke yake ndio pia zina-prevent STIs."),
     ("Myths, stigma and fear stop young people using contraception — which is why correct information and youth-friendly services matter.",
      "Imani za uongo, unyanyapaa na hofu huwazuia vijana kutumia uzazi wa mpango — ndiyo maana taarifa sahihi na huduma rafiki ni muhimu.",
      "Myths, stigma na fear zinawazuia vijana kutumia contraception — ndio maana correct information na youth-friendly services ni muhimu."),
     ("Unsafe abortion is a leading cause of adolescent maternal death, and stigma is one of its main drivers.",
      "Utoaji mimba usio salama ni sababu kuu ya vifo vya uzazi kwa vijana, na unyanyapaa ni mojawapo ya vichocheo vyake vikuu.",
      "Unsafe abortion ni leading cause ya adolescent maternal death, na stigma ni mojawapo ya main drivers zake."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Msichana haendi kwa mtu hatari kwa sababu hajui hatari. Anaenda kwa sababu anaogopa aliye salama zaidi kuliko anavyoiogopa hatari.",
     "Msichana haendi kwa mtu hatari kwa sababu hajui hatari. Huenda kwa sababu anamwogopa aliye salama zaidi kuliko anavyoiogopa hatari.",
     "Dem haendi kwa msee hatari kwa sababu hajui danger. Anaenda kwa sababu anaogopa aliye safe zaidi kuliko anavyoogopa danger.")},
   ]},
 ],

 "quiz": [
  {"q": "Which contraceptive type also protects against STIs?",
   "options": ["Implants", "Barrier methods such as condoms", "Injections", "Natural methods"],
   "answer": "B",
   "explain": "Hormonal methods stop pregnancy and give no protection against infection whatsoever — the most consequential misunderstanding in the module."},

  {"q": "A peer says she is on an implant so she no longer needs condoms. What is the correct response?",
   "options": ["Agree — implants are highly effective",
               "Separate the two risks: the implant covers pregnancy, only condoms cover infection",
               "Tell her to stop the implant",
               "Suggest she use natural methods instead"],
   "answer": "B",
   "explain": "The implant is excellent at stopping pregnancy and does absolutely nothing about HIV or any other STI."},

  {"q": "How do hormonal methods work?",
   "options": ["By blocking sperm physically",
               "By stopping the release of eggs, or preventing a fertilised egg growing in the womb",
               "By killing infections",
               "By tracking fertile days"],
   "answer": "B",
   "explain": "Pills, injections, implants and IUDs all work hormonally — which is why none of them touch STI risk."},

  {"q": "Which are barriers to contraceptive use in the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Lack of information about methods and where to get them",
               "Misconceptions and myths",
               "Shyness about discussing reproductive health",
               "Fear of being judged",
               "Contraceptives being illegal in Kenya"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Contraception is legal and available. Every listed barrier is about access, information or fear — none is about the method failing."},

  {"q": "Teenage pregnancy is defined as pregnancy in a girl aged:",
   "options": ["13 to 19", "10 to 19", "15 to 19", "12 to 18"],
   "answer": "B",
   "explain": "The lower bound of 10 is deliberate, and matches the adolescent age range used throughout the curriculum."},

  {"q": "Which are early signs of pregnancy? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Missed periods", "Tender or swollen breasts", "Frequent urination",
               "Nausea and vomiting", "Sudden weight loss"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Signs differ from person to person and between pregnancies — which is why a test, not a symptom list, is what confirms it."},

  {"q": "What is unsafe abortion?",
   "options": ["Any abortion",
               "Termination by someone lacking the necessary skills, or in an environment below minimum medical standards",
               "An abortion performed after three months",
               "An abortion the family disagrees with"],
   "answer": "B",
   "explain": "The curriculum names it as a leading cause of maternal death among adolescents and youth."},

  {"q": "According to the curriculum, which drives unsafe abortion? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Social stigma and fear of judgement",
               "Limited reproductive health services, especially rural",
               "Pregnancies resulting from rape or coercion",
               "Economic barriers to affording safe services",
               "Girls being unaware that it is dangerous"],
   "answer": ["A", "B", "C", "D"],
   "explain": "She usually knows it is dangerous. She goes because she fears the safe provider more than she fears the danger."},

  {"q": "A frightened 16-year-old thinks she may be pregnant and mentions someone who can 'sort it out' cheaply. What matters most?",
   "options": ["Promising secrecy and giving her time to decide alone",
               "Being honest about what you can keep private, getting her a test today, and escalating",
               "Telling her family immediately without discussion",
               "Advising her which option to choose"],
   "answer": "B",
   "explain": "She has just described the exact path to an unsafe provider — fear, secrecy, cost. Leaving her alone with it is how adolescent maternal deaths happen."},

  {"q": "What is a peer educator's role when a pregnancy is suspected?",
   "options": ["Diagnose it from the symptoms",
               "Get her to a test and a health worker quickly, record the referral and follow up",
               "Advise her on what to do about it",
               "Wait until she is certain"],
   "answer": "B",
   "explain": "Early confirmation opens every option and protects her health; delay closes options one by one."},
 ],
}
