# Module 12 (part 1 of 2) — Understanding Gender Based Violence
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 12.
# Trilingual: English / Kiswahili / Sheng.
#
# TONE NOTE: definitions are kept clinical and non-graphic, as the deck does.
# Nothing here frames a survivor as responsible for what was done to them.

LESSON = {
 "file": "m12a-understanding-gbv.html",
 "module_code": "M12",
 "module_slug": "gender-based-violence",
 "lesson_slug": "m12a-understanding-gbv",
 "module_label": "Peer Educator · M12 · Part 1 of 2",
 "title": "Understanding Gender Based Violence",
 "icon": "🛡️",
 "duration": 45,

 "objectives": [
  ("Define gender-based violence and the related terms",
   "Fafanua ukatili wa kijinsia na maneno yanayohusiana",
   "Define gender-based violence na maneno yanayohusiana"),
  ("Describe the different types of GBV",
   "Eleza aina mbalimbali za ukatili wa kijinsia",
   "Describe types tofauti za GBV"),
  ("Identify the effects of GBV on individuals and communities",
   "Tambua athari za ukatili wa kijinsia kwa watu binafsi na jamii",
   "Tambua effects za GBV kwa watu binafsi na community"),
  ("Recognise the warning signs of a potential perpetrator",
   "Tambua dalili za onyo za mtu anayeweza kutenda ukatili",
   "Tambua warning signs za msee anayeweza kutenda ukatili"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Most adolescents are harmed by someone they already know and trust. What does that change about how we teach safety?",
  "<strong>🔍 Swali Kubwa:</strong> Vijana wengi hudhurika na mtu wanayemjua na kumwamini tayari. Hilo linabadilisha nini kuhusu jinsi tunavyofundisha usalama?",
  "<strong>🔍 Big Question:</strong> Vijana wengi wanadhurika na msee wanayemjua na kumtrust tayari. Hiyo inabadilisha nini kuhusu jinsi tunavyofundisha safety?"),

 "slides": [

  # ── 1. Definitions ────────────────────────────────────────────────
  {"icon": "📖",
   "head": ("The Words, Precisely", "Maneno, Kwa Usahihi", "Maneno, Kwa Usahihi"),
   "blocks": [
    {"type": "p", "text": (
     "These terms have exact meanings in Kenyan law. A peer educator who uses them loosely cannot be trusted with them — and a survivor listening will notice immediately.",
     "Maneno haya yana maana kamili katika sheria za Kenya. Mwelimishaji rika anayeyatumia kiholela hawezi kuaminiwa nayo — na manusura anayesikiliza atagundua mara moja.",
     "Haya maneno yana maana exact kwa sheria za Kenya. Peer educator anayeyatumia loosely hawezi ku-trustiwa nayo — na survivor anayesikiliza atagundua mara moja.")},
    {"type": "key_term", "term": ("🔑 Gender Based Violence (GBV)", "🔑 Ukatili wa Kijinsia", "🔑 Gender Based Violence (GBV)"), "text": (
     "Any harmful act done to a person against their will, based on their gender or resulting from power inequality.",
     "Kitendo chochote cha kudhuru kinachofanywa kwa mtu bila ridhaa yake, kutokana na jinsia yake au kutokana na usawa duni wa madaraka.",
     "Kitendo chochote cha kudhuru kinachofanywa kwa msee bila consent yake, kutokana na gender yake ama power inequality.")},
    {"type": "key_term", "term": ("🔑 Sexual and Gender Based Violence (SGBV)", "🔑 Ukatili wa Kingono na Kijinsia", "🔑 Sexual and Gender Based Violence (SGBV)"), "text": (
     "Any sexual act, attempted sexual act, unwanted sexual comment or advance, using coercion, threats or force — by any person, regardless of their relationship to the survivor, in any setting.",
     "Kitendo chochote cha kingono, jaribio la kitendo cha kingono, maoni au ushawishi wa kingono usiotakikana, kwa kutumia shurutisho, vitisho au nguvu — na mtu yeyote, bila kujali uhusiano wake na manusura, mahali popote.",
     "Kitendo chochote cha kingono, attempt ya kitendo cha kingono, unwanted sexual comment ama advance, kwa kutumia coercion, threats ama force — na msee yeyote, bila kujali relationship yake na survivor, mahali popote.")},
    {"type": "table",
     "headers": [("Term", "Neno", "Term"), ("Meaning in Kenyan law", "Maana katika sheria ya Kenya", "Maana kwa sheria ya Kenya")],
     "rows": [
      [("Rape", "Ubakaji", "Rape"),
       ("Penetration of a person's genital organs without consent, or where consent was obtained by force, threats or intimidation of any kind.",
        "Kuingiliwa kwa viungo vya siri vya mtu bila ridhaa, au pale ridhaa ilipopatikana kwa nguvu, vitisho au kutishwa kwa aina yoyote.",
        "Penetration ya genital organs za msee bila consent, ama pale consent ilipopatikana kwa force, threats ama intimidation ya aina yoyote.")],
      [("Defilement", "Kudhalilisha mtoto", "Defilement"),
       ("Penetration of a <strong>child's</strong> genital organs. A child is anyone below 18. Consent is not a defence.",
        "Kuingiliwa kwa viungo vya siri vya <strong>mtoto</strong>. Mtoto ni yeyote chini ya miaka 18. Ridhaa si utetezi.",
        "Penetration ya genital organs za <strong>mtoto</strong>. Mtoto ni yeyote chini ya 18. Consent si defence.")],
      [("Incest", "Kujamiiana na ndugu", "Incest"),
       ("Sexual intercourse with a family member or close relative — including adopted and half siblings.",
        "Kujamiiana na mwanafamilia au ndugu wa karibu — wakiwemo wa kuasili na wa kambo.",
        "Sexual intercourse na family member ama close relative — wakiwemo wa kuasili na half siblings.")],
      [("Date rape", "Ubakaji wa mchumba", "Date rape"),
       ("Sexual assault where the perpetrator is someone the survivor knows — a friend or acquaintance — occurring during a social outing.",
        "Shambulio la kingono ambapo mtendaji ni mtu anayemjua manusura — rafiki au mtu anayemfahamu — likitokea wakati wa matembezi ya kijamii.",
        "Sexual assault ambapo perpetrator ni msee anayemjua survivor — friend ama acquaintance — ikihappen wakati wa social outing.")],
     ]},
   ]},

  # ── 2. Types ──────────────────────────────────────────────────────
  {"icon": "🗂️",
   "head": ("The Six Types", "Aina Sita", "Types Sita"),
   "blocks": [
    {"type": "p", "text": (
     "Most people picture only the first one. Naming all six is what lets a young person recognise what is happening to them.",
     "Watu wengi hufikiria ya kwanza tu. Kuzitaja zote sita ndiko kunakomwezesha kijana kutambua kinachomtokea.",
     "Wasee wengi wanafikiria ya kwanza tu. Ku-name zote sita ndio inamwezesha kijana kutambua kinachomhappen.")},
    {"type": "table",
     "headers": [("Type", "Aina", "Type"), ("What it looks like", "Inavyoonekana", "Inavyoonekana")],
     "rows": [
      [("Sexual violence", "Ukatili wa kingono", "Sexual violence"),
       ("Defilement, rape, attempted defilement or rape, unwanted sexual advances or comments",
        "Kudhalilisha mtoto, ubakaji, majaribio ya hayo, ushawishi au maoni ya kingono yasiyotakikana",
        "Defilement, rape, attempts za hayo, unwanted sexual advances ama comments")],
      [("Physical violence", "Ukatili wa kimwili", "Physical violence"),
       ("Slaps, kicks, punches, mutilation, burns, use of weapons",
        "Makofi, mateke, ngumi, kukatwa viungo, kuchomwa, matumizi ya silaha",
        "Makofi, mateke, ngumi, mutilation, burns, matumizi ya weapons")],
      [("Psychological / emotional", "Kisaikolojia / kihisia", "Psychological / emotional"),
       ("Shouting, humiliation, intimidation, threats, belittling, confining or isolating someone from family and friends",
        "Kupiga kelele, kufedhehesha, kutisha, vitisho, kudharau, kumfungia au kumtenga mtu na familia na marafiki",
        "Kupiga kelele, humiliation, intimidation, threats, kudharau, ku-confine ama ku-isolate msee na family na friends")],
      [("Socio-economic", "Kiuchumi-kijamii", "Socio-economic"),
       ("Denial of resources; trafficking of women and girls for economic gain",
        "Kunyimwa rasilimali; kusafirisha wanawake na wasichana kwa faida ya kiuchumi",
        "Kunyimwa resources; trafficking ya wanawake na wasichana kwa economic gain")],
      [("Harmful practices", "Mila hatari", "Harmful practices"),
       ("Female genital mutilation, child marriage, child labour",
        "Ukeketaji, ndoa za utotoni, ajira ya watoto",
        "Female genital mutilation, child marriage, child labour")],
      [("Intimate partner violence", "Ukatili wa mwenzi", "Intimate partner violence"),
       ("Any behaviour in an intimate relationship causing physical, sexual or psychological harm — including reproductive coercion",
        "Tabia yoyote katika uhusiano wa karibu inayosababisha madhara ya kimwili, kingono au kisaikolojia — ikiwemo kulazimishwa kuhusu uzazi",
        "Behaviour yoyote kwa intimate relationship inayosababisha physical, sexual ama psychological harm — ikiwemo reproductive coercion")],
     ]},
   ]},

  # ── 3. Against children ───────────────────────────────────────────
  {"icon": "🧒",
   "head": ("Violence Against Children", "Ukatili Dhidi ya Watoto", "Violence Dhidi ya Watoto"),
   "blocks": [
    {"type": "table",
     "headers": [("Category", "Kundi", "Category"), ("Includes", "Inajumuisha", "Inajumuisha")],
     "rows": [
      [("Exploitation", "Unyonyaji", "Exploitation"),
       ("Illegal and harmful child labour; using children for begging; commercial sexual exploitation; child trafficking; using children in criminal acts",
        "Ajira haramu na hatari ya watoto; kuwatumia watoto kuomba; unyonyaji wa kingono kibiashara; usafirishaji wa watoto; kuwatumia watoto katika uhalifu",
        "Illegal na harmful child labour; kuwatumia watoto kuomba; commercial sexual exploitation; child trafficking; kuwatumia watoto kwa criminal acts")],
      [("Neglect", "Kutelekezwa", "Neglect"),
       ("Deprivation of food, health care, safe health habits, education, play and creative activity, or physical and emotional care",
        "Kunyimwa chakula, huduma za afya, tabia salama za afya, elimu, michezo na shughuli za ubunifu, au malezi ya kimwili na kihisia",
        "Kunyimwa chakula, health care, safe health habits, education, play na creative activity, ama physical na emotional care")],
      [("Sexual violence", "Ukatili wa kingono", "Sexual violence"),
       ("Inappropriate sexual touching; incest; early marriage; defilement; showing a child pornography or explicit sexual language; forcing a child to witness sexual acts",
        "Kuguswa vibaya kingono; kujamiiana na ndugu; ndoa za mapema; kudhalilisha mtoto; kumwonyesha mtoto ponografia au lugha ya kingono; kumlazimisha mtoto kushuhudia vitendo vya kingono",
        "Inappropriate sexual touching; incest; early marriage; defilement; kumwonyesha mtoto pornography ama explicit sexual language; ku-force mtoto kushuhudia sexual acts")],
      [("Physical and emotional", "Kimwili na kihisia", "Physical na emotional"),
       ("Bullying, slapping, hitting by hand or object, torture, emotional violence, and at its worst, killing",
        "Uonevu, kupiga makofi, kupiga kwa mkono au kifaa, mateso, ukatili wa kihisia, na kwa ubaya zaidi, kuua",
        "Bullying, kupiga makofi, kupiga kwa mkono ama kifaa, torture, emotional violence, na kwa worst, kuua")],
     ]},
    {"type": "warn", "title": ("⚠️ Consent is not a defence with a child", "⚠️ Ridhaa si utetezi kwa mtoto", "⚠️ Consent si defence kwa mtoto"), "text": (
     " A child is anyone under 18. If a peer tells you 'she agreed' or 'he wanted to', that is still defilement in law. Your job is not to weigh that — it is to escalate it.",
     " Mtoto ni yeyote chini ya miaka 18. Rika akikuambia 'alikubali' au 'alitaka', bado ni kudhalilisha mtoto kisheria. Kazi yako si kupima hilo — ni kulipeleka juu.",
     " Mtoto ni yeyote chini ya 18. Msee akikuambia 'alikubali' ama 'alitaka', bado ni defilement kisheria. Job yako si ku-weigh hiyo — ni ku-escalate.")},
   ]},

  # ── 4. Effects ────────────────────────────────────────────────────
  {"icon": "💔",
   "head": ("What It Does to People", "Inavyowafanya Watu", "Inavyowafanya Wasee"),
   "blocks": [
    {"type": "table",
     "headers": [("Physical", "Kimwili", "Physical"), ("Emotional", "Kihisia", "Emotional"), ("Social", "Kijamii", "Social")],
     "rows": [
      [("Injuries — bruises, fractures, burns, internal bleeding",
        "Majeraha — michubuko, mivunjiko, kuungua, kutokwa damu ndani",
        "Injuries — bruises, fractures, burns, internal bleeding"),
       ("Low self-esteem and loss of confidence",
        "Kujithamini duni na kupoteza kujiamini",
        "Low self-esteem na kupoteza confidence"),
       ("Stigma, rejection and isolation of survivors",
        "Unyanyapaa, kukataliwa na kutengwa kwa manusura",
        "Stigma, rejection na isolation ya survivors")],
      [("Chronic pain or disability from repeated abuse",
        "Maumivu sugu au ulemavu kutokana na unyanyasaji wa mara kwa mara",
        "Chronic pain ama disability kutokana na repeated abuse"),
       ("Shame, guilt or helplessness",
        "Aibu, hatia au kukosa msaada",
        "Shame, guilt ama helplessness"),
       ("Breakdown of family and community relationships",
        "Kuvunjika kwa mahusiano ya familia na jamii",
        "Kuvunjika kwa family na community relationships")],
      [("Unintended pregnancy, or unsafe abortion",
        "Mimba isiyotarajiwa, au utoaji mimba usio salama",
        "Unintended pregnancy, ama unsafe abortion"),
       ("Anxiety, depression and post-traumatic stress",
        "Wasiwasi, msongo wa mawazo na mfadhaiko baada ya kiwewe",
        "Anxiety, depression na post-traumatic stress"),
       ("Poor school attendance or dropout, especially among girls",
        "Kuhudhuria shule vibaya au kuacha shule, hasa kwa wasichana",
        "Poor school attendance ama dropout, hasa kwa wasichana")],
      [("STIs, including HIV",
        "Magonjwa ya zinaa, ikiwemo VVU",
        "STIs, ikiwemo HIV"),
       ("Suicidal thoughts or self-harm",
        "Mawazo ya kujiua au kujidhuru",
        "Suicidal thoughts ama self-harm"),
       ("Loss of social and economic opportunity",
        "Kupoteza fursa za kijamii na kiuchumi",
        "Kupoteza social na economic opportunities")],
      [("Sleep disturbance, headaches, fatigue — and in severe cases, death",
        "Kukosa usingizi, maumivu ya kichwa, uchovu — na katika hali mbaya, kifo",
        "Kukosa usingizi, headaches, fatigue — na kwa severe cases, kifo"),
       ("Fear and mistrust of others, and of intimate relationships",
        "Hofu na kutokuamini wengine, na mahusiano ya karibu",
        "Fear na kutokutrust wengine, na intimate relationships"),
       ("Cycles of violence passed down through generations",
        "Mizunguko ya ukatili inayopitishwa kwa vizazi",
        "Cycles za violence zinazopitishwa kwa generations")],
     ]},
    {"type": "tip", "title": ("💡 Why the social column matters to you", "💡 Kwa nini safu ya kijamii ni muhimu kwako", "💡 Kwa nini social column ni muhimu kwako"), "text": (
     " The physical and emotional harm is done by the perpetrator. The social harm — stigma, rejection, isolation — is done by the community afterwards. That second layer is the one a peer educator is actually positioned to prevent.",
     " Madhara ya kimwili na kihisia hufanywa na mtendaji. Madhara ya kijamii — unyanyapaa, kukataliwa, kutengwa — hufanywa na jamii baadaye. Safu hiyo ya pili ndiyo mwelimishaji rika yuko katika nafasi ya kuizuia.",
     " Physical na emotional harm inafanywa na perpetrator. Social harm — stigma, rejection, isolation — inafanywa na community baadaye. Hiyo layer ya pili ndio peer educator yuko kwa position ya kui-prevent.")},
   ]},

  # ── 5. Who ────────────────────────────────────────────────────────
  {"icon": "👤",
   "head": ("Who Actually Does This", "Nani Hasa Hufanya Hivi", "Nani Hasa Anafanya Hivi"),
   "blocks": [
    {"type": "p", "text": (
     "This is the part that is hardest to teach, because it contradicts what young people are usually told about strangers.",
     "Hii ndiyo sehemu ngumu zaidi kufundisha, kwa sababu inapingana na kile vijana huambiwa kuhusu wageni.",
     "Hii ndio part ngumu zaidi kufundisha, kwa sababu inapinga kile vijana wanaambiwa kuhusu strangers.")},
    {"type": "p", "text": (
     "Adolescents are most often violated by <strong>people known to them</strong> — relatives, parents, teachers and friends. Also religious leaders, boyfriends and girlfriends, workers and workmates. And strangers, yes.",
     "Vijana mara nyingi hudhurika na <strong>watu wanaowajua</strong> — ndugu, wazazi, walimu na marafiki. Pia viongozi wa dini, wapenzi, wafanyakazi na wenzao kazini. Na wageni, ndiyo.",
     "Vijana mara nyingi wanadhurika na <strong>wasee wanaowajua</strong> — relatives, wazazi, teachers na friends. Pia religious leaders, boyfriends na girlfriends, workers na workmates. Na strangers, ndio.")},
    {"type": "warn", "title": ("⚠️ Anybody can violate an adolescent", "⚠️ Yeyote anaweza kumdhuru kijana", "⚠️ Yeyote anaweza kumdhuru kijana"), "text": (
     " Position, respect and relationship are not protective. Teaching 'avoid strangers' alone leaves a young person defenceless against the far commoner case — someone they were told to trust.",
     " Cheo, heshima na uhusiano si kinga. Kufundisha 'epuka wageni' peke yake humwacha kijana bila ulinzi dhidi ya hali ya kawaida zaidi — mtu aliyeambiwa amwamini.",
     " Position, respect na relationship si protection. Kufundisha 'avoid strangers' peke yake inamwacha kijana bila protection dhidi ya case common zaidi — msee aliyeambiwa amtrust.")},
    {"type": "facilitator", "minutes": 8, "text": (
     "Handle this slide carefully. In any group this size, someone present has likely experienced it. Do not ask for personal stories or invite disclosure in front of others. State the facts, then say clearly that anyone who wants to talk can find you afterwards — and mean it.",
     "Shughulikia slaidi hii kwa uangalifu. Katika kundi lolote la ukubwa huu, huenda mtu aliyepo amewahi kupitia hili. Usiombe hadithi binafsi wala kualika ufichuzi mbele ya wengine. Sema ukweli, kisha useme wazi kwamba yeyote anayetaka kuzungumza anaweza kukupata baadaye — na umaanishe.",
     "Handle hii slide kwa uangalifu. Kwa group yoyote ya size hii, huenda msee aliyepo amewahi ku-experience hii. Usiombe personal stories wala ku-invite disclosure mbele ya wengine. Sema facts, kisha useme wazi ati yeyote anayetaka kuongea anaweza kukupata baadaye — na umean.")},
   ]},

  # ── 6. Warning signs ──────────────────────────────────────────────
  {"icon": "🚩",
   "head": ("Warning Signs to Watch For", "Dalili za Onyo za Kuangalia", "Warning Signs za Kuangalia"),
   "blocks": [
    {"type": "p", "text": (
     "Watch for people who do these things — to you, or to anyone around you.",
     "Angalia watu wanaofanya mambo haya — kwako, au kwa yeyote aliye karibu nawe.",
     "Angalia wasee wanaofanya haya mambo — kwako, ama kwa yeyote aliye karibu na wewe.")},
    {"type": "list", "items": [
     ("<strong>Touch inappropriately</strong> — touching private parts, or hugging and tickling that does not stop",
      "<strong>Kugusa vibaya</strong> — kugusa sehemu za siri, au kukumbatia na kuchekesha kusikoisha",
      "<strong>Ku-touch inappropriately</strong> — kugusa private parts, ama kukumbatia na kuchekesha kusikoisha"),
     ("<strong>Ignore your boundaries</strong> — not respecting privacy in the toilet or bathroom, or refusing to let go when you pull away",
      "<strong>Kupuuza mipaka yako</strong> — kutoheshimu faragha chooni au bafuni, au kukataa kukuachia unapojivuta",
      "<strong>Ku-ignore boundaries zako</strong> — kutoheshimu privacy chooni ama bathroom, ama kukataa kukuachia unapojivuta"),
     ("<strong>Seek isolation with you</strong> — preferring time alone with you when other adults are not around",
      "<strong>Kutafuta upweke nawe</strong> — kupendelea kuwa nawe peke yenu wakati watu wazima wengine hawapo",
      "<strong>Kutafuta isolation na wewe</strong> — kupendelea time peke yenu wakati watu wazima wengine hawako"),
     ("<strong>Give gifts without reason</strong> — money or presents with no occasion and no clear explanation",
      "<strong>Kutoa zawadi bila sababu</strong> — pesa au zawadi bila tukio wala maelezo wazi",
      "<strong>Kutoa gifts bila reason</strong> — pesa ama presents bila occasion wala clear explanation"),
     ("<strong>Talk about sexual topics</strong> — asking you to discuss sexual matters, or making sexual comments",
      "<strong>Kuzungumza mada za kingono</strong> — kukuomba ujadili mambo ya kingono, au kutoa maoni ya kingono",
      "<strong>Kuongea sexual topics</strong> — kukuomba u-discuss sexual matters, ama kutoa sexual comments"),
     ("<strong>Make threats</strong> — 'if you don't do this, I'll stop being your friend' or 'I'll break up with you'",
      "<strong>Kutoa vitisho</strong> — 'usipofanya hivi, sitakuwa rafiki yako tena' au 'nitaachana nawe'",
      "<strong>Kutoa threats</strong> — 'usipofanya hii, sitakuwa friend wako' ama 'nitakuachana na wewe'"),
     ("<strong>Show anger or violence</strong> — frequent rage, violent acts, or threats to harm you or people you care about, even if they apologise afterwards",
      "<strong>Kuonyesha hasira au ukatili</strong> — ghadhabu za mara kwa mara, vitendo vya jeuri, au vitisho vya kukudhuru wewe au unaowajali, hata wakiomba msamaha baadaye",
      "<strong>Kuonyesha anger ama violence</strong> — rage ya mara kwa mara, violent acts, ama threats za kukudhuru wewe ama wasee unaowajali, hata waki-apologise baadaye"),
     ("<strong>Control your actions</strong> — ignoring your needs, deciding for you, limiting your freedom",
      "<strong>Kudhibiti matendo yako</strong> — kupuuza mahitaji yako, kukuamulia, kupunguza uhuru wako",
      "<strong>Ku-control actions zako</strong> — ku-ignore needs zako, kukuamulia, kupunguza freedom yako"),
    ]},
    {"type": "sheng", "text": (
     "Kuomba msamaha baada ya kudhuru si mabadiliko. Ni sehemu ya mzunguko. Angalia kinachotokea baada ya msamaha, si msamaha wenyewe.",
     "Kuomba msamaha baada ya kudhuru si mabadiliko. Ni sehemu ya mzunguko. Angalia kinachotokea baada ya msamaha, si msamaha wenyewe.",
     "Ku-apologise baada ya kudhuru si change. Ni part ya cycle. Angalia kinachohappen baada ya apology, si apology yenyewe.")},
   ]},

  # ── 7. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A 15-year-old in your group mentions that an uncle keeps giving her money and airtime for no reason, and prefers to sit with her when nobody else is home. She says he is 'just being kind'.",
      "Msichana wa miaka 15 kwenye kundi lako anataja kwamba mjomba wake anaendelea kumpa pesa na salio bila sababu, na anapendelea kukaa naye wakati hakuna mtu mwingine nyumbani. Anasema ni 'wema tu'.",
      "Dem wa miaka 15 kwa group yako anataja ati uncle wake anaendelea kumpa pesa na airtime bila reason, na anapendelea kukaa naye wakati hakuna msee mwingine nyumbani. Anasema ni 'kindness tu'."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Nothing yet — nothing has actually happened, and accusing an uncle is serious",
                "Hakuna bado — hakuna kilichotokea, na kumshtaki mjomba ni jambo zito",
                "Hakuna bado — hakuna kilicho-happen, na ku-accuse uncle ni serious"),
       "outcome": ("Two warning signs are already present: gifts without reason, and seeking isolation. Waiting for something to happen is waiting for harm. Raising a concern is not an accusation — it is what the warning signs are for.",
                   "Dalili mbili za onyo tayari zipo: zawadi bila sababu, na kutafuta upweke. Kusubiri kitu kitokee ni kusubiri madhara. Kutoa wasiwasi si mashtaka — ndiyo maana dalili za onyo zipo.",
                   "Warning signs mbili tayari ziko: gifts bila reason, na kutafuta isolation. Kungoja kitu kihappen ni kungoja harm. Ku-raise concern si accusation — ndio maana warning signs ziko.")},
      {"kind": "good",
       "text": ("Name the pattern to her without alarming her, and raise it with your supervising adult",
                "Mtajie mchoro huo bila kumtisha, na ulipeleke kwa mtu mzima anayekusimamia",
                "Mtajie hiyo pattern bila kumscare, na uli-raise kwa msimamizi wako"),
       "outcome": ("You said: 'That might be nothing. But two of the things we listed today are in what you just said — gifts with no reason, and wanting to be alone with you. You haven't done anything wrong, and I'd like us to tell someone who can keep an eye out.' She agreed. Nothing had happened yet — which was the point. ✅",
                   "Ulisema: 'Huenda si kitu. Lakini mawili kati ya tuliyoorodhesha leo yamo katika uliyosema — zawadi bila sababu, na kutaka kuwa peke yenu. Hujafanya kosa lolote, na ningependa tumwambie mtu anayeweza kuangalia.' Alikubali. Hakuna kilichokuwa kimetokea bado — na hilo ndilo lengo. ✅",
                   "Ulisema: 'Huenda si kitu. Lakini mbili kati ya tulizo-list leo ziko kwa ulichosema — gifts bila reason, na kutaka kuwa peke yenu. Haujafanya kosa lolote, na ningependa tumwambie msee anayeweza ku-keep an eye.' Alikubali. Hakuna kilicho-happen bado — na hiyo ndio point. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "During a session a young man argues that if a girl went to a man's house willingly, then whatever followed was partly her fault. Several others nod.",
      "Wakati wa kipindi kijana anahoji kwamba msichana akienda nyumbani kwa mwanamume kwa hiari, basi kilichofuata kilikuwa kwa sehemu kosa lake. Wengine kadhaa wanaitikia.",
      "Wakati wa session msee anaargue ati dem akienda nyumbani kwa mse kwa hiari, basi kilichofollow kilikuwa partly kosa lake. Wengine kadhaa wanaitikia."),
     "question": ("How do you handle this?", "Unashughulikia hili vipi?", "Una-handle hii aje?"),
     "choices": [
      {"kind": "bad",
       "text": ("Move on quickly — arguing will only make the session tense",
                "Endelea haraka — kubishana kutafanya kipindi kiwe na wasiwasi tu",
                "Endelea haraka — ku-argue itafanya session iwe tense tu"),
       "outcome": ("Silence reads as agreement. If a survivor is in that room, they have just heard the group decide that people like them are partly to blame — and they will not be coming to you afterwards.",
                   "Ukimya husomeka kama kukubaliana. Kama manusura yumo chumbani humo, ndio wamesikia kundi likiamua kwamba watu kama wao wana lawama kwa sehemu — na hawatakuja kwako baadaye.",
                   "Silence inasomeka kama agreement. Kama survivor yuko kwa hiyo room, ndio wamesikia group ika-decide ati wasee kama wao wana blame partly — na hawatakuja kwako baadaye.")},
      {"kind": "good",
       "text": ("Separate the two things: a decision to go somewhere, and another person's decision to do harm",
                "Tenganisha mambo mawili: uamuzi wa kwenda mahali, na uamuzi wa mtu mwingine wa kudhuru",
                "Separate vitu viwili: decision ya kuenda mahali, na decision ya msee mwingine ya kudhuru"),
       "outcome": ("You said: 'She decided to walk through a door. He decided to commit a crime. Those are two different decisions, and only one of them is illegal. We can talk about safety all day — it still doesn't move the blame.' The nodding stopped. ✅",
                   "Ulisema: 'Aliamua kupita mlangoni. Yeye aliamua kutenda uhalifu. Hayo ni maamuzi mawili tofauti, na moja tu kati yayo ni haramu. Tunaweza kuzungumza usalama siku nzima — bado hayahamishi lawama.' Kuitikia kulikoma. ✅",
                   "Ulisema: 'Ali-decide kupita mlangoni. Yeye ali-decide kutenda crime. Hizo ni decisions mbili tofauti, na moja tu kati yake ni illegal. Tunaweza kuongea safety siku nzima — bado haihamishi blame.' Kuitikia kuli-stop. ✅")},
     ]},
   ]},

  # ── 8. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("GBV causes serious, lasting harm — physical, emotional and social.",
      "Ukatili wa kijinsia husababisha madhara makubwa ya kudumu — ya kimwili, kihisia na kijamii.",
      "GBV inasababisha serious, lasting harm — physical, emotional na social."),
     ("It can be done by anyone: relatives, friends, teachers, partners or strangers.",
      "Unaweza kufanywa na yeyote: ndugu, marafiki, walimu, wapenzi au wageni.",
      "Inaweza kufanywa na yeyote: relatives, friends, teachers, partners ama strangers."),
     ("A child is anyone under 18, and consent is never a defence in defilement.",
      "Mtoto ni yeyote chini ya miaka 18, na ridhaa si utetezi kamwe katika kudhalilisha mtoto.",
      "Mtoto ni yeyote chini ya 18, na consent si defence kamwe kwa defilement."),
     ("Responsibility always lies with the person who chose to cause harm — never with the survivor.",
      "Lawama daima ni ya aliyechagua kudhuru — kamwe si ya manusura.",
      "Responsibility daima ni ya aliye-choose kudhuru — kamwe si ya survivor."),
    ]},
    {"type": "p", "text": (
     "Part 2 covers what to do when it has already happened — the first hour, the 72-hour window, and the harmful practices that are still defended as tradition.",
     "Sehemu ya 2 inahusu la kufanya likishatokea — saa ya kwanza, muda wa saa 72, na mila hatari zinazoendelea kutetewa kama utamaduni.",
     "Part 2 inacover la kufanya ikishahappen — hour ya kwanza, window ya masaa 72, na harmful practices zinazoendelea ku-defendiwa kama tradition.")},
   ]},
 ],

 "quiz": [
  {"q": "How does the curriculum define gender-based violence?",
   "options": ["Any violence between a man and a woman",
               "Any harmful act done against a person's will, based on their gender or resulting from power inequality",
               "Only physical assault",
               "Violence that happens inside a marriage"],
   "answer": "B",
   "explain": "Power inequality is central to the definition — which is why it covers far more than physical assault between partners."},

  {"q": "In Kenyan law, defilement is:",
   "options": ["Any sexual act without consent",
               "Penetration of a child's genital organs — a child being anyone under 18",
               "Sexual assault by a stranger",
               "The same thing as incest"],
   "answer": "B",
   "explain": "Because the survivor is a child, consent is not a defence. That distinction is the whole point of the separate term."},

  {"q": "A peer tells you a 16-year-old 'agreed' to sex with an adult. What is true?",
   "options": ["If she agreed, no offence occurred",
               "It is still defilement — consent is not a defence where the survivor is under 18",
               "It depends on how old the adult is",
               "It is only an offence if she reports it"],
   "answer": "B",
   "explain": "Your role is not to weigh whether she agreed. It is to escalate."},

  {"q": "Which are types of GBV named in the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Psychological or emotional violence",
               "Socio-economic violence, including denial of resources",
               "Harmful practices such as FGM and child marriage",
               "Intimate partner violence, including reproductive coercion",
               "Accidental injury"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Accidental injury is not GBV — intent and power are what define it. The other four are among the six named types."},

  {"q": "Who most often violates adolescents?",
   "options": ["Strangers",
               "People known to them — relatives, parents, teachers and friends",
               "Only men in positions of authority",
               "Other adolescents"],
   "answer": "B",
   "explain": "This is why teaching 'avoid strangers' alone leaves young people defenceless against the far commoner case."},

  {"q": "Which of these are warning signs of a potential perpetrator? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Giving money or gifts with no occasion or clear reason",
               "Preferring to be alone with a young person when other adults are away",
               "Refusing to let go when the young person pulls away",
               "Asking a young person to discuss sexual topics",
               "Asking about their schoolwork"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Asking about schoolwork is ordinary interest. The other four are on the curriculum's warning list."},

  {"q": "Someone apologises sincerely after every violent episode. What does the curriculum say?",
   "options": ["An apology shows they are changing",
               "Frequent anger or violence remains a warning sign even if they later apologise",
               "Apologies mean the relationship can be repaired without help",
               "It is only a warning sign if they do not apologise"],
   "answer": "B",
   "explain": "The apology is part of the cycle, not an exit from it. Watch what happens after the apology, not the apology."},

  {"q": "A group member says a survivor was 'partly to blame' for going somewhere willingly. What is the best response?",
   "options": ["Move on to avoid tension",
               "Agree that she should have been more careful",
               "Separate her decision to go somewhere from another person's decision to cause harm",
               "Ask the group to vote on it"],
   "answer": "C",
   "explain": "Silence reads as agreement — and any survivor in the room hears the group decide people like them are to blame."},

  {"q": "Which harm is caused by the community rather than the perpetrator?",
   "options": ["Physical injury",
               "Post-traumatic stress",
               "Stigma, rejection and social isolation",
               "Unintended pregnancy"],
   "answer": "C",
   "explain": "That second layer of harm is the one a peer educator is actually positioned to prevent."},

  {"q": "Which is an example of violence against children through NEGLECT?",
   "options": ["Bullying at school",
               "Deprivation of food, health care or education",
               "Showing a child pornography",
               "Child trafficking"],
   "answer": "B",
   "explain": "Neglect is deprivation — of food, health care, safe health habits, education, play, or physical and emotional care."},
 ],
}
