# Module 12 (part 2 of 2) — Responding to GBV and Harmful Practices
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 12.
# Trilingual: English / Kiswahili / Sheng.
#
# TONE NOTE: the deck's prevention section is framed around personal safety
# steps. Those are included faithfully, but with an explicit statement that
# responsibility never transfers to the survivor — otherwise the section reads
# as blame to anyone in the room who has already been harmed.

LESSON = {
 "file": "m12b-responding-to-gbv.html",
 "module_code": "M12",
 "module_slug": "gender-based-violence",
 "lesson_slug": "m12b-responding-to-gbv",
 "module_label": "Peer Educator · M12 · Part 2 of 2",
 "title": "Responding to GBV and Harmful Practices",
 "icon": "🆘",
 "duration": 60,

 "objectives": [
  ("Describe what to do immediately after sexual violence",
   "Eleza la kufanya mara baada ya ukatili wa kingono",
   "Describe la kufanya mara baada ya sexual violence"),
  ("Explain the 72-hour window and what post-rape care provides",
   "Eleza muda wa saa 72 na huduma baada ya ubakaji inatoa nini",
   "Explain window ya masaa 72 na post-rape care inatoa nini"),
  ("Describe ways to prevent GBV without shifting blame to survivors",
   "Eleza njia za kuzuia ukatili bila kuhamisha lawama kwa manusura",
   "Describe njia za ku-prevent GBV bila kuhamisha blame kwa survivors"),
  ("Discuss harmful practices — FGM, child marriage and child labour — and their impact",
   "Jadili mila hatari — ukeketaji, ndoa za utotoni na ajira ya watoto — na athari zake",
   "Discuss harmful practices — FGM, child marriage na child labour — na impact zake"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> A survivor's first instinct is almost always to wash. Why is the most natural thing to do also the one that costs them most?",
  "<strong>🔍 Swali Kubwa:</strong> Hisia ya kwanza ya manusura karibu daima ni kuoga. Kwa nini jambo la asili zaidi kufanya ndilo linalowagharimu zaidi?",
  "<strong>🔍 Big Question:</strong> Instinct ya kwanza ya survivor karibu daima ni kuoga. Kwa nini kitu cha natural zaidi kufanya ndio kinachowagharimu zaidi?"),

 "slides": [

  # ── 1. The first hour ─────────────────────────────────────────────
  {"icon": "🕐",
   "head": ("The First Hour", "Saa ya Kwanza", "Hour ya Kwanza"),
   "blocks": [
    {"type": "p", "text": (
     "If someone tells you they have just been raped or defiled, these are the things that matter in the first hour. Know them well enough to say them calmly.",
     "Mtu akikuambia amebakwa au kudhalilishwa hivi punde, haya ndiyo mambo muhimu katika saa ya kwanza. Yajue vizuri vya kutosha kuyasema kwa utulivu.",
     "Msee akikuambia amebakwa ama kudhalilishwa saa hii, haya ndio mambo muhimu kwa hour ya kwanza. Yajue vizuri enough kuyasema kwa utulivu.")},
    {"type": "list", "ordered": True, "items": [
     ("<strong>Talk to someone immediately.</strong> That has already happened — they told you. Do not send them away to think about it.",
      "<strong>Zungumza na mtu mara moja.</strong> Hilo tayari limetokea — walikuambia. Usiwaache waende kufikiria.",
      "<strong>Ongea na msee mara moja.</strong> Hiyo tayari ime-happen — walikuambia. Usiwaache waende kufikiria."),
     ("<strong>Do not bath or change clothes.</strong> This is the hardest thing to ask and the most important.",
      "<strong>Usioge wala kubadilisha nguo.</strong> Hili ndilo gumu zaidi kuomba na muhimu zaidi.",
      "<strong>Usioge wala kubadilisha nguo.</strong> Hii ndio ngumu zaidi kuomba na muhimu zaidi."),
     ("<strong>Do not pass urine or stool if it can be avoided.</strong> Same reason.",
      "<strong>Usikojoe wala kwenda haja kubwa ikiwezekana.</strong> Sababu ile ile.",
      "<strong>Usikojoe wala kwenda haja kubwa ikiwezekana.</strong> Sababu hiyo hiyo."),
     ("<strong>Preserve whatever evidence there is</strong> — clothing, bedding, anything at the scene.",
      "<strong>Hifadhi ushahidi wowote uliopo</strong> — nguo, matandiko, chochote eneo la tukio.",
      "<strong>Preserve evidence yoyote iliyopo</strong> — nguo, bedding, chochote kwa scene."),
     ("<strong>Get to a safe space.</strong> Away from the person who did it, and away from anyone protecting them.",
      "<strong>Fika mahali salama.</strong> Mbali na aliyefanya, na mbali na yeyote anayemlinda.",
      "<strong>Fika safe space.</strong> Mbali na aliyefanya, na mbali na yeyote anayem-protect."),
     ("<strong>Go to the nearest health facility.</strong> Today. Not tomorrow.",
      "<strong>Nenda kituo cha afya cha karibu.</strong> Leo. Si kesho.",
      "<strong>Nenda health facility ya karibu.</strong> Leo. Si kesho."),
    ]},
    {"type": "tip", "title": ("💡 How to ask someone not to wash", "💡 Jinsi ya kumwomba mtu asioge", "💡 Jinsi ya kumwomba msee asioge"), "text": (
     " Say why, not just what. 'I know you want to wash — anyone would. But what's on you right now is the evidence, and once it's gone nobody can get it back. Can we go first, and then you wash there?' Explaining the reason is what makes it bearable.",
     " Sema kwa nini, si tu nini. 'Najua unataka kuoga — yeyote angetaka. Lakini kilicho juu yako sasa ndio ushahidi, na kikienda hakuna anayeweza kukirudisha. Twende kwanza, kisha uoge huko?' Kueleza sababu ndiko kunakofanya iwezekane.",
     " Sema kwa nini, si tu nini. 'Najua unataka kuoga — yeyote angetaka. Lakini kilicho juu yako saa hii ndio evidence, na kikienda hakuna anayeweza kukirudisha. Twende kwanza, kisha uoge kule?' Ku-explain reason ndio inafanya iwezekane.")},
   ]},

  # ── 2. Post-rape care ─────────────────────────────────────────────
  {"icon": "🏥",
   "head": ("Post-Rape Care and the 72-Hour Window", "Huduma Baada ya Ubakaji na Muda wa Saa 72", "Post-Rape Care na Window ya Masaa 72"),
   "blocks": [
    {"type": "p", "text": (
     "Post-rape care is given to anyone who has been through any form of sexual violence. It should be sought <strong>as soon as possible, and within 72 hours</strong>.",
     "Huduma baada ya ubakaji hutolewa kwa yeyote aliyepitia aina yoyote ya ukatili wa kingono. Inapaswa kutafutwa <strong>haraka iwezekanavyo, na ndani ya saa 72</strong>.",
     "Post-rape care inatolewa kwa yeyote aliyepitia aina yoyote ya sexual violence. Inafaa kutafutwa <strong>haraka iwezekanavyo, na ndani ya masaa 72</strong>.")},
    {"type": "table",
     "headers": [("Care provided", "Huduma inayotolewa", "Care inayotolewa"), ("Why it matters", "Kwa nini ni muhimu", "Kwa nini ni muhimu")],
     "rows": [
      [("Pregnancy prevention", "Kuzuia mimba", "Pregnancy prevention"),
       ("Prevents unintended pregnancy", "Huzuia mimba isiyotarajiwa", "Ina-prevent unintended pregnancy")],
      [("HIV prevention (PEP)", "Kuzuia VVU (PEP)", "HIV prevention (PEP)"),
       ("Reduces the chance of HIV infection — this is the 72-hour medicine from M13B",
        "Hupunguza uwezekano wa kuambukizwa VVU — hii ndiyo dawa ya saa 72 kutoka M13B",
        "Inapunguza chance ya HIV infection — hii ndio dawa ya masaa 72 kutoka M13B")],
      [("Treatment of physical injuries", "Matibabu ya majeraha", "Treatment ya injuries"),
       ("Promotes healing and reduces pain", "Husaidia kupona na kupunguza maumivu", "Inasaidia healing na kupunguza pain")],
      [("STI prevention and management", "Kuzuia na kudhibiti magonjwa ya zinaa", "STI prevention na management"),
       ("Protects from other infections", "Hulinda dhidi ya maambukizi mengine", "Inalinda dhidi ya infections zingine")],
      [("Hepatitis B and tetanus prevention", "Kuzuia homa ya ini B na pepopunda", "Hepatitis B na tetanus prevention"),
       ("Prevents additional disease", "Huzuia magonjwa ya ziada", "Ina-prevent magonjwa ya ziada")],
      [("Psychosocial support", "Msaada wa kisaikolojia", "Psychosocial support"),
       ("Helps the survivor cope emotionally and mentally", "Humsaidia manusura kukabiliana kihisia na kiakili", "Inamsaidia survivor ku-cope emotionally na mentally")],
      [("Collection of evidence", "Ukusanyaji wa ushahidi", "Collection ya evidence"),
       ("Important for court and for justice", "Muhimu kwa mahakama na haki", "Muhimu kwa court na justice")],
      [("Linkage to safe spaces", "Kuunganishwa na maeneo salama", "Linkage kwa safe spaces"),
       ("Provides safety and protection", "Hutoa usalama na ulinzi", "Inatoa safety na protection")],
      [("Referral to legal and police support", "Rufaa kwa msaada wa kisheria na polisi", "Referral kwa legal na police support"),
       ("Helps the survivor get justice", "Humsaidia manusura kupata haki", "Inamsaidia survivor kupata justice")],
     ]},
    {"type": "warn", "title": ("⚠️ Care is not conditional on reporting", "⚠️ Huduma haitegemei kuripoti", "⚠️ Care hai-dependi na kuripoti"), "text": (
     " A survivor can receive medical care without going to the police. Reporting is their decision and can follow later — but the medicine cannot. Never let 'I don't want to report' become a reason not to go to the facility.",
     " Manusura anaweza kupata matibabu bila kwenda polisi. Kuripoti ni uamuzi wake na kunaweza kufuata baadaye — lakini dawa haiwezi. Usiruhusu kamwe 'sitaki kuripoti' kuwa sababu ya kutokwenda kituoni.",
     " Survivor anaweza kupata medical care bila kuenda polisi. Kuripoti ni decision yake na inaweza kufollow baadaye — lakini dawa haiwezi. Usiruhusu kamwe 'sitaki kuripoti' kuwa sababu ya kutokuenda facility.")},
   ]},

  # ── 3. Your role ──────────────────────────────────────────────────
  {"icon": "🚧",
   "head": ("Your Role, and Its Limits", "Jukumu Lako, na Mipaka Yake", "Role Yako, na Limits Zake"),
   "blocks": [
    {"type": "table",
     "headers": [("You do", "Wewe fanya", "Wewe fanya"), ("You do not", "Wewe usifanye", "Wewe usifanye")],
     "rows": [
      [("Listen without judgement and believe them",
        "Sikiliza bila kuhukumu na uwaamini",
        "Listen bila kujudge na uwabelieve"),
       ("Investigate, or ask for details you do not need",
        "Chunguza, au kuomba maelezo usiyohitaji",
        "Ku-investigate, ama kuomba details usizohitaji")],
      [("Explain the 72-hour window plainly",
        "Eleza muda wa saa 72 kwa uwazi",
        "Explain window ya masaa 72 kwa uwazi"),
       ("Examine any injury, or offer medical advice",
        "Kuchunguza jeraha lolote, au kutoa ushauri wa matibabu",
        "Ku-examine injury yoyote, ama kutoa medical advice")],
      [("Go with them to the facility if they want",
        "Nenda nao kituoni wakitaka",
        "Enda nao facility wakitaka"),
       ("Confront or contact the person who did it",
        "Kumkabili au kuwasiliana na aliyefanya",
        "Ku-confront ama ku-contact aliyefanya")],
      [("Escalate to your supervising adult the same day",
        "Peleka kwa mtu mzima anayekusimamia siku hiyo hiyo",
        "Escalate kwa msimamizi wako siku hiyo hiyo"),
       ("Promise to keep it secret",
        "Kuahidi kuiweka siri",
        "Ku-promise kuiweka secret")],
      [("Record the referral and follow it up (Module 16)",
        "Rekodi rufaa na uifuatilie (Moduli 16)",
        "Record referral na uifollow up (Module 16)"),
       ("Discuss it with other peers, ever",
        "Kulijadili na wenzako, kamwe",
        "Ku-discuss na wasee wengine, kamwe")],
     ]},
    {"type": "warn", "title": ("⚠️ Never promise secrecy before you have heard it", "⚠️ Usiahidi siri kabla hujasikia", "⚠️ Usi-promise secrecy kabla hujasikia"), "text": (
     " If someone says 'promise you won't tell', the honest answer is: 'I won't gossip about this. But if you're in danger, I can't carry it alone — and I'll tell you before I tell anyone.' Promising first and breaking it later destroys trust far more than being honest up front.",
     " Mtu akisema 'ahidi hutasema', jibu la ukweli ni: 'Sitasengenya kuhusu hili. Lakini ukiwa hatarini, siwezi kulibeba peke yangu — na nitakuambia kabla sijamwambia mtu.' Kuahidi kwanza na kuvunja baadaye huharibu imani kuliko kuwa mkweli mwanzoni.",
     " Msee akisema 'promise hutasema', honest answer ni: 'Sitagossip kuhusu hii. Lakini ukiwa hatarini, siwezi kuibeba peke yangu — na nitakuambia kabla nimwambie mtu.' Ku-promise kwanza na kuvunja baadaye inaharibu trust kuliko kuwa honest mwanzoni.")},
   ]},

  # ── 4. Prevention ─────────────────────────────────────────────────
  {"icon": "🧭",
   "head": ("Prevention — and Who It Belongs To", "Kuzuia — na Ni Jukumu la Nani", "Prevention — na Ni Jukumu la Nani"),
   "blocks": [
    {"type": "warn", "title": ("⚠️ Read this before the list", "⚠️ Soma hili kabla ya orodha", "⚠️ Soma hii kabla ya list"), "text": (
     " Everything below reduces risk. <strong>None of it transfers blame.</strong> If someone did all of it and was still harmed, the fault is entirely the perpetrator's. Say this out loud before you teach the list, every single time — someone in the room needs to hear it.",
     " Kila kilicho hapa chini hupunguza hatari. <strong>Hakuna kinachohamisha lawama.</strong> Mtu akifanya yote na bado akadhurika, kosa ni la mtendaji kabisa. Sema hili kwa sauti kabla ya kufundisha orodha, kila mara — mtu chumbani anahitaji kulisikia.",
     " Kila kilicho hapa chini kinapunguza risk. <strong>Hakuna kinachohamisha blame.</strong> Msee akifanya yote na bado adhurike, kosa ni la perpetrator kabisa. Sema hii kwa sauti kabla ufundishe list, kila time — msee kwa room anahitaji kuisikia.")},
    {"type": "list", "items": [
     ("Think about your safety — avoid places you consider unsafe, secluded areas or empty buildings",
      "Fikiria usalama wako — epuka maeneo unayoyaona si salama, sehemu za faragha au majengo tupu",
      "Fikiria safety yako — avoid places unazoona si safe, secluded areas ama empty buildings"),
     ("Avoid being at someone's home when no parents or adults are there",
      "Epuka kuwa nyumbani kwa mtu wakati hakuna wazazi au watu wazima",
      "Avoid kuwa nyumbani kwa msee wakati hakuna wazazi ama watu wazima"),
     ("Make sure someone knows where you are going, who with, and when you will be back",
      "Hakikisha mtu anajua unakoenda, na nani, na utarudi lini",
      "Hakikisha msee anajua unakoenda, na nani, na utarudi lini"),
     ("Be careful about gifts from people — it can be a trap",
      "Kuwa mwangalifu na zawadi kutoka kwa watu — inaweza kuwa mtego",
      "Kuwa careful na gifts kutoka kwa wasee — inaweza kuwa trap"),
     ("Avoid drugs and substance use — they remove your ability to read a situation",
      "Epuka dawa za kulevya — huondoa uwezo wako wa kutathmini hali",
      "Avoid drugs na substance use — zinaondoa uwezo wako wa ku-read situation"),
     ("Be firm saying no to any inappropriate behaviour or advance",
      "Kuwa imara kusema hapana kwa tabia au ushawishi wowote usiofaa",
      "Kuwa firm kusema no kwa behaviour ama advance yoyote isiyofaa"),
     ("Flee if you can, or scream for help",
      "Kimbia ukiweza, au piga kelele kuomba msaada",
      "Kimbia ukiweza, ama piga kelele kuomba msaada"),
     ("Go out as a group and be each other's safe keeper",
      "Nendeni kama kikundi na mlindane",
      "Endeni kama group na mlindane"),
    ]},
   ]},

  # ── 5. FGM ────────────────────────────────────────────────────────
  {"icon": "🚫",
   "head": ("Harmful Practices — FGM", "Mila Hatari — Ukeketaji", "Harmful Practices — FGM"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Harmful practices", "🔑 Mila hatari", "🔑 Harmful practices"), "text": (
     "Behaviours, attitudes or practices that negatively affect the fundamental rights of adolescents — their right to life, health, dignity, education and physical integrity.",
     "Tabia, mitazamo au mila zinazoathiri vibaya haki za msingi za vijana — haki yao ya kuishi, afya, hadhi, elimu na uadilifu wa mwili.",
     "Behaviours, attitudes ama practices zinazoathiri vibaya fundamental rights za vijana — right yao ya kuishi, health, dignity, education na physical integrity.")},
    {"type": "p", "text": (
     "Female genital mutilation is the removal of part or all of the female private parts for non-medical reasons.",
     "Ukeketaji ni kuondoa sehemu au yote ya viungo vya siri vya mwanamke kwa sababu zisizo za kimatibabu.",
     "FGM ni kuondoa part ama yote ya female private parts kwa sababu zisizo za kimatibabu.")},
    {"type": "list", "items": [
     ("<strong>Risks:</strong> heavy blood loss, infections, risk of contracting HIV, and sexual and childbirth complications",
      "<strong>Hatari:</strong> kupoteza damu nyingi, maambukizi, hatari ya kuambukizwa VVU, na matatizo ya kingono na ya kujifungua",
      "<strong>Risks:</strong> kupoteza damu nyingi, infections, risk ya ku-contract HIV, na sexual na childbirth complications"),
     ("<strong>There is an alternative.</strong> Girls can go through Alternative Rites of Passage to mark the transition into adulthood — a coming-of-age ceremony, family or community celebration, or a training programme.",
      "<strong>Kuna mbadala.</strong> Wasichana wanaweza kupitia Mila Mbadala za Kuvuka kuadhimisha kuingia utu uzima — sherehe ya kuvuka, sherehe ya familia au jamii, au programu ya mafunzo.",
      "<strong>Kuna alternative.</strong> Wasichana wanaweza kupitia Alternative Rites of Passage ku-mark transition kuingia utu uzima — coming-of-age ceremony, family ama community celebration, ama training programme."),
    ]},
    {"type": "tip", "title": ("💡 Why the alternative matters in the conversation", "💡 Kwa nini mbadala ni muhimu kwenye mazungumzo", "💡 Kwa nini alternative ni muhimu kwa conversation"), "text": (
     " Families who practise FGM are usually trying to mark something real — that a girl has become a woman, and belongs. Attacking the belonging wins nothing. Offering a way to mark it that does not cut is what actually shifts communities.",
     " Familia zinazofanya ukeketaji kwa kawaida hujaribu kuadhimisha jambo halisi — kwamba msichana amekuwa mwanamke, na ni wa jamii. Kushambulia hali hiyo hakushindi chochote. Kutoa njia ya kuadhimisha isiyokata ndiyo inayobadilisha jamii kweli.",
     " Families zinazofanya FGM kwa kawaida zina-try ku-mark kitu real — ati dem amekuwa mwanamke, na ni wa community. Ku-attack hiyo belonging haishindi kitu. Kutoa njia ya ku-mark isiyokata ndio ina-shift communities kweli.")},
   ]},

  # ── 6. Child marriage & labour ────────────────────────────────────
  {"icon": "⚖️",
   "head": ("Child Marriage and Child Labour", "Ndoa za Utotoni na Ajira ya Watoto", "Child Marriage na Child Labour"),
   "blocks": [
    {"type": "table",
     "headers": [("", "", ""), ("Child marriage", "Ndoa za utotoni", "Child marriage"), ("Child labour", "Ajira ya watoto", "Child labour")],
     "rows": [
      [("What it is", "Ni nini", "Ni nini"),
       ("<strong>Marriage before 18 is illegal in Kenya.</strong>", "<strong>Ndoa kabla ya miaka 18 ni haramu Kenya.</strong>", "<strong>Marriage kabla ya 18 ni illegal Kenya.</strong>"),
       ("Work done for wages by children aged 5 to 17", "Kazi inayofanywa kwa malipo na watoto wa miaka 5 hadi 17", "Kazi inayofanywa kwa wages na watoto wa miaka 5 hadi 17")],
      [("Why it harms", "Kwa nini inadhuru", "Kwa nini inadhuru"),
       ("Pregnancy and childbirth complications, school dropout, STI and HIV infection, and GBV",
        "Matatizo ya ujauzito na kujifungua, kuacha shule, maambukizi ya zinaa na VVU, na ukatili wa kijinsia",
        "Pregnancy na childbirth complications, school dropout, STI na HIV infection, na GBV"),
       ("Prevents normal growth and development, and takes the child out of school",
        "Huzuia ukuaji na maendeleo ya kawaida, na humtoa mtoto shuleni",
        "Inazuia normal growth na development, na inamtoa mtoto shuleni")],
      [("What to say", "Cha kusema", "Cha kusema"),
       ("Marrying at the right time lets you finish your education and lets your body finish growing",
        "Kuoa au kuolewa wakati sahihi kunakuwezesha kumaliza elimu na mwili wako kukamilisha kukua",
        "Ku-marry wakati sahihi kunakuwezesha kumaliza education na mwili wako kukamilisha kukua"),
       ("If someone wants to take you out of school to give you work, do not accept — report them to a teacher, parent or guardian",
        "Mtu akitaka kukutoa shuleni akupe kazi, usikubali — mripoti kwa mwalimu, mzazi au mlezi",
        "Msee akitaka kukutoa shuleni akupe kazi, usikubali — m-report kwa teacher, mzazi ama guardian")],
     ]},
    {"type": "list", "items": [
     ("<strong>Talk openly</strong> about harmful practices so the community can find solutions that fit it",
      "<strong>Zungumza wazi</strong> kuhusu mila hatari ili jamii ipate suluhisho zinazoifaa",
      "<strong>Ongea wazi</strong> kuhusu harmful practices ili community ipate solutions zinazoifit"),
     ("<strong>Report</strong> any harmful practice you know is happening",
      "<strong>Ripoti</strong> mila hatari yoyote unayojua inaendelea",
      "<strong>Report</strong> harmful practice yoyote unayojua inaendelea"),
     ("<strong>Encourage friends</strong> to share information and teach others why these practices harm",
      "<strong>Wahimize marafiki</strong> kushiriki taarifa na kuwafundisha wengine kwa nini mila hizi hudhuru",
      "<strong>Encourage friends</strong> kushare info na kuwafundisha wengine kwa nini hizi practices zinadhuru"),
     ("<strong>Take part in safe alternative rites of passage</strong> where community programmes offer them",
      "<strong>Shiriki katika mila mbadala salama za kuvuka</strong> pale programu za jamii zinapozitoa",
      "<strong>Shiriki kwa safe alternative rites of passage</strong> pale community programmes zinapozitoa"),
     ("<strong>Male circumcision as a rite of passage does not mean starting sex</strong> — that link is a myth worth breaking out loud",
      "<strong>Tohara ya kiume kama mila ya kuvuka haimaanishi kuanza ngono</strong> — uhusiano huo ni imani potofu inayostahili kuvunjwa kwa sauti",
      "<strong>Male circumcision kama rite of passage haimaanishi kuanza sex</strong> — hiyo link ni myth inayostahili kuvunjwa kwa sauti"),
    ]},
   ]},

  # ── 7. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A friend calls you an hour after being raped. She is already in the shower. She says she cannot bear to be dirty and she does not want to go to any hospital.",
      "Rafiki anakupigia simu saa moja baada ya kubakwa. Tayari yuko bafuni. Anasema hawezi kuvumilia kuwa mchafu na hataki kwenda hospitali yoyote.",
      "Friend anakupigia call hour moja baada ya kubakwa. Tayari yuko shower. Anasema hawezi ku-bear kuwa mchafu na hataki kuenda hospital yoyote."),
     "question": ("What matters most in this call?", "Nini ni muhimu zaidi kwenye simu hii?", "Nini ni muhimu zaidi kwa hii call?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell her firmly to stop washing immediately because she is destroying evidence",
                "Mwambie kwa ukali aache kuoga mara moja kwa sababu anaharibu ushahidi",
                "Mwambie firmly aache kuoga mara moja kwa sababu anaharibu evidence"),
       "outcome": ("Being ordered, an hour after an assault, by someone focused on evidence rather than on her, is likely to end the call. The evidence matters — but she is already in the shower, and the medicine still works whether or not she washed.",
                   "Kuamriwa, saa moja baada ya shambulio, na mtu anayejali ushahidi badala yake, kunaweza kumaliza simu. Ushahidi ni muhimu — lakini tayari yuko bafuni, na dawa bado hufanya kazi awe ameoga au la.",
                   "Ku-orderiwa, hour moja baada ya assault, na msee anayefocus kwa evidence badala yake, inaweza ku-end call. Evidence ni muhimu — lakini tayari yuko shower, na dawa bado inawork awe ameoga ama la.")},
      {"kind": "good",
       "text": ("Focus on getting her to care today — the medicine works regardless of the shower",
                "Zingatia kumfikisha kwenye huduma leo — dawa hufanya kazi bila kujali kuoga",
                "Focus kumfikisha kwa care leo — dawa inawork bila kujali shower"),
       "outcome": ("You said: 'You're allowed to wash. That doesn't stop anything that matters today — there's medicine that prevents HIV and pregnancy and it works for three days. That's the bit we can't lose. I'll come to you and we'll go together, and you don't have to talk to police at all if you don't want to.' She went. ✅",
                   "Ulisema: 'Unaruhusiwa kuoga. Hilo halizuii chochote muhimu leo — kuna dawa inayozuia VVU na mimba na hufanya kazi kwa siku tatu. Hicho ndicho hatuwezi kupoteza. Nitakuja kwako na tutaenda pamoja, na huhitaji kuzungumza na polisi kabisa usipotaka.' Alienda. ✅",
                   "Ulisema: 'Unaruhusiwa kuoga. Hiyo hai-stop kitu muhimu leo — kuna dawa inayozuia HIV na pregnancy na inawork kwa siku tatu. Hicho ndio hatuwezi kupoteza. Nitakuja kwako na tutaenda pamoja, na huhitaji kuongea na polisi kabisa usipotaka.' Alienda. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A 14-year-old in your community is being prepared for a cutting ceremony next month. Her grandmother says it is how girls in the family have always become women.",
      "Msichana wa miaka 14 katika jamii yako anaandaliwa kwa sherehe ya kukeketwa mwezi ujao. Bibi yake anasema ndivyo wasichana wa familia hiyo wamekuwa wanawake daima.",
      "Dem wa miaka 14 kwa community yako ana-prepariwa kwa cutting ceremony mwezi ujao. Grandmother wake anasema ndio jinsi wasichana wa hiyo family wamekuwa wanawake daima."),
     "question": ("What is the most effective thing you can do?", "Ni lipi jambo lenye ufanisi zaidi unaloweza kufanya?", "Ni kitu gani chenye effectiveness zaidi unachoweza kufanya?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell the grandmother the practice is barbaric and illegal, in front of the family",
                "Mwambie bibi kwamba mila hiyo ni ya kikatili na haramu, mbele ya familia",
                "Mwambie grandmother ati hiyo practice ni barbaric na illegal, mbele ya family"),
       "outcome": ("Publicly shaming an elder hardens the family and closes your access. The ceremony still happens — just without anyone who might have intervened being told the date. Being right in the wrong way protects nobody.",
                   "Kumwaibisha mzee hadharani hufanya familia iwe ngumu na kufunga ufikiaji wako. Sherehe bado hutokea — tu bila yeyote ambaye angeweza kuingilia kuambiwa tarehe. Kuwa sahihi kwa njia isiyofaa hakumlindi mtu.",
                   "Ku-shame elder publicly inafanya family iwe ngumu na inafunga access yako. Ceremony bado inahappen — tu bila yeyote ambaye angeweza ku-intervene kuambiwa date. Kuwa sahihi kwa njia mbaya hai-protect mtu.")},
      {"kind": "good",
       "text": ("Escalate to your supervising adult, and raise alternative rites of passage as the way to keep the ceremony without the cutting",
                "Peleka kwa mtu mzima anayekusimamia, na uibue mila mbadala za kuvuka kama njia ya kubaki na sherehe bila kukata",
                "Escalate kwa msimamizi wako, na u-raise alternative rites of passage kama njia ya ku-keep ceremony bila cutting"),
       "outcome": ("A child at imminent risk goes to your supervising adult — that part is not optional. Alongside it, offering an Alternative Rite of Passage gives the family a way to keep what they actually wanted: marking that she has grown up, and belongs. ✅",
                   "Mtoto aliye hatarini mara moja huenda kwa mtu mzima anayekusimamia — sehemu hiyo si ya hiari. Pamoja na hilo, kutoa Mila Mbadala ya Kuvuka huipa familia njia ya kubaki na walichotaka kweli: kuadhimisha kwamba amekua, na ni wao. ✅",
                   "Mtoto aliye kwa imminent risk anaenda kwa msimamizi wako — hiyo part si optional. Pamoja na hiyo, kutoa Alternative Rite of Passage inaipa family njia ya ku-keep walichotaka kweli: ku-mark ati amekua, na ni wao. ✅")},
     ]},
   ]},

  # ── 8. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("All survivors of GBV need to seek urgent care.",
      "Manusura wote wa ukatili wa kijinsia wanahitaji kutafuta huduma ya haraka.",
      "Survivors wote wa GBV wanahitaji kutafuta urgent care."),
     ("Survivors of sexual violence should reach a hospital within 72 hours.",
      "Manusura wa ukatili wa kingono wanapaswa kufika hospitali ndani ya saa 72.",
      "Survivors wa sexual violence wanafaa kufika hospital ndani ya masaa 72."),
     ("Medical care does not depend on reporting to police — that decision is the survivor's, and can come later.",
      "Matibabu hayategemei kuripoti polisi — uamuzi huo ni wa manusura, na unaweza kuja baadaye.",
      "Medical care hai-dependi na kuripoti polisi — hiyo decision ni ya survivor, na inaweza kuja baadaye."),
     ("Prevention starts with awareness and action: trust your instincts, say NO to unwanted contact, report abuse, and speak out against harmful practices.",
      "Kuzuia huanza na uelewa na hatua: amini hisia zako, sema HAPANA kwa mguso usiotakikana, ripoti unyanyasaji, na pinga mila hatari.",
      "Prevention inaanza na awareness na action: trust instincts zako, sema NO kwa unwanted contact, report abuse, na pinga harmful practices."),
     ("Responsibility never sits with the survivor. It sits with the person who chose to cause harm.",
      "Lawama kamwe si ya manusura. Ni ya aliyechagua kudhuru.",
      "Responsibility kamwe si ya survivor. Ni ya aliye-choose kudhuru."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Hutaweza kubatilisha kilichotokea. Lakini saa 72 zijazo bado zinaweza kubadilishwa — na hapo ndipo wewe uko.",
     "Hutaweza kubatilisha kilichotokea. Lakini saa 72 zijazo bado zinaweza kubadilishwa — na hapo ndipo wewe upo.",
     "Huwezi ku-undo kilicho-happen. Lakini masaa 72 yanayokuja bado yanaweza ku-changiwa — na hapo ndio wewe uko.")},
   ]},
 ],

 "quiz": [
  {"q": "Within what time should a survivor of sexual violence reach a health facility?",
   "options": ["24 hours", "72 hours", "One week", "One month"],
   "answer": "B",
   "explain": "As soon as possible, and within 72 hours — the same window as PEP in Module 13B."},

  {"q": "Which should a survivor avoid doing immediately after sexual violence? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Bathing or washing",
               "Changing clothes",
               "Talking to someone they trust",
               "Passing urine or stool, if it can be avoided"],
   "answer": ["A", "B", "D"],
   "explain": "Talking to someone immediately is exactly what they SHOULD do. The other three can destroy evidence."},

  {"q": "A survivor says she does not want to go to the police. What follows?",
   "options": ["Without a police report she cannot receive medical care",
               "Medical care is not conditional on reporting — reporting is her decision and can come later",
               "You should report on her behalf",
               "She must decide within 24 hours"],
   "answer": "B",
   "explain": "Never let 'I don't want to report' become a reason not to go to the facility. The medicine has a deadline; the report does not."},

  {"q": "Which are part of post-rape care? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["HIV prevention",
               "Pregnancy prevention",
               "Psychosocial support",
               "Collection of evidence",
               "Arresting the perpetrator"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Arrest is a police matter. Post-rape care is the clinical and support package, which includes referral to legal and police support."},

  {"q": "A peer says 'promise you won't tell anyone'. What is the honest response?",
   "options": ["Promise, so they open up",
               "Refuse to listen unless they agree you can tell",
               "Say you will not gossip, but cannot carry it alone if they are in danger — and will tell them before telling anyone",
               "Promise, then tell your supervisor anyway"],
   "answer": "C",
   "explain": "Promising first and breaking it later destroys trust far more than being honest up front."},

  {"q": "What does the curriculum say about responsibility for GBV?",
   "options": ["It is shared when the survivor took risks",
               "It lies entirely with the person who chose to cause harm",
               "It depends on the circumstances",
               "It lies with the community"],
   "answer": "B",
   "explain": "Safety advice reduces risk. It never transfers blame — and that must be said out loud before teaching any prevention list."},

  {"q": "What is an Alternative Rite of Passage?",
   "options": ["A medical form of FGM performed safely",
               "A ceremony, celebration or training programme marking the transition to adulthood without cutting",
               "A legal exemption for certain communities",
               "A ceremony performed after the age of 18"],
   "answer": "B",
   "explain": "It preserves what the family actually wanted — marking that she has grown up and belongs — without the cutting."},

  {"q": "Which are risks of FGM named in the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Heavy blood loss",
               "Infections",
               "Risk of contracting HIV",
               "Sexual and childbirth complications",
               "Improved fertility"],
   "answer": ["A", "B", "C", "D"],
   "explain": "FGM carries no health benefit whatsoever. It is defined as removal for non-medical reasons."},

  {"q": "In Kenya, marriage before the age of 18:",
   "options": ["Is legal with parental consent",
               "Is illegal",
               "Is legal from age 16",
               "Depends on the county"],
   "answer": "B",
   "explain": "It is illegal, and carries pregnancy and childbirth complications, school dropout, STI and HIV infection, and GBV."},

  {"q": "A grandmother is preparing a 14-year-old for a cutting ceremony. What is the most effective response?",
   "options": ["Publicly tell her the practice is barbaric and illegal",
               "Escalate to your supervising adult, and offer an Alternative Rite of Passage",
               "Say nothing — it is a family matter",
               "Wait until after the ceremony and then report"],
   "answer": "B",
   "explain": "A child at imminent risk is escalated — that is not optional. Publicly shaming an elder just closes your access while the ceremony goes ahead anyway."},
 ],
}
