# Module 13A — STIs, HIV and AHD in Early Adolescents (10–14 years)
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 13A.
# Trilingual: English / Kiswahili / Sheng.
#
# AGE NOTE: the deck deliberately pitches 13A younger than 13B. This lesson
# follows that: simpler sentences, transmission taught mainly through blood,
# sharps and mother-to-baby, heavy emphasis on what does NOT transmit, and on
# kindness rather than clinical detail. Facilitators running it for the older
# end of the band should use M13B instead.

LESSON = {
 "file": "m13a-stis-hiv-early-adolescents.html",
 "module_code": "M13A",
 "module_slug": "stis-hiv-early-adolescents",
 "lesson_slug": "m13a-stis-hiv-early-adolescents",
 "module_label": "Peer Educator · M13A · Ages 10–14",
 "title": "STIs and HIV — Ages 10 to 14",
 "icon": "🎗️",
 "duration": 60,

 "objectives": [
  ("Define STIs, how they spread and how they do not spread",
   "Fafanua magonjwa ya zinaa, jinsi yanavyoenea na jinsi yasivyoenea",
   "Define STIs, jinsi zinavyospread na jinsi hazispread"),
  ("Outline prevention, and what to do if you think you have an STI",
   "Eleza kinga, na la kufanya ukidhani una ugonjwa wa zinaa",
   "Outline prevention, na la kufanya ukifikiri una STI"),
  ("Explain the basic facts about HIV and Advanced HIV Disease",
   "Eleza ukweli wa msingi kuhusu VVU na Ugonjwa wa VVU wa Hali ya Juu",
   "Explain basic facts kuhusu HIV na Advanced HIV Disease"),
  ("Explain why testing matters, and how to live positively with HIV",
   "Eleza kwa nini kupimwa ni muhimu, na jinsi ya kuishi vyema na VVU",
   "Explain kwa nini testing ni muhimu, na jinsi ya kuishi positively na HIV"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> More young people are hurt by what others believe about HIV than by the virus itself. How does that happen?",
  "<strong>🔍 Swali Kubwa:</strong> Vijana wengi hudhurika na yale wengine wanayoamini kuhusu VVU kuliko virusi vyenyewe. Hilo hutokeaje?",
  "<strong>🔍 Big Question:</strong> Vijana wengi wanadhurika na yale wengine wanaamini kuhusu HIV kuliko virus yenyewe. Hiyo inahappen aje?"),

 "slides": [

  {"icon": "📖",
   "head": ("What STIs Are", "Magonjwa ya Zinaa ni Nini", "STIs ni Nini"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Sexually Transmitted Infection (STI)", "🔑 Ugonjwa wa Zinaa", "🔑 Sexually Transmitted Infection (STI)"), "text": (
     "An illness that is mainly passed from one person to another through sexual contact.",
     "Ugonjwa unaopitishwa hasa kutoka kwa mtu mmoja hadi mwingine kwa kugusana kingono.",
     "Ugonjwa unaopitishwa hasa kutoka msee mmoja hadi mwingine kwa sexual contact.")},
    {"type": "list", "items": [
     ("Some STIs can also pass <strong>from a mother to her baby</strong> during pregnancy, birth or breastfeeding",
      "Baadhi ya magonjwa ya zinaa yanaweza pia kupita <strong>kutoka kwa mama hadi mtoto</strong> wakati wa ujauzito, kujifungua au kunyonyesha",
      "Baadhi ya STIs zinaweza pia ku-pass <strong>kutoka mama hadi mtoto</strong> wakati wa pregnancy, kujifungua ama breastfeeding"),
     ("Some can pass <strong>by sharing unclean needles or sharp objects</strong>",
      "Baadhi yanaweza kupita <strong>kwa kushiriki sindano au vitu vyenye ncha kali visivyo safi</strong>",
      "Baadhi zinaweza ku-pass <strong>kwa kushare needles ama sharp objects zisizo safi</strong>"),
     ("If they are not treated, STIs can make people very sick and cause long-term health problems",
      "Yasipotibiwa, magonjwa ya zinaa yanaweza kumfanya mtu mgonjwa sana na kusababisha matatizo ya afya ya muda mrefu",
      "Zisipo-treatiwa, STIs zinaweza kumfanya msee mgonjwa sana na kusababisha long-term health problems"),
    ]},
    {"type": "warn", "title": ("⚠️ The most important fact on this slide", "⚠️ Ukweli muhimu zaidi kwenye slaidi hii", "⚠️ Fact muhimu zaidi kwa hii slide"), "text": (
     " <strong>A person can have an STI without showing any signs at all — and can still pass it to others.</strong> This is why you cannot tell by looking at someone, and why nobody should ever be judged on appearance.",
     " <strong>Mtu anaweza kuwa na ugonjwa wa zinaa bila kuonyesha dalili zozote — na bado akapitisha kwa wengine.</strong> Ndiyo maana huwezi kujua kwa kumtazama mtu, na ndiyo maana hakuna anayepaswa kuhukumiwa kwa muonekano.",
     " <strong>Msee anaweza kuwa na STI bila kuonyesha signs zozote — na bado a-pass kwa wengine.</strong> Ndio maana huwezi kujua kwa kum-look msee, na ndio maana hakuna anayefaa ku-judgiwa kwa appearance.")},
   ]},

  {"icon": "🚫",
   "head": ("How STIs Do NOT Spread", "Jinsi Magonjwa ya Zinaa YASIVYOENEA", "Jinsi STIs HAZISPREAD"),
   "blocks": [
    {"type": "p", "text": (
     "Learn this list properly. Almost every unkind thing done to someone with HIV comes from believing one of these.",
     "Jifunze orodha hii vizuri. Karibu kila jambo baya linalofanywa kwa mwenye VVU linatokana na kuamini mojawapo ya haya.",
     "Jifunze hii list properly. Karibu kila kitu kibaya kinachofanywa kwa msee mwenye HIV kinatokana na kuamini mojawapo ya haya.")},
    {"type": "table",
     "headers": [("❌ You CANNOT get an STI from", "❌ HUWEZI kupata ugonjwa wa zinaa kwa", "❌ HUWEZI kupata STI kwa"),
                 ("❌ Or from", "❌ Au kwa", "❌ Ama kwa")],
     "rows": [
      [("Hugging or shaking hands", "Kukumbatiana au kupeana mikono", "Kukumbatiana ama kupeana mikono"),
       ("Sharing a toilet or bedding", "Kushiriki choo au matandiko", "Kushare choo ama bedding")],
      [("Sharing food", "Kushiriki chakula", "Kushare chakula"),
       ("Bites from mosquitoes or other insects", "Kuumwa na mbu au wadudu wengine", "Kuumwa na mbu ama wadudu wengine")],
      [("Sitting next to someone", "Kukaa karibu na mtu", "Kukaa karibu na msee"),
       ("Swimming in the same water", "Kuogelea maji yale yale", "Kuogelea maji yale yale")],
      [("Sharing the same desk at school", "Kushiriki dawati moja shuleni", "Kushare desk moja shuleni"),
       ("Playing sports together", "Kucheza michezo pamoja", "Kucheza michezo pamoja")],
      [("Breathing the same air", "Kupumua hewa moja", "Kupumua hewa moja"), ("", "", "")],
     ]},
    {"type": "tip", "title": ("💡 The answer to the Big Question", "💡 Jibu la Swali Kubwa", "💡 Jibu la Big Question"), "text": (
     " Every item in that table is something people have actually refused to do with someone living with HIV — sharing a desk, sitting together, eating together. The virus did not cause that. A wrong belief did. Correcting the list is not a small thing; it is the main protection a peer educator can offer someone living with HIV.",
     " Kila kitu katika jedwali hilo ni kitu ambacho watu wamekataa kufanya na mtu anayeishi na VVU — kushiriki dawati, kukaa pamoja, kula pamoja. Virusi havikusababisha hilo. Imani potofu ilisababisha. Kusahihisha orodha si jambo dogo; ndiyo ulinzi mkuu mwelimishaji rika anaweza kumpa mtu anayeishi na VVU.",
     " Kila kitu kwa hiyo table ni kitu ambacho wasee wame-refuse kufanya na msee anayeishi na HIV — kushare desk, kukaa pamoja, kukula pamoja. Virus haikusababisha hiyo. Wrong belief ilisababisha. Ku-correct list si kitu kidogo; ndio main protection peer educator anaweza kumpa msee anayeishi na HIV.")},
   ]},

  {"icon": "🛡️",
   "head": ("Preventing STIs, and What to Do", "Kuzuia Magonjwa ya Zinaa, na La Kufanya", "Ku-prevent STIs, na La Kufanya"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Abstain from sex</strong> — at your age this is the complete answer, and it is not a small thing to choose",
      "<strong>Jizuie na ngono</strong> — katika umri wako hili ndilo jibu kamili, na si jambo dogo kulichagua",
      "<strong>Abstain na sex</strong> — kwa age yako hii ndio complete answer, na si kitu kidogo ku-choose"),
     ("<strong>Do not share sharp objects</strong> — razors, needles, earrings",
      "<strong>Usishiriki vitu vyenye ncha kali</strong> — wembe, sindano, hereni",
      "<strong>Usishare sharp objects</strong> — wembe, needles, earrings"),
     ("<strong>Make safe decisions in risky situations</strong> — using the four steps below",
      "<strong>Fanya maamuzi salama katika hali hatarishi</strong> — ukitumia hatua nne hapa chini",
      "<strong>Fanya safe decisions kwa risky situations</strong> — ukitumia steps nne hapa chini"),
    ]},
    {"type": "table",
     "headers": [("Step", "Hatua", "Step"), ("Ask yourself", "Jiulize", "Jiulize")],
     "rows": [
      [("1. Stop and think", "1. Simama na ufikiri", "1. Stop na ufikiri"),
       ("What could happen here?", "Ni nini kinaweza kutokea hapa?", "Ni nini kinaweza ku-happen hapa?")],
      [("2. Get the facts", "2. Pata ukweli", "2. Pata facts"),
       ("Do I actually know the risks and how to prevent them?", "Je, kweli najua hatari na jinsi ya kuzizuia?", "Je, kweli najua risks na jinsi ya kuzi-prevent?")],
      [("3. Check your values", "3. Angalia maadili yako", "3. Check values zako"),
       ("Does this fit what is right for me?", "Je, hii inaendana na kilicho sahihi kwangu?", "Je, hii ina-fit kilicho sahihi kwangu?")],
      [("4. Choose safety", "4. Chagua usalama", "4. Chagua safety"),
       ("What protects my health now and later?", "Ni nini kinacholinda afya yangu sasa na baadaye?", "Ni nini kinacholinda health yangu saa hii na baadaye?")],
     ]},
    {"type": "example", "title": ("🇰🇪 If you think you have an STI", "🇰🇪 Ukidhani una ugonjwa wa zinaa", "🇰🇪 Ukifikiri una STI"), "text": (
     "Go to any health facility near you and follow what the health worker says. <strong>Remember: STIs can be cured.</strong> Going early is easier than going late, and nobody at the facility is there to judge you.",
     "Nenda kituo chochote cha afya karibu nawe na ufuate anachosema mhudumu wa afya. <strong>Kumbuka: magonjwa ya zinaa yanatibika.</strong> Kwenda mapema ni rahisi kuliko kwenda kuchelewa, na hakuna aliye kituoni kukuhukumu.",
     "Nenda facility yoyote ya afya karibu na wewe na ufuate anachosema health worker. <strong>Kumbuka: STIs zina-cure.</strong> Kwenda mapema ni rahisi kuliko kwenda late, na hakuna msee kwa facility yuko kuku-judge.")},
   ]},

  {"icon": "🦠",
   "head": ("HIV and Advanced HIV Disease", "VVU na Ugonjwa wa VVU wa Hali ya Juu", "HIV na Advanced HIV Disease"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 HIV", "🔑 VVU", "🔑 HIV"), "text": (
     "Human Immunodeficiency Virus. It attacks the immune system — your body's defence army — and weakens it, making it easier for other infections to attack.",
     "Virusi Vya Ukimwi. Hushambulia kinga ya mwili — jeshi la ulinzi la mwili wako — na kuidhoofisha, na kufanya iwe rahisi kwa maambukizi mengine kushambulia.",
     "Human Immunodeficiency Virus. Inashambulia immune system — defence army ya mwili wako — na kui-weaken, ikifanya iwe rahisi kwa infections zingine ku-attack.")},
    {"type": "key_term", "term": ("🔑 AHD — Advanced HIV Disease", "🔑 Ugonjwa wa VVU wa Hali ya Juu", "🔑 AHD — Advanced HIV Disease"), "text": (
     "The final stage of HIV infection, where the immune system is badly damaged and the person becomes sick with many infections.",
     "Hatua ya mwisho ya maambukizi ya VVU, ambapo kinga ya mwili imeharibiwa vibaya na mtu anaugua maambukizi mengi.",
     "Final stage ya HIV infection, ambapo immune system imeharibika vibaya na msee anaugua infections nyingi.")},
    {"type": "table",
     "headers": [("HIV", "VVU", "HIV"), ("AHD", "Hali ya Juu", "AHD")],
     "rows": [
      [("A virus that enters the body and weakens the immune system.",
        "Virusi vinavyoingia mwilini na kudhoofisha kinga.",
        "Virus inayoingia mwilini na ku-weaken immune system."),
       ("The illness that develops after HIV has badly damaged the immune system over time.",
        "Ugonjwa unaokua baada ya VVU kuharibu kinga vibaya baada ya muda.",
        "Ugonjwa unao-develop baada ya HIV kuharibu immune system vibaya baada ya muda.")],
      [("<strong>With treatment, HIV can be controlled and may never lead to AHD.</strong>",
        "<strong>Kwa matibabu, VVU vinaweza kudhibitiwa na visifikie kamwe hali ya juu.</strong>",
        "<strong>Na treatment, HIV inaweza ku-controliwa na isifikie kamwe AHD.</strong>"),
       ("Happens when the immune system is too weak to protect the body from infections.",
        "Hutokea wakati kinga ni dhaifu mno kulinda mwili dhidi ya maambukizi.",
        "Inahappen wakati immune system ni weak sana kulinda mwili dhidi ya infections.")],
     ]},
    {"type": "sheng", "text": (
     "Unaweza kuwa rafiki na mtu mwenye VVU. Mnaweza kushiriki dawati, sahani, chumba na maisha. Hakuna kitakachokupata.",
     "Unaweza kuwa rafiki na mtu mwenye VVU. Mnaweza kushiriki dawati, sahani, chumba na maisha. Hakuna kitakachokupata.",
     "Unaweza kuwa friend na msee mwenye HIV. Mnaweza kushare desk, sahani, room na maisha. Hakuna kitakachokupata.")},
   ]},

  {"icon": "💊",
   "head": ("How HIV Is Prevented", "Jinsi VVU Vinavyozuiwa", "Jinsi HIV Ina-preventiwa"),
   "blocks": [
    {"type": "table",
     "headers": [("Method", "Njia", "Method"), ("What it is", "Ni nini", "Ni nini")],
     "rows": [
      [("<strong>PrEP</strong> — Pre-Exposure Prophylaxis", "<strong>PrEP</strong> — Kinga Kabla ya Kuambukizwa", "<strong>PrEP</strong> — Pre-Exposure Prophylaxis"),
       ("ARV medicine taken by someone who is HIV-negative, to prevent infection. They must test negative before starting. It comes as oral pills, an injection, or a vaginal ring, and is used together with safer behaviour.",
        "Dawa ya ARV inayochukuliwa na mtu asiye na VVU, kuzuia maambukizi. Lazima apimwe akiwa hana kabla ya kuanza. Huja kama vidonge, sindano, au pete ya uke, na hutumika pamoja na tabia salama.",
        "ARV medicine inayochukuliwa na msee asiye na HIV, ku-prevent infection. Lazima a-test negative kabla ya kuanza. Inakuja kama oral pills, injection, ama vaginal ring, na inatumika pamoja na safer behaviour.")],
      [("<strong>PEP</strong> — Post-Exposure Prophylaxis", "<strong>PEP</strong> — Kinga Baada ya Kuambukizwa", "<strong>PEP</strong> — Post-Exposure Prophylaxis"),
       ("ARV medicine taken <strong>within 72 hours</strong> after a possible exposure. They must test negative before starting. <strong>After 72 hours it no longer works.</strong>",
        "Dawa ya ARV inayochukuliwa <strong>ndani ya saa 72</strong> baada ya uwezekano wa kuambukizwa. Lazima apimwe akiwa hana kabla ya kuanza. <strong>Baada ya saa 72 haifanyi kazi tena.</strong>",
        "ARV medicine inayochukuliwa <strong>ndani ya masaa 72</strong> baada ya possible exposure. Lazima a-test negative kabla ya kuanza. <strong>Baada ya masaa 72 hai-work tena.</strong>")],
      [("<strong>PMTCT</strong> — preventing mother-to-child transmission", "<strong>PMTCT</strong> — kuzuia maambukizi kutoka mama kwenda mtoto", "<strong>PMTCT</strong> — ku-prevent mother-to-child transmission"),
       ("Testing and treatment during pregnancy, medicine for the newborn, and continued care while breastfeeding — so a mother with HIV can have a baby without HIV.",
        "Kupimwa na matibabu wakati wa ujauzito, dawa kwa mtoto mchanga, na huduma endelevu wakati wa kunyonyesha — ili mama mwenye VVU aweze kupata mtoto asiye na VVU.",
        "Testing na treatment wakati wa pregnancy, dawa kwa newborn, na continued care wakati wa breastfeeding — ili mama mwenye HIV aweze kupata mtoto asiye na HIV.")],
     ]},
    {"type": "list", "items": [
     ("<strong>Do not share sharp objects</strong>",
      "<strong>Usishiriki vitu vyenye ncha kali</strong>",
      "<strong>Usishare sharp objects</strong>"),
     ("<strong>Practise safe behaviours</strong>",
      "<strong>Fanya tabia salama</strong>",
      "<strong>Practise safe behaviours</strong>"),
     ("<strong>Get correct information from trusted adults</strong> — not from rumours",
      "<strong>Pata taarifa sahihi kutoka kwa watu wazima wanaoaminika</strong> — si kutoka uvumi",
      "<strong>Pata correct info kutoka kwa trusted adults</strong> — si kutoka rumours"),
    ]},
    {"type": "warn", "title": ("⚠️ Where your role ends", "⚠️ Jukumu lako linapoishia", "⚠️ Role yako inaishia wapi"), "text": (
     " Knowing that PrEP and PEP exist is your job. Deciding who should take them, or in what dose, is a clinician's — and PEP needs an HIV test first. What you must never forget is the 72-hour deadline, because that is the one where a delay cannot be undone.",
     " Kujua kwamba PrEP na PEP zipo ni kazi yako. Kuamua nani achukue, au kwa kipimo kipi, ni ya daktari — na PEP inahitaji kipimo cha VVU kwanza. Usichopaswa kusahau kamwe ni muda wa saa 72, kwa sababu hapo ndipo kuchelewa hakuwezi kurekebishwa.",
     " Kujua ati PrEP na PEP ziko ni job yako. Ku-decide nani a-take, ama kwa dose ipi, ni ya clinician — na PEP inahitaji HIV test kwanza. Usichofaa kusahau kamwe ni deadline ya masaa 72, kwa sababu hapo ndipo delay haiwezi ku-undoiwa.")},
   ]},

  {"icon": "🧪",
   "head": ("Testing, and What Happens Without It", "Kupimwa, na Kinachotokea Bila Hilo", "Testing, na Kinachohappen Bila Hiyo"),
   "blocks": [
    {"type": "table",
     "headers": [("Testing matters because", "Kupimwa ni muhimu kwa sababu", "Testing ni muhimu kwa sababu"),
                 ("If HIV is left untreated", "VVU visipotibiwa", "HIV ikiachwa bila treatment")],
     "rows": [
      [("<strong>You know your status</strong> — and nobody can know it any other way",
        "<strong>Unajua hali yako</strong> — na hakuna anayeweza kuijua kwa njia nyingine",
        "<strong>Unajua status yako</strong> — na hakuna anayeweza kuijua kwa njia nyingine"),
       ("Pain and discomfort", "Maumivu na usumbufu", "Pain na discomfort")],
      [("<strong>Positive → start treatment early</strong>, and treatment works",
        "<strong>Ukiwa nayo → anza matibabu mapema</strong>, na matibabu hufanya kazi",
        "<strong>Positive → anza treatment early</strong>, na treatment inawork"),
       ("Risks to fertility", "Hatari kwa uwezo wa kuzaa", "Risks kwa fertility")],
      [("<strong>Negative → learn how to stay that way</strong>",
        "<strong>Usipokuwa nayo → jifunze jinsi ya kubaki hivyo</strong>",
        "<strong>Negative → jifunze jinsi ya kubaki hivyo</strong>"),
       ("Serious illness, and death", "Ugonjwa mkali, na kifo", "Serious illness, na kifo")],
      [("", "", ""),
       ("Passing it to others without knowing", "Kuwaambukiza wengine bila kujua", "Ku-pass kwa wengine bila kujua")],
     ]},
    {"type": "p", "text": (
     "<strong>Living positively with HIV</strong> means taking ARVs every day, eating well, staying active, looking after your mental wellbeing, and having people around you — support groups and peer networks. People living with HIV have rights, and discrimination against them is wrong.",
     "<strong>Kuishi vyema na VVU</strong> maana yake kuchukua ARV kila siku, kula vizuri, kuwa na shughuli, kutunza ustawi wako wa akili, na kuwa na watu karibu nawe — vikundi vya msaada na mitandao ya rika. Watu wanaoishi na VVU wana haki, na kuwabagua ni kosa.",
     "<strong>Kuishi positively na HIV</strong> inamaanisha kuchukua ARVs kila siku, kukula vizuri, kuwa active, ku-look after mental wellbeing yako, na kuwa na wasee karibu na wewe — support groups na peer networks. Wasee wanaoishi na HIV wana rights, na ku-discriminate ni kosa.")},
    {"type": "tip", "title": ("💡 Undetectable = Untransmittable", "💡 Isiyogundulika = Haiambukizi", "💡 Undetectable = Untransmittable"), "text": (
     " Taking ARVs every day brings the amount of virus in the blood so low it cannot be detected — and at that point it cannot be passed on. This is why treatment is prevention, and why someone on treatment is not a danger to anybody.",
     " Kuchukua ARV kila siku hupunguza kiasi cha virusi damuni hadi kisiweze kugundulika — na wakati huo hakiwezi kupitishwa. Ndiyo maana matibabu ni kinga, na ndiyo maana aliye kwenye matibabu si hatari kwa yeyote.",
     " Kuchukua ARVs kila siku inapunguza kiasi cha virus kwa damu hadi kisiweze ku-detectiwa — na wakati huo haiwezi ku-passiwa. Ndio maana treatment ni prevention, na ndio maana msee aliye kwa treatment si danger kwa yeyote.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A new pupil joins your class. Word spreads that his mother died of AIDS. Children start refusing to sit at his desk or share the football.",
      "Mwanafunzi mpya anajiunga na darasa lenu. Habari zinaenea kwamba mama yake alifariki kwa ukimwi. Watoto wanaanza kukataa kukaa dawati lake au kushiriki mpira.",
      "Student mpya anajoin class yenu. Story inaspread ati mama yake alifariki kwa AIDS. Watoto wanaanza ku-refuse kukaa desk yake ama kushare mpira."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell them he probably does not have HIV himself, so it is fine",
                "Waambie pengine yeye mwenyewe hana VVU, kwa hivyo ni sawa",
                "Waambie pengine yeye mwenyewe hana HIV, so ni poa"),
       "outcome": ("That defends him only if he is negative — which means if he were positive, the shunning would be justified. You have accidentally agreed with the thing you were trying to fix. Also, his status is nobody's business, including yours.",
                   "Hilo linamtetea tu kama hana — maana yake kama angekuwa nayo, kumtenga kungekuwa na haki. Umekubaliana bila kukusudia na kile ulichokuwa unajaribu kurekebisha. Pia, hali yake si shughuli ya mtu, ikiwemo wewe.",
                   "Hiyo inam-defend tu kama ni negative — meaning kama angekuwa positive, ku-shun kungekuwa justified. Ume-agree bila kukusudia na kile ulichokuwa una-try ku-fix. Pia, status yake si biashara ya msee, ikiwemo wewe.")},
      {"kind": "good",
       "text": ("Correct the actual belief — HIV does not spread through desks, food or football",
                "Sahihisha imani yenyewe — VVU haviambukizwi kwa dawati, chakula au mpira",
                "Correct belief yenyewe — HIV haiambukizwi kwa desk, chakula ama football"),
       "outcome": ("You said: 'It doesn't matter whose status is what — you cannot catch HIV from a desk, a plate or a ball. Not from sitting together, not from sharing air. That's not an opinion, it's how the virus works.' You sat next to him yourself. Two others did the same by Friday. ✅",
                   "Ulisema: 'Haijalishi hali ya nani ni ipi — huwezi kupata VVU kutoka dawati, sahani au mpira. Si kwa kukaa pamoja, si kwa kushiriki hewa. Hilo si maoni, ndivyo virusi vinavyofanya kazi.' Ulikaa karibu naye mwenyewe. Wengine wawili walifanya vivyo hivyo kufikia Ijumaa. ✅",
                   "Ulisema: 'Haijalishi status ya nani ni ipi — huwezi kupata HIV kutoka desk, plate ama ball. Si kwa kukaa pamoja, si kwa kushare hewa. Hiyo si opinion, ndio jinsi virus inavyowork.' Ulikaa karibu naye mwenyewe. Wengine wawili walifanya same by Friday. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A 13-year-old tells you an older boy touched him two days ago and he has told nobody. He is frightened and ashamed.",
      "Mvulana wa miaka 13 anakuambia mvulana mkubwa alimgusa siku mbili zilizopita na hajamwambia mtu. Ameogopa na anaona aibu.",
      "Mse wa miaka 13 anakuambia mse mkubwa alim-touch siku mbili zilizopita na hajamwambia msee. Ameogopa na anaona aibu."),
     "question": ("What matters most right now?", "Nini ni muhimu zaidi sasa hivi?", "Nini ni muhimu zaidi saa hii?"),
     "choices": [
      {"kind": "bad",
       "text": ("Reassure him and let him decide when he is ready to tell someone",
                "Mfariji na umwache aamue lini yuko tayari kumwambia mtu",
                "M-reassure na umwache a-decide lini yuko ready kumwambia msee"),
       "outcome": ("Two days is inside the 72-hour window, and it is closing. This is also abuse of a child, which is never a secret a peer educator keeps — Module 12 is explicit. Waiting for readiness costs him both the medicine and the protection.",
                   "Siku mbili ziko ndani ya muda wa saa 72, na unafungwa. Pia huu ni unyanyasaji wa mtoto, ambao kamwe si siri mwelimishaji rika anayoiweka — Moduli 12 iko wazi. Kusubiri utayari kunamgharimu dawa na ulinzi.",
                   "Siku mbili ziko ndani ya window ya masaa 72, na inafungwa. Pia hii ni abuse ya mtoto, ambayo kamwe si secret peer educator ana-keep — Module 12 iko wazi. Kungoja readiness kunamgharimu dawa na protection.")},
      {"kind": "good",
       "text": ("Get him to a trusted adult and a health facility today, and tell him you are doing it and why",
                "Mfikishe kwa mtu mzima anayeaminika na kituo cha afya leo, na umwambie unafanya hivyo na kwa nini",
                "M-fikishe kwa trusted adult na health facility leo, na umwambie unafanya hivyo na kwa nini"),
       "outcome": ("You said: 'You didn't do anything wrong, and I'm not going to gossip about this. But I can't keep it to myself, because you're not safe — and there's medicine that only works for three days. I'll come with you now.' He went. He was inside the window. ✅",
                   "Ulisema: 'Hukufanya kosa lolote, na sitasengenya kuhusu hili. Lakini siwezi kulificha, kwa sababu hauko salama — na kuna dawa inayofanya kazi kwa siku tatu tu. Nitakuja nawe sasa.' Alienda. Alikuwa ndani ya muda. ✅",
                   "Ulisema: 'Hukufanya kosa lolote, na sitagossip kuhusu hii. Lakini siwezi kuificha, kwa sababu hauko safe — na kuna dawa inayowork kwa siku tatu tu. Nitakuja na wewe saa hii.' Alienda. Alikuwa ndani ya window. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("HIV does not spread through everyday contact.",
      "VVU haviambukizwi kwa mguso wa kila siku.",
      "HIV haiambukizwi kwa everyday contact."),
     ("Protect yourself by avoiding risky behaviours and never sharing sharp objects.",
      "Jilinde kwa kuepuka tabia hatarishi na kutoshiriki vitu vyenye ncha kali kamwe.",
      "Ji-protect kwa ku-avoid risky behaviours na kutoshare sharp objects kamwe."),
     ("Be kind to everyone. Stigma hurts people — often more than the virus does.",
      "Kuwa mwema kwa kila mtu. Unyanyapaa huumiza watu — mara nyingi kuliko virusi.",
      "Kuwa mwema kwa kila msee. Stigma inaumiza wasee — mara nyingi kuliko virus."),
     ("Testing and treatment save lives. You cannot know your status any other way.",
      "Kupimwa na matibabu huokoa maisha. Huwezi kujua hali yako kwa njia nyingine.",
      "Testing na treatment zinaokoa maisha. Huwezi kujua status yako kwa njia nyingine."),
     ("People with HIV can live long, healthy lives if they take their ARVs.",
      "Watu wenye VVU wanaweza kuishi maisha marefu na yenye afya wakichukua ARV zao.",
      "Wasee wenye HIV wanaweza kuishi long, healthy lives wakichukua ARVs zao."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Huwezi kupata VVU kwa kuwa rafiki wa mtu. Lakini unaweza kumdhuru mtu kwa kukataa kuwa rafiki yake.",
     "Huwezi kupata VVU kwa kuwa rafiki wa mtu. Lakini unaweza kumdhuru mtu kwa kukataa kuwa rafiki yake.",
     "Huwezi kupata HIV kwa kuwa friend wa msee. Lakini unaweza kumdhuru msee kwa ku-refuse kuwa friend wake.")},
   ]},
 ],

 "quiz": [
  {"q": "Which of these CAN pass an STI? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Sexual contact",
               "From a mother to her baby during pregnancy, birth or breastfeeding",
               "Sharing unclean needles or sharp objects",
               "Sharing a desk at school"],
   "answer": ["A", "B", "C"],
   "explain": "Sharing a desk carries no risk at all. Almost every unkind act toward someone with HIV comes from believing otherwise."},

  {"q": "Can a person have an STI without any signs?",
   "options": ["No — there are always symptoms",
               "Yes — and they can still pass it to others",
               "Only in the first week",
               "Only adults can"],
   "answer": "B",
   "explain": "This is why you cannot tell by looking at someone, and why nobody should be judged on appearance."},

  {"q": "What is the difference between HIV and AHD?",
   "options": ["They are the same thing",
               "HIV is the virus; AHD is the illness that develops after HIV has badly damaged the immune system",
               "AHD affects only adults",
               "HIV is curable, AHD is not"],
   "answer": "B",
   "explain": "With treatment, HIV can be controlled and may never lead to AHD."},

  {"q": "Within what time must PEP be started?",
   "options": ["24 hours", "72 hours", "One week", "One month"],
   "answer": "B",
   "explain": "After 72 hours it no longer works — which is the one deadline in this module where a delay cannot be undone."},

  {"q": "What is PMTCT?",
   "options": ["A type of HIV test",
               "Preventing mother-to-child transmission, so a mother with HIV can have a baby without HIV",
               "A support group",
               "A kind of ARV"],
   "answer": "B",
   "explain": "Testing and treatment in pregnancy, medicine for the newborn, and continued care while breastfeeding."},

  {"q": "What does 'Undetectable = Untransmittable' mean?",
   "options": ["The person no longer has HIV",
               "Daily ARVs lower the virus so far it cannot be detected — and at that point cannot be passed on",
               "The test was faulty",
               "They can stop treatment"],
   "answer": "B",
   "explain": "This is why treatment is prevention, and why someone on treatment is not a danger to anybody."},

  {"q": "Classmates refuse to share a desk with a boy whose mother died of AIDS. What is the best response?",
   "options": ["Say he probably does not have HIV himself",
               "Correct the belief — HIV does not spread through desks, food or football, whatever anyone's status",
               "Ask a teacher to move him",
               "Say nothing"],
   "answer": "B",
   "explain": "Saying 'he probably doesn't have it' implies the shunning would be justified if he did — accidentally agreeing with the thing you meant to fix."},

  {"q": "What are the four decision-making steps for a risky situation?",
   "options": ["Ask, decide, act, review",
               "Stop and think; get the facts; check your values; choose safety",
               "Run, hide, tell, report",
               "Plan, prepare, protect, proceed"],
   "answer": "B",
   "explain": "Each step is a question you ask yourself before the situation decides for you."},

  {"q": "A 13-year-old says an older boy touched him two days ago. What matters most?",
   "options": ["Letting him decide when he is ready to tell someone",
               "Getting him to a trusted adult and a health facility today, and telling him you are doing it and why",
               "Keeping it secret as he asked",
               "Confronting the older boy"],
   "answer": "B",
   "explain": "Two days is inside the closing 72-hour window, and abuse of a child is never a secret a peer educator keeps."},

  {"q": "If HIV is left untreated, what can happen? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Pain and discomfort", "Risks to fertility", "Serious illness and death",
               "Passing it to others without knowing", "It clears up by itself"],
   "answer": ["A", "B", "C", "D"],
   "explain": "HIV does not clear by itself — but with ARVs taken daily, people live long, healthy lives."},
 ],
}
