# Module 13B (part 2 of 2) — HIV, PrEP, PEP and Advanced HIV Disease  [ages 15–24]
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Modules 13A/13B.
#
# NOTE ON SCOPE: the deck carries full clinical PrEP dosing (mg, regimens).
# That is prescriber territory — a peer educator who dose-advises causes harm.
# This lesson teaches WHAT each product is, WHO it is for, and the safety
# messages, and routes every dosing question to the facility. See the
# "Where your role ends" slide.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m13b2-hiv-prep-pep-ahd.html",
 "module_code": "M13B",
 "module_slug": "stis-hiv-young-people",
 "lesson_slug": "m13b2-hiv-prep-pep-ahd",
 "module_label": "Peer Educator · M13B · Part 2 of 2",
 "title": "HIV, PrEP, PEP and Advanced HIV Disease",
 "icon": "🎗️",
 "duration": 60,

 "objectives": [
  ("Define HIV and explain how it is and is not transmitted",
   "Fafanua VVU na ueleze jinsi vinavyoambukizwa na jinsi visivyoambukizwa",
   "Define HIV na explain jinsi inavyoambukizwa na jinsi haiambukizwi"),
  ("Explain the difference between HIV and Advanced HIV Disease",
   "Eleza tofauti kati ya VVU na Ugonjwa wa VVU wa Hali ya Juu",
   "Explain tofauti kati ya HIV na Advanced HIV Disease"),
  ("Describe PrEP and PEP, and who each is for",
   "Eleza PrEP na PEP, na kila moja ni ya nani",
   "Describe PrEP na PEP, na kila moja ni ya nani"),
  ("Explain the 72-hour PEP window and act on it without delay",
   "Eleza muda wa saa 72 wa PEP na uchukue hatua bila kuchelewa",
   "Explain window ya masaa 72 ya PEP na uchukue hatua bila kuchelewa"),
  ("Support a peer to live positively with HIV and challenge stigma",
   "Msaidie rika kuishi vyema na VVU na upinge unyanyapaa",
   "Support msee kuishi positively na HIV na challenge stigma"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> There is a medicine that stops HIV after exposure — but only for three days. How many people near you know that?",
  "<strong>🔍 Swali Kubwa:</strong> Kuna dawa inayozuia VVU baada ya kuambukizwa — lakini kwa siku tatu tu. Ni watu wangapi karibu nawe wanajua hilo?",
  "<strong>🔍 Big Question:</strong> Kuna dawa inayostop HIV baada ya exposure — lakini kwa siku tatu tu. Ni wasee wangapi karibu na wewe wanajua hiyo?"),

 "slides": [

  # ── 1. HIV vs AHD ─────────────────────────────────────────────────
  {"icon": "📖",
   "head": ("HIV and Advanced HIV Disease", "VVU na Ugonjwa wa VVU wa Hali ya Juu", "HIV na Advanced HIV Disease"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 HIV — Human Immunodeficiency Virus", "🔑 VVU — Virusi Vya Ukimwi", "🔑 HIV — Human Immunodeficiency Virus"), "text": (
     "A virus that attacks the immune system — the body's defence army — weakening it so other infections can take hold.",
     "Virusi vinavyoshambulia kinga ya mwili — jeshi la ulinzi la mwili — vikiidhoofisha ili maambukizi mengine yaweze kushika.",
     "Virus inayoshambulia immune system — defence army ya mwili — ikii-weaken ili infections zingine ziweze kushika.")},
    {"type": "key_term", "term": ("🔑 AHD — Advanced HIV Disease", "🔑 Ugonjwa wa VVU wa Hali ya Juu", "🔑 AHD — Advanced HIV Disease"), "text": (
     "The final stage of HIV infection, where the immune system is badly damaged and the person becomes sick with many infections and diseases.",
     "Hatua ya mwisho ya maambukizi ya VVU, ambapo kinga ya mwili imeharibiwa vibaya na mtu anaugua maambukizi na magonjwa mengi.",
     "Final stage ya HIV infection, ambapo immune system imeharibika vibaya na msee anaugua infections na magonjwa mengi.")},
    {"type": "table",
     "headers": [("HIV", "VVU", "HIV"), ("AHD", "Hali ya Juu", "AHD")],
     "rows": [
      [("A virus that enters the body and weakens the immune system.",
        "Virusi vinavyoingia mwilini na kudhoofisha kinga.",
        "Virus inayoingia mwilini na ku-weaken immune system."),
       ("The illness that develops after HIV has badly damaged the immune system over time.",
        "Ugonjwa unaokua baada ya VVU kuharibu kinga vibaya baada ya muda.",
        "Ugonjwa unao-develop baada ya HIV kuharibu immune system vibaya baada ya muda.")],
      [("<strong>With treatment, HIV can be controlled and may never lead to AHD.</strong>",
        "<strong>Kwa matibabu, VVU vinaweza kudhibitiwa na visisababishe kamwe hali ya juu.</strong>",
        "<strong>Na treatment, HIV inaweza ku-controliwa na isilead kamwe kwa AHD.</strong>"),
       ("Happens when the immune system is too weak to protect the body from infections.",
        "Hutokea wakati kinga ni dhaifu mno kulinda mwili dhidi ya maambukizi.",
        "Inahappen wakati immune system ni weak sana kulinda mwili dhidi ya infections.")],
     ]},
    {"type": "warn", "title": ("⚠️ The single most important sentence here", "⚠️ Sentensi muhimu zaidi hapa", "⚠️ Sentence muhimu zaidi hapa"), "text": (
     " <strong>Advanced HIV Disease is the result of late diagnosis and untreated infection — not an inevitable progression.</strong> Someone diagnosed early and on treatment may never reach it. That is why testing is the whole game.",
     " <strong>Ugonjwa wa VVU wa hali ya juu ni matokeo ya kugunduliwa kuchelewa na maambukizi yasiyotibiwa — si maendeleo yasiyoepukika.</strong> Aliyegunduliwa mapema na yuko kwenye matibabu anaweza asifike huko kamwe. Ndiyo maana kupimwa ndilo jambo lote.",
     " <strong>Advanced HIV Disease ni result ya late diagnosis na untreated infection — si progression isiyoepukika.</strong> Msee aliyegunduliwa early na yuko kwa treatment anaweza asifike huko kamwe. Ndio maana kupimwa ndio game yote.")},
   ]},

  # ── 2. Transmission ───────────────────────────────────────────────
  {"icon": "🔄",
   "head": ("How HIV Spreads — and How It Does Not", "Jinsi VVU Vinavyoenea — na Jinsi Visivyoenea", "Jinsi HIV Inavyospread — na Jinsi Haispread"),
   "blocks": [
    {"type": "table",
     "headers": [("✅ HIV CAN spread through", "✅ VVU VINAWEZA kuenea kwa", "✅ HIV INAWEZA kuspread kwa"),
                 ("❌ HIV CANNOT spread through", "❌ VVU HAVIWEZI kuenea kwa", "❌ HIV HAIWEZI kuspread kwa")],
     "rows": [
      [("Unprotected vaginal, anal or oral sex with an infected partner",
        "Ngono ya uke, haja kubwa au mdomo bila kinga na mwenzi aliyeambukizwa",
        "Unprotected vaginal, anal ama oral sex na partner aliyeambukizwa"),
       ("Sitting next to someone, or sharing a desk",
        "Kukaa karibu na mtu, au kushiriki dawati",
        "Kukaa karibu na msee, ama kushare desk")],
      [("Sharing needles, syringes or other sharp objects",
        "Kushiriki sindano, sirinji au vitu vingine vyenye ncha kali",
        "Kushare needles, syringes ama sharp objects zingine"),
       ("Breathing the same air",
        "Kupumua hewa moja",
        "Kupumua hewa moja")],
      [("Mother to child during pregnancy, childbirth or breastfeeding without treatment",
        "Mama kwa mtoto wakati wa ujauzito, kujifungua au kunyonyesha bila matibabu",
        "Mama kwa mtoto wakati wa pregnancy, kujifungua ama breastfeeding bila treatment")],
      [("Receiving infected blood products — rare where blood is tested",
        "Kupokea bidhaa za damu zilizoambukizwa — nadra pale damu inapopimwa",
        "Kupokea infected blood products — rare pale damu inapimwa"),
       ("Mosquito or insect bites; swimming together; playing sports",
        "Kuumwa na mbu au wadudu; kuogelea pamoja; kucheza michezo",
        "Kuumwa na mbu ama wadudu; kuogelea pamoja; kucheza michezo")],
     ]},
    {"type": "tip", "title": ("💡 Say this out loud in every session", "💡 Sema hili kwa sauti kila kipindi", "💡 Sema hii kwa sauti kila session"), "text": (
     " You can be friends with someone who has HIV. You can share a desk, a plate, a room and a life with them. Stigma harms more young people than the virus does — and stigma is the thing a peer educator is actually positioned to change.",
     " Unaweza kuwa rafiki na mtu mwenye VVU. Unaweza kushiriki dawati, sahani, chumba na maisha naye. Unyanyapaa hudhuru vijana wengi kuliko virusi — na unyanyapaa ndicho kitu ambacho mwelimishaji rika yuko katika nafasi ya kukibadilisha.",
     " Unaweza kuwa friend na msee mwenye HIV. Unaweza kushare desk, sahani, room na maisha naye. Stigma inadhuru vijana wengi kuliko virus — na stigma ndio kitu ambacho peer educator yuko kwa position ya ku-change.")},
   ]},

  # ── 3. PEP ────────────────────────────────────────────────────────
  {"icon": "⏰",
   "head": ("PEP — The 72-Hour Window", "PEP — Muda wa Saa 72", "PEP — Window ya Masaa 72"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 PEP — Post-Exposure Prophylaxis", "🔑 PEP — Kinga Baada ya Kuambukizwa", "🔑 PEP — Post-Exposure Prophylaxis"), "text": (
     "ARV medicine taken AFTER a possible exposure to HIV, to stop the infection taking hold. It must be started within 72 hours — and the sooner within that window, the better it works.",
     "Dawa ya ARV inayochukuliwa BAADA ya uwezekano wa kuambukizwa VVU, kuzuia maambukizi kushika. Lazima ianze ndani ya saa 72 — na mapema zaidi ndani ya muda huo, ndivyo inavyofanya kazi vizuri.",
     "ARV medicine inayochukuliwa BAADA ya possible exposure ya HIV, kustop infection isishike. Lazima ianze ndani ya masaa 72 — na mapema zaidi ndani ya hiyo window, ndivyo inavyowork better.")},
    {"type": "p", "text": (
     "This is the single most time-critical fact in the whole curriculum. Everything else can wait a day. This cannot.",
     "Hii ndiyo taarifa yenye muda mfupi zaidi katika mtaala mzima. Kila kitu kingine kinaweza kusubiri siku moja. Hii haiwezi.",
     "Hii ndio fact yenye muda mfupi zaidi kwa curriculum nzima. Kila kitu kingine kinaweza kungoja siku moja. Hii haiwezi.")},
    {"type": "list", "items": [
     ("<strong>Who needs it:</strong> anyone with a possible HIV exposure in the last 72 hours — including survivors of sexual violence",
      "<strong>Nani anaihitaji:</strong> yeyote aliye na uwezekano wa kuambukizwa VVU katika saa 72 zilizopita — wakiwemo manusura wa ukatili wa kingono",
      "<strong>Nani anaihitaji:</strong> yeyote mwenye possible HIV exposure kwa masaa 72 yaliyopita — wakiwemo survivors wa sexual violence"),
     ("<strong>Where:</strong> any health facility — survivors of sexual violence should go within 72 hours for care",
      "<strong>Wapi:</strong> kituo chochote cha afya — manusura wa ukatili wa kingono waende ndani ya saa 72 kwa huduma",
      "<strong>Wapi:</strong> facility yoyote ya afya — survivors wa sexual violence waende ndani ya masaa 72 kwa care"),
     ("<strong>Your job:</strong> know the window, say it plainly, and go with them today — not tomorrow",
      "<strong>Kazi yako:</strong> jua muda, useme wazi, na uende nao leo — si kesho",
      "<strong>Job yako:</strong> jua window, useme wazi, na uende nao leo — si kesho"),
    ]},
    {"type": "warn", "title": ("⚠️ Never say 'go when you feel ready'", "⚠️ Usiseme kamwe 'nenda ukiwa tayari'", "⚠️ Usiseme kamwe 'nenda ukiwa ready'"), "text": (
     " Being ready is not a medical category. The clock started at the exposure, not at the conversation. If someone is inside 72 hours, that is a same-day referral — see Module 16.",
     " Kuwa tayari si kipimo cha kimatibabu. Saa ilianza wakati wa kuambukizwa, si wakati wa mazungumzo. Kama mtu yuko ndani ya saa 72, hiyo ni rufaa ya siku hiyo hiyo — angalia Moduli 16.",
     " Kuwa ready si medical category. Clock ilianza wakati wa exposure, si wakati wa conversation. Kama msee yuko ndani ya masaa 72, hiyo ni same-day referral — angalia Module 16.")},
   ]},

  # ── 4. PrEP ───────────────────────────────────────────────────────
  {"icon": "🛡️",
   "head": ("PrEP — Prevention Before Exposure", "PrEP — Kinga Kabla ya Kuambukizwa", "PrEP — Prevention Kabla ya Exposure"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 PrEP — Pre-Exposure Prophylaxis", "🔑 PrEP — Kinga Kabla ya Kuambukizwa", "🔑 PrEP — Pre-Exposure Prophylaxis"), "text": (
     "A highly effective medicine or injection taken by someone who does NOT have HIV, to prevent them acquiring it. PrEP is for HIV-negative people at ongoing risk.",
     "Dawa au sindano yenye ufanisi mkubwa inayochukuliwa na mtu ASIYE na VVU, kumzuia kuvipata. PrEP ni kwa watu wasio na VVU walio katika hatari endelevu.",
     "Medicine ama injection yenye effectiveness kubwa inayochukuliwa na msee ASIYE na HIV, kumzuia kuipata. PrEP ni kwa wasee HIV-negative walio kwa ongoing risk.")},
    {"type": "p", "text": (
     "PrEP now comes in several forms. You do not need to know the doses — you need to know that choices exist, so nobody walks away thinking it is a daily pill or nothing.",
     "PrEP sasa inakuja kwa aina kadhaa. Huhitaji kujua vipimo — unahitaji kujua kwamba chaguo zipo, ili asiondoke mtu akifikiri ni kidonge cha kila siku au hakuna.",
     "PrEP saa hii inakuja kwa forms kadhaa. Huhitaji kujua doses — unahitaji kujua ati choices ziko, ili asiondoke msee akifikiri ni daily pill ama hakuna.")},
    {"type": "table",
     "headers": [("Form", "Aina", "Form"), ("What it is", "Ni nini", "Ni nini"), ("How often", "Mara ngapi", "Mara ngapi")],
     "rows": [
      [("Daily oral PrEP", "PrEP ya kumeza kila siku", "Daily oral PrEP"),
       ("Tablets taken with or without food; usable during conception, pregnancy and breastfeeding",
        "Vidonge vinavyochukuliwa na au bila chakula; vinaweza kutumika wakati wa kupata mimba, ujauzito na kunyonyesha",
        "Tablets zinazochukuliwa na ama bila chakula; zinaweza kutumika wakati wa conception, pregnancy na breastfeeding"),
       ("Every day", "Kila siku", "Kila siku")],
      [("Event-driven (2-1-1)", "Ya tukio (2-1-1)", "Event-driven (2-1-1)"),
       ("Tablets around a specific occasion, for men who have sex with men",
        "Vidonge kuzunguka tukio maalum, kwa wanaume wanaofanya ngono na wanaume",
        "Tablets kuzunguka occasion maalum, kwa men who have sex with men"),
       ("Around the event", "Kuzunguka tukio", "Kuzunguka event")],
      [("Dapivirine Vaginal Ring", "Pete ya Uke ya Dapivirine", "Dapivirine Vaginal Ring"),
       ("A silicone ring self-inserted into the vagina, releasing medicine locally. Does not protect against non-vaginal exposure.",
        "Pete ya silikoni inayojiingiza ukeni, ikitoa dawa hapo hapo. Hailindi dhidi ya kuambukizwa nje ya uke.",
        "Silicone ring inayojiingiza kwa vagina, ikitoa dawa hapo hapo. Hailindi dhidi ya exposure nje ya vaginal."),
       ("Replaced monthly", "Hubadilishwa kila mwezi", "Inabadilishwa kila mwezi")],
      [("CAB-LA injection", "Sindano ya CAB-LA", "CAB-LA injection"),
       ("Cabotegravir, injected into the buttock muscle. Not started during pregnancy or breastfeeding, but may be continued.",
        "Cabotegravir, inayochomwa kwenye msuli wa tako. Haianzishwi wakati wa ujauzito au kunyonyesha, lakini inaweza kuendelezwa.",
        "Cabotegravir, inayochomwa kwa muscle ya buttock. Haianzishwi wakati wa pregnancy ama breastfeeding, lakini inaweza kuendelezwa."),
       ("Every 8 weeks", "Kila wiki 8", "Kila wiki 8")],
      [("Lenacapavir (LEN)", "Lenacapavir (LEN)", "Lenacapavir (LEN)"),
       ("An injection under the skin. Safe in pregnancy, breastfeeding and severe kidney disease. <strong>Not used for treatment.</strong>",
        "Sindano chini ya ngozi. Salama wakati wa ujauzito, kunyonyesha na ugonjwa mkali wa figo. <strong>Haitumiwi kwa matibabu.</strong>",
        "Injection chini ya ngozi. Safe wakati wa pregnancy, breastfeeding na severe kidney disease. <strong>Haitumiwi kwa treatment.</strong>"),
       ("Every 6 months", "Kila miezi 6", "Kila miezi 6")],
     ]},
    {"type": "tip", "title": ("💡 Before anyone starts PrEP", "💡 Kabla mtu hajaanza PrEP", "💡 Kabla msee aanze PrEP"), "text": (
     " The facility checks HIV status first, asks about any exposure in the past 72 hours (a PEP question, not a PrEP one), checks for signs of very recent HIV infection, and reviews other medicines and allergies. PrEP is never simply handed over.",
     " Kituo hukagua hali ya VVU kwanza, huuliza kuhusu kuambukizwa katika saa 72 zilizopita (swali la PEP, si la PrEP), hukagua dalili za maambukizi mapya sana ya VVU, na hukagua dawa nyingine na mzio. PrEP haitolewi tu hivi hivi.",
     " Facility inacheck HIV status kwanza, inauliza kuhusu exposure kwa masaa 72 yaliyopita (question ya PEP, si ya PrEP), inacheck signs za very recent HIV infection, na inareview dawa zingine na allergies. PrEP haitolewi tu hivi hivi.")},
   ]},

  # ── 5. Boundary ───────────────────────────────────────────────────
  {"icon": "🚧",
   "head": ("Where Your Role Ends", "Jukumu Lako Linapoishia", "Role Yako Inaishia Wapi"),
   "blocks": [
    {"type": "warn", "title": ("⚠️ Do not advise on doses", "⚠️ Usishauri kuhusu vipimo", "⚠️ Usi-advise kuhusu doses"), "text": (
     " The national curriculum contains full PrEP dosing tables because clinicians use them. <strong>You are not a prescriber.</strong> Naming the products and who they suit is your job. Deciding which one, at what dose, and whether someone is eligible, is the facility's.",
     " Mtaala wa kitaifa una majedwali kamili ya vipimo vya PrEP kwa sababu madaktari huyatumia. <strong>Wewe si mwagizaji wa dawa.</strong> Kutaja bidhaa na zinazomfaa nani ni kazi yako. Kuamua ipi, kwa kipimo kipi, na kama mtu anastahili, ni kazi ya kituo.",
     " National curriculum ina full PrEP dosing tables kwa sababu clinicians wanazitumia. <strong>Wewe si prescriber.</strong> Ku-name products na zinazomfaa nani ni job yako. Ku-decide ipi, kwa dose ipi, na kama msee anastahili, ni job ya facility.")},
    {"type": "list", "items": [
     ("<strong>Say:</strong> 'PrEP exists, there are several forms, and the clinic will work out which fits you.'",
      "<strong>Sema:</strong> 'PrEP ipo, kuna aina kadhaa, na kliniki itatafuta inayokufaa.'",
      "<strong>Sema:</strong> 'PrEP iko, kuna forms kadhaa, na clinic itafigure out inayokufit.'"),
     ("<strong>Do not say:</strong> how many tablets, when, or that a particular product suits them",
      "<strong>Usiseme:</strong> vidonge vingapi, lini, au kwamba bidhaa fulani inamfaa",
      "<strong>Usiseme:</strong> tablets ngapi, lini, ama ati product fulani inamfit"),
     ("<strong>Report side effects onward.</strong> Any unwanted reaction to a medicine goes to the nearest health facility.",
      "<strong>Ripoti madhara.</strong> Athari yoyote isiyotakikana ya dawa huenda kituo cha afya cha karibu.",
      "<strong>Report side effects.</strong> Reaction yoyote isiyotakikana ya dawa inaenda facility ya afya ya karibu."),
    ]},
    {"type": "facilitator", "minutes": 8, "text": (
     "Run a quick sorting exercise: read out ten statements and have the group call 'peer educator' or 'clinician' for each. Include borderline ones — 'explaining the 72-hour window' is yours; 'telling someone to take two tablets' is not.",
     "Endesha zoezi la haraka la kupanga: soma kauli kumi na uwaache kundi liseme 'mwelimishaji rika' au 'daktari' kwa kila moja. Jumuisha zile za mpakani — 'kueleza muda wa saa 72' ni yako; 'kumwambia mtu ameze vidonge viwili' si yako.",
     "Run quick sorting exercise: soma statements kumi na uwache group i-call 'peer educator' ama 'clinician' kwa kila moja. Include zile za borderline — 'ku-explain window ya masaa 72' ni yako; 'kumwambia msee ameze tablets mbili' si yako.")},
   ]},

  # ── 6. PrEP key messages ──────────────────────────────────────────
  {"icon": "📌",
   "head": ("Five Things to Remember About PrEP", "Mambo Matano ya Kukumbuka Kuhusu PrEP", "Vitu Vitano vya Kukumbuka Kuhusu PrEP"),
   "blocks": [
    {"type": "list", "ordered": True, "items": [
     ("<strong>No PrEP product protects immediately.</strong> Protection builds after starting — it is not a same-day shield.",
      "<strong>Hakuna bidhaa ya PrEP inayolinda mara moja.</strong> Ulinzi hujengeka baada ya kuanza — si ngao ya siku hiyo hiyo.",
      "<strong>Hakuna PrEP product inayolinda immediately.</strong> Protection inajengeka baada ya kuanza — si shield ya siku hiyo hiyo."),
     ("<strong>Continuous use means continuous protection.</strong> Stop taking it and the protection stops too.",
      "<strong>Matumizi endelevu maana yake ulinzi endelevu.</strong> Ukiacha kuitumia ulinzi nao huacha.",
      "<strong>Continuous use inamaanisha continuous protection.</strong> Ukiacha kuitumia protection nayo inaacha."),
     ("<strong>Correct use gives maximum effectiveness.</strong> Taken as advised, it works extremely well.",
      "<strong>Matumizi sahihi hutoa ufanisi wa juu zaidi.</strong> Ikichukuliwa kama ilivyoshauriwa, hufanya kazi vizuri sana.",
      "<strong>Correct use inatoa maximum effectiveness.</strong> Ikichukuliwa kama ilivyo-advisiwa, inawork poa sana."),
     ("<strong>Switching between products is allowed</strong> when clinically appropriate — some overlap may be needed.",
      "<strong>Kubadilisha kati ya bidhaa kunaruhusiwa</strong> inapofaa kimatibabu — huenda mwingiliano kidogo ukahitajika.",
      "<strong>Ku-switch kati ya products kunaruhusiwa</strong> inapofaa clinically — huenda overlap kidogo ikahitajika."),
     ("<strong>Restarting is supported.</strong> Someone can stop, and later decide to start again.",
      "<strong>Kuanza upya kunasaidiwa.</strong> Mtu anaweza kuacha, na baadaye aamue kuanza tena.",
      "<strong>Ku-restart kunasupportiwa.</strong> Msee anaweza kuacha, na baadaye a-decide kuanza tena."),
    ]},
    {"type": "sheng", "text": (
     "PrEP si kwa 'watu wa aina fulani'. Ni kwa yeyote asiye na VVU aliye katika hatari — na hatari si tabia, ni hali. Ndiyo maana kuiuliza si aibu.",
     "PrEP si ya 'watu wa aina fulani'. Ni ya yeyote asiye na VVU aliye hatarini — na hatari si tabia, ni hali. Ndiyo maana kuiuliza si aibu.",
     "PrEP si ya 'wasee wa aina fulani'. Ni ya yeyote asiye na HIV aliye at risk — na risk si character, ni situation. Ndio maana kuiuliza si aibu.")},
   ]},

  # ── 7. Living positively ──────────────────────────────────────────
  {"icon": "💚",
   "head": ("Living Positively with HIV", "Kuishi Vyema na VVU", "Kuishi Positively na HIV"),
   "blocks": [
    {"type": "p", "text": (
     "A young person who tests positive has not received a death sentence. They have received information, and with treatment a full life follows.",
     "Kijana anayepimwa na kupatikana na VVU hajapokea hukumu ya kifo. Amepokea taarifa, na kwa matibabu maisha kamili hufuata.",
     "Kijana anayepimwa akapatikana na HIV hajapokea death sentence. Amepokea information, na na treatment maisha kamili yanafollow.")},
    {"type": "list", "items": [
     ("<strong>Start and stay on ARVs.</strong> Treatment controls the virus and prevents progression to AHD.",
      "<strong>Anza na uendelee na ARV.</strong> Matibabu hudhibiti virusi na huzuia kuendelea hadi hali ya juu.",
      "<strong>Anza na uendelee na ARVs.</strong> Treatment ina-control virus na inazuia progression hadi AHD."),
     ("<strong>Undetectable means untransmittable.</strong> Someone with a suppressed viral load does not pass HIV on sexually.",
      "<strong>Isiyogundulika maana yake haiambukizi.</strong> Mtu mwenye kiwango cha virusi kilichodhibitiwa haambukizi VVU kingono.",
      "<strong>Undetectable inamaanisha untransmittable.</strong> Msee mwenye suppressed viral load haambukizi HIV kingono."),
     ("<strong>Keep clinic appointments</strong> — monitoring is how treatment stays on track.",
      "<strong>Hudhuria miadi ya kliniki</strong> — ufuatiliaji ndiko matibabu yanavyoendelea vizuri.",
      "<strong>Hudhuria clinic appointments</strong> — monitoring ndio inafanya treatment iendelee poa."),
     ("<strong>Disclosure is their decision, not yours</strong> — support it, never force or pre-empt it.",
      "<strong>Kufichua ni uamuzi wake, si wako</strong> — uunge mkono, usilazimishe wala kutangulia.",
      "<strong>Disclosure ni decision yake, si yako</strong> — support, usiforce wala kutangulia."),
    ]},
    {"type": "example", "title": ("🇰🇪 Njeri — Kisumu", "🇰🇪 Njeri — Kisumu", "🇰🇪 Njeri — Kisumu"), "text": (
     "Njeri, 21, tested positive at a peer-led outreach. She started treatment the same week. Two years on she is in college, her viral load is suppressed, and she is now a peer educator herself. The thing that changed her outcome was not the medicine alone — it was testing before she felt ill.",
     "Njeri, miaka 21, alipimwa akapatikana na VVU kwenye ufikiaji ulioongozwa na rika. Alianza matibabu wiki hiyo hiyo. Miaka miwili baadaye yuko chuoni, kiwango chake cha virusi kimedhibitiwa, na sasa yeye mwenyewe ni mwelimishaji rika. Kilichobadilisha matokeo yake si dawa peke yake — ni kupimwa kabla hajajisikia mgonjwa.",
     "Njeri, 21, alipimwa akapatikana na HIV kwa peer-led outreach. Alianza treatment wiki hiyo hiyo. Miaka miwili baadaye yuko college, viral load yake ime-suppressiwa, na saa hii yeye mwenyewe ni peer educator. Kilicho-change outcome yake si dawa peke yake — ni kupimwa kabla ajiskie mgonjwa.")},
   ]},

  # ── 8. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "It is Sunday evening. A peer tells you she was sexually assaulted on Friday night. She has told nobody and does not want to go anywhere tonight.",
      "Ni jioni ya Jumapili. Rika anakuambia alinyanyaswa kingono usiku wa Ijumaa. Hajamwambia mtu na hataki kwenda popote usiku huu.",
      "Ni Sunday evening. Msee anakuambia ali-assaultiwa kingono Friday usiku. Hajamwambia mtu na hataki kuenda popote usiku huu."),
     "question": ("What matters most right now?", "Nini ni muhimu zaidi sasa hivi?", "Nini ni muhimu zaidi saa hii?"),
     "choices": [
      {"kind": "bad",
       "text": ("Respect her wish and arrange to go together on Monday",
                "Heshimu matakwa yake na upange kwenda pamoja Jumatatu",
                "Respect wish yake na u-arrange kuenda pamoja Monday"),
       "outcome": ("Friday night to Monday is past 72 hours. PEP would no longer be an option, and the window for emergency contraception and forensic care is closing too. Respecting her wish here means losing the only thing that was still reversible.",
                   "Kuanzia usiku wa Ijumaa hadi Jumatatu ni zaidi ya saa 72. PEP isingekuwa chaguo tena, na muda wa uzazi wa dharura na huduma za ushahidi nao unafungwa. Kuheshimu matakwa yake hapa kunamaanisha kupoteza kitu pekee kilichokuwa bado kinaweza kurekebishwa.",
                   "Kuanzia Friday usiku hadi Monday ni zaidi ya masaa 72. PEP isingekuwa option tena, na window ya emergency contraception na forensic care nayo inafungwa. Ku-respect wish yake hapa inamaanisha kupoteza kitu pekee kilichokuwa bado kinaweza ku-reversiwa.")},
      {"kind": "good",
       "text": ("Explain the 72-hour window gently and get her to a facility tonight, with her consent",
                "Eleza muda wa saa 72 kwa upole na umfikishe kituoni usiku huu, kwa ridhaa yake",
                "Explain window ya masaa 72 kwa upole na umfikishe facility usiku huu, kwa consent yake"),
       "outcome": ("You said: 'I'm not going to tell anyone what happened — that's yours. But there's a medicine that can stop HIV, and it only works for three days. We're at hour sixty-something. I'll come with you now and you say only what you want to say.' She went. ✅",
                   "Ulisema: 'Sitamwambia mtu kilichotokea — hicho ni chako. Lakini kuna dawa inayoweza kuzuia VVU, na hufanya kazi kwa siku tatu tu. Tuko saa sitini na kitu. Nitakuja nawe sasa na useme tu unachotaka kusema.' Alienda. ✅",
                   "Ulisema: 'Sitamwambia mtu kilichohappen — hicho ni chako. Lakini kuna dawa inayoweza ku-stop HIV, na inawork kwa siku tatu tu. Tuko hour sixty-something. Nitakuja na wewe saa hii na useme tu unachotaka kusema.' Alienda. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A peer asks you exactly how many PrEP tablets he should take and when, because the queue at the clinic is long and he would rather just start.",
      "Rika anakuuliza ni vidonge vingapi hasa vya PrEP achukue na lini, kwa sababu foleni kliniki ni ndefu na angependa tu kuanza.",
      "Msee anakuuliza ni tablets ngapi hasa za PrEP achukue na lini, kwa sababu queue ya clinic ni ndefu na angependa tu kuanza."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell him the regimen from the curriculum — the information is in your training",
                "Mwambie utaratibu kutoka mtaalani — taarifa iko katika mafunzo yako",
                "Mwambie regimen kutoka curriculum — info iko kwa training yako"),
       "outcome": ("Being trained on a table does not make you a prescriber. PrEP requires an HIV test first — if he already has HIV, taking PrEP alone can cause drug resistance. That single missing step is why eligibility is assessed at a facility.",
                   "Kufunzwa jedwali hakukufanyi mwagizaji wa dawa. PrEP inahitaji kipimo cha VVU kwanza — kama tayari ana VVU, kuchukua PrEP peke yake kunaweza kusababisha usugu wa dawa. Hatua hiyo moja iliyokosekana ndiyo sababu ustahiki hupimwa kituoni.",
                   "Ku-trainiwa kwa table haikufanyi prescriber. PrEP inahitaji HIV test kwanza — kama tayari ana HIV, kuchukua PrEP peke yake inaweza kusababisha drug resistance. Hiyo step moja iliyokosekana ndio sababu eligibility inapimwa facility.")},
      {"kind": "good",
       "text": ("Explain why the test comes first, and help him get seen without the long queue",
                "Eleza kwa nini kipimo huja kwanza, na umsaidie aonwe bila foleni ndefu",
                "Explain kwa nini test inakuja kwanza, na umsaidie aonwe bila queue ndefu"),
       "outcome": ("You said: 'I can't tell you doses — that's the clinician's call, and it starts with an HIV test, because PrEP on its own isn't right if you already have HIV. But the queue I can help with.' You arranged a fast-track through the referral you already knew. ✅",
                   "Ulisema: 'Siwezi kukuambia vipimo — hilo ni la daktari, na huanza na kipimo cha VVU, kwa sababu PrEP peke yake haifai kama tayari una VVU. Lakini foleni naweza kusaidia.' Ulipanga njia ya haraka kupitia rufaa uliyoijua tayari. ✅",
                   "Ulisema: 'Siwezi kukuambia doses — hiyo ni ya daktari, na inaanza na HIV test, kwa sababu PrEP peke yake haifai kama tayari una HIV. Lakini queue naweza kusaidia.' Uli-arrange fast-track kupitia referral uliyoijua tayari. ✅")},
     ]},
   ]},

  # ── 9. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("HIV attacks the immune system; AHD is what follows when it goes untreated for too long.",
      "VVU hushambulia kinga ya mwili; hali ya juu ndiyo hufuata visipotibiwa kwa muda mrefu.",
      "HIV inashambulia immune system; AHD ndio inafollow ikiachwa bila treatment muda mrefu."),
     ("Advanced HIV Disease is the result of late diagnosis — not an inevitable ending.",
      "Ugonjwa wa VVU wa hali ya juu ni matokeo ya kugunduliwa kuchelewa — si mwisho usioepukika.",
      "Advanced HIV Disease ni result ya late diagnosis — si ending isiyoepukika."),
     ("PEP must start within 72 hours of exposure. Sooner is better.",
      "PEP lazima ianze ndani ya saa 72 baada ya kuambukizwa. Mapema ni bora.",
      "PEP lazima ianze ndani ya masaa 72 baada ya exposure. Mapema ni better."),
     ("PrEP is for HIV-negative people at ongoing risk, and comes in several forms — the facility decides which.",
      "PrEP ni kwa watu wasio na VVU walio katika hatari endelevu, na inakuja kwa aina kadhaa — kituo huamua ipi.",
      "PrEP ni kwa wasee HIV-negative walio kwa ongoing risk, na inakuja kwa forms kadhaa — facility ina-decide ipi."),
     ("Undetectable means untransmittable. Treatment works, and stigma harms more than the virus.",
      "Isiyogundulika maana yake haiambukizi. Matibabu hufanya kazi, na unyanyapaa hudhuru kuliko virusi.",
      "Undetectable inamaanisha untransmittable. Treatment inawork, na stigma inadhuru kuliko virus."),
    ]},
   ]},
 ],

 "quiz": [
  {"q": "What is the difference between HIV and AHD?",
   "options": ["They are two names for the same thing",
               "HIV is the virus; AHD is the illness that develops after HIV has badly damaged the immune system",
               "AHD is a different virus",
               "HIV affects adults, AHD affects children"],
   "answer": "B",
   "explain": "With treatment, HIV can be controlled and may never lead to AHD. AHD reflects late diagnosis, not inevitability."},

  {"q": "PEP must be started within:",
   "options": ["24 hours of exposure", "72 hours of exposure", "One week of exposure", "One month of exposure"],
   "answer": "B",
   "explain": "72 hours — and the sooner inside that window, the better it works. This is the most time-critical fact in the curriculum."},

  {"q": "Which of these CANNOT transmit HIV? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Mosquito bites",
               "Sharing a desk at school",
               "Sharing needles or syringes",
               "Swimming in the same water",
               "Breathing the same air"],
   "answer": ["A", "B", "D", "E"],
   "explain": "Only sharing needles transmits HIV. The other four are exactly the myths that drive the stigma stopping people from testing."},

  {"q": "Who is PrEP for?",
   "options": ["People already living with HIV",
               "HIV-negative people at ongoing risk of acquiring HIV",
               "Anyone who has had an exposure in the last 72 hours",
               "Only sex workers"],
   "answer": "B",
   "explain": "PrEP prevents HIV in people who do not have it. Someone with a possible exposure in the last 72 hours needs PEP, not PrEP."},

  {"q": "A peer asks you exactly how many PrEP tablets to take. What should you do?",
   "options": ["Tell him — the dosing table was in your training",
               "Explain that dosing and eligibility are decided at the facility, starting with an HIV test",
               "Guess based on what a friend takes",
               "Tell him PrEP is not available in Kenya"],
   "answer": "B",
   "explain": "PrEP requires an HIV test first — taking it alone when already HIV-positive risks drug resistance. Dosing is a prescriber's decision."},

  {"q": "Which are true about PrEP? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["No PrEP product protects immediately",
               "Continuous use means continuous protection",
               "Once you start, you can never stop or restart",
               "Switching between products is allowed when clinically appropriate",
               "It comes in oral, ring and injectable forms"],
   "answer": ["A", "B", "D", "E"],
   "explain": "Restarting is explicitly supported — someone can stop and later decide to start again."},

  {"q": "'Undetectable means untransmittable' means:",
   "options": ["The person no longer has HIV",
               "A person with a suppressed viral load does not pass HIV on sexually",
               "The test was wrong",
               "They can stop treatment"],
   "answer": "B",
   "explain": "Suppression is achieved and maintained by staying on treatment — which is why keeping appointments matters."},

  {"q": "A peer was assaulted on Friday night and tells you on Sunday evening. What matters most?",
   "options": ["Waiting until she feels ready to go",
               "Getting her to a facility tonight, with her consent, because the 72-hour window is closing",
               "Reporting to police first",
               "Telling her family"],
   "answer": "B",
   "explain": "The clock started at the exposure, not the conversation. Being ready is not a medical category — and PEP, emergency contraception and forensic care all have windows."},

  {"q": "Whose decision is it to disclose an HIV status?",
   "options": ["The peer educator's, if it protects others",
               "The person living with HIV — support it, never force or pre-empt it",
               "The clinic's",
               "The family's"],
   "answer": "B",
   "explain": "Disclosure belongs to the person. Your role is to support the decision, not to make or announce it."},

  {"q": "Why is testing described as 'the whole game' for HIV?",
   "options": ["Because tests are free",
               "Because early diagnosis and treatment mean a person may never progress to AHD",
               "Because testing is required by law",
               "Because a negative test means lifetime protection"],
   "answer": "B",
   "explain": "AHD results from late diagnosis and untreated infection. Testing early is what makes the difference between a controlled condition and advanced disease."},
 ],
}
