# Module 13B (part 1 of 2) — STIs and Condoms  [ages 15–24]
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 13B.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m13b1-stis-and-condoms.html",
 "module_code": "M13B",
 "module_slug": "stis-hiv-young-people",
 "lesson_slug": "m13b1-stis-and-condoms",
 "module_label": "Peer Educator · M13B · Part 1 of 2",
 "title": "STIs and Condoms",
 "icon": "🎗️",
 "duration": 45,

 "objectives": [
  ("Define STIs and distinguish them from urinary tract infections",
   "Fafanua magonjwa ya zinaa na uyatofautishe na maambukizi ya njia ya mkojo",
   "Define STIs na uzitofautishe na urinary tract infections"),
  ("Identify the signs and symptoms of the main types of STI",
   "Tambua dalili za aina kuu za magonjwa ya zinaa",
   "Tambua signs na symptoms za types kuu za STI"),
  ("Explain why early testing and treatment matter",
   "Eleza kwa nini upimaji na matibabu ya mapema ni muhimu",
   "Explain kwa nini early testing na treatment ni muhimu"),
  ("Describe STI prevention, including correct and consistent condom use",
   "Eleza kuzuia magonjwa ya zinaa, ikiwemo matumizi sahihi na ya kudumu ya kondomu",
   "Describe STI prevention, ikiwemo correct na consistent condom use"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> If an infection has no symptoms at all, what would ever make someone go and get tested?",
  "<strong>🔍 Swali Kubwa:</strong> Kama maambukizi hayana dalili kabisa, ni nini kingemfanya mtu aende kupimwa?",
  "<strong>🔍 Big Question:</strong> Kama infection haina symptoms kabisa, ni nini kingemfanya msee aende kupimwa?"),

 "slides": [

  # ── 1. What STIs are ──────────────────────────────────────────────
  {"icon": "📖",
   "head": ("What STIs Are — and What They Are Not", "Magonjwa ya Zinaa ni Nini — na Si Nini", "STIs ni Nini — na Si Nini"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Sexually Transmitted Infection (STI)", "🔑 Ugonjwa wa Zinaa", "🔑 Sexually Transmitted Infection (STI)"), "text": (
     "An illness caused by bacteria, viruses or parasites, spread through unprotected sex with an infected partner. STIs are among the most common diseases in Kenya, especially among 15–24 year-olds.",
     "Ugonjwa unaosababishwa na bakteria, virusi au vimelea, unaoenea kwa ngono isiyo salama na mwenzi aliyeambukizwa. Magonjwa ya zinaa ni kati ya magonjwa ya kawaida zaidi Kenya, hasa kwa wenye miaka 15–24.",
     "Ugonjwa unaosababishwa na bacteria, virus ama parasites, unaospread kwa unprotected sex na partner aliyeambukizwa. STIs ni kati ya magonjwa common zaidi Kenya, hasa kwa wa miaka 15–24.")},
    {"type": "table",
     "headers": [("STI", "Ugonjwa wa zinaa", "STI"), ("UTI", "Maambukizi ya njia ya mkojo", "UTI")],
     "rows": [
      [("Spread mainly through sexual contact",
        "Huenea hasa kwa kugusana kingono",
        "Inaspread hasa kwa sexual contact"),
       ("Can come from sexual contact, but also poor hygiene or overgrowth of normal bacteria",
        "Yanaweza kutoka kwa ngono, lakini pia usafi duni au ukuaji wa bakteria wa kawaida",
        "Inaweza kutoka kwa sex, lakini pia poor hygiene ama overgrowth ya normal bacteria")],
     ]},
    {"type": "warn", "title": ("⚠️ Correct this early", "⚠️ Sahihisha hili mapema", "⚠️ Correct hii early"), "text": (
     " STIs spread through sexual contact — <strong>not</strong> by hugging, sharing food, sharing a desk or using the same toilet. A peer educator who leaves that confusion standing fuels the stigma that stops people testing.",
     " Magonjwa ya zinaa huenea kwa kugusana kingono — <strong>si</strong> kwa kukumbatiana, kushiriki chakula, kushiriki dawati au kutumia choo kimoja. Mwelimishaji rika anayeacha mkanganyiko huo huchochea unyanyapaa unaozuia watu kupimwa.",
     " STIs zinaspread kwa sexual contact — <strong>si</strong> kwa kukumbatiana, kushare chakula, kushare desk ama kutumia choo kimoja. Peer educator anayeacha hiyo confusion ina-fuel stigma inayozuia wasee kupimwa.")},
   ]},

  # ── 2. Silent infections ──────────────────────────────────────────
  {"icon": "🤫",
   "head": ("The Ones You Cannot See", "Zile Usizoweza Kuona", "Zile Huwezi Kuona"),
   "blocks": [
    {"type": "table",
     "headers": [("Symptomatic", "Zenye dalili", "Symptomatic"), ("Asymptomatic", "Zisizo na dalili", "Asymptomatic")],
     "rows": [
      [("Visible signs: discharge, sores, itching, swelling, pain",
        "Dalili zinazoonekana: majimaji, vidonda, kuwashwa, kuvimba, maumivu",
        "Visible signs: discharge, sores, kuwashwa, kuvimba, pain"),
       ("No visible signs at all — but the infection is still there",
        "Hakuna dalili zinazoonekana kabisa — lakini maambukizi bado yapo",
        "Hakuna visible signs kabisa — lakini infection bado iko")],
     ]},
    {"type": "list", "items": [
     ("An asymptomatic infection still <strong>harms your body over time</strong>",
      "Maambukizi yasiyo na dalili bado <strong>hudhuru mwili wako baada ya muda</strong>",
      "Asymptomatic infection bado <strong>inadhuru mwili wako baada ya muda</strong>"),
     ("It can still <strong>spread to others</strong>",
      "Bado yanaweza <strong>kuenea kwa wengine</strong>",
      "Bado inaweza <strong>ku-spread kwa wengine</strong>"),
     ("<strong>Chlamydia and gonorrhoea</strong> often show no symptoms at all",
      "<strong>Klamidia na kisonono</strong> mara nyingi hayaonyeshi dalili kabisa",
      "<strong>Chlamydia na gonorrhea</strong> mara nyingi hazionyeshi symptoms kabisa"),
    ]},
    {"type": "tip", "title": ("💡 The answer to the Big Question", "💡 Jibu la Swali Kubwa", "💡 Jibu la Big Question"), "text": (
     " Nothing about how you feel tells you whether you have an STI. That is precisely why testing is not something you do when worried — it is something you do routinely, and before a new relationship.",
     " Hakuna kitu kuhusu jinsi unavyojisikia kinachokuambia kama una ugonjwa wa zinaa. Ndiyo maana kupimwa si kitu unachofanya ukiwa na wasiwasi — ni kitu unachofanya kwa kawaida, na kabla ya uhusiano mpya.",
     " Hakuna kitu kuhusu jinsi unavyojiskia kinachokuambia kama una STI. Ndio maana kupimwa si kitu unachofanya ukiwa na wasiwasi — ni kitu unachofanya routinely, na kabla ya relationship mpya.")},
   ]},

  # ── 3. Types table ────────────────────────────────────────────────
  {"icon": "🔬",
   "head": ("The Four Types", "Aina Nne", "Types Nne"),
   "blocks": [
    {"type": "table",
     "headers": [("Type", "Aina", "Type"), ("Examples", "Mifano", "Examples"), ("Signs to watch for", "Dalili za kuangalia", "Signs za kuangalia")],
     "rows": [
      [("Bacterial", "Bakteria", "Bacterial"),
       ("Gonorrhoea, chlamydia, syphilis", "Kisonono, klamidia, kaswende", "Gonorrhea, chlamydia, syphilis"),
       ("Pain or burning when passing urine; discharge; pain or swelling in the testicles; pain in the lower abdomen; sores or rashes. Syphilis can start as a painless sore that disappears while the infection stays.",
        "Maumivu au kuungua wakati wa kukojoa; majimaji; maumivu au kuvimba kwa korodani; maumivu tumbo la chini; vidonda au upele. Kaswende inaweza kuanza kama kidonda kisicho na maumivu kinachotoweka huku maambukizi yakibaki.",
        "Pain ama kuungua wakati wa kukojoa; discharge; pain ama kuvimba kwa testicles; pain kwa lower abdomen; sores ama rashes. Syphilis inaweza kuanza kama painless sore inayotoweka huku infection ikibaki.")],
      [("Viral", "Virusi", "Viral"),
       ("HIV, herpes, HPV, hepatitis B", "VVU, herpes, HPV, homa ya ini B", "HIV, herpes, HPV, hepatitis B"),
       ("Flu-like sickness; painful blisters; warts or lumps on the genitals or anus.",
        "Ugonjwa kama homa ya mafua; malengelenge yenye maumivu; vijineno au uvimbe sehemu za siri au njia ya haja kubwa.",
        "Flu-like sickness; painful blisters; warts ama lumps kwa genitals ama anus.")],
      [("Parasitic", "Vimelea", "Parasitic"),
       ("Trichomoniasis, pubic lice", "Trikomoniasis, chawa wa sehemu za siri", "Trichomoniasis, pubic lice"),
       ("Itching; pain when passing urine or after sex; yellow-green smelly discharge.",
        "Kuwashwa; maumivu wakati wa kukojoa au baada ya ngono; majimaji ya njano-kijani yenye harufu.",
        "Kuwashwa; pain wakati wa kukojoa ama baada ya sex; yellow-green smelly discharge.")],
      [("Fungal", "Fangasi", "Fungal"),
       ("Candidiasis (yeast infection)", "Kandidiasis (fangasi)", "Candidiasis (yeast infection)"),
       ("Itching and redness; white patches or rash.",
        "Kuwashwa na wekundu; mabaka meupe au upele.",
        "Kuwashwa na redness; white patches ama rash.")],
     ]},
    {"type": "p", "text": (
     "Some STIs are rare — chancroid, lymphogranuloma venereum (LGV) and granuloma inguinale. You do not need to diagnose any of these. You need to recognise that something warrants a visit.",
     "Baadhi ya magonjwa ya zinaa ni nadra — chancroid, lymphogranuloma venereum (LGV) na granuloma inguinale. Huhitaji kutambua ugonjwa wowote kati ya hivi. Unahitaji kutambua kwamba jambo linahitaji ziara.",
     "Baadhi ya STIs ni rare — chancroid, lymphogranuloma venereum (LGV) na granuloma inguinale. Huhitaji ku-diagnose yoyote kati ya hizi. Unahitaji kutambua ati kitu kinahitaji visit.")},
   ]},

  # ── 4. Testing early ──────────────────────────────────────────────
  {"icon": "⏱️",
   "head": ("Why Testing Early Matters", "Kwa Nini Kupimwa Mapema ni Muhimu", "Kwa Nini Early Testing ni Muhimu"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>It protects your health.</strong> Most STIs are curable — and treatment is straightforward when caught early.",
      "<strong>Hulinda afya yako.</strong> Magonjwa mengi ya zinaa yanatibika — na matibabu ni rahisi yakigundulika mapema.",
      "<strong>Inalinda health yako.</strong> STIs nyingi zina-cure — na treatment ni rahisi zikigundulika early."),
     ("<strong>It stops you passing it on.</strong> Some infections have no cure but can be managed to lower transmission — HIV, herpes, hepatitis B.",
      "<strong>Huzuia kuwaambukiza wengine.</strong> Baadhi ya maambukizi hayana tiba lakini yanaweza kusimamiwa kupunguza kuenea — VVU, herpes, homa ya ini B.",
      "<strong>Inazuia kupass kwa wengine.</strong> Baadhi ya infections hazina cure lakini zinaweza ku-managiwa kupunguza transmission — HIV, herpes, hepatitis B."),
     ("<strong>It protects your fertility.</strong> Some STIs can make it harder to have children later in life.",
      "<strong>Hulinda uwezo wako wa kuzaa.</strong> Baadhi ya magonjwa ya zinaa yanaweza kufanya iwe vigumu kupata watoto baadaye.",
      "<strong>Inalinda fertility yako.</strong> Baadhi ya STIs zinaweza kufanya iwe ngumu kupata watoto baadaye."),
     ("<strong>Waiting makes it harder.</strong> The longer an infection stays in the body, the harder it can be to treat.",
      "<strong>Kusubiri hufanya iwe vigumu.</strong> Kadri maambukizi yanavyokaa mwilini, ndivyo yanavyoweza kuwa magumu kutibu.",
      "<strong>Kungoja inafanya iwe ngumu.</strong> Kadri infection inavyokaa mwilini, ndivyo inavyoweza kuwa ngumu ku-treat."),
    ]},
    {"type": "example", "title": ("🇰🇪 What to say if a peer suspects something", "🇰🇪 Cha kusema rika akihisi kitu", "🇰🇪 Cha kusema msee akihisi kitu"), "text": (
     "'Go to any health facility near you and follow what the clinician says. Most STIs can be cured — and the sooner you go, the simpler it is.' That is the whole message. You are not diagnosing; you are removing the reason to delay.",
     "'Nenda kituo chochote cha afya karibu nawe na ufuate anachosema daktari. Magonjwa mengi ya zinaa yanatibika — na kadri unavyoenda mapema, ndivyo inavyokuwa rahisi.' Huo ndio ujumbe wote. Hutambui ugonjwa; unaondoa sababu ya kuchelewa.",
     "'Nenda facility yoyote ya afya karibu na wewe na ufuate anachosema daktari. STIs nyingi zina-cure — na kadri unavyoenda mapema, ndivyo inavyokuwa rahisi.' Huo ndio message yote. Huna-diagnose; unaondoa sababu ya kuchelewa.")},
   ]},

  # ── 5. Prevention ─────────────────────────────────────────────────
  {"icon": "🛡️",
   "head": ("Preventing STIs", "Kuzuia Magonjwa ya Zinaa", "Ku-prevent STIs"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Abstinence and self-control</strong> — choosing not to have sex is the only way to be 100% safe",
      "<strong>Kujizuia na kujidhibiti</strong> — kuchagua kutofanya ngono ndiyo njia pekee ya kuwa salama kwa asilimia 100",
      "<strong>Abstinence na self-control</strong> — kuchagua kutofanya sex ndio njia pekee ya kuwa 100% safe"),
     ("<strong>Avoid the risk multipliers</strong> — drugs, alcohol and pornography lead to unsafe choices",
      "<strong>Epuka vinavyoongeza hatari</strong> — dawa za kulevya, pombe na ponografia husababisha maamuzi yasiyo salama",
      "<strong>Avoid risk multipliers</strong> — drugs, pombe na pornography zinasababisha unsafe choices"),
     ("<strong>Faithfulness and communication</strong> — be faithful to one partner and keep talking honestly",
      "<strong>Uaminifu na mawasiliano</strong> — kuwa mwaminifu kwa mwenzi mmoja na endelea kuzungumza kwa ukweli",
      "<strong>Faithfulness na communication</strong> — kuwa faithful kwa partner mmoja na endelea kuongea kwa ukweli"),
     ("<strong>Condoms</strong> — male or female, used correctly and consistently every single time",
      "<strong>Kondomu</strong> — za kiume au za kike, zikitumika kwa usahihi na kila mara",
      "<strong>Condoms</strong> — za kiume ama za kike, zikitumika correctly na kila time"),
     ("<strong>Never share sharp objects</strong> — razors, needles, earrings",
      "<strong>Usishiriki vitu vyenye ncha kali</strong> — wembe, sindano, hereni",
      "<strong>Usishare sharp objects</strong> — wembe, needles, earrings"),
     ("<strong>Vaccination</strong> — HPV and hepatitis B vaccines both prevent viral STIs",
      "<strong>Chanjo</strong> — chanjo za HPV na homa ya ini B zote huzuia magonjwa ya zinaa ya virusi",
      "<strong>Vaccination</strong> — HPV na hepatitis B vaccines zote zina-prevent viral STIs"),
     ("<strong>Mother-to-child transmission</strong> is prevented by early testing, treatment in pregnancy, medicine for the newborn and continued care while breastfeeding",
      "<strong>Maambukizi kutoka mama kwenda mtoto</strong> huzuiwa kwa kupima mapema, matibabu wakati wa ujauzito, dawa kwa mtoto mchanga na huduma endelevu wakati wa kunyonyesha",
      "<strong>Mother-to-child transmission</strong> ina-preventiwa kwa early testing, treatment wakati wa pregnancy, dawa kwa newborn na continued care wakati wa breastfeeding"),
    ]},
    {"type": "facilitator", "minutes": 8, "text": (
     "Use the deck's decision-making steps as a short role play: Stop and think — what could happen? Get the facts. Check your values. Choose safety. Have pairs run it on a real scenario they suggest, not one you supply.",
     "Tumia hatua za kufanya maamuzi za mtaala kama uigizaji mfupi: Simama na ufikiri — nini kinaweza kutokea? Pata ukweli. Angalia maadili yako. Chagua usalama. Waache jozi waendeshe kwa hali halisi wanayopendekeza, si uliyoitoa wewe.",
     "Tumia decision-making steps za deck kama role play fupi: Stop na ufikiri — nini kinaweza kuhappen? Pata facts. Check values zako. Chagua safety. Wacha pairs wa-run kwa real scenario wanayosuggest, si uliyoitoa wewe.")},
   ]},

  # ── 6. Condoms ────────────────────────────────────────────────────
  {"icon": "🛡️",
   "head": ("Condoms and Dual Protection", "Kondomu na Ulinzi Maradufu", "Condoms na Dual Protection"),
   "blocks": [
    {"type": "p", "text": (
     "A condom is a barrier method — worn on the penis (male condom, latex or non-latex for those with a latex allergy) or inserted into the vagina (female condom, made of plastic).",
     "Kondomu ni njia ya kizuizi — huvaliwa kwenye uume (kondomu ya kiume, mpira au isiyo ya mpira kwa wenye mzio) au huingizwa ukeni (kondomu ya kike, iliyotengenezwa kwa plastiki).",
     "Condom ni barrier method — inavaliwa kwa penis (male condom, latex ama non-latex kwa wenye latex allergy) ama inaingizwa kwa vagina (female condom, ya plastic).")},
    {"type": "key_term", "term": ("🔑 Dual Protection", "🔑 Ulinzi Maradufu", "🔑 Dual Protection"), "text": (
     "Condoms protect against infections AND pregnancy at the same time. That makes them unique among contraceptives — no other method does both.",
     "Kondomu hulinda dhidi ya maambukizi NA ujauzito kwa wakati mmoja. Hilo huzifanya za kipekee kati ya njia za uzazi wa mpango — hakuna njia nyingine inayofanya vyote viwili.",
     "Condoms zinalinda dhidi ya infections NA pregnancy kwa wakati mmoja. Hiyo inazifanya unique kati ya contraceptives — hakuna method nyingine inayofanya zote mbili.")},
    {"type": "list", "items": [
     ("Protect against HIV and other STIs",
      "Hulinda dhidi ya VVU na magonjwa mengine ya zinaa",
      "Zinalinda dhidi ya HIV na STIs zingine"),
     ("Prevent unintended pregnancies",
      "Huzuia mimba zisizotarajiwa",
      "Zina-prevent unintended pregnancies"),
     ("Give a person direct control over their own sexual health",
      "Humpa mtu udhibiti wa moja kwa moja wa afya yake ya uzazi",
      "Zinampa msee direct control ya sexual health yake"),
    ]},
    {"type": "warn", "title": ("⚠️ Correct AND consistent", "⚠️ Sahihi NA kila mara", "⚠️ Correct NA consistent"), "text": (
     " Effectiveness drops sharply with incorrect or inconsistent use. 'Most of the time' is not how condoms work — one unprotected occasion is enough. Correct use every single time is the whole message.",
     " Ufanisi hushuka sana kwa matumizi yasiyo sahihi au yasiyo ya kila mara. 'Mara nyingi' si jinsi kondomu zinavyofanya kazi — tukio moja bila kinga linatosha. Matumizi sahihi kila mara ndio ujumbe wote.",
     " Effectiveness inashuka sana na incorrect ama inconsistent use. 'Most of the time' si jinsi condoms zinavyowork — occasion moja bila protection inatosha. Correct use kila time ndio message yote.")},
   ]},

  # ── 7. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "Wafula, 20, tells you he had unprotected sex a month ago but feels completely fine, so he sees no reason to test.",
      "Wafula, miaka 20, anakuambia alifanya ngono bila kinga mwezi mmoja uliopita lakini anajisikia vizuri kabisa, hivyo haoni sababu ya kupimwa.",
      "Wafula, 20, anakuambia alifanya sex bila protection mwezi mmoja uliopita lakini anajiskia poa kabisa, so haoni sababu ya kupimwa."),
     "question": ("What do you tell him?", "Unamwambia nini?", "Unamwambia nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Agree — no symptoms after a month probably means he is clear",
                "Kubaliana — bila dalili baada ya mwezi mmoja labda yuko salama",
                "Agree — bila symptoms baada ya mwezi mmoja labda yuko clear"),
       "outcome": ("Chlamydia and gonorrhoea often produce no symptoms at all, while still damaging the body and spreading to partners. Feeling fine is not evidence. Agreeing here costs him a simple cure now in exchange for a harder problem later.",
                   "Klamidia na kisonono mara nyingi hayaonyeshi dalili kabisa, huku yakiendelea kudhuru mwili na kuenea kwa wenzi. Kujisikia vizuri si ushahidi. Kukubaliana hapa kunamgharimu tiba rahisi sasa badala ya tatizo gumu baadaye.",
                   "Chlamydia na gonorrhea mara nyingi hazionyeshi symptoms kabisa, huku zikiendelea kudhuru mwili na ku-spread kwa partners. Kujiskia poa si evidence. Ku-agree hapa inamgharimu simple cure saa hii badala ya problem ngumu baadaye.")},
      {"kind": "good",
       "text": ("Explain that the commonest STIs are often silent, and testing is the only way to know",
                "Eleza kwamba magonjwa ya zinaa ya kawaida zaidi mara nyingi ni kimya, na kupimwa ndiyo njia pekee ya kujua",
                "Explain ati STIs common zaidi mara nyingi ni silent, na kupimwa ndio njia pekee ya kujua"),
       "outcome": ("You said: 'The two most common ones usually show nothing at all — that's what makes them common. A test takes minutes, and if there's anything it's almost always curable now.' He tested. It was negative, and he stopped treating testing as an admission of something. ✅",
                   "Ulisema: 'Yale mawili ya kawaida zaidi kwa kawaida hayaonyeshi chochote — ndiyo inayoyafanya kuwa ya kawaida. Kipimo huchukua dakika, na kama kuna kitu karibu daima kinatibika sasa.' Alipimwa. Hakuwa nacho, na akaacha kuona kupimwa kama kukiri jambo. ✅",
                   "Ulisema: 'Zile mbili common zaidi kwa kawaida hazionyeshi kitu — ndio inazifanya kuwa common. Test inachukua dakika, na kama kuna kitu karibu daima kina-cure saa hii.' Alipimwa. Hakuwa nayo, na akaacha kuona kupimwa kama ku-admit kitu. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "In a session, a young man says condoms are pointless because 'they fail anyway — my friend used one and his girlfriend still got pregnant.'",
      "Katika kipindi, kijana anasema kondomu hazina maana kwa sababu 'zinashindwa tu — rafiki yangu alitumia moja na mpenzi wake bado akapata mimba.'",
      "Kwa session, msee anasema condoms hazina maana kwa sababu 'zina-fail tu — friend wangu alitumia moja na girlfriend wake bado akapata mimba.'"),
     "question": ("How do you respond?", "Unajibu vipi?", "Una-respond aje?"),
     "choices": [
      {"kind": "bad",
       "text": ("Quote a success percentage and move on",
                "Taja asilimia ya mafanikio na uendelee",
                "Quote success percentage na uendelee"),
       "outcome": ("A statistic does not answer the story he just told, so the room keeps his version. The real issue is hidden in the word 'used one' — a single occasion. Missing that means the myth survives the session intact.",
                   "Takwimu haijibu hadithi aliyoisimulia, hivyo chumba kinabaki na toleo lake. Suala halisi limefichwa katika neno 'alitumia moja' — tukio moja. Kukosa hilo kunamaanisha imani potofu inasalimika kipindi kizima.",
                   "Statistic haijibu story aliyoiambia, so room inabaki na version yake. Real issue imefichwa kwa neno 'alitumia moja' — occasion moja. Ku-miss hiyo inamaanisha myth inasurvive session nzima.")},
      {"kind": "good",
       "text": ("Draw out the difference between using one once and using one every time, correctly",
                "Toa tofauti kati ya kutumia moja mara moja na kutumia kila mara, kwa usahihi",
                "Toa tofauti kati ya kutumia moja mara moja na kutumia kila time, correctly"),
       "outcome": ("You asked: 'Every time, or that time?' He said that time. You said: 'That's the whole thing — effectiveness drops right off with inconsistent or incorrect use. It’s not “most of the time” protection.' The group worked out the rest themselves. ✅",
                   "Uliuliza: 'Kila mara, au mara ile?' Alisema mara ile. Ulisema: 'Hilo ndilo jambo lote — ufanisi hushuka sana kwa matumizi yasiyo ya kila mara au yasiyo sahihi. Si ulinzi wa “mara nyingi”.' Kundi lilijua lililobaki lenyewe. ✅",
                   "Uliuliza: 'Kila time, ama ile time?' Alisema ile time. Ulisema: 'Hiyo ndio kitu chote — effectiveness inashuka sana na inconsistent ama incorrect use. Si “most of the time” protection.' Group ilifigure out iliyobaki wenyewe. ✅")},
     ]},
   ]},

  # ── 8. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("STIs spread through sexual contact — not by hugging or sharing food.",
      "Magonjwa ya zinaa huenea kwa kugusana kingono — si kwa kukumbatiana au kushiriki chakula.",
      "STIs zinaspread kwa sexual contact — si kwa kukumbatiana ama kushare chakula."),
     ("Choosing not to have sex is the only way to be 100% safe from STIs.",
      "Kuchagua kutofanya ngono ndiyo njia pekee ya kuwa salama kwa asilimia 100.",
      "Kuchagua kutofanya sex ndio njia pekee ya kuwa 100% safe."),
     ("Many STIs are silent — regular testing, and testing before a new relationship, is how they are found.",
      "Magonjwa mengi ya zinaa ni kimya — kupimwa mara kwa mara, na kabla ya uhusiano mpya, ndiko kunakoyagundua.",
      "STIs nyingi ni silent — regular testing, na kupimwa kabla ya relationship mpya, ndio inazigundua."),
     ("Most STIs are curable. Complete the treatment, inform partners, and follow up.",
      "Magonjwa mengi ya zinaa yanatibika. Maliza matibabu, wajulishe wenzi, na fuatilia.",
      "STIs nyingi zina-cure. Maliza treatment, inform partners, na follow up."),
     ("Condoms are the only method that prevents both infection and pregnancy — but only with correct, consistent use.",
      "Kondomu ndiyo njia pekee inayozuia maambukizi na ujauzito — lakini kwa matumizi sahihi ya kila mara tu.",
      "Condoms ndio method pekee inayozuia infection na pregnancy — lakini na correct, consistent use tu."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Huwezi kuangalia mtu ukajua. Huwezi kujiangalia mwenyewe ukajua. Kipimo pekee ndicho kinajua — na hicho ndicho kinachofanya kupimwa kuwa kawaida, si kukiri.",
     "Huwezi kumwangalia mtu ukajua. Huwezi kujiangalia mwenyewe ukajua. Kipimo pekee ndicho kinajua — na ndicho kinachofanya kupimwa kuwa kawaida, si kukiri.",
     "Huwezi ku-look msee ukajua. Huwezi kujilook mwenyewe ukajua. Test pekee ndio inajua — na hiyo ndio inafanya kupimwa kuwa normal, si ku-admit kitu.")},
   ]},
 ],

 "quiz": [
  {"q": "What is the main difference between an STI and a UTI?",
   "options": ["STIs are curable, UTIs are not",
               "STIs spread mainly through sexual contact; UTIs can also come from poor hygiene or normal bacteria overgrowth",
               "UTIs only affect women",
               "There is no real difference"],
   "answer": "B",
   "explain": "UTIs can follow sexual contact, but also arise from hygiene or bacterial overgrowth. STIs spread mainly through sexual contact."},

  {"q": "Which two common STIs frequently show no symptoms at all?",
   "options": ["Syphilis and herpes",
               "Chlamydia and gonorrhoea",
               "Candidiasis and pubic lice",
               "Hepatitis B and HPV"],
   "answer": "B",
   "explain": "Both are often completely silent while still damaging the body and spreading to partners — which is why they are so common."},

  {"q": "Which of these can spread an STI? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Unprotected sexual contact",
               "Sharing a desk at school",
               "Sharing razors or needles",
               "Mother to child during pregnancy, birth or breastfeeding",
               "Hugging someone who is infected"],
   "answer": ["A", "C", "D"],
   "explain": "Sharing a desk and hugging carry no risk. Leaving that confusion standing is what fuels the stigma that stops people testing."},

  {"q": "Syphilis can begin as:",
   "options": ["A painful blister that never heals",
               "A painless sore that disappears while the infection stays",
               "A yellow-green discharge only",
               "Severe abdominal pain"],
   "answer": "B",
   "explain": "The sore going away does not mean the infection has. This is exactly why 'it cleared up' is not reassurance."},

  {"q": "What does 'dual protection' mean?",
   "options": ["Using two condoms at once",
               "Protection against both infection and pregnancy at the same time",
               "Both partners being tested",
               "Using a condom plus abstinence"],
   "answer": "B",
   "explain": "Condoms are unique among contraceptives in doing both. Using two condoms at once is in fact unsafe."},

  {"q": "Which are reasons to test early? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Most STIs are curable, and treatment is simpler when caught early",
               "It prevents passing the infection to others",
               "Some STIs can affect fertility later in life",
               "The longer an infection stays, the harder it can be to treat",
               "A negative test means you never need to test again"],
   "answer": ["A", "B", "C", "D"],
   "explain": "A negative result reflects that moment only. Testing is routine, and repeated before new relationships."},

  {"q": "A peer says he used a condom once and his partner still got pregnant, so condoms do not work. What is the key issue?",
   "options": ["He is probably lying",
               "The difference between using one on one occasion and using one correctly every time",
               "Condoms genuinely do not work",
               "He should have used two"],
   "answer": "B",
   "explain": "Effectiveness drops sharply with inconsistent or incorrect use. Condoms are not 'most of the time' protection."},

  {"q": "Which vaccines listed in the curriculum prevent viral STIs?",
   "options": ["Measles and polio",
               "HPV and hepatitis B",
               "BCG and tetanus",
               "Yellow fever and typhoid"],
   "answer": "B",
   "explain": "Both HPV and hepatitis B are vaccine-preventable viral STIs — a rare and powerful prevention tool."},

  {"q": "A peer suspects he has an STI. What is the correct peer educator response?",
   "options": ["Work out which STI it is from his symptoms",
               "Tell him to wait and see whether it clears up",
               "Send him to any nearby health facility and reassure him most STIs are curable",
               "Advise him to buy antibiotics from a chemist"],
   "answer": "C",
   "explain": "Diagnosing is outside your role. Your job is to remove the reason to delay and get him through the door."},

  {"q": "Which statement about asymptomatic STIs is TRUE?",
   "options": ["They cannot be passed to others",
               "They do no harm because there are no symptoms",
               "They still harm the body over time and can still spread",
               "They always develop symptoms within a month"],
   "answer": "C",
   "explain": "No symptoms does not mean no infection. The damage and the transmission both continue silently."},
 ],
}
