# Module 14 (part 1 of 2) — Tuberculosis: What It Is and How to Spot It
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 14.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m14a-tb-what-it-is.html",
 "module_code": "M14",
 "module_slug": "tuberculosis",
 "lesson_slug": "m14a-tb-what-it-is",
 "module_label": "Peer Educator · M14 · Part 1 of 2",
 "title": "Tuberculosis — What It Is and How to Spot It",
 "icon": "🫁",
 "duration": 45,

 "objectives": [
  ("Define tuberculosis and identify where in the body it affects",
   "Fafanua kifua kikuu na utambue mahali mwilini kinapoathiri",
   "Define tuberculosis na utambue mahali mwilini inapoathiri"),
  ("List the signs and symptoms of TB",
   "Orodhesha dalili na ishara za kifua kikuu",
   "List signs na symptoms za TB"),
  ("Describe the types of TB and how it is diagnosed",
   "Eleza aina za kifua kikuu na jinsi kinavyotambuliwa",
   "Describe types za TB na jinsi inavyo-diagnosiwa"),
  ("Correct the common myths about TB",
   "Sahihisha imani potofu za kawaida kuhusu kifua kikuu",
   "Correct common myths kuhusu TB"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> TB is curable, and treatment is free in Kenya. So why is it still among the top ten causes of death in the world?",
  "<strong>🔍 Swali Kubwa:</strong> Kifua kikuu kinatibika, na matibabu ni bure Kenya. Basi kwa nini bado ni kati ya sababu kumi kuu za vifo duniani?",
  "<strong>🔍 Big Question:</strong> TB ina-cure, na treatment ni free Kenya. So kwa nini bado ni kati ya top ten causes za vifo duniani?"),

 "slides": [

  {"icon": "📖",
   "head": ("What TB Is", "Kifua Kikuu ni Nini", "TB ni Nini"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Tuberculosis (TB)", "🔑 Kifua Kikuu (TB)", "🔑 Tuberculosis (TB)"), "text": (
     "An infectious disease that spreads from person to person <strong>through the air</strong>, caused by a bacterium called <em>Mycobacterium tuberculosis</em>.",
     "Ugonjwa wa kuambukiza unaoenea kutoka mtu hadi mtu <strong>kupitia hewa</strong>, unaosababishwa na bakteria aitwaye <em>Mycobacterium tuberculosis</em>.",
     "Infectious disease inayospread kutoka msee hadi msee <strong>kupitia hewa</strong>, inayosababishwa na bacteria anayeitwa <em>Mycobacterium tuberculosis</em>.")},
    {"type": "list", "items": [
     ("TB germs spread in air droplets when an infected person <strong>coughs, breathes, talks, sings or sneezes</strong>",
      "Vijidudu vya TB huenea katika matone ya hewa mtu aliyeambukizwa anapo<strong>kohoa, kupumua, kuzungumza, kuimba au kupiga chafya</strong>",
      "TB germs zinaspread kwa air droplets msee aliyeambukizwa anapo<strong>kohoa, kupumua, kuongea, kuimba ama kupiga chafya</strong>"),
     ("It mainly affects the <strong>lungs</strong>, but can attack almost any living tissue in the body — <strong>except hair, teeth and nails</strong>",
      "Huathiri hasa <strong>mapafu</strong>, lakini kinaweza kushambulia karibu tishu yoyote hai mwilini — <strong>isipokuwa nywele, meno na kucha</strong>",
      "Inaathiri hasa <strong>lungs</strong>, lakini inaweza ku-attack karibu tissue yoyote hai mwilini — <strong>isipokuwa nywele, meno na kucha</strong>"),
     ("It is <strong>one of the top ten causes of death worldwide</strong> — and it is <strong>completely preventable and treatable</strong>",
      "Ni <strong>kati ya sababu kumi kuu za vifo duniani</strong> — na <strong>kinaweza kuzuiwa na kutibiwa kabisa</strong>",
      "Ni <strong>kati ya top ten causes za vifo duniani</strong> — na <strong>inaweza ku-preventiwa na ku-treatiwa kabisa</strong>"),
     ("TB remains a leading health challenge in <strong>high-burden settings like Kenya</strong>",
      "Kifua kikuu bado ni changamoto kuu ya afya katika <strong>maeneo yenye mzigo mkubwa kama Kenya</strong>",
      "TB bado ni leading health challenge kwa <strong>high-burden settings kama Kenya</strong>"),
    ]},
    {"type": "warn", "title": ("⚠️ Airborne, not contact", "⚠️ Kwa hewa, si kwa kugusana", "⚠️ Airborne, si contact"), "text": (
     " <strong>TB does not spread through touch, food, sharing plates or hugs.</strong> It spreads through air. Get this precise, because the wrong version of it is what makes people isolate someone who is already frightened and unwell.",
     " <strong>Kifua kikuu hakiambukizwi kwa kugusana, chakula, kushiriki sahani au kukumbatiana.</strong> Huenea kwa hewa. Fahamu hili kwa usahihi, kwa sababu toleo lisilo sahihi ndilo linalowafanya watu wamtenge aliyekwisha ogopa na kuugua.",
     " <strong>TB haiambukizwi kwa touch, chakula, kushare plates ama hugs.</strong> Inaspread kupitia hewa. Jua hii precisely, kwa sababu wrong version ndio inafanya wasee wam-isolate msee aliyeshaogopa na kuugua.")},
   ]},

  {"icon": "🔍",
   "head": ("Signs and Symptoms", "Dalili na Ishara", "Signs na Symptoms"),
   "blocks": [
    {"type": "p", "text": (
     "Any of these should send someone for screening at the nearest health facility — immediately, not after waiting to see whether it passes.",
     "Yoyote kati ya haya yanapaswa kumpeleka mtu kupimwa kituo cha afya cha karibu — mara moja, si baada ya kusubiri kuona kama yatapita.",
     "Yoyote kati ya haya inafaa kumpeleka msee kupimwa kwa health facility ya karibu — mara moja, si baada ya kungoja kuona kama itapita.")},
    {"type": "list", "items": [
     ("<strong>A cough of any duration</strong> — the curriculum is deliberate here; do not wait for two weeks before acting",
      "<strong>Kikohozi cha muda wowote</strong> — mtaala ni wa makusudi hapa; usisubiri wiki mbili kabla ya kuchukua hatua",
      "<strong>Cough ya duration yoyote</strong> — curriculum ni deliberate hapa; usingoje wiki mbili kabla uchukue hatua"),
     ("<strong>Blood-stained mucus</strong> when coughing",
      "<strong>Makohozi yenye damu</strong> unapokohoa",
      "<strong>Mucus yenye damu</strong> unapokohoa"),
     ("<strong>Unintended weight loss</strong>",
      "<strong>Kupungua uzito bila kukusudia</strong>",
      "<strong>Unintended weight loss</strong>"),
     ("<strong>Drenching night sweats</strong> — soaking, not ordinary warmth",
      "<strong>Jasho jingi usiku</strong> — la kulowanisha, si joto la kawaida",
      "<strong>Drenching night sweats</strong> — la kulowanisha, si joto la kawaida"),
     ("<strong>Hotness of body</strong> — fever",
      "<strong>Joto la mwili</strong> — homa",
      "<strong>Hotness ya mwili</strong> — fever"),
     ("<strong>Chest pain</strong>, and other symptoms depending on which part of the body is infected",
      "<strong>Maumivu ya kifua</strong>, na dalili nyingine kutegemea sehemu ya mwili iliyoambukizwa",
      "<strong>Chest pain</strong>, na symptoms zingine kutegemea sehemu ya mwili iliyoambukizwa"),
    ]},
    {"type": "tip", "title": ("💡 How TB is confirmed", "💡 Jinsi kifua kikuu kinavyothibitishwa", "💡 Jinsi TB ina-confirmiwa"), "text": (
     " TB is confirmed in the laboratory by testing <strong>sputum — kikohozi</strong>. A peer educator does not diagnose TB and cannot tell from symptoms alone. What you can do is recognise the pattern and get the person to a facility where the test happens.",
     " Kifua kikuu huthibitishwa maabara kwa kupima <strong>makohozi — kikohozi</strong>. Mwelimishaji rika hatambui kifua kikuu wala hawezi kujua kwa dalili peke yake. Unachoweza kufanya ni kutambua mchoro na kumfikisha mtu kituoni ambapo kipimo hufanyika.",
     " TB ina-confirmiwa lab kwa ku-test <strong>sputum — kikohozi</strong>. Peer educator ha-diagnose TB wala hawezi kujua kwa symptoms peke yake. Unachoweza kufanya ni ku-recognise pattern na kumfikisha msee facility ambapo test inahappen.")},
   ]},

  {"icon": "🗂️",
   "head": ("The Types of TB", "Aina za Kifua Kikuu", "Types za TB"),
   "blocks": [
    {"type": "table",
     "headers": [("By where it affects", "Kwa mahali inapoathiri", "Kwa mahali inapoathiri"), ("What that means", "Maana yake", "Maana yake")],
     "rows": [
      [("<strong>Pulmonary TB</strong>", "<strong>TB ya mapafu</strong>", "<strong>Pulmonary TB</strong>"),
       ("Affects the lungs — the most common type. It spreads easily to others through the air when the person coughs, sneezes or talks.",
        "Huathiri mapafu — aina ya kawaida zaidi. Huenea kwa urahisi kwa wengine kupitia hewa mtu anapokohoa, kupiga chafya au kuzungumza.",
        "Inaathiri lungs — type ya kawaida zaidi. Inaspread easily kwa wengine kupitia hewa msee anapokohoa, kupiga chafya ama kuongea.")],
      [("<strong>Extra-pulmonary TB</strong>", "<strong>TB ya nje ya mapafu</strong>", "<strong>Extra-pulmonary TB</strong>"),
       ("Affects other parts — brain (TB meningitis), lymph nodes, bones and joints, abdomen, skin or urinary system. <strong>Less contagious, but still serious.</strong>",
        "Huathiri sehemu nyingine — ubongo (homa ya uti wa mgongo ya TB), tezi, mifupa na viungo, tumbo, ngozi au njia ya mkojo. <strong>Huambukiza kidogo, lakini bado ni hatari.</strong>",
        "Inaathiri sehemu zingine — brain (TB meningitis), lymph nodes, mifupa na joints, tumbo, ngozi ama urinary system. <strong>Less contagious, lakini bado serious.</strong>")],
     ]},
    {"type": "table",
     "headers": [("By response to medicine", "Kwa majibu kwa dawa", "Kwa response kwa dawa"), ("What that means", "Maana yake", "Maana yake")],
     "rows": [
      [("<strong>Drug-sensitive TB</strong>", "<strong>TB inayoitikia dawa</strong>", "<strong>Drug-sensitive TB</strong>"),
       ("Treated successfully with the standard TB drugs, <strong>provided free in health facilities</strong>.",
        "Hutibiwa kwa mafanikio kwa dawa za kawaida za TB, <strong>zinazotolewa bure katika vituo vya afya</strong>.",
        "Ina-treatiwa successfully na standard TB drugs, <strong>zinazotolewa free kwa health facilities</strong>.")],
      [("<strong>Drug-resistant TB</strong>", "<strong>TB sugu kwa dawa</strong>", "<strong>Drug-resistant TB</strong>"),
       ("Harder to treat, because the germs no longer respond to the usual medicines. Requires stronger and longer treatment.",
        "Ngumu zaidi kutibu, kwa sababu vijidudu haviitikii tena dawa za kawaida. Inahitaji matibabu makali na marefu zaidi.",
        "Ngumu zaidi ku-treat, kwa sababu germs hazi-respond tena kwa dawa za kawaida. Inahitaji treatment kali na ndefu zaidi.")],
     ]},
    {"type": "warn", "title": ("⚠️ Where drug-resistant TB comes from", "⚠️ TB sugu inatoka wapi", "⚠️ Drug-resistant TB inatoka wapi"), "text": (
     " A major route is people stopping their medicine early because they felt better. The bacteria that survive a half-finished course are the hardest ones — and they are what gets passed on next. That single fact is why adherence is the whole of part 2.",
     " Njia kuu ni watu kuacha dawa mapema kwa sababu walijisikia vizuri. Bakteria wanaonusurika kozi isiyokamilika ndio wagumu zaidi — na ndio hupitishwa baadaye. Ukweli huo mmoja ndiyo sababu kufuata dawa ni sehemu yote ya pili.",
     " Route kuu ni wasee ku-stop dawa mapema kwa sababu walijiskia better. Bacteria wanao-survive half-finished course ndio wagumu zaidi — na ndio zina-passiwa baadaye. Hiyo fact moja ndio sababu adherence ni part yote ya pili.")},
   ]},

  {"icon": "🚫",
   "head": ("Myths and Facts", "Imani Potofu na Ukweli", "Myths na Facts"),
   "blocks": [
    {"type": "table",
     "headers": [("Myth", "Imani potofu", "Myth"), ("Fact", "Ukweli", "Fact")],
     "rows": [
      [("TB only affects old people", "Kifua kikuu huathiri wazee tu", "TB inaathiri wazee tu"),
       ("TB affects <strong>anyone</strong> — including adolescents and young people, whether rich or poor.",
        "Kifua kikuu huathiri <strong>yeyote</strong> — wakiwemo vijana, matajiri au maskini.",
        "TB inaathiri <strong>yeyote</strong> — wakiwemo vijana, matajiri ama maskini.")],
      [("TB is caused by witchcraft", "Kifua kikuu husababishwa na uchawi", "TB inasababishwa na uchawi"),
       ("TB is caused by a bacterium, and it is <strong>treatable</strong>.",
        "Kifua kikuu husababishwa na bakteria, na <strong>kinatibika</strong>.",
        "TB inasababishwa na bacteria, na <strong>ina-treatika</strong>.")],
      [("You can stop the drugs once you feel better", "Unaweza kuacha dawa ukishajisikia vizuri", "Unaweza ku-stop dawa ukishajiskia better"),
       ("<strong>NO.</strong> You must finish all your TB medicine — feeling better is not the same as being cured.",
        "<strong>HAPANA.</strong> Lazima umalize dawa zako zote za TB — kujisikia vizuri si sawa na kupona.",
        "<strong>NO.</strong> Lazima umalize dawa zako zote za TB — kujiskia better si sawa na ku-cure.")],
      [("All TB patients have HIV", "Wagonjwa wote wa TB wana VVU", "TB patients wote wana HIV"),
       ("Not all. However, people with weakened immunity — including those living with HIV — are at <strong>higher risk</strong> of getting TB.",
        "Si wote. Hata hivyo, watu wenye kinga dhaifu — wakiwemo wanaoishi na VVU — wako katika <strong>hatari zaidi</strong> ya kupata TB.",
        "Si wote. However, wasee wenye weakened immunity — wakiwemo wanaoishi na HIV — wako kwa <strong>higher risk</strong> ya kupata TB.")],
     ]},
    {"type": "sheng", "text": (
     "Imani potofu ya nne ndiyo hatari zaidi. Watu wanapodhani TB inamaanisha VVU, wanaacha kupimwa TB kabisa — na wanaenda kufa kwa ugonjwa unaotibika.",
     "Imani potofu ya nne ndiyo hatari zaidi. Watu wanapodhani TB inamaanisha VVU, huacha kupimwa TB kabisa — na huenda kufa kwa ugonjwa unaotibika.",
     "Myth ya nne ndio hatari zaidi. Wasee wanapofikiri TB inamaanisha HIV, wana-stop kupimwa TB kabisa — na wanaenda kufa kwa ugonjwa unao-treatika.")},
   ]},

  {"icon": "⚠️",
   "head": ("Why Young People Are at Risk", "Kwa Nini Vijana Wako Hatarini", "Kwa Nini Vijana Wako at Risk"),
   "blocks": [
    {"type": "p", "text": (
     "Young people are at higher risk for a reason that has nothing to do with their behaviour: <strong>they spend most of their lives in crowded shared spaces</strong> — schools, clubs, dormitories, social gatherings. TB travels in shared air.",
     "Vijana wako katika hatari zaidi kwa sababu isiyohusiana na tabia zao: <strong>hutumia sehemu kubwa ya maisha yao katika maeneo yenye msongamano</strong> — shule, vilabu, mabweni, mikusanyiko. Kifua kikuu husafiri katika hewa inayoshirikiwa.",
     "Vijana wako kwa higher risk kwa sababu isiyohusiana na behaviour yao: <strong>wanatumia sehemu kubwa ya maisha yao kwa crowded shared spaces</strong> — shule, clubs, dorms, gatherings. TB inasafiri kwa shared air.")},
    {"type": "list", "items": [
     ("Young people <strong>living close to someone who is infected</strong>",
      "Vijana <strong>wanaoishi karibu na mtu aliyeambukizwa</strong>",
      "Vijana <strong>wanaoishi karibu na msee aliyeambukizwa</strong>"),
     ("Those with <strong>weakened immunity</strong> — from HIV or other immune-weakening conditions",
      "Wenye <strong>kinga dhaifu</strong> — kutokana na VVU au hali nyingine zinazodhoofisha kinga",
      "Wenye <strong>weakened immunity</strong> — kutokana na HIV ama conditions zingine zinazo-weaken immunity"),
     ("Those who <strong>abuse alcohol, drugs and other harmful substances</strong> — the link back to Module 10",
      "Wanaotumia vibaya <strong>pombe, dawa za kulevya na vitu vingine vyenye madhara</strong> — uhusiano na Moduli 10",
      "Wanaotumia vibaya <strong>pombe, drugs na substances zingine</strong> — link na Module 10"),
    ]},
    {"type": "warn", "title": ("⚠️ What untreated TB does to a young person", "⚠️ TB isiyotibiwa inamfanya nini kijana", "⚠️ Untreated TB inamfanya nini kijana"), "text": (
     " It makes them very sick and very weak, it spreads easily to their family and friends, and <strong>it can kill them</strong>. All three of those are avoidable with a free test and a free course of medicine.",
     " Humfanya awe mgonjwa sana na dhaifu sana, huenea kwa urahisi kwa familia na marafiki zake, na <strong>kinaweza kumuua</strong>. Yote hayo matatu yanaweza kuepukwa kwa kipimo cha bure na kozi ya bure ya dawa.",
     " Inamfanya awe mgonjwa sana na weak sana, inaspread easily kwa family na friends wake, na <strong>inaweza kumuua</strong>. Zote hizo tatu zinaweza ku-avoidiwa na free test na free course ya dawa.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A classmate has been coughing for about ten days, has lost weight, and wakes up with his bedding soaked. He says it is just a cold and it will pass.",
      "Mwanafunzi mwenzako amekuwa akikohoa kwa takriban siku kumi, amepungua uzito, na huamka matandiko yake yakiwa yamelowa. Anasema ni mafua tu na yatapita.",
      "Classmate amekuwa akikohoa kwa karibu siku kumi, amepungua weight, na anaamka bedding yake ikiwa imelowa. Anasema ni cold tu na itapita."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Suggest he waits until the cough has lasted two weeks before going anywhere",
                "Pendekeza asubiri hadi kikohozi kifikie wiki mbili kabla ya kwenda popote",
                "Suggest angoje mpaka cough ifike wiki mbili kabla aende popote"),
       "outcome": ("The curriculum says a cough <em>of any duration</em> with these signs warrants immediate screening — and he has three of them together: cough, weight loss and drenching night sweats. Waiting is more days of him infecting a shared classroom.",
                   "Mtaala unasema kikohozi <em>cha muda wowote</em> pamoja na dalili hizi kinastahili kupimwa mara moja — na ana tatu kati yake pamoja: kikohozi, kupungua uzito na jasho jingi usiku. Kusubiri ni siku zaidi za yeye kuambukiza darasa linaloshirikiwa.",
                   "Curriculum inasema cough <em>ya duration yoyote</em> pamoja na hizi signs inastahili immediate screening — na ana tatu kati yake pamoja: cough, weight loss na drenching night sweats. Kungoja ni siku zaidi za yeye ku-infect shared classroom.")},
      {"kind": "good",
       "text": ("Name the three signs together and get him screened at the nearest facility now",
                "Taja dalili tatu pamoja na umfikishe kupimwa kituo cha karibu sasa",
                "Name signs tatu pamoja na um-fikishe kupimwa facility ya karibu saa hii"),
       "outcome": ("You said: 'A cold doesn't make you lose weight, and it doesn't soak your bedding. Those three together is what they screen for — it's a free sputum test and it takes one visit. If it's nothing, you've lost an afternoon.' It was TB, caught early. ✅",
                   "Ulisema: 'Mafua hayakufanyi upunguze uzito, wala hayalowanishi matandiko. Hizo tatu pamoja ndizo wanazopimia — ni kipimo cha bure cha makohozi na huchukua ziara moja. Kama si kitu, umepoteza alasiri.' Kilikuwa kifua kikuu, kilichogunduliwa mapema. ✅",
                   "Ulisema: 'Cold haikufanyi upunguze weight, wala hailowanishi bedding. Hizo tatu pamoja ndio wanazo-screen — ni free sputum test na inachukua visit moja. Kama si kitu, umepoteza afternoon.' Ilikuwa TB, iliyo-catchiwa early. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A family believes their son's TB was sent by a neighbour through witchcraft, and are taking him to be cleansed rather than to the clinic.",
      "Familia inaamini kifua kikuu cha mwanawe kilitumwa na jirani kupitia uchawi, na wanampeleka kutakaswa badala ya kliniki.",
      "Family inaamini TB ya son wao ilitumwa na neighbour kupitia uchawi, na wanampeleka ku-cleansiwa badala ya clinic."),
     "question": ("How do you approach this?", "Unakabilianaje na hili?", "Una-approach hii aje?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell them witchcraft is not real and they are risking their son's life",
                "Waambie uchawi si kweli na wanahatarisha maisha ya mwanawe",
                "Waambie uchawi si kweli na wana-risk maisha ya son wao"),
       "outcome": ("Attacking the belief head-on makes you an opponent of the family rather than an ally of the boy. They stop telling you where he is, and the one thing that would save him — free medicine — never starts. Being right is not the same as being effective.",
                   "Kushambulia imani moja kwa moja kunakufanya uwe mpinzani wa familia badala ya mshirika wa mvulana. Wanaacha kukuambia alipo, na kitu kimoja kingemwokoa — dawa ya bure — hakianzi kamwe. Kuwa sahihi si sawa na kuwa na ufanisi.",
                   "Ku-attack belief head-on kunakufanya uwe opponent wa family badala ya ally wa mse. Wana-stop kukuambia yuko wapi, na kitu kimoja kingemwokoa — free medicine — haianzi kamwe. Kuwa sahihi si sawa na kuwa effective.")},
      {"kind": "good",
       "text": ("Do not fight the belief — offer the free test as something that costs them nothing to add",
                "Usipigane na imani — toa kipimo cha bure kama kitu kisichowagharimu chochote kuongeza",
                "Usi-fight belief — toa free test kama kitu kisichowa-cost chochote kuongeza"),
       "outcome": ("You said: 'I'm not asking you to stop anything. The test is free and takes one visit — if it's TB, the medicine is free too, and it works. You can do both.' They did the test. He started treatment that week and finished it. ✅",
                   "Ulisema: 'Siwaombi mwache chochote. Kipimo ni bure na huchukua ziara moja — kama ni TB, dawa nayo ni bure, na hufanya kazi. Mnaweza kufanya vyote.' Walifanya kipimo. Alianza matibabu wiki hiyo na akayamaliza. ✅",
                   "Ulisema: 'Siwaombi mwache kitu. Test ni free na inachukua visit moja — kama ni TB, dawa nayo ni free, na inawork. Mnaweza kufanya zote.' Walifanya test. Alianza treatment wiki hiyo na akaimaliza. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("TB spreads through the air — not through touch, food or hugs.",
      "Kifua kikuu huenea kwa hewa — si kwa kugusana, chakula au kukumbatiana.",
      "TB inaspread kupitia hewa — si kwa touch, chakula ama hugs."),
     ("TB can affect anyone, not just adults or people living with HIV.",
      "Kifua kikuu kinaweza kumwathiri yeyote, si watu wazima au wanaoishi na VVU tu.",
      "TB inaweza kuathiri yeyote, si watu wazima ama wanaoishi na HIV tu."),
     ("A cough of any duration, with weight loss or night sweats, means screening today.",
      "Kikohozi cha muda wowote, pamoja na kupungua uzito au jasho la usiku, maana yake kupimwa leo.",
      "Cough ya duration yoyote, na weight loss ama night sweats, inamaanisha screening leo."),
     ("TB is confirmed by a laboratory sputum test — not by looking at someone.",
      "Kifua kikuu huthibitishwa kwa kipimo cha makohozi maabara — si kwa kumtazama mtu.",
      "TB ina-confirmiwa na lab sputum test — si kwa kum-look msee."),
    ]},
    {"type": "p", "text": (
     "Part 2 covers treatment, why finishing the medicine matters so much, contact management and prevention.",
     "Sehemu ya 2 inahusu matibabu, kwa nini kumaliza dawa ni muhimu sana, usimamizi wa waliokutana na mgonjwa na kinga.",
     "Part 2 inacover treatment, kwa nini kumaliza dawa ni muhimu sana, contact management na prevention.")},
   ]},
 ],

 "quiz": [
  {"q": "How does TB spread?",
   "options": ["Through touching an infected person", "Through the air, in droplets when someone coughs, talks, sings or sneezes",
               "Through sharing food", "Through mosquito bites"],
   "answer": "B",
   "explain": "Getting this precise matters — the wrong version is what makes people isolate someone who is already frightened and unwell."},

  {"q": "Which parts of the body can TB NOT affect?",
   "options": ["The brain", "The bones and joints", "Hair, teeth and nails", "The lymph nodes"],
   "answer": "C",
   "explain": "TB mainly affects the lungs but can attack almost any living tissue — except hair, teeth and nails."},

  {"q": "How long must a cough last before TB screening is warranted?",
   "options": ["Two weeks", "One month", "A cough of any duration warrants screening", "Three days"],
   "answer": "C",
   "explain": "The curriculum is deliberate on this. Waiting is more days of transmission in a shared classroom."},

  {"q": "Which are signs and symptoms of TB? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Blood-stained mucus when coughing", "Unintended weight loss",
               "Drenching night sweats", "Chest pain", "Yellowing of the eyes"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Jaundice is a sickle cell sign from Module 8, not TB."},

  {"q": "How is TB confirmed?",
   "options": ["By examining the symptoms", "By a laboratory test on sputum (kikohozi)",
               "By a blood pressure reading", "By an X-ray alone"],
   "answer": "B",
   "explain": "A peer educator does not diagnose TB — you recognise the pattern and get the person to where the test happens."},

  {"q": "What is extra-pulmonary TB?",
   "options": ["A more severe form of lung TB",
               "TB affecting other parts such as the brain, lymph nodes, bones, abdomen or skin — less contagious but still serious",
               "TB that is resistant to drugs",
               "TB in people with HIV"],
   "answer": "B",
   "explain": "Pulmonary TB affects the lungs and spreads easily through air; extra-pulmonary is less contagious but still serious."},

  {"q": "Which of these are MYTHS about TB? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["TB only affects old people", "TB is caused by witchcraft",
               "You can stop the drugs once you feel better", "All TB patients have HIV",
               "TB treatment is free in Kenya"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Free treatment is a fact, not a myth. The HIV myth is the most dangerous — it stops people testing for TB at all."},

  {"q": "Why are adolescents at higher risk of TB?",
   "options": ["Their immune systems are weaker than adults'",
               "They spend most of their lives in crowded shared spaces — schools, clubs, dormitories",
               "They are more likely to smoke",
               "They do not wash their hands"],
   "answer": "B",
   "explain": "It has nothing to do with their behaviour. TB travels in shared air, and young people share a lot of air."},

  {"q": "Where does drug-resistant TB largely come from?",
   "options": ["Being infected by an animal",
               "People stopping their medicine early because they felt better",
               "Taking too much medicine",
               "Living in a city"],
   "answer": "B",
   "explain": "The bacteria that survive a half-finished course are the hardest ones — and they are what gets passed on next."},

  {"q": "A family believes their son's TB came from witchcraft. What is the effective approach?",
   "options": ["Tell them witchcraft is not real",
               "Do not fight the belief — offer the free test as something that costs nothing to add",
               "Report them to the authorities",
               "Wait until the boy gets worse"],
   "answer": "B",
   "explain": "Attacking the belief makes you an opponent of the family rather than an ally of the boy — and the free medicine never starts."},
 ],
}
