# Module 14 (part 2 of 2) — Tuberculosis: Treatment, Prevention and Contact Management
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 14.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m14b-tb-treatment-and-prevention.html",
 "module_code": "M14",
 "module_slug": "tuberculosis",
 "lesson_slug": "m14b-tb-treatment-and-prevention",
 "module_label": "Peer Educator · M14 · Part 2 of 2",
 "title": "Tuberculosis — Treatment and Prevention",
 "icon": "💊",
 "duration": 45,

 "objectives": [
  ("Describe how TB is treated and why finishing the medicine matters",
   "Eleza jinsi kifua kikuu kinavyotibiwa na kwa nini kumaliza dawa ni muhimu",
   "Describe jinsi TB inavyo-treatiwa na kwa nini kumaliza dawa ni muhimu"),
  ("Explain the complications of untreated TB",
   "Eleza matatizo ya kifua kikuu kisichotibiwa",
   "Explain complications za TB isiyo-treatiwa"),
  ("Explain contact management and TB preventive therapy",
   "Eleza usimamizi wa waliokutana na mgonjwa na tiba kinga ya TB",
   "Explain contact management na TB preventive therapy"),
  ("Describe how TB is prevented, and how to support rather than judge",
   "Eleza jinsi kifua kikuu kinavyozuiwa, na jinsi ya kusaidia badala ya kuhukumu",
   "Describe jinsi TB ina-preventiwa, na jinsi ya kusaidia badala ya kujudge"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> The medicine is free and it works. So what is the single most common reason a young person with TB does not get better?",
  "<strong>🔍 Swali Kubwa:</strong> Dawa ni bure na hufanya kazi. Basi ni sababu ipi moja ya kawaida zaidi kijana mwenye kifua kikuu asipopona?",
  "<strong>🔍 Big Question:</strong> Dawa ni free na inawork. So ni sababu ipi moja common zaidi kijana mwenye TB asipo-recover?"),

 "slides": [

  {"icon": "💊",
   "head": ("TB ina TIBA — TB Has a Cure", "TB ina TIBA", "TB ina TIBA — TB Ina Cure"),
   "blocks": [
    {"type": "table",
     "headers": [("Treatment", "Matibabu", "Treatment"), ("What it means for a young person", "Maana yake kwa kijana", "Maana yake kwa kijana")],
     "rows": [
      [("<strong>TB treatment is FREE in Kenya</strong>", "<strong>Matibabu ya TB ni BURE Kenya</strong>", "<strong>TB treatment ni FREE Kenya</strong>"),
       ("Cost is not a reason to stay away. Say this plainly — many families do not know it.",
        "Gharama si sababu ya kukaa mbali. Sema hivi wazi — familia nyingi hazijui.",
        "Cost si sababu ya kukaa mbali. Sema hivi wazi — families nyingi hazijui.")],
      [("<strong>Treatment takes 4 to 9 months</strong>", "<strong>Matibabu huchukua miezi 4 hadi 9</strong>", "<strong>Treatment inachukua miezi 4 hadi 9</strong>"),
       ("This is a long time to keep taking medicine while feeling well — which is exactly where it goes wrong.",
        "Huu ni muda mrefu wa kuendelea kutumia dawa huku ukijisikia vizuri — ndipo hasa mambo huharibika.",
        "Huu ni muda mrefu wa kuendelea kutumia dawa huku ukijiskia poa — ndio hasa mambo yanaharibika.")],
      [("<strong>TB is CURABLE</strong> if the medicine is finished as prescribed",
        "<strong>Kifua kikuu KINATIBIKA</strong> kama dawa itamalizwa kama ilivyoagizwa",
        "<strong>TB INA-CURE</strong> kama dawa itamalizwa kama ilivyo-prescribiwa"),
       ("Not managed. Not controlled. <strong>Cured.</strong> Very few serious diseases offer that.",
        "Si kudhibitiwa. Si kusimamiwa. <strong>Kuponywa.</strong> Magonjwa machache mazito hutoa hilo.",
        "Si ku-managiwa. Si ku-controliwa. <strong>Ku-cure.</strong> Magonjwa machache serious yanatoa hiyo.")],
     ]},
    {"type": "warn", "title": ("⚠️ The answer to the Big Question", "⚠️ Jibu la Swali Kubwa", "⚠️ Jibu la Big Question"), "text": (
     " <strong>Stopping the medicine early because you feel better.</strong> TB medicine makes a person feel well long before the bacteria are gone. Someone who stops at that point is not cured — they relapse, and the germs that survived are the drug-resistant ones. <strong>Never stop TB medicine without a doctor's advice, even if you feel completely fine.</strong>",
     " <strong>Kuacha dawa mapema kwa sababu unajisikia vizuri.</strong> Dawa ya TB humfanya mtu ajisikie vizuri muda mrefu kabla bakteria hawajaisha. Anayeacha wakati huo hajapona — hurudiwa, na vijidudu vilivyonusurika ndivyo sugu kwa dawa. <strong>Usiache kamwe dawa ya TB bila ushauri wa daktari, hata ukijisikia vizuri kabisa.</strong>",
     " <strong>Ku-stop dawa mapema kwa sababu unajiskia better.</strong> TB medicine inamfanya msee ajiskie poa muda mrefu kabla bacteria ziishe. Msee anaye-stop wakati huo haja-cure — ana-relapse, na germs zilizo-survive ndio drug-resistant. <strong>Usi-stop kamwe TB medicine bila advice ya daktari, hata ukijiskia poa kabisa.</strong>")},
    {"type": "sheng", "text": (
     "Kujisikia vizuri si kupona. Ni dawa ikifanya kazi. Ukiacha hapo, unakiruhusu kirudi kikiwa na nguvu zaidi.",
     "Kujisikia vizuri si kupona. Ni dawa ikifanya kazi. Ukiacha hapo, unakiruhusu kirudi kikiwa na nguvu zaidi.",
     "Kujiskia better si ku-cure. Ni dawa iki-work. Uki-stop hapo, unairuhusu irudi ikiwa na nguvu zaidi.")},
   ]},

  {"icon": "🤝",
   "head": ("How a Peer Educator Supports Adherence", "Jinsi Mwelimishaji Rika Anavyounga Mkono Kufuata Dawa", "Jinsi Peer Educator Ana-support Adherence"),
   "blocks": [
    {"type": "p", "text": (
     "Four to nine months of daily medicine is a long time, and most of it is spent feeling perfectly well. This is where a peer genuinely changes an outcome.",
     "Miezi minne hadi tisa ya dawa za kila siku ni muda mrefu, na sehemu kubwa yake hutumika ukijisikia vizuri kabisa. Hapa ndipo rika hubadilisha matokeo kweli.",
     "Miezi minne hadi tisa ya daily medicine ni muda mrefu, na sehemu kubwa yake inatumika ukijiskia poa kabisa. Hapa ndio peer ana-change outcome kweli.")},
    {"type": "list", "items": [
     ("<strong>Ask how the medicine is going</strong>, not how they are feeling — feeling fine is not the measure",
      "<strong>Uliza dawa inaendeleaje</strong>, si wanajisikiaje — kujisikia vizuri si kipimo",
      "<strong>Uliza dawa inaendeleaje</strong>, si wanajiskia aje — kujiskia poa si measure"),
     ("<strong>Know their clinic date</strong> and check in around it",
      "<strong>Jua tarehe yao ya kliniki</strong> na uwaangalie karibu nayo",
      "<strong>Jua clinic date yao</strong> na u-check in karibu nayo"),
     ("<strong>Treat a missed dose as ordinary, not shameful</strong> — someone who expects to be scolded stops telling you",
      "<strong>Chukulia dozi iliyokosekana kama jambo la kawaida, si la aibu</strong> — anayetarajia kukaripiwa huacha kukuambia",
      "<strong>Treat missed dose kama ordinary, si shameful</strong> — msee anayetarajia ku-scoldiwa ana-stop kukuambia"),
     ("<strong>Escalate side effects</strong> to the facility rather than advising on them yourself",
      "<strong>Peleka madhara</strong> kituoni badala ya kushauri wewe mwenyewe",
      "<strong>Escalate side effects</strong> kwa facility badala ya ku-advise wewe mwenyewe"),
     ("<strong>Do not disclose their status to anyone</strong> — Module 16's confidentiality applies here in full",
      "<strong>Usifichue hali yao kwa yeyote</strong> — usiri wa Moduli 16 unatumika hapa kikamilifu",
      "<strong>Usi-disclose status yao kwa yeyote</strong> — confidentiality ya Module 16 inatumika hapa fully"),
    ]},
   ]},

  {"icon": "🫀",
   "head": ("What Happens If It Is Not Treated Properly", "Kinachotokea Kisipotibiwa Ipasavyo", "Kinachohappen Kisipo-treatiwa Properly"),
   "blocks": [
    {"type": "p", "text": (
     "If TB is not treated early and properly, it causes serious and often permanent damage:",
     "Kifua kikuu kisipotibiwa mapema na ipasavyo, husababisha uharibifu mkubwa na mara nyingi wa kudumu:",
     "TB isipo-treatiwa early na properly, inasababisha serious na mara nyingi permanent damage:")},
    {"type": "list", "items": [
     ("<strong>Heart problems</strong>",
      "<strong>Matatizo ya moyo</strong>",
      "<strong>Heart problems</strong>"),
     ("<strong>Fluid around the lungs</strong>, and permanent lung scarring (fibrosis)",
      "<strong>Maji kuzunguka mapafu</strong>, na makovu ya kudumu ya mapafu (fibrosis)",
      "<strong>Fluid kuzunguka lungs</strong>, na permanent lung scarring (fibrosis)"),
     ("<strong>Damage to other organs</strong> — loss of hearing, inflammation of the testes or ovaries, brain damage",
      "<strong>Uharibifu wa viungo vingine</strong> — kupoteza usikivu, kuvimba kwa korodani au ovari, uharibifu wa ubongo",
      "<strong>Damage kwa organs zingine</strong> — kupoteza hearing, inflammation ya testes ama ovaries, brain damage"),
     ("<strong>Death</strong>",
      "<strong>Kifo</strong>",
      "<strong>Kifo</strong>"),
    ]},
    {"type": "tip", "title": ("💡 Use this list carefully", "💡 Tumia orodha hii kwa uangalifu", "💡 Tumia hii list kwa uangalifu"), "text": (
     " This is a frightening list, and fear is a poor motivator on its own — it makes people avoid testing rather than seek it. Pair it every time with the other half of the fact: <strong>all of this is prevented by a free test and a finished course of free medicine.</strong> Fear without a door is just despair.",
     " Hii ni orodha ya kutisha, na hofu peke yake ni kichocheo duni — hufanya watu waepuke kupimwa badala ya kutafuta. Iunganishe kila mara na nusu nyingine ya ukweli: <strong>yote haya huzuiwa kwa kipimo cha bure na kozi iliyokamilika ya dawa za bure.</strong> Hofu bila mlango ni kukata tamaa tu.",
     " Hii ni frightening list, na fear peke yake ni poor motivator — inafanya wasee wa-avoid testing badala ya kui-seek. I-pair kila time na half nyingine ya fact: <strong>yote haya zina-preventiwa na free test na finished course ya free medicine.</strong> Fear bila door ni despair tu.")},
   ]},

  {"icon": "👨‍👩‍👧",
   "head": ("Contact Management", "Usimamizi wa Waliokutana na Mgonjwa", "Contact Management"),
   "blocks": [
    {"type": "key_term", "term": ("🔑 Contact management", "🔑 Usimamizi wa waliokutana na mgonjwa", "🔑 Contact management"), "text": (
     "The process of identifying the close contacts from a household who have been exposed to someone with TB.",
     "Mchakato wa kutambua watu wa karibu wa nyumbani waliokutana na mtu mwenye kifua kikuu.",
     "Process ya ku-identify close contacts wa household waliokuwa exposed kwa msee mwenye TB.")},
    {"type": "table",
     "headers": [("It is done in order to", "Hufanywa ili", "Inafanywa ili"), ("Why that matters", "Kwa nini ni muhimu", "Kwa nini ni muhimu")],
     "rows": [
      [("<strong>Screen those contacts for TB</strong>",
        "<strong>Kuwapima hao watu kifua kikuu</strong>",
        "<strong>Ku-screen hao contacts kwa TB</strong>"),
       ("Someone in the household may already have it without symptoms yet.",
        "Mtu nyumbani anaweza kuwa nacho tayari bila dalili bado.",
        "Msee kwa household anaweza kuwa nayo tayari bila symptoms bado.")],
      [("<strong>Offer TB Preventive Therapy (TPT)</strong>",
        "<strong>Kutoa Tiba Kinga ya TB (TPT)</strong>",
        "<strong>Kutoa TB Preventive Therapy (TPT)</strong>"),
       ("Medicine that stops exposed people developing the disease at all — and stops further transmission in the community.",
        "Dawa inayowazuia walioambukizwa kupata ugonjwa kabisa — na kuzuia kuenea zaidi katika jamii.",
        "Dawa inayozuia exposed people ku-develop disease kabisa — na ku-stop further transmission kwa community.")],
     ]},
    {"type": "warn", "title": ("⚠️ Contacts are not only family", "⚠️ Waliokutana si familia tu", "⚠️ Contacts si family tu"), "text": (
     " The curriculum is explicit that contacts also include <strong>the people a young person spends most of their time with — at school and in the community</strong>. For an adolescent, that is a classroom and a dormitory, not just a home. If a classmate is diagnosed, the class is a contact group, and saying so is not gossip — it is how transmission stops.",
     " Mtaala uko wazi kwamba waliokutana pia ni pamoja na <strong>watu ambao kijana hutumia muda mwingi nao — shuleni na katika jamii</strong>. Kwa kijana, hilo ni darasa na bweni, si nyumba tu. Mwanafunzi mwenzako akigunduliwa, darasa ni kundi la waliokutana, na kusema hivyo si kusengenya — ndivyo kuenea kunavyokoma.",
     " Curriculum iko wazi ati contacts pia ni pamoja na <strong>wasee ambao kijana anatumia time nyingi nao — shuleni na kwa community</strong>. Kwa kijana, hiyo ni classroom na dorm, si nyumba tu. Classmate aki-diagnosiwa, class ni contact group, na kusema hivyo si gossip — ndio jinsi transmission ina-stop.")},
   ]},

  {"icon": "🛡️",
   "head": ("Prevention", "Kinga", "Prevention"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>BCG vaccine</strong>, given at birth, protects against the severe forms of TB",
      "<strong>Chanjo ya BCG</strong>, inayotolewa wakati wa kuzaliwa, hulinda dhidi ya aina kali za kifua kikuu",
      "<strong>BCG vaccine</strong>, inayotolewa wakati wa kuzaliwa, inalinda dhidi ya severe forms za TB"),
     ("<strong>Proper ventilation — open the windows, let air flow.</strong> The single cheapest and most effective thing a school can do",
      "<strong>Uingizaji hewa mzuri — fungua madirisha, ruhusu hewa ipite.</strong> Jambo la bei nafuu na lenye ufanisi zaidi shule inaweza kufanya",
      "<strong>Proper ventilation — fungua windows, wacha hewa i-flow.</strong> Kitu cha bei nafuu na effective zaidi shule inaweza kufanya"),
     ("<strong>Wearing a mask</strong> in high-risk areas",
      "<strong>Kuvaa barakoa</strong> katika maeneo yenye hatari kubwa",
      "<strong>Kuvaa mask</strong> kwa high-risk areas"),
     ("<strong>Cough etiquette</strong> — covering the mouth when coughing",
      "<strong>Adabu za kukohoa</strong> — kufunika mdomo unapokohoa",
      "<strong>Cough etiquette</strong> — kufunika mdomo unapokohoa"),
     ("<strong>Adherence to medication</strong>, so TB is not passed to healthy people",
      "<strong>Kufuata dawa</strong>, ili kifua kikuu kisipitishwe kwa watu wenye afya",
      "<strong>Adherence kwa medication</strong>, ili TB isi-passiwe kwa healthy people"),
    ]},
    {"type": "facilitator", "minutes": 10, "text": (
     "Do the ventilation audit with the group in the room you are sitting in. How many windows are there, how many are open, and who decided that? In most Kenyan classrooms the answer is that they are shut because of noise or cold, and nobody has ever weighed that against TB. It is the one prevention step the group can change today, themselves, for free.",
     "Fanya ukaguzi wa uingizaji hewa na kundi katika chumba mnamokaa. Kuna madirisha mangapi, mangapi yamefunguliwa, na nani aliamua hivyo? Katika madarasa mengi ya Kenya jibu ni kwamba yamefungwa kwa sababu ya kelele au baridi, na hakuna aliyewahi kupima hilo dhidi ya kifua kikuu. Ni hatua moja ya kinga ambayo kundi linaweza kuibadilisha leo, wenyewe, bure.",
     "Fanya ventilation audit na group kwa room mnamokaa. Kuna windows ngapi, ngapi zimefunguliwa, na nani ali-decide hivyo? Kwa classrooms nyingi za Kenya answer ni ati zimefungwa kwa sababu ya kelele ama baridi, na hakuna msee amewahi ku-weigh hiyo dhidi ya TB. Ni prevention step moja ambayo group inaweza kui-change leo, wenyewe, free.")},
   ]},

  {"icon": "🎯",
   "head": ("Zero TB Deaths, Zero TB Disease, Zero TB Suffering", "Sifuri Vifo, Sifuri Ugonjwa, Sifuri Mateso", "Zero TB Deaths, Zero TB Disease, Zero TB Suffering"),
   "blocks": [
    {"type": "p", "text": (
     "Those are Kenya's national and the global TB elimination goals. Notice that the third one — <strong>zero TB suffering</strong> — is not about the bacteria at all. It is about how people with TB are treated by everyone around them.",
     "Hayo ni malengo ya kitaifa ya Kenya na ya kimataifa ya kutokomeza kifua kikuu. Angalia kwamba la tatu — <strong>sifuri mateso ya TB</strong> — halihusu bakteria kabisa. Linahusu jinsi watu wenye TB wanavyotendewa na wote waliowazunguka.",
     "Hayo ni national goals za Kenya na global TB elimination goals. Angalia ati la tatu — <strong>zero TB suffering</strong> — halihusu bacteria kabisa. Linahusu jinsi wasee wenye TB wanavyotendewa na wote waliowazunguka.")},
    {"type": "warn", "title": ("⚠️ The part that belongs to you", "⚠️ Sehemu inayokuhusu wewe", "⚠️ Part inayokuhusu wewe"), "text": (
     " You cannot deliver zero deaths or zero disease on your own — those need clinics, drugs and systems. <strong>Zero suffering is largely stigma, and stigma is made of what people say in classrooms and at home.</strong> That one is genuinely within your reach, and it starts with correcting the airborne-not-contact fact every single time you hear it wrong.",
     " Huwezi kufikisha sifuri vifo au sifuri ugonjwa peke yako — hayo yanahitaji kliniki, dawa na mifumo. <strong>Sifuri mateso ni unyanyapaa kwa kiasi kikubwa, na unyanyapaa umeundwa na yale watu husema madarasani na nyumbani.</strong> Hilo liko ndani ya uwezo wako kweli, na huanza kwa kusahihisha ukweli wa hewa-si-kugusana kila mara unaposikia vibaya.",
     " Huwezi ku-deliver zero deaths ama zero disease peke yako — hizo zinahitaji clinics, dawa na systems. <strong>Zero suffering ni stigma kwa kiasi kikubwa, na stigma ime-madiwa na yale wasee wanasema classrooms na nyumbani.</strong> Hiyo iko ndani ya reach yako kweli, na inaanza kwa ku-correct fact ya airborne-si-contact kila time unasikia vibaya.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "Your friend started TB treatment two months ago. He tells you he feels completely fine now and is thinking of stopping — the tablets make him nauseous and he has four months left.",
      "Rafiki yako alianza matibabu ya TB miezi miwili iliyopita. Anakuambia sasa anajisikia vizuri kabisa na anafikiria kuacha — vidonge vinamletea kichefuchefu na amebakiza miezi minne.",
      "Friend wako alianza TB treatment miezi miwili iliyopita. Anakuambia saa hii anajiskia poa kabisa na anafikiria ku-stop — tablets zinamletea nausea na amebakiza miezi minne."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell him to push through and take them anyway — it is only four more months",
                "Mwambie avumilie na azitumie hata hivyo — ni miezi minne tu zaidi",
                "Mwambie a-push through na azitumie anyway — ni miezi minne tu zaidi"),
       "outcome": ("You addressed the wrong problem. Feeling better is only half of what he said — the nausea is a side effect, and side effects can often be managed at the facility. Telling him to endure it silently makes stopping more likely, not less.",
                   "Ulishughulikia tatizo lisilo sahihi. Kujisikia vizuri ni nusu tu ya aliyosema — kichefuchefu ni athari ya dawa, na athari mara nyingi zinaweza kudhibitiwa kituoni. Kumwambia avumilie kimya kunafanya kuacha kuwe na uwezekano zaidi, si mdogo.",
                   "Uli-address wrong problem. Kujiskia better ni half tu ya alichosema — nausea ni side effect, na side effects mara nyingi zinaweza ku-managiwa kwa facility. Kumwambia a-endure kimya kunafanya ku-stop kuwe likely zaidi, si less.")},
      {"kind": "good",
       "text": ("Explain what stopping actually causes, and get the nausea reviewed at the clinic",
                "Eleza kuacha kunasababisha nini hasa, na ufanye kichefuchefu kikaguliwe kliniki",
                "Explain ku-stop kunasababisha nini hasa, na u-get nausea i-reviewiwe clinic"),
       "outcome": ("You said: 'Feeling fine is the medicine working, not the TB being gone. If you stop now it comes back stronger and harder to treat. But the nausea is a real thing — tell the clinic, they can often change something. Let's go on your next date.' They adjusted his regimen. He finished. ✅",
                   "Ulisema: 'Kujisikia vizuri ni dawa ikifanya kazi, si TB kuisha. Ukiacha sasa kitarudi kikiwa na nguvu zaidi na kigumu kutibu. Lakini kichefuchefu ni jambo halisi — waambie kliniki, mara nyingi wanaweza kubadilisha kitu. Twende siku yako ijayo.' Walirekebisha dawa zake. Alimaliza. ✅",
                   "Ulisema: 'Kujiskia poa ni dawa iki-work, si TB kuisha. Uki-stop saa hii itarudi ikiwa na nguvu zaidi na ngumu ku-treat. Lakini nausea ni kitu real — ambia clinic, mara nyingi wanaweza ku-change kitu. Twende date yako ijayo.' Wali-adjust regimen yake. Alimaliza. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A pupil in your class is diagnosed with TB. Others start moving their desks away and refusing to share anything with him.",
      "Mwanafunzi darasani kwako amegunduliwa na kifua kikuu. Wengine wanaanza kusogeza madawati yao mbali na kukataa kushiriki chochote naye.",
      "Student kwa class yako ame-diagnosiwa na TB. Wengine wanaanza ku-move desks zao mbali na ku-refuse kushare kitu naye."),
     "question": ("What is the right response?", "Jibu sahihi ni lipi?", "Response sahihi ni ipi?"),
     "choices": [
      {"kind": "bad",
       "text": ("Say nothing about his diagnosis and quietly let the class settle down on its own",
                "Usiseme lolote kuhusu ugonjwa wake na uache darasa litulie lenyewe kimya",
                "Usiseme kitu kuhusu diagnosis yake na uache class itulie yenyewe kimya"),
       "outcome": ("It will not settle. The class already knows, and the belief driving them — that TB spreads by contact — is wrong and correctable. Silence leaves a sick teenager isolated during a nine-month treatment course, which is exactly the 'TB suffering' the national goal names.",
                   "Halitatulia. Darasa tayari linajua, na imani inayowasukuma — kwamba TB huenea kwa kugusana — si sahihi na inaweza kusahihishwa. Ukimya humwacha kijana mgonjwa ametengwa wakati wa kozi ya matibabu ya miezi tisa, ambayo ndiyo hasa 'mateso ya TB' lengo la kitaifa linalotaja.",
                   "Haitatulia. Class tayari inajua, na belief inayowa-drive — ati TB inaspread kwa contact — si sahihi na inaweza ku-correctiwa. Silence inamwacha teenager mgonjwa isolated wakati wa nine-month treatment course, ambayo ndio hasa 'TB suffering' national goal inayo-name.")},
      {"kind": "good",
       "text": ("Correct the transmission facts to the whole class, and open the windows",
                "Sahihisha ukweli wa maambukizi kwa darasa zima, na ufungue madirisha",
                "Correct transmission facts kwa class nzima, na ufungue windows"),
       "outcome": ("You said: 'TB is airborne, not contact. You cannot get it from his desk, his book or his plate. What actually reduces risk in this room is air — so open the windows.' You opened them. The desks came back within a week, and the ventilation stayed. ✅",
                   "Ulisema: 'TB huenea kwa hewa, si kwa kugusana. Huwezi kukipata kutoka dawati lake, kitabu chake au sahani yake. Kinachopunguza hatari chumbani humu ni hewa — kwa hivyo fungueni madirisha.' Uliyafungua. Madawati yalirudi ndani ya wiki, na uingizaji hewa ukabaki. ✅",
                   "Ulisema: 'TB ni airborne, si contact. Huwezi kuipata kutoka desk yake, book yake ama plate yake. Kinachopunguza risk kwa hii room ni hewa — so fungueni windows.' Uliyafungua. Desks zilirudi ndani ya wiki, na ventilation ika-stay. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("TB is curable, and treatment is free in Kenya.",
      "Kifua kikuu kinatibika, na matibabu ni bure Kenya.",
      "TB ina-cure, na treatment ni free Kenya."),
     ("Treatment takes 4 to 9 months — and you must finish it, even when you feel completely well.",
      "Matibabu huchukua miezi 4 hadi 9 — na lazima uyamalize, hata ukijisikia vizuri kabisa.",
      "Treatment inachukua miezi 4 hadi 9 — na lazima uimalize, hata ukijiskia poa kabisa."),
     ("Stopping early causes relapse and drug-resistant TB. Never stop without a doctor's advice.",
      "Kuacha mapema husababisha kurudiwa na TB sugu. Usiache kamwe bila ushauri wa daktari.",
      "Ku-stop early kunasababisha relapse na drug-resistant TB. Usi-stop kamwe bila advice ya daktari."),
     ("Contact management screens the household — and for a young person, the classroom counts too.",
      "Usimamizi wa waliokutana hupima nyumba — na kwa kijana, darasa nalo linahesabika.",
      "Contact management ina-screen household — na kwa kijana, classroom nayo ina-count."),
     ("Early testing and treatment save lives. Supporting, rather than judging, someone with TB helps break the stigma.",
      "Kupimwa na kutibiwa mapema huokoa maisha. Kumsaidia, badala ya kumhukumu, mwenye TB husaidia kuvunja unyanyapaa.",
      "Early testing na treatment zinaokoa maisha. Ku-support, badala ya ku-judge, msee mwenye TB inasaidia ku-break stigma."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Fungua dirisha. Maliza dawa. Kaa karibu na rafiki yako. Hivyo vitatu ndivyo vinavyokomesha kifua kikuu.",
     "Fungua dirisha. Maliza dawa. Kaa karibu na rafiki yako. Hivyo vitatu ndivyo vinavyokomesha kifua kikuu.",
     "Fungua window. Maliza dawa. Kaa karibu na friend wako. Hizo tatu ndizo zina-stop TB.")},
   ]},
 ],

 "quiz": [
  {"q": "How long does TB treatment take?",
   "options": ["2 weeks", "1 to 2 months", "4 to 9 months", "Lifelong"],
   "answer": "C",
   "explain": "Most of that time is spent feeling perfectly well — which is exactly where adherence fails."},

  {"q": "What is the most common reason a young person with TB does not get better?",
   "options": ["The medicine does not work",
               "They stop taking it early because they feel better",
               "They cannot afford it",
               "They are misdiagnosed"],
   "answer": "B",
   "explain": "Feeling better is the medicine working, not the TB being gone. Treatment is free, so cost is not the barrier."},

  {"q": "What does stopping TB medicine early cause?",
   "options": ["Nothing, if you feel well",
               "Relapse, and drug-resistant TB — the surviving bacteria are the hardest to treat",
               "A shorter second course",
               "Immunity to TB"],
   "answer": "B",
   "explain": "Never stop TB medicine without a doctor's advice, even if you feel completely fine."},

  {"q": "Which are complications of untreated TB? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Heart problems", "Fluid around the lungs and permanent scarring",
               "Loss of hearing and brain damage", "Death", "Improved immunity"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Always pair this list with the other half of the fact: all of it is prevented by a free test and a finished free course."},

  {"q": "What is TB Preventive Therapy (TPT) for?",
   "options": ["Treating active TB",
               "Stopping exposed contacts from developing the disease at all",
               "Replacing the BCG vaccine",
               "Treating drug-resistant TB"],
   "answer": "B",
   "explain": "It is offered through contact management, and it stops further transmission in the community."},

  {"q": "Who counts as a contact for an adolescent with TB?",
   "options": ["Only household members",
               "Household members, and the people they spend most time with at school and in the community",
               "Only people they have touched",
               "Only family members with symptoms"],
   "answer": "B",
   "explain": "For an adolescent that means a classroom and a dormitory, not just a home."},

  {"q": "Which are TB prevention measures? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["BCG vaccine at birth", "Proper ventilation — opening windows",
               "Cough etiquette", "Wearing a mask in high-risk areas", "Avoiding shared plates"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Shared plates carry no TB risk — TB is airborne. Ventilation is the cheapest and most effective step a school can take."},

  {"q": "A friend on TB treatment wants to stop because of nausea and feeling well. What should you do?",
   "options": ["Tell him to endure it silently for four more months",
               "Explain what stopping causes, and get the nausea reviewed at the clinic",
               "Agree he can stop since he feels fine",
               "Tell him to halve the dose"],
   "answer": "B",
   "explain": "Side effects are real and often manageable. Telling him to endure it silently makes stopping more likely, not less."},

  {"q": "Classmates move their desks away from a pupil diagnosed with TB. What is the right response?",
   "options": ["Say nothing and let it settle",
               "Correct the transmission facts to the whole class, and open the windows",
               "Move him to the back of the room",
               "Ask him to stay home"],
   "answer": "B",
   "explain": "TB is airborne, not contact — and air, not distance from a desk, is what actually reduces risk in that room."},

  {"q": "Of the three national goals — zero TB deaths, zero TB disease, zero TB suffering — which is most within a peer educator's reach?",
   "options": ["Zero deaths", "Zero disease", "Zero suffering", "None of them"],
   "answer": "C",
   "explain": "Deaths and disease need clinics, drugs and systems. Suffering is largely stigma, and stigma is made of what people say in classrooms and at home."},
 ],
}
