# Module 15 — Accidents, Injuries and Emergencies
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 15.
# Trilingual: English / Kiswahili / Sheng.
#
# SCOPE NOTE: the deck lists first aid (ABC, CPR, wound care) as a
# demonstration. CPR cannot be learned from a slide. This lesson explains what
# the skills are and why they matter, and routes learners to hands-on
# certification — consistent with the role boundaries in M1, M13B and M9.

LESSON = {
 "file": "m15-accidents-and-emergencies.html",
 "module_code": "M15",
 "module_slug": "accidents-and-emergencies",
 "lesson_slug": "m15-accidents-and-emergencies",
 "module_label": "Peer Educator · Module 15 of 19",
 "title": "Accidents, Injuries and Emergencies",
 "icon": "🚑",
 "duration": 60,

 "objectives": [
  ("Identify common types of accidents and injuries",
   "Tambua aina za kawaida za ajali na majeraha",
   "Tambua types za kawaida za accidents na injuries"),
  ("Explain the causes and risk factors in schools, homes and communities",
   "Eleza sababu na hatari shuleni, nyumbani na katika jamii",
   "Explain causes na risk factors shuleni, nyumbani na kwa community"),
  ("Demonstrate prevention strategies for different environments",
   "Onyesha mbinu za kuzuia kwa mazingira tofauti",
   "Onyesha prevention strategies kwa environments tofauti"),
  ("Recognise an emergency and know how to summon help in time",
   "Tambua dharura na ujue jinsi ya kuomba msaada kwa wakati",
   "Tambua emergency na ujue jinsi ya kuomba msaada kwa wakati"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> Most injuries that reach a Kenyan hospital were predictable an hour earlier. So what is it that people fail to see?",
  "<strong>🔍 Swali Kubwa:</strong> Majeraha mengi yanayofika hospitali Kenya yalikuwa yanatabirika saa moja mapema. Basi ni nini watu wanaposhindwa kuona?",
  "<strong>🔍 Big Question:</strong> Injuries nyingi zinazofika hospital Kenya zilikuwa predictable hour moja mapema. So ni nini wasee wanashindwa kuona?"),

 "slides": [

  {"icon": "📖",
   "head": ("Three Words", "Maneno Matatu", "Maneno Matatu"),
   "blocks": [
    {"type": "table",
     "headers": [("Term", "Neno", "Term"), ("Meaning", "Maana", "Maana")],
     "rows": [
      [("Accident", "Ajali", "Accident"),
       ("An unexpected event that occurs suddenly and can cause harm to people, property or the environment.",
        "Tukio lisilotarajiwa linalotokea ghafla na linaloweza kudhuru watu, mali au mazingira.",
        "Unexpected event inayohappen ghafla na inayoweza kudhuru wasee, property ama environment.")],
      [("Injury", "Jeraha", "Injury"),
       ("Physical harm or damage to the body resulting from an accident or an unsafe action.",
        "Madhara ya kimwili au uharibifu wa mwili unaotokana na ajali au kitendo kisicho salama.",
        "Physical harm ama damage kwa mwili inayotokana na accident ama unsafe action.")],
      [("Emergency", "Dharura", "Emergency"),
       ("A sudden, unexpected situation requiring immediate action to prevent loss of life, serious injury or further harm.",
        "Hali ya ghafla, isiyotarajiwa inayohitaji hatua ya haraka kuzuia kupoteza maisha, jeraha kubwa au madhara zaidi.",
        "Sudden, unexpected situation inayohitaji immediate action ku-prevent kupoteza maisha, serious injury ama further harm.")],
     ]},
    {"type": "p", "text": (
     "Injuries range from minor cuts and bruises to fractures, burns, head trauma and poisoning. They affect not only the person but their family, school and community — through lost productivity, medical costs and emotional strain.",
     "Majeraha huanzia mikato midogo na michubuko hadi mivunjiko, kuungua, jeraha la kichwa na sumu. Huathiri si mtu tu bali familia yake, shule na jamii — kupitia uzalishaji uliopotea, gharama za matibabu na mzigo wa kihisia.",
     "Injuries zinaanzia minor cuts na bruises hadi fractures, burns, head trauma na poisoning. Zinaathiri si msee tu bali family yake, shule na community — kupitia lost productivity, medical costs na emotional strain.")},
   ]},

  {"icon": "🚗",
   "head": ("What Actually Injures Young Kenyans", "Kinachowajeruhi Vijana wa Kenya Hasa", "Kinachowa-injure Vijana wa Kenya Hasa"),
   "blocks": [
    {"type": "table",
     "headers": [("Type", "Aina", "Type"), ("What it looks like here", "Inavyoonekana hapa", "Inavyoonekana hapa")],
     "rows": [
      [("Road traffic", "Ajali za barabarani", "Road traffic"),
       ("Pedestrian knockdowns, <strong>boda boda</strong> crashes, passenger injuries in matatus and cars. Causes: over-speeding, distracted walking or driving, no helmet, unsafe crossings, driving unqualified or under the influence.",
        "Watembea kwa miguu kugongwa, ajali za <strong>boda boda</strong>, majeraha ya abiria katika matatu na magari. Sababu: mwendo kasi, kutembea au kuendesha bila umakini, bila kofia, kuvuka pasipo salama, kuendesha bila sifa au ukiwa umelewa.",
        "Pedestrian knockdowns, <strong>boda boda</strong> crashes, passenger injuries kwa matatu na magari. Causes: over-speeding, distracted walking ama driving, bila helmet, unsafe crossings, kuendesha bila qualification ama ukiwa umelewa.")],
      [("Sports, recreation and falls", "Michezo, burudani na kuanguka", "Sports, recreation na falls"),
       ("Sprains, fractures, concussions and dislocations — common in football, athletics, cycling. Falls from trees, rooftops, stairs and playground equipment.",
        "Kuteguka, mivunjiko, mtikisiko wa ubongo na kutengana kwa viungo — kawaida katika mpira, riadha, baiskeli. Kuanguka kutoka miti, paa, ngazi na vifaa vya kuchezea.",
        "Sprains, fractures, concussions na dislocations — common kwa football, athletics, cycling. Falls kutoka miti, rooftops, stairs na playground equipment.")],
      [("Burns and scalds", "Kuungua", "Burns na scalds"),
       ("Open-fire cooking, kerosene stoves, hot liquids, electrical faults. <strong>Burns are a major cause of disability among Kenyan youth</strong> (MOH Burns Registry, 2019).",
        "Kupika kwa moto wazi, majiko ya mafuta ya taa, vimiminika moto, hitilafu za umeme. <strong>Kuungua ni sababu kubwa ya ulemavu kwa vijana wa Kenya</strong> (MOH Burns Registry, 2019).",
        "Open-fire cooking, kerosene stoves, hot liquids, electrical faults. <strong>Burns ni major cause ya disability kwa vijana wa Kenya</strong> (MOH Burns Registry, 2019).")],
      [("Drowning", "Kuzama", "Drowning"),
       ("Swimming in rivers, dams or lakes without supervision; flood-related drowning in areas such as Budalangi and Tana River County.",
        "Kuogelea mitoni, mabwawani au maziwani bila usimamizi; kuzama kutokana na mafuriko katika maeneo kama Budalangi na Kaunti ya Tana River.",
        "Kuogelea rivers, dams ama lakes bila supervision; flood-related drowning kwa areas kama Budalangi na Tana River County.")],
      [("Poisoning", "Sumu", "Poisoning"),
       ("Household chemicals — detergents, pesticides. Snake bites and insect stings, notably in rural and pastoralist regions.",
        "Kemikali za nyumbani — sabuni, dawa za wadudu. Kuumwa na nyoka na wadudu, hasa maeneo ya vijijini na ya wafugaji.",
        "Household chemicals — detergents, pesticides. Snake bites na insect stings, hasa rural na pastoralist regions.")],
      [("Violence and assault", "Ukatili na mashambulizi", "Violence na assault"),
       ("Cuts, bruises and fractures from fights, and injuries from gender-based violence — see Module 12.",
        "Mikato, michubuko na mivunjiko kutokana na mapigano, na majeraha ya ukatili wa kijinsia — angalia Moduli 12.",
        "Cuts, bruises na fractures kutokana na fights, na injuries za gender-based violence — angalia Module 12.")],
      [("Choking and breathing", "Kukwama na kupumua", "Choking na breathing"),
       ("Choking on food or small objects; asthma attacks and allergic reactions.",
        "Kukwama na chakula au vitu vidogo; mashambulizi ya pumu na mzio.",
        "Choking na chakula ama vitu vidogo; asthma attacks na allergic reactions.")],
     ]},
   ]},

  {"icon": "🫁",
   "head": ("Recognising a Breathing Emergency", "Kutambua Dharura ya Kupumua", "Ku-recognise Breathing Emergency"),
   "blocks": [
    {"type": "p", "text": (
     "This is the one where minutes decide the outcome, so learn the signs precisely.",
     "Hii ndiyo ambapo dakika huamua matokeo, hivyo jifunze dalili kwa usahihi.",
     "Hii ndio ambapo dakika zina-decide outcome, so jifunze signs kwa usahihi.")},
    {"type": "list", "items": [
     ("Difficulty breathing, speaking or coughing",
      "Ugumu wa kupumua, kuzungumza au kukohoa",
      "Ugumu wa kupumua, kuongea ama kukohoa"),
     ("A red, puffy face — then skin turning blue as oxygen runs out",
      "Uso mwekundu, uliovimba — kisha ngozi kuwa buluu oksijeni inapoisha",
      "Uso mwekundu, puffy — kisha ngozi kuwa blue oxygen inapoisha"),
     ("Wheezing or noisy breathing; chest tightness and pain",
      "Kupumua kwa mluzi au kwa kelele; kifua kubana na maumivu",
      "Wheezing ama noisy breathing; chest tightness na pain"),
     ("Extreme fatigue and confusion from lack of oxygen",
      "Uchovu mkubwa na kuchanganyikiwa kutokana na ukosefu wa oksijeni",
      "Extreme fatigue na confusion kutokana na ukosefu wa oxygen"),
     ("<strong>Signs of distress</strong> — pointing to the throat or grasping the neck",
      "<strong>Dalili za dhiki</strong> — kuonyesha koo au kushika shingo",
      "<strong>Signs za distress</strong> — kuonyesha koo ama kushika shingo"),
    ]},
    {"type": "warn", "title": ("⚠️ Someone choking may make no sound at all", "⚠️ Anayekwama anaweza asitoe sauti kabisa", "⚠️ Msee anaye-choke anaweza asitoe sauti kabisa"), "text": (
     " A person coughing forcefully still has an airway. A person who cannot cough, speak or breathe is the emergency — and they will be silent. Hands at the throat is the universal signal. Do not wait for noise.",
     " Mtu anayekohoa kwa nguvu bado ana njia ya hewa. Mtu asiyeweza kukohoa, kuzungumza wala kupumua ndiye dharura — na atakuwa kimya. Mikono kooni ndiyo ishara ya kimataifa. Usisubiri kelele.",
     " Msee anayekohoa kwa nguvu bado ana airway. Msee asiyeweza kukohoa, kuongea wala kupumua ndio emergency — na atakuwa kimya. Mikono kooni ndio universal signal. Usingoje kelele.")},
   ]},

  {"icon": "⚠️",
   "head": ("Why Accidents Happen", "Kwa Nini Ajali Hutokea", "Kwa Nini Accidents Zinahappen"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Unsafe environments</strong> — poor lighting, no pedestrian crossings",
      "<strong>Mazingira yasiyo salama</strong> — mwanga hafifu, hakuna vivuko vya watembea kwa miguu",
      "<strong>Unsafe environments</strong> — poor lighting, hakuna pedestrian crossings"),
     ("<strong>Risk-taking behaviour</strong> — swimming in unsafe water, playing near roads",
      "<strong>Tabia za kuhatarisha</strong> — kuogelea majini yasiyo salama, kucheza karibu na barabara",
      "<strong>Risk-taking behaviour</strong> — kuogelea kwa unsafe water, kucheza karibu na road"),
     ("<strong>Lack of safety gear</strong> — no helmets, no seat belts",
      "<strong>Ukosefu wa vifaa vya usalama</strong> — hakuna kofia, hakuna mikanda",
      "<strong>Lack ya safety gear</strong> — hakuna helmets, hakuna seat belts"),
     ("<strong>Inadequate supervision</strong> during risky activities",
      "<strong>Usimamizi duni</strong> wakati wa shughuli hatarishi",
      "<strong>Inadequate supervision</strong> wakati wa risky activities"),
     ("<strong>Limited knowledge of the hazard</strong> — not knowing what is dangerous",
      "<strong>Ujuzi mdogo wa hatari</strong> — kutojua kilicho hatari",
      "<strong>Limited knowledge ya hazard</strong> — kutojua kilicho hatari"),
     ("<strong>Carelessness and over-speeding</strong>",
      "<strong>Uzembe na mwendo kasi</strong>",
      "<strong>Carelessness na over-speeding</strong>"),
     ("<strong>Driving under the influence</strong> of alcohol or drugs — the direct link to Module 10",
      "<strong>Kuendesha ukiwa umelewa</strong> pombe au dawa — uhusiano wa moja kwa moja na Moduli 10",
      "<strong>Kuendesha ukiwa umelewa</strong> pombe ama drugs — direct link na Module 10"),
    ]},
    {"type": "tip", "title": ("💡 The answer to the Big Question", "💡 Jibu la Swali Kubwa", "💡 Jibu la Big Question"), "text": (
     " Almost every item on that list is visible before the accident, not after. What people fail to see is not the danger itself but the ordinariness of it — the missing helmet on a route ridden a hundred times, the unlit stairs used every night. Predictable is not the same as noticed.",
     " Karibu kila kitu kwenye orodha hiyo kinaonekana kabla ya ajali, si baadaye. Watu hushindwa kuona si hatari yenyewe bali ukawaida wake — kofia inayokosekana kwenye njia iliyopitiwa mara mia, ngazi zisizo na mwanga zinazotumika kila usiku. Kutabirika si sawa na kuonwa.",
     " Karibu kila kitu kwa hiyo list kinaonekana kabla ya accident, si baadaye. Wasee wanashindwa kuona si danger yenyewe ni ordinariness yake — helmet inayokosekana kwa route iliyo-ridiwa mara mia, unlit stairs zinazotumika kila usiku. Predictable si sawa na noticed.")},
   ]},

  {"icon": "🛡️",
   "head": ("Prevention, by Setting", "Kuzuia, kwa Mazingira", "Prevention, kwa Setting"),
   "blocks": [
    {"type": "table",
     "headers": [("Setting", "Mazingira", "Setting"), ("What to do", "Cha kufanya", "Cha kufanya")],
     "rows": [
      [("Road", "Barabarani", "Road"),
       ("Use zebra crossings, wear a helmet on a boda boda, and keep your phone away while walking near roads.",
        "Tumia vivuko, vaa kofia kwenye boda boda, na weka simu mbali unapotembea karibu na barabara.",
        "Tumia zebra crossings, vaa helmet kwa boda boda, na weka phone mbali unapotembea karibu na road.")],
      [("Sport", "Michezoni", "Sport"),
       ("Warm-up exercises and protective gear — the same warm-up taught in Module 7.",
        "Mazoezi ya kujipasha moto na vifaa vya kinga — kujipasha moto kule kule kunakofundishwa Moduli 7.",
        "Warm-up exercises na protective gear — warm-up ile ile inayofundishwa Module 7.")],
      [("Home", "Nyumbani", "Home"),
       ("Lock away chemicals and pesticides; supervise cooking, especially around open fires and kerosene stoves.",
        "Fungia kemikali na dawa za wadudu; simamia upishi, hasa karibu na moto wazi na majiko ya mafuta ya taa.",
        "Lock away chemicals na pesticides; supervise cooking, hasa karibu na open fires na kerosene stoves.")],
      [("Water", "Majini", "Water"),
       ("Swim only in safe, supervised places — never alone in a river, dam or flooded area.",
        "Ogelea tu mahali salama, penye usimamizi — kamwe peke yako mtoni, bwawani au eneo la mafuriko.",
        "Ogelea tu mahali safe, penye supervision — kamwe peke yako mtoni, dam ama flooded area.")],
      [("Violence", "Ukatili", "Violence"),
       ("Conflict resolution skills, and safe spaces for young people — Modules 5 and 12.",
        "Ujuzi wa kutatua migogoro, na maeneo salama kwa vijana — Moduli 5 na 12.",
        "Conflict resolution skills, na safe spaces kwa vijana — Modules 5 na 12.")],
      [("Community", "Jamii", "Community"),
       ("Rules enforced — including prosecution of serious offenders such as drunk drivers.",
        "Sheria kutekelezwa — ikiwemo kushtaki wakosaji wakubwa kama wanaoendesha wakiwa wamelewa.",
        "Rules ku-enforciwa — ikiwemo prosecution ya serious offenders kama drunk drivers.")],
     ]},
   ]},

  {"icon": "🆘",
   "head": ("When It Has Already Happened", "Likishatokea Tayari", "Ikishahappen Tayari"),
   "blocks": [
    {"type": "list", "ordered": True, "items": [
     ("<strong>Make the scene safe first.</strong> You cannot help anyone if you become the second casualty — check for traffic, fire, live electricity or water.",
      "<strong>Fanya eneo liwe salama kwanza.</strong> Huwezi kumsaidia mtu ukiwa mwathirika wa pili — angalia magari, moto, umeme au maji.",
      "<strong>Fanya scene iwe safe kwanza.</strong> Huwezi kusaidia msee ukiwa second casualty — check traffic, moto, live electricity ama maji."),
     ("<strong>Call for help immediately</strong> and say clearly where you are, what happened, and how many people are hurt.",
      "<strong>Piga simu ya msaada mara moja</strong> na useme wazi ulipo, kilichotokea, na watu wangapi wamejeruhiwa.",
      "<strong>Call for help immediately</strong> na useme wazi uko wapi, kilicho-happen, na wasee wangapi wame-injuriwa."),
     ("<strong>Do not move a seriously injured person</strong> unless they are in further danger — especially after a fall or a road crash, where a spinal injury may be present.",
      "<strong>Usimsogeze mtu aliyejeruhiwa vibaya</strong> isipokuwa yuko hatarini zaidi — hasa baada ya kuanguka au ajali ya barabarani, ambapo jeraha la uti wa mgongo linaweza kuwepo.",
      "<strong>Usim-move msee aliye-injuriwa seriously</strong> unless yuko kwa further danger — hasa baada ya fall ama road crash, ambapo spinal injury inaweza kuwepo."),
     ("<strong>Stay with them</strong> and keep them calm until help arrives.",
      "<strong>Baki naye</strong> na umweke mtulivu hadi msaada ufike.",
      "<strong>Baki naye</strong> na um-keep calm mpaka msaada ufike."),
    ]},
    {"type": "warn", "title": ("⚠️ First aid needs hands-on training, not a slide", "⚠️ Huduma ya kwanza inahitaji mafunzo ya vitendo", "⚠️ First aid inahitaji hands-on training"), "text": (
     " The curriculum lists airway–breathing–circulation, CPR, and bleeding control. <strong>None of these can be learned from a lesson.</strong> Know what they are and why they matter — then get certified properly. The Kenya Red Cross runs first aid training, and a peer educator who has done it is worth ten who have read about it.",
     " Mtaala unaorodhesha njia ya hewa–kupumua–mzunguko, CPR, na kudhibiti damu. <strong>Hakuna kati ya haya kinachoweza kujifunzwa kutoka somo.</strong> Jua ni nini na kwa nini ni muhimu — kisha upate cheti ipasavyo. Msalaba Mwekundu wa Kenya huendesha mafunzo ya huduma ya kwanza, na mwelimishaji rika aliyeyafanya ana thamani ya kumi waliosoma tu.",
     " Curriculum ina-list airway–breathing–circulation, CPR, na bleeding control. <strong>Hakuna kati ya hizi inayoweza kujifunzwa kutoka lesson.</strong> Jua ni nini na kwa nini ni muhimu — kisha u-get certified properly. Kenya Red Cross ina-run first aid training, na peer educator aliyefanya ana value ya kumi waliosoma tu.")},
    {"type": "table",
     "headers": [("Service", "Huduma", "Service"), ("Number", "Nambari", "Number")],
     "rows": [
      [("Kenya Red Cross — emergency and ambulance", "Msalaba Mwekundu Kenya — dharura na gari la wagonjwa", "Kenya Red Cross — emergency na ambulance"),
       ("<strong>1199</strong>", "<strong>1199</strong>", "<strong>1199</strong>")],
      [("National emergency lines", "Simu za dharura za kitaifa", "National emergency lines"),
       ("<strong>719</strong> · <strong>0729 471 414</strong> · <strong>0732 353 535</strong>",
        "<strong>719</strong> · <strong>0729 471 414</strong> · <strong>0732 353 535</strong>",
        "<strong>719</strong> · <strong>0729 471 414</strong> · <strong>0732 353 535</strong>")],
      [("Childline Kenya — anyone under 18", "Childline Kenya — yeyote chini ya 18", "Childline Kenya — yeyote chini ya 18"),
       ("<strong>116</strong>", "<strong>116</strong>", "<strong>116</strong>")],
     ]},
    {"type": "facilitator", "minutes": 10, "text": (
     "Have the group work out, for their own school, exactly what they would do: who has a phone, what the nearest facility is, how someone would get there, and who holds the keys to the gate at night. Most schools have never answered those four questions, and the answers take ten minutes.",
     "Waache kundi litafute, kwa shule yao, hasa watakachofanya: nani ana simu, kituo cha karibu ni kipi, mtu angefikaje huko, na nani ana funguo za lango usiku. Shule nyingi hazijawahi kujibu maswali hayo manne, na majibu huchukua dakika kumi.",
     "Wacha group i-work out, kwa shule yao, exactly watakachofanya: nani ana phone, facility ya karibu ni ipi, msee angefikaje kule, na nani ana keys za gate usiku. Shule nyingi hazijawahi ku-answer hizo questions nne, na answers zinachukua dakika kumi.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A boda boda knocks down a boy outside your school. He is conscious but says his back hurts and he cannot feel one leg properly. A crowd gathers.",
      "Boda boda inamgonga mvulana nje ya shule yako. Yuko na fahamu lakini anasema mgongo unamuuma na hawezi kuhisi mguu mmoja vizuri. Umati unakusanyika.",
      "Boda boda ina-knock down mse nje ya shule yako. Yuko conscious lakini anasema mgongo unamuuma na hawezi kufeel mguu mmoja properly."),
     "question": ("What is the most important thing you do?", "Ni kitu gani muhimu zaidi unachofanya?", "Ni kitu gani muhimu zaidi unachofanya?"),
     "choices": [
      {"kind": "bad",
       "text": ("Help the crowd lift him into a matatu to get him to hospital fast",
                "Saidia umati kumbeba hadi kwenye matatu ili afike hospitali haraka",
                "Saidia crowd kum-lift hadi matatu ili afike hospital haraka"),
       "outcome": ("Back pain and loss of feeling in a limb after a road crash point to a possible spinal injury. Moving him without support is exactly how a recoverable injury becomes a permanent one. Speed matters — but not more than the spine.",
                   "Maumivu ya mgongo na kupoteza hisia kwenye kiungo baada ya ajali ya barabarani yanaashiria uwezekano wa jeraha la uti wa mgongo. Kumsogeza bila msaada ndiyo hasa jinsi jeraha linaloweza kupona linavyokuwa la kudumu. Kasi ni muhimu — lakini si zaidi ya uti wa mgongo.",
                   "Back pain na kupoteza feeling kwa limb baada ya road crash zina-point kwa possible spinal injury. Kum-move bila support ndio hasa jinsi recoverable injury inavyokuwa permanent. Speed ni muhimu — lakini si zaidi ya spine.")},
      {"kind": "good",
       "text": ("Keep him still, make the scene safe, and call for an ambulance",
                "Mweke bila kusogea, fanya eneo liwe salama, na uite gari la wagonjwa",
                "M-keep still, fanya scene iwe safe, na u-call ambulance"),
       "outcome": ("You said loudly: 'Nobody move him — his back is hurt.' You got someone to stop traffic, called 1199, and stayed talking to him until help came. He walked out of hospital three weeks later. ✅",
                   "Ulisema kwa sauti: 'Msimsogeze — mgongo wake umeumia.' Ulimwambia mtu asimamishe magari, ukapiga 1199, na ukabaki ukizungumza naye hadi msaada ulipofika. Alitoka hospitali akitembea wiki tatu baadaye. ✅",
                   "Ulisema kwa sauti: 'Hakuna msee ana-move — mgongo wake umeumia.' Uliambia msee a-stop traffic, uka-call 1199, na ukabaki uki-talk naye mpaka msaada ufike. Alitoka hospital akitembea wiki tatu baadaye. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "During lunch a girl stands up suddenly, cannot speak or cough, and grabs at her throat. Her face is going red.",
      "Wakati wa chakula cha mchana msichana anasimama ghafla, hawezi kuzungumza wala kukohoa, na anashika koo lake. Uso wake unakuwa mwekundu.",
      "Wakati wa lunch dem anasimama ghafla, hawezi kuongea wala kukohoa, na anashika koo lake. Uso wake unakuwa mwekundu."),
     "question": ("What does this mean?", "Hii inamaanisha nini?", "Hii inamaanisha nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("She will probably cough it up — give her water and wait a moment",
                "Pengine atakikohoa — mpe maji na usubiri kidogo",
                "Pengine atakikohoa — mpe maji na ungoje kidogo"),
       "outcome": ("Someone who cannot cough has no moving air, and water cannot pass a blocked airway either. The silence and the hands at the throat are the emergency signs — waiting is the one thing that guarantees the outcome gets worse.",
                   "Asiyeweza kukohoa hana hewa inayosogea, na maji hayawezi kupita njia ya hewa iliyoziba. Ukimya na mikono kooni ndizo dalili za dharura — kusubiri ndilo jambo pekee linalohakikisha matokeo yanazidi kuwa mabaya.",
                   "Msee asiyeweza kukohoa hana moving air, na maji haziwezi ku-pass blocked airway. Silence na mikono kooni ndio emergency signs — kungoja ndio kitu pekee kinacho-guarantee outcome inazidi kuwa mbaya.")},
      {"kind": "good",
       "text": ("Recognise it as a choking emergency, shout for a trained adult, and call for help now",
                "Itambue kama dharura ya kukwama, piga kelele umwite mtu mzima aliyefunzwa, na uombe msaada sasa",
                "I-recognise kama choking emergency, piga kelele u-call mtu mzima aliye-trained, na u-call help saa hii"),
       "outcome": ("You shouted for the teacher who had first aid training and sent someone else to call at the same time. She was fine within a minute. You had never been trained yourself — but you knew the signs, and you knew who had. ✅",
                   "Ulimwita kwa kelele mwalimu aliyekuwa na mafunzo ya huduma ya kwanza na ukamtuma mtu mwingine apige simu wakati huo huo. Alikuwa sawa ndani ya dakika. Wewe mwenyewe hukuwahi kufunzwa — lakini ulijua dalili, na ulijua nani alikuwa amefunzwa. ✅",
                   "Uli-shout kum-call teacher aliyekuwa na first aid training na uka-send msee mwingine a-call wakati huo huo. Alikuwa poa ndani ya dakika. Wewe mwenyewe hukuwahi ku-trainiwa — lakini ulijua signs, na ulijua nani alikuwa ame-trainiwa. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Safety starts with you: every action counts.</strong> Take personal responsibility for preventing accidents.",
      "<strong>Usalama huanza na wewe: kila kitendo kinahesabika.</strong> Chukua jukumu binafsi la kuzuia ajali.",
      "<strong>Safety inaanza na wewe: kila action ina-count.</strong> Chukua personal responsibility ya ku-prevent accidents."),
     ("<strong>Speak up, step in: peer support saves lives.</strong>",
      "<strong>Sema, ingilia: msaada wa rika huokoa maisha.</strong>",
      "<strong>Speak up, step in: peer support inaokoa maisha.</strong>"),
     ("Most adolescent injuries are predictable, and therefore preventable.",
      "Majeraha mengi ya vijana yanatabirika, na hivyo yanaweza kuzuiwa.",
      "Injuries nyingi za vijana ni predictable, na hivyo zinaweza ku-preventiwa."),
     ("Do not move a seriously injured person unless they are in further danger.",
      "Usimsogeze mtu aliyejeruhiwa vibaya isipokuwa yuko hatarini zaidi.",
      "Usim-move msee aliye-injuriwa seriously unless yuko kwa further danger."),
     ("Knowing the emergency number matters as much as knowing first aid — and calm, clear reporting gets help there faster.",
      "Kujua nambari ya dharura ni muhimu kama kujua huduma ya kwanza — na kuripoti kwa utulivu na uwazi hufikisha msaada haraka.",
      "Kujua emergency number ni muhimu kama kujua first aid — na calm, clear reporting inafikisha msaada faster."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Huhitaji kuwa daktari. Unahitaji kutokuwa mtu wa pili aliyejeruhiwa, kujua nambari, na kutomsogeza.",
     "Huhitaji kuwa daktari. Unahitaji kutokuwa mtu wa pili aliyejeruhiwa, kujua nambari, na kutomsogeza.",
     "Huhitaji kuwa daktari. Unahitaji kutokuwa second casualty, kujua number, na kutom-move.")},
   ]},
 ],

 "quiz": [
  {"q": "What distinguishes an emergency from an accident?",
   "options": ["They are the same",
               "An emergency requires immediate action to prevent loss of life, serious injury or further harm",
               "An emergency only happens in hospitals",
               "An accident is always more serious"],
   "answer": "B",
   "explain": "An accident is the unexpected event; an injury is the harm; an emergency is the situation demanding immediate action."},

  {"q": "According to the MOH Burns Registry (2019), burns are:",
   "options": ["Rare among Kenyan youth",
               "A major cause of disability among Kenyan youth",
               "Only a risk in industrial settings",
               "Declining rapidly"],
   "answer": "B",
   "explain": "Open-fire cooking, kerosene stoves, hot liquids and electrical faults are the common sources."},

  {"q": "A boy is hit by a boda boda, has back pain and cannot feel one leg. What must you NOT do?",
   "options": ["Call for an ambulance",
               "Move him into a vehicle to reach hospital faster",
               "Make the scene safe",
               "Stay with him and keep him calm"],
   "answer": "B",
   "explain": "Those signs suggest a possible spinal injury. Moving him without support is how a recoverable injury becomes permanent."},

  {"q": "Which are signs of a choking or breathing emergency? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Inability to speak, cough or breathe",
               "Skin turning blue",
               "Hands grasping at the throat",
               "Forceful, loud coughing"],
   "answer": ["A", "B", "C"],
   "explain": "Someone coughing forcefully still has an airway. The true emergency is usually silent."},

  {"q": "What should you do FIRST at the scene of an accident?",
   "options": ["Start first aid immediately",
               "Make the scene safe — you cannot help if you become the second casualty",
               "Move the injured person to safety",
               "Take a photograph for evidence"],
   "answer": "B",
   "explain": "Check for traffic, fire, live electricity or water before you approach."},

  {"q": "Which are causes of accidents named in the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Unsafe environments such as poor lighting",
               "Lack of safety gear such as helmets and seat belts",
               "Driving under the influence of alcohol or drugs",
               "Inadequate supervision during risky activities",
               "Bad luck"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Almost every listed cause is visible before the accident. Predictable is not the same as noticed."},

  {"q": "Where is flood-related drowning specifically noted as a risk?",
   "options": ["Nairobi and Mombasa", "Budalangi and Tana River County",
               "Only at the coast", "Nowhere specific"],
   "answer": "B",
   "explain": "Alongside unsupervised swimming in rivers, dams and lakes."},

  {"q": "What is the correct position on first aid skills like CPR?",
   "options": ["They can be learned from this lesson",
               "Know what they are and why they matter, then get hands-on certification — the Kenya Red Cross runs training",
               "Only doctors should know them",
               "They are not useful in Kenya"],
   "answer": "B",
   "explain": "None of airway–breathing–circulation, CPR or bleeding control can be learned from a slide."},

  {"q": "Which number reaches the Kenya Red Cross for emergencies and ambulance?",
   "options": ["116", "719", "1192", "1199"],
   "answer": "D",
   "explain": "116 is Childline, 719 a national emergency line, and 1192 is NACADA for substance dependence."},

  {"q": "What should you say when calling for help?",
   "options": ["As little as possible to save time",
               "Where you are, what happened, and how many people are hurt",
               "Only your name",
               "Wait for them to ask questions"],
   "answer": "B",
   "explain": "Calm, clear reporting gets help to the scene faster — which is why knowing the number matters as much as knowing first aid."},
 ],
}
