# Module 16 — Referral and Linkage
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 16.
# Helplines cross-checked against the ARISE resources page and lesson content.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m16-referral-and-linkage.html",
 "module_code": "M16",
 "module_slug": "referral-and-linkage",
 "lesson_slug": "m16-referral-and-linkage",
 "module_label": "Peer Educator · Module 16 of 19",
 "title": "Referral and Linkage",
 "icon": "🔗",
 "duration": 60,

 "objectives": [
  ("Explain what referral and linkage mean for adolescent and youth services",
   "Eleza rufaa na uunganishaji vinamaanisha nini katika huduma za vijana",
   "Explain referral na linkage inamaanisha nini kwa youth services"),
  ("Identify when a referral is needed and what services exist",
   "Tambua wakati rufaa inahitajika na huduma zilizopo",
   "Tambua wakati referral inahitajika na services zilizopo"),
  ("Demonstrate supportive communication when making a referral",
   "Onyesha mawasiliano yenye msaada wakati wa kutoa rufaa",
   "Onyesha supportive communication wakati wa kufanya referral"),
  ("Apply case scenarios to practise referral in a youth-friendly way",
   "Tumia mifano ya matukio kufanya mazoezi ya rufaa kwa njia rafiki kwa vijana",
   "Tumia case scenarios ku-practice referral kwa njia friendly kwa vijana"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> You gave someone a phone number and they never called it. Did you refer them?",
  "<strong>🔍 Swali Kubwa:</strong> Ulimpa mtu nambari ya simu na hakuipiga kamwe. Je, ulimpa rufaa?",
  "<strong>🔍 Big Question:</strong> Ulimpatia msee number na hakuipiga kamwe. Je, ulim-refer?"),

 "slides": [

  # ── 1. Two words ──────────────────────────────────────────────────
  {"icon": "📖",
   "head": ("Two Words, Two Different Jobs", "Maneno Mawili, Kazi Mbili Tofauti", "Maneno Mbili, Jobs Mbili Tofauti"),
   "blocks": [
    {"type": "p", "text": (
     "Most people use these two words as if they mean the same thing. They do not, and the difference is where young people get lost.",
     "Watu wengi hutumia maneno haya mawili kana kwamba yana maana moja. Hayana, na tofauti hiyo ndipo vijana hupotea.",
     "Wasee wengi wanatumia hizi maneno mbili kama zina maana moja. Hazina, na hiyo tofauti ndio mahali vijana wanapotea.")},
    {"type": "key_term", "term": ("🔑 Referral", "🔑 Rufaa", "🔑 Referral"), "text": (
     "A deliberate hand-off that connects a 10–24 year-old to a service they need — HIV testing, PrEP, PEP, family planning, GBV care, mental health counselling, social protection or legal support.",
     "Kukabidhi kwa makusudi kunakomuunganisha kijana wa miaka 10–24 na huduma anayohitaji — kipimo cha HIV, PrEP, PEP, uzazi wa mpango, huduma za ukatili wa kijinsia, ushauri wa afya ya akili, ulinzi wa kijamii au msaada wa kisheria.",
     "Deliberate hand-off inayo-connect msee wa 10–24 na service anayohitaji — HIV testing, PrEP, PEP, family planning, GBV care, mental health counselling, social protection ama legal support.")},
    {"type": "key_term", "term": ("🔑 Linkage", "🔑 Uunganishaji", "🔑 Linkage"), "text": (
     "The processes and partnerships that make sure the young person actually reaches, receives and continues that care — with feedback coming back to you.",
     "Michakato na ushirikiano unaohakikisha kijana anafika, anapokea na anaendelea na huduma hiyo — na maoni yakirudi kwako.",
     "Processes na partnerships zinazohakikisha kijana ana-reach, ana-receive na anaendelea na hiyo care — na feedback inarudi kwako.")},
    {"type": "warn", "title": ("⚠️ The distinction that matters", "⚠️ Tofauti ya maana", "⚠️ Tofauti ya maana"), "text": (
     " A phone number handed over is not a referral. A referral you never followed up is not linkage. If the young person did not receive the service, the job is not finished — whatever you wrote down.",
     " Nambari ya simu uliyompa si rufaa. Rufaa usiyoifuatilia si uunganishaji. Kama kijana hakupokea huduma, kazi haijaisha — hata uliandika nini.",
     " Number uliyompatia si referral. Referral ambayo hukui-follow up si linkage. Kama kijana hakupata service, job haijaisha — hata uliandika nini.")},
   ]},

  # ── 2. The three steps ────────────────────────────────────────────
  {"icon": "🪜",
   "head": ("The Three Steps", "Hatua Tatu", "Steps Tatu"),
   "blocks": [
    {"type": "p", "text": (
     "You identify the need, give first-line information, do a brief risk assessment — and then these three steps follow, in order.",
     "Unatambua hitaji, unatoa taarifa za awali, unafanya tathmini fupi ya hatari — kisha hatua hizi tatu zinafuata, kwa mpangilio.",
     "Una-identify need, unatoa first-line info, unafanya brief risk assessment — kisha hizi steps tatu zinafuata, kwa order.")},
    {"type": "list", "ordered": True, "items": [
     ("<strong>Issue and record the referral.</strong> Write it down. An undocumented referral cannot be followed up, and cannot be counted.",
      "<strong>Toa na rekodi rufaa.</strong> Iandike. Rufaa isiyoandikwa haiwezi kufuatiliwa, wala kuhesabiwa.",
      "<strong>Issue na record referral.</strong> Iandike. Referral isiyo-recorded haiwezi ku-followiwa up, wala kuhesabiwa."),
     ("<strong>Follow up until the service is received.</strong> Not until they leave you — until they arrive there.",
      "<strong>Fuatilia hadi huduma ipokewe.</strong> Si hadi wakuache — hadi wafike kule.",
      "<strong>Follow up mpaka service i-receiviwe.</strong> Si mpaka wakuache — mpaka wafike kule."),
     ("<strong>Re-refer or escalate when needed.</strong> If it did not land, it is not their failure. Send it again, or send it higher.",
      "<strong>Toa rufaa tena au peleka juu inapohitajika.</strong> Kama haikufika, si kosa lao. Ituma tena, au ipeleke juu.",
      "<strong>Re-refer ama escalate inapohitajika.</strong> Kama haiku-land, si failure yao. Ituma tena, ama ipeleke juu."),
    ]},
    {"type": "facilitator", "minutes": 8, "text": (
     "Ask the group how many referrals they think get lost between step 1 and step 2. Then ask what would have caught it. Almost every answer is 'someone checked back' — which is exactly step 2.",
     "Uliza kundi ni rufaa ngapi wanadhani hupotea kati ya hatua ya 1 na ya 2. Kisha uliza ni nini kingeligundua. Karibu kila jibu ni 'mtu alirudi kuangalia' — ambayo ndiyo hasa hatua ya 2.",
     "Uliza group ni referrals ngapi wanafikiri zinapotea kati ya step 1 na step 2. Kisha uliza ni nini kingeigundua. Karibu kila jibu ni 'msee alirudi kucheki' — ambayo ndio hasa step 2.")},
   ]},

  # ── 3. When to refer ──────────────────────────────────────────────
  {"icon": "🚦",
   "head": ("When to Refer, and Where", "Wakati wa Kutoa Rufaa, na Wapi", "Wakati wa Ku-refer, na Wapi"),
   "blocks": [
    {"type": "table",
     "headers": [("What you notice", "Unachokiona", "Unachoona"),
                 ("Where it goes", "Inakoenda", "Inaenda wapi")],
     "rows": [
      [("Possible HIV exposure in the last 72 hours", "Uwezekano wa kuambukizwa HIV katika saa 72 zilizopita", "Possible HIV exposure kwa masaa 72 yaliyopita"),
       ("Health facility <strong>the same day</strong> — PEP only works inside that window",
        "Kituo cha afya <strong>siku hiyo hiyo</strong> — PEP hufanya kazi ndani ya muda huo tu",
        "Health facility <strong>siku hiyo hiyo</strong> — PEP inawork ndani ya hiyo window tu")],
      [("Sexual assault or violence", "Unyanyasaji wa kingono au vurugu", "Sexual assault ama violence"),
       ("GBV helpline <strong>1195</strong> and a facility offering SGBV care",
        "Simu ya ukatili wa kijinsia <strong>1195</strong> na kituo kinachotoa huduma za SGBV",
        "GBV helpline <strong>1195</strong> na facility inayotoa SGBV care")],
      [("Talk of suicide, or severe distress", "Mazungumzo ya kujiua, au dhiki kali", "Story ya suicide, ama distress kali"),
       ("Mental health line <strong>1190</strong> and your supervising adult, same day",
        "Nambari ya afya ya akili <strong>1190</strong> na mtu mzima anayekusimamia, siku hiyo hiyo",
        "Mental health line <strong>1190</strong> na msimamizi wako, siku hiyo hiyo")],
      [("Substance dependence", "Utegemezi wa dawa za kulevya", "Substance dependence"),
       ("NACADA <strong>1192</strong> — free counselling and referral countrywide",
        "NACADA <strong>1192</strong> — ushauri na rufaa bila malipo nchi nzima",
        "NACADA <strong>1192</strong> — free counselling na referral nchi nzima")],
      [("Abuse of someone under 18", "Unyanyasaji wa mtu chini ya miaka 18", "Abuse ya msee chini ya 18"),
       ("Childline Kenya <strong>116</strong> — and escalate to your supervisor",
        "Childline Kenya <strong>116</strong> — na peleka kwa msimamizi wako",
        "Childline Kenya <strong>116</strong> — na escalate kwa supervisor wako")],
      [("Pregnancy, or contraception needs", "Ujauzito, au mahitaji ya uzazi wa mpango", "Pregnancy, ama contraception needs"),
       ("Youth-friendly SRH services at the nearest facility",
        "Huduma za afya ya uzazi rafiki kwa vijana katika kituo cha karibu",
        "Youth-friendly SRH services kwa facility ya karibu")],
     ]},
    {"type": "tip", "title": ("💡 Know your map before you need it", "💡 Jua ramani yako kabla ya kuihitaji", "💡 Jua map yako kabla uihitaji"), "text": (
     " Build your own list now: which facility, which days, which hours, who to ask for. A referral made from memory in a crisis is the one that fails.",
     " Jenga orodha yako sasa: kituo kipi, siku zipi, saa zipi, umuulize nani. Rufaa inayotolewa kwa kumbukumbu wakati wa dharura ndiyo inayoshindwa.",
     " Jenga list yako saa hii: facility ipi, siku zipi, masaa gani, uulize nani. Referral unayofanya kwa memory wakati wa crisis ndio inafail.")},
   ]},

  # ── 4. What good looks like ───────────────────────────────────────
  {"icon": "✅",
   "head": ("What a Good Referral System Looks Like", "Mfumo Mzuri wa Rufaa Unavyoonekana", "Referral System Poa Inavyoonekana"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Peer-led</strong> — championed by a trained, trusted fellow young person",
      "<strong>Unaongozwa na rika</strong> — unasimamiwa na kijana mwenzako aliyefunzwa na anayeaminika",
      "<strong>Peer-led</strong> — inasimamiwa na kijana mwenzako aliye-trained na wa kutrust"),
     ("<strong>Age-appropriate</strong> — what a 12-year-old needs is not what a 22-year-old needs (10–14, 15–19, 20–24)",
      "<strong>Unaofaa kwa umri</strong> — anachohitaji mtoto wa miaka 12 si anachohitaji wa miaka 22 (10–14, 15–19, 20–24)",
      "<strong>Age-appropriate</strong> — anachohitaji msee wa 12 si anachohitaji wa 22 (10–14, 15–19, 20–24)"),
     ("<strong>Youth-friendly</strong> — after-school and weekend hours, private space, fast-track for referred young people",
      "<strong>Rafiki kwa vijana</strong> — saa za baada ya shule na wikendi, nafasi ya faragha, njia ya haraka kwa waliopewa rufaa",
      "<strong>Youth-friendly</strong> — masaa ya after-school na weekend, private space, fast-track kwa waliopewa referral"),
     ("<strong>Close and reachable</strong> — near where young people live, study or work",
      "<strong>Karibu na unaofikika</strong> — karibu na wanapoishi, kusoma au kufanya kazi",
      "<strong>Karibu na inayo-reachika</strong> — karibu na wanapoishi, kusoma ama kufanya kazi"),
     ("<strong>Private and non-judgemental</strong> — confidential, respectful care every time",
      "<strong>Wa faragha na usiohukumu</strong> — huduma ya siri na yenye heshima kila wakati",
      "<strong>Private na non-judgemental</strong> — confidential, respectful care kila time"),
     ("<strong>It actually connects</strong> — health or non-health, the young person ends up cared for",
      "<strong>Unaunganisha kweli</strong> — afya au si afya, kijana anaishia kupata huduma",
      "<strong>Ina-connect kweli</strong> — health ama non-health, kijana anaishia kupata care"),
    ]},
   ]},

  # ── 5. Their rights ───────────────────────────────────────────────
  {"icon": "⚖️",
   "head": ("The Young Person's Rights in a Referral", "Haki za Kijana Katika Rufaa", "Rights za Kijana Kwa Referral"),
   "blocks": [
    {"type": "p", "text": (
     "You are handing someone into a system. These are the things they are entitled to once they get there — and the things you should tell them to expect.",
     "Unamkabidhi mtu kwenye mfumo. Haya ndiyo mambo anayostahili akifika huko — na mambo unayopaswa kumwambia atarajie.",
     "Unamkabidhi msee kwa system. Hizi ndio vitu anastahili akifika kule — na vitu unafaa kumwambia a-expect.")},
    {"type": "list", "items": [
     ("<strong>Privacy comes first</strong> — the service should be friendly and should not judge them",
      "<strong>Faragha kwanza</strong> — huduma iwe rafiki na isihukumu",
      "<strong>Privacy kwanza</strong> — service iwe friendly na isijudge"),
     ("<strong>Consent and assent matter</strong> — under 18, some services need a parent or guardian, unless the young person is considered mature or emancipated",
      "<strong>Ridhaa ni muhimu</strong> — chini ya miaka 18, huduma zingine zinahitaji mzazi au mlezi, isipokuwa kijana anachukuliwa kuwa amekomaa au huru",
      "<strong>Consent na assent ni muhimu</strong> — chini ya 18, services zingine zinahitaji mzazi ama guardian, unless kijana anachukuliwa mature ama emancipated"),
     ("<strong>No stigma, no harm</strong> — nobody should make them feel ashamed for coming",
      "<strong>Hakuna unyanyapaa</strong> — hakuna anayepaswa kuwafanya waaibike kwa kuja",
      "<strong>No stigma, no harm</strong> — hakuna anayefaa kuwafanya waskie aibu kwa kuja"),
     ("<strong>Follow-up is part of the service</strong> — not just a paper, but making sure they get the help",
      "<strong>Ufuatiliaji ni sehemu ya huduma</strong> — si karatasi tu, bali kuhakikisha wanapata msaada",
      "<strong>Follow-up ni part ya service</strong> — si karatasi tu, ni kuhakikisha wanapata msaada"),
     ("<strong>Digital reminders only with consent</strong> — an SMS or WhatsApp can expose someone at home",
      "<strong>Vikumbusho vya kidijitali kwa ridhaa tu</strong> — SMS au WhatsApp inaweza kumweka wazi mtu nyumbani",
      "<strong>Digital reminders na consent tu</strong> — SMS ama WhatsApp inaweza ku-expose msee nyumbani"),
     ("<strong>Extra support for those who need it</strong> — young mothers, adolescents with disabilities, those out of school",
      "<strong>Msaada wa ziada kwa wanaohitaji</strong> — mama vijana, vijana wenye ulemavu, walio nje ya shule",
      "<strong>Extra support kwa wanaohitaji</strong> — young mothers, vijana wenye disability, walio nje ya shule"),
    ]},
   ]},

  # ── 6. How to say it ──────────────────────────────────────────────
  {"icon": "💬",
   "head": ("How to Actually Make the Referral", "Jinsi ya Kutoa Rufaa Hasa", "Jinsi ya Kufanya Referral Hasa"),
   "blocks": [
    {"type": "p", "text": (
     "A referral is a conversation, not an instruction. How you say it decides whether they go.",
     "Rufaa ni mazungumzo, si agizo. Jinsi unavyoisema huamua kama wataenda.",
     "Referral ni conversation, si instruction. Jinsi unavyoisema inaamua kama wataenda.")},
    {"type": "table",
     "headers": [("Instead of", "Badala ya", "Badala ya"), ("Say", "Sema", "Sema")],
     "rows": [
      [('"You need to go to the clinic."', '"Unahitaji kwenda kliniki."', '"Unahitaji kuenda clinic."'),
       ('"There is someone at the clinic who deals with this every day. Would you want to go?"',
        '"Kuna mtu kliniki anayeshughulikia hili kila siku. Ungependa kwenda?"',
        '"Kuna msee clinic anayehandle hii kila siku. Ungependa kuenda?"')],
      [('"Here is the number, call them."', '"Hii ndiyo nambari, wapigie."', '"Hii ndio number, wapigie."'),
       ('"Do you want me to come with you? Or shall I call and ask for you?"',
        '"Unataka nije nawe? Au nipige nikuulizie?"',
        '"Unataka nikuje na wewe? Ama nipige nikuulizie?"')],
      [('"Don\'t worry, it will be fine."', '"Usijali, itakuwa sawa."', '"Usiworry, itakuwa poa."'),
       ('"I don\'t know exactly what they will say, but I know they will not judge you."',
        '"Sijui hasa watasema nini, lakini najua hawatakuhukumu."',
        '"Sijui exactly watasema nini, lakini najua hawatakujudge."')],
      [('"I\'ll tell them what you told me."', '"Nitawaambia ulichoniambia."', '"Nitawaambia ulichoniambia."'),
       ('"You decide what you share. I will only say what you want me to say."',
        '"Wewe amua utakachoshiriki. Nitasema tu unachotaka niseme."',
        '"Wewe decide utakachoshare. Nitasema tu unachotaka niseme."')],
     ]},
    {"type": "example", "title": ("🇰🇪 Kipchoge — Eldoret", "🇰🇪 Kipchoge — Eldoret", "🇰🇪 Kipchoge — Eldoret"), "text": (
     "Kipchoge referred four peers in one month and recorded all four. When he checked back a week later, three had gone and one had not. He asked why — she was afraid of meeting a neighbour in the queue. He arranged a Saturday slot for her instead. That is the whole difference between referral and linkage.",
     "Kipchoge alitoa rufaa kwa wenzake wanne kwa mwezi mmoja na akawaandika wote wanne. Aliporudi kuangalia wiki moja baadaye, watatu walikuwa wameenda na mmoja hakuwa ameenda. Aliuliza kwa nini — aliogopa kukutana na jirani kwenye foleni. Alimpangia nafasi ya Jumamosi badala yake. Hiyo ndiyo tofauti yote kati ya rufaa na uunganishaji.",
     "Kipchoge ali-refer wasee wanne kwa mwezi mmoja na aka-record wote wanne. Aliporudi kucheki wiki moja baadaye, watatu walikuwa wameenda na mmoja hakuenda. Aliuliza kwa nini — aliogopa kukutana na neighbour kwa queue. Akampangia Saturday slot badala yake. Hiyo ndio tofauti yote kati ya referral na linkage.")},
   ]},

  # ── 7. Directory ──────────────────────────────────────────────────
  {"icon": "📞",
   "head": ("The Numbers to Know", "Nambari za Kujua", "Numbers za Kujua"),
   "blocks": [
    {"type": "table",
     "headers": [("Service", "Huduma", "Service"), ("Number", "Nambari", "Number"), ("For", "Kwa", "Kwa")],
     "rows": [
      [("Childline Kenya", "Childline Kenya", "Childline Kenya"), ("<strong>116</strong>", "<strong>116</strong>", "<strong>116</strong>"),
       ("Any child under 18 at risk", "Mtoto yeyote chini ya 18 aliye hatarini", "Mtoto yeyote chini ya 18 aliye hatarini")],
      [("Mental Health Support", "Msaada wa Afya ya Akili", "Mental Health Support"), ("<strong>1190</strong>", "<strong>1190</strong>", "<strong>1190</strong>"),
       ("Distress, suicidal thoughts", "Dhiki, mawazo ya kujiua", "Distress, suicidal thoughts")],
      [("NACADA", "NACADA", "NACADA"), ("<strong>1192</strong>", "<strong>1192</strong>", "<strong>1192</strong>"),
       ("Drugs and substance dependence", "Utegemezi wa dawa za kulevya", "Drugs na substance dependence")],
      [("National GBV Helpline", "Simu ya Kitaifa ya Ukatili wa Kijinsia", "National GBV Helpline"), ("<strong>1195</strong>", "<strong>1195</strong>", "<strong>1195</strong>"),
       ("Gender-based violence, 24 hours", "Ukatili wa kijinsia, saa 24", "Gender-based violence, masaa 24")],
      [("Kenya Red Cross", "Msalaba Mwekundu Kenya", "Kenya Red Cross"), ("<strong>1199</strong>", "<strong>1199</strong>", "<strong>1199</strong>"),
       ("Emergencies and disaster response", "Dharura na majibu ya maafa", "Emergencies na disaster response")],
     ]},
    {"type": "tip", "title": ("💡 Add your local ones", "💡 Ongeza za eneo lako", "💡 Add za local yako"), "text": (
     " These are national. Write in your own county referral hospital, the nearest youth-friendly centre, and the name of one person at each who will take your call.",
     " Hizi ni za kitaifa. Andika hospitali ya rufaa ya kaunti yako, kituo cha karibu rafiki kwa vijana, na jina la mtu mmoja katika kila kimoja atakayepokea simu yako.",
     " Hizi ni za national. Andika county referral hospital yako, youth-friendly centre ya karibu, na jina la msee mmoja kwa kila moja atakayepokea call yako.")},
   ]},

  # ── 8. Practice ───────────────────────────────────────────────────
  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "Achieng, 16, tells you she thinks she may have been exposed to HIV two nights ago. She is frightened and does not want her mother to know.",
      "Achieng, miaka 16, anakuambia anadhani huenda aliambukizwa HIV usiku wa juzi. Ameogopa na hataki mama yake ajue.",
      "Achieng, 16, anakuambia anafikiri huenda ali-exposiwa kwa HIV juzi usiku. Ameogopa na hataki mother wake ajue."),
     "question": ("What do you do first?", "Unafanya nini kwanza?", "Unafanya nini kwanza?"),
     "choices": [
      {"kind": "bad",
       "text": ("Give her the clinic's number and tell her to go when she is ready",
                "Mpe nambari ya kliniki na umwambie aende akiwa tayari",
                "Mpatie number ya clinic na umwambie aende akiwa ready"),
       "outcome": ("PEP only works within 72 hours of exposure, and two nights have already gone. 'When she is ready' may be after the window closes. This is the referral that has to happen today, not the one that waits for confidence.",
                   "PEP hufanya kazi ndani ya saa 72 tu baada ya kuambukizwa, na usiku wa juzi tayari umepita. 'Akiwa tayari' inaweza kuwa baada ya muda kuisha. Hii ni rufaa inayopaswa kutokea leo, si inayosubiri ujasiri.",
                   "PEP inawork ndani ya masaa 72 tu baada ya exposure, na juzi tayari imepita. 'Akiwa ready' inaweza kuwa baada ya window kufungwa. Hii ni referral inayofaa kuhappen leo, si inayongoja confidence.")},
      {"kind": "good",
       "text": ("Explain the 72-hour window, and offer to go with her to the facility today",
                "Eleza muda wa saa 72, na jitolee kwenda naye kituoni leo",
                "Explain window ya masaa 72, na offer kwenda naye facility leo"),
       "outcome": ("You said: 'There's a medicine that can stop this, but it only works if you start within three days — and we're inside that. I can come with you now. You decide what you tell them.' She went. That is a referral, recorded, followed through. ✅",
                   "Ulisema: 'Kuna dawa inayoweza kuzuia hili, lakini hufanya kazi tu ukianza ndani ya siku tatu — na tuko ndani ya muda huo. Naweza kuja nawe sasa. Wewe amua utawaambia nini.' Alienda. Hiyo ni rufaa, iliyoandikwa, iliyofuatiliwa. ✅",
                   "Ulisema: 'Kuna dawa inaweza ku-stop hii, lakini inawork tu ukianza ndani ya siku tatu — na tuko ndani ya hiyo window. Naweza kuja na wewe saa hii. Wewe decide utawaambia nini.' Alienda. Hiyo ni referral, recorded, followed through. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "You referred Brian to the youth centre for substance counselling three weeks ago. You recorded it. You have not checked back since, and you see him looking unwell.",
      "Ulimpa Brian rufaa kwenda kituo cha vijana kwa ushauri wa dawa za kulevya wiki tatu zilizopita. Uliandika. Hujarudi kuangalia tangu wakati huo, na unamwona akionekana mgonjwa.",
      "Uli-refer Brian kwa youth centre kwa substance counselling wiki tatu zilizopita. Uli-record. Hujarudi kucheki tangu wakati huo, na unamuona akionekana mgonjwa."),
     "question": ("What does linkage require here?", "Uunganishaji unahitaji nini hapa?", "Linkage inahitaji nini hapa?"),
     "choices": [
      {"kind": "bad",
       "text": ("Nothing — you referred him and recorded it, so your part is done",
                "Hakuna — ulimpa rufaa na ukaandika, kwa hivyo sehemu yako imeisha",
                "Hakuna — uli-refer na uka-record, so part yako imeisha"),
       "outcome": ("This is the commonest failure in the whole system. A recorded referral with no follow-up produces a good report and a young person who never got help. Step 2 exists precisely for this.",
                   "Hili ndilo kosa la kawaida zaidi katika mfumo mzima. Rufaa iliyoandikwa bila ufuatiliaji hutoa ripoti nzuri na kijana ambaye hakupata msaada kamwe. Hatua ya 2 ipo kwa ajili ya hili hasa.",
                   "Hii ndio failure ya kawaida zaidi kwa system nzima. Referral iliyo-recorded bila follow-up inatoa report nzuri na kijana ambaye hakupata msaada. Step 2 iko kwa ajili ya hii hasa.")},
      {"kind": "good",
       "text": ("Ask him whether he got there, and re-refer or escalate if he did not",
                "Muulize kama alifika, na umpe rufaa tena au peleka juu kama hakufika",
                "Muulize kama alifika, na u-re-refer ama escalate kama hakufika"),
       "outcome": ("Brian had gone once, been told to come back on a weekday, and could not miss school. You escalated to your supervisor, who arranged a Saturday appointment. The first referral did not fail because Brian failed — it failed because nobody checked. ✅",
                   "Brian alikuwa amekwenda mara moja, akaambiwa arudi siku ya kazi, na hakuweza kukosa shule. Ulipeleka kwa msimamizi wako, aliyepanga miadi ya Jumamosi. Rufaa ya kwanza haikushindwa kwa sababu Brian alishindwa — ilishindwa kwa sababu hakuna aliyeangalia. ✅",
                   "Brian alikuwa ameenda mara moja, akaambiwa arudi weekday, na hakuweza kukosa shule. Uli-escalate kwa supervisor wako, ambaye alipanga Saturday appointment. Referral ya kwanza haiku-fail kwa sababu Brian ali-fail — ili-fail kwa sababu hakuna aliye-check. ✅")},
     ]},
   ]},

  # ── 9. Key messages ───────────────────────────────────────────────
  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Referral and linkage must always protect privacy and confidentiality.",
      "Rufaa na uunganishaji lazima daima vilinde faragha na usiri.",
      "Referral na linkage lazima daima zilinde privacy na confidentiality."),
     ("A referral is a deliberate hand-off — not a phone number handed over.",
      "Rufaa ni kukabidhi kwa makusudi — si nambari ya simu iliyotolewa.",
      "Referral ni deliberate hand-off — si number iliyotolewa."),
     ("Linkage means following up until the service is actually received.",
      "Uunganishaji maana yake ni kufuatilia hadi huduma ipokewe kweli.",
      "Linkage ina maana ku-follow up mpaka service i-receiviwe kweli."),
     ("Record every referral — an undocumented referral cannot be followed up.",
      "Rekodi kila rufaa — rufaa isiyoandikwa haiwezi kufuatiliwa.",
      "Record kila referral — referral isiyo-recorded haiwezi ku-followiwa up."),
     ("Re-refer or escalate when the first attempt does not land.",
      "Toa rufaa tena au peleka juu jaribio la kwanza linaposhindwa.",
      "Re-refer ama escalate wakati attempt ya kwanza hai-land."),
    ]},
    {"type": "sheng", "label": "Bottom Line", "text": (
     "Kazi yako haiishi pale unapotoa rufaa. Inaisha pale mtu anapopata msaada. Kati ya hizo mbili ndipo kazi halisi iko.",
     "Kazi yako haiishi unapotoa rufaa. Inaisha mtu anapopata msaada. Kati ya hizo mbili ndipo kazi halisi ipo.",
     "Job yako haiishi pale una-refer. Inaisha pale msee anapata msaada. Kati ya hizo mbili ndio job halisi iko.")},
   ]},
 ],

 "quiz": [
  {"q": "What is the difference between a referral and linkage?",
   "options": ["They mean the same thing",
               "A referral is the hand-off; linkage is making sure the service is actually received",
               "A referral is written; linkage is spoken",
               "Linkage happens first, then the referral"],
   "answer": "B",
   "explain": "The referral connects; linkage ensures the young person reaches, receives and continues the care, with feedback to the referrer."},

  {"q": "Achieng may have been exposed to HIV two nights ago. What makes this urgent?",
   "options": ["HIV tests only work in the first week",
               "PEP only works if started within 72 hours of exposure",
               "The clinic closes at the end of the month",
               "She will be contagious after three days"],
   "answer": "B",
   "explain": "PEP must begin inside the 72-hour window. A referral that waits for the young person to feel ready may miss it entirely."},

  {"q": "Which of these are steps in the referral process? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Issue and record the referral",
               "Follow up until the service is received",
               "Diagnose the condition before referring",
               "Re-refer or escalate if the first attempt does not land"],
   "answer": ["A", "B", "D"],
   "explain": "Diagnosing is a clinical act outside the peer educator role. The other three are the process."},

  {"q": "Why must every referral be recorded?",
   "options": ["Because donors require paperwork",
               "Because an undocumented referral cannot be followed up or counted",
               "Because the young person needs a copy to be admitted",
               "Because it protects the peer educator legally"],
   "answer": "B",
   "explain": "Follow-up is impossible without a record, and step 2 depends entirely on knowing who was referred where."},

  {"q": "A peer educator refers someone, records it, and never checks back. What has happened?",
   "options": ["The process is complete",
               "Referral happened but linkage did not",
               "Linkage happened but referral did not",
               "Neither referral nor linkage happened"],
   "answer": "B",
   "explain": "This is the commonest failure — a good report, and a young person who never got help."},

  {"q": "Which helpline would you use for gender-based violence in Kenya?",
   "options": ["116", "1190", "1192", "1195"],
   "answer": "D",
   "explain": "1195 is the National GBV helpline, free and available 24 hours. 116 is Childline, 1190 mental health, 1192 NACADA."},

  {"q": "Which describe a youth-friendly referral system? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["After-school and weekend hours",
               "A private space to be seen in",
               "One standard approach for everyone aged 10 to 24",
               "Located near where young people live, study or work",
               "Fast-track for young people who arrive with a referral"],
   "answer": ["A", "B", "D", "E"],
   "explain": "Age-appropriateness matters — the deck separates 10–14, 15–19 and 20–24 because their needs genuinely differ."},

  {"q": "A 15-year-old is nervous that an SMS appointment reminder will be seen at home. What is correct?",
   "options": ["Send it anyway — appointment reminders improve attendance",
               "Digital reminders should only be used with the young person's consent",
               "Send it to the parent instead",
               "Refuse the referral until the family is informed"],
   "answer": "B",
   "explain": "A reminder can expose someone at home. Consent for digital contact is part of protecting confidentiality."},

  {"q": "Which is the better thing to say when making a referral?",
   "options": ["\"You need to go to the clinic.\"",
               "\"Here is the number, call them.\"",
               "\"Do you want me to come with you, or shall I call and ask for you?\"",
               "\"Don't worry, it will be fine.\""],
   "answer": "C",
   "explain": "Offering to accompany or call converts an instruction into a hand-off, and leaves the choice with the young person."},

  {"q": "Brian did not attend because the clinic only opened on weekdays and he could not miss school. Whose failure is this?",
   "options": ["Brian's — he did not prioritise his health",
               "The system's — and it should be escalated so an alternative is arranged",
               "The clinic's alone, and nothing can be done",
               "Nobody's — some referrals simply do not work"],
   "answer": "B",
   "explain": "A referral that does not land is not the young person's failure. Re-referring or escalating is step 3, not an optional extra."},
 ],
}
