# Module 17 (part 1 of 2) — Advocacy and Social Behaviour Change
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 17.
# Trilingual: English / Kiswahili / Sheng.

LESSON = {
 "file": "m17a-advocacy-and-sbc.html",
 "module_code": "M17",
 "module_slug": "advocacy-and-sbcc",
 "lesson_slug": "m17a-advocacy-and-sbc",
 "module_label": "Peer Educator · M17 · Part 1 of 2",
 "title": "Advocacy and Social Behaviour Change",
 "icon": "📣",
 "duration": 45,

 "objectives": [
  ("Define advocacy, social behaviour change and SBCC",
   "Fafanua utetezi, mabadiliko ya tabia za kijamii na SBCC",
   "Define advocacy, social behaviour change na SBCC"),
  ("Outline the importance and key components of SBC for young people",
   "Eleza umuhimu na vipengele muhimu vya SBC kwa vijana",
   "Outline importance na key components za SBC kwa vijana"),
  ("Describe the stages a person passes through when behaviour changes",
   "Eleza hatua ambazo mtu hupitia tabia inapobadilika",
   "Describe stages ambazo msee anapitia behaviour inapo-change"),
  ("Choose the right channel and audience for a behaviour change message",
   "Chagua njia sahihi na hadhira kwa ujumbe wa mabadiliko ya tabia",
   "Chagua channel sahihi na audience kwa behaviour change message"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> You have spent eighteen modules learning to change one person at a time. What would it take to change the conditions instead?",
  "<strong>🔍 Swali Kubwa:</strong> Umetumia moduli kumi na nane kujifunza kubadilisha mtu mmoja mmoja. Ingechukua nini kubadilisha mazingira badala yake?",
  "<strong>🔍 Big Question:</strong> Umetumia modules kumi na nane kujifunza ku-change msee mmoja mmoja. Ingechukua nini ku-change conditions badala yake?"),

 "slides": [

  {"icon": "📖",
   "head": ("The Words", "Maneno", "Maneno"),
   "blocks": [
    {"type": "table",
     "headers": [("Term", "Neno", "Term"), ("Meaning", "Maana", "Maana")],
     "rows": [
      [("<strong>Social Behaviour Change (SBC)</strong>", "<strong>Mabadiliko ya Tabia za Kijamii (SBC)</strong>", "<strong>Social Behaviour Change (SBC)</strong>"),
       ("A strategic way of helping people and communities change behaviour, by understanding their challenges and using the right solutions to improve health and wellbeing.",
        "Njia ya kimkakati ya kuwasaidia watu na jamii kubadilisha tabia, kwa kuelewa changamoto zao na kutumia suluhisho sahihi kuboresha afya na ustawi.",
        "Strategic way ya kuwasaidia wasee na communities ku-change behaviour, kwa kuelewa challenges zao na kutumia solutions sahihi ku-improve health na wellbeing.")],
      [("<strong>Advocacy</strong>", "<strong>Utetezi</strong>", "<strong>Advocacy</strong>"),
       ("Engaging <strong>policymakers</strong> to prioritise adolescent and youth health in policy, and to secure resources and political commitment for it.",
        "Kushirikiana na <strong>watunga sera</strong> ili wapewe kipaumbele afya ya vijana katika sera, na kupata rasilimali na dhamira ya kisiasa kwa ajili yake.",
        "Ku-engage <strong>policymakers</strong> ili wa-prioritise adolescent na youth health kwa policy, na ku-secure resources na political commitment kwa ajili yake.")],
      [("<strong>Communication</strong>", "<strong>Mawasiliano</strong>", "<strong>Communication</strong>"),
       ("The active process of exchanging information, ideas, thoughts and emotions between two or more people.",
        "Mchakato hai wa kubadilishana taarifa, mawazo, fikra na hisia kati ya watu wawili au zaidi.",
        "Active process ya ku-exchange information, ideas, thoughts na emotions kati ya wasee wawili ama zaidi.")],
      [("<strong>SBCC</strong>", "<strong>SBCC</strong>", "<strong>SBCC</strong>"),
       ("Social Behaviour Change Communication — using various channels of knowledge to help people make healthy choices and change behaviour.",
        "Mawasiliano ya Mabadiliko ya Tabia za Kijamii — kutumia njia mbalimbali za maarifa kuwasaidia watu kufanya maamuzi bora ya afya na kubadilisha tabia.",
        "Social Behaviour Change Communication — kutumia channels mbalimbali za knowledge kuwasaidia wasee ku-make healthy choices na ku-change behaviour.")],
      [("<strong>Social mobilisation</strong>", "<strong>Uhamasishaji wa kijamii</strong>", "<strong>Social mobilisation</strong>"),
       ("Engaging, empowering and uniting individuals, families, communities, institutions and stakeholders to support education, skills and the holistic growth of adolescents.",
        "Kushirikisha, kuwezesha na kuunganisha watu binafsi, familia, jamii, taasisi na wadau kusaidia elimu, ujuzi na ukuaji kamili wa vijana.",
        "Ku-engage, ku-empower na ku-unite watu binafsi, families, communities, institutions na stakeholders ku-support education, skills na holistic growth ya vijana.")],
     ]},
    {"type": "tip", "title": ("💡 The distinction that matters", "💡 Tofauti ya maana", "💡 Tofauti ya maana"), "text": (
     " <strong>SBCC targets the community. Advocacy targets the people who decide.</strong> Persuading a hundred young people to seek contraception achieves little if the clinic has none in stock — that second problem is fixed by advocacy, not by another session. Knowing which of the two a problem needs is the whole skill of this module.",
     " <strong>SBCC hulenga jamii. Utetezi hulenga wanaoamua.</strong> Kuwashawishi vijana mia moja watafute uzazi wa mpango hakusaidii sana kama kliniki haina bidhaa — tatizo hilo la pili hurekebishwa kwa utetezi, si kwa kipindi kingine. Kujua ni lipi kati ya mawili tatizo linahitaji ndio ujuzi wote wa moduli hii.",
     " <strong>SBCC ina-target community. Advocacy ina-target wanao-decide.</strong> Ku-persuade vijana mia moja watafute contraception haisaidii sana kama clinic haina stock — hiyo problem ya pili ina-fixiwa na advocacy, si na session ingine. Kujua ni ipi kati ya mbili problem inahitaji ndio skill yote ya hii module.")},
   ]},

  {"icon": "🎯",
   "head": ("Why SBC Matters for Young People", "Kwa Nini SBC ni Muhimu kwa Vijana", "Kwa Nini SBC ni Muhimu kwa Vijana"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Empowers policymakers</strong> to understand adolescent issues better, and to prioritise them",
      "<strong>Huwawezesha watunga sera</strong> kuelewa masuala ya vijana vizuri zaidi, na kuyapa kipaumbele",
      "<strong>Ina-empower policymakers</strong> kuelewa adolescent issues better, na kuzi-prioritise"),
     ("<strong>Amplifies the voices of young people</strong>, driving long-term systemic change",
      "<strong>Hukuza sauti za vijana</strong>, na kuleta mabadiliko ya kimfumo ya muda mrefu",
      "<strong>Ina-amplify voices za vijana</strong>, ikileta long-term systemic change"),
     ("<strong>Promotes awareness of and access to</strong> essential information and services",
      "<strong>Hukuza uelewa na upatikanaji</strong> wa taarifa na huduma muhimu",
      "<strong>Ina-promote awareness na access</strong> ya essential information na services"),
     ("<strong>Encourages community participation</strong> and supportive networks around young people",
      "<strong>Huhimiza ushiriki wa jamii</strong> na mitandao ya msaada kuzunguka vijana",
      "<strong>Ina-encourage community participation</strong> na supportive networks kuzunguka vijana"),
     ("<strong>Builds collaboration</strong> between young people and their communities",
      "<strong>Hujenga ushirikiano</strong> kati ya vijana na jamii zao",
      "<strong>Inajenga collaboration</strong> kati ya vijana na communities zao"),
    ]},
   ]},

  {"icon": "🧩",
   "head": ("The Seven Components", "Vipengele Saba", "Components Saba"),
   "blocks": [
    {"type": "table",
     "headers": [("Component", "Kipengele", "Component"), ("What it means in practice", "Maana yake kivitendo", "Maana yake practically")],
     "rows": [
      [("Reaching different groups", "Kufikia makundi tofauti", "Ku-reach groups tofauti"),
       ("Tailor the message to a specific group so it is actually relevant to them.",
        "Rekebisha ujumbe kwa kundi mahususi ili uwafae kweli.",
        "Tailor message kwa specific group ili iwa-fit kweli.")],
      [("Planning with facts", "Kupanga kwa ukweli", "Ku-plan na facts"),
       ("Design strategies from data and cultural context, not from assumption.",
        "Buni mikakati kutoka data na muktadha wa kitamaduni, si kutoka dhana.",
        "Design strategies kutoka data na cultural context, si kutoka assumption.")],
      [("Sharing information", "Kushiriki taarifa", "Ku-share information"),
       ("Use multiple channels — one channel reaches one kind of person.",
        "Tumia njia nyingi — njia moja hufikia aina moja ya mtu.",
        "Tumia channels nyingi — channel moja inafikia aina moja ya msee.")],
      [("Building skills", "Kujenga ujuzi", "Kujenga skills"),
       ("Empower communities and young people to lead the change themselves.",
        "Wawezeshe jamii na vijana kuongoza mabadiliko wenyewe.",
        "Empower communities na vijana ku-lead change wenyewe.")],
      [("Better rules and support", "Sheria bora na msaada", "Better rules na support"),
       ("Create the environment that makes the new behaviour sustainable.",
        "Unda mazingira yanayofanya tabia mpya idumu.",
        "Create environment inayofanya new behaviour i-sustain.")],
      [("Checking progress", "Kuangalia maendeleo", "Ku-check progress"),
       ("Track what is happening and adapt — this is Module 18.",
        "Fuatilia kinachoendelea na urekebishe — hii ni Moduli 18.",
        "Track kinachohappen na u-adapt — hii ni Module 18.")],
      [("Working together", "Kufanya kazi pamoja", "Kufanya kazi pamoja"),
       ("Engage stakeholders across sectors — health, education, community, government.",
        "Shirikisha wadau katika sekta zote — afya, elimu, jamii, serikali.",
        "Engage stakeholders across sectors — health, education, community, government.")],
     ]},
   ]},

  {"icon": "🪜",
   "head": ("The Eight Stages of Behaviour Change", "Hatua Nane za Mabadiliko ya Tabia", "Stages Nane za Behaviour Change"),
   "blocks": [
    {"type": "p", "text": (
     "Nobody moves from not knowing to doing in one step. This ladder is how it actually happens — and knowing which rung someone is on tells you what to say next.",
     "Hakuna anayehama kutoka kutojua hadi kutenda kwa hatua moja. Ngazi hii ndivyo hutokea hasa — na kujua mtu yuko kizingiti kipi kunakuambia la kusema baadaye.",
     "Hakuna msee anahama kutoka kutojua hadi kufanya kwa step moja. Hii ladder ndio jinsi inavyohappen — na kujua msee yuko rung ipi kunakuambia la kusema next.")},
    {"type": "table",
     "headers": [("Stage", "Hatua", "Stage"), ("What is happening", "Kinachoendelea", "Kinachohappen")],
     "rows": [
      [("1. Awareness", "1. Uelewa", "1. Awareness"),
       ("They hear about it — through media campaigns, school education or a peer conversation.",
        "Wanasikia kuhusu — kupitia kampeni za vyombo vya habari, elimu shuleni au mazungumzo ya rika.",
        "Wanasikia kuhusu — kupitia media campaigns, school education ama peer conversation.")],
      [("2. Interest and knowledge", "2. Hamu na maarifa", "2. Interest na knowledge"),
       ("Curiosity leads them to seek more information and understand the issue better.",
        "Udadisi huwapeleka kutafuta taarifa zaidi na kuelewa suala vizuri.",
        "Curiosity inawapeleka kutafuta info zaidi na kuelewa issue better.")],
      [("3. Attitude formation", "3. Kuunda mtazamo", "3. Attitude formation"),
       ("Peer norms, cultural beliefs, family values and personal experience shape what they now think about it.",
        "Kanuni za rika, imani za kitamaduni, maadili ya familia na uzoefu binafsi huunda wanachofikiri sasa.",
        "Peer norms, cultural beliefs, family values na personal experience zina-shape wanachofikiri saa hii.")],
      [("4. Decision / intention", "4. Uamuzi / nia", "4. Decision / intention"),
       ("A conscious decision to change — deciding to avoid smoking, or to talk to a friend about quitting.",
        "Uamuzi wa makusudi wa kubadilika — kuamua kuepuka uvutaji, au kuzungumza na rafiki kuhusu kuacha.",
        "Conscious decision ya ku-change — ku-decide ku-avoid smoking, ama kuongea na friend kuhusu ku-quit.")],
      [("5. Trial", "5. Kujaribu", "5. Trial"),
       ("They test the new behaviour — saying no once, or joining a support group.",
        "Wanajaribu tabia mpya — kusema hapana mara moja, au kujiunga na kikundi cha msaada.",
        "Wana-test new behaviour — kusema no mara moja, ama kujoin support group.")],
      [("6. Adoption", "6. Kukubali", "6. Adoption"),
       ("The behaviour becomes routine — regularly avoiding risky situations.",
        "Tabia inakuwa ya kawaida — kuepuka hali hatarishi mara kwa mara.",
        "Behaviour inakuwa routine — ku-avoid risky situations regularly.")],
      [("7. Maintenance", "7. Kudumisha", "7. Maintenance"),
       ("It holds, with ongoing support and strong coping skills — Module 5 and Module 9.",
        "Inadumu, kwa msaada endelevu na ujuzi imara wa kukabiliana — Moduli 5 na 9.",
        "Ina-hold, na ongoing support na strong coping skills — Module 5 na Module 9.")],
      [("8. Advocacy", "8. Utetezi", "8. Advocacy"),
       ("Some go further — becoming peer leaders or educators, leading campaigns, mentoring others.",
        "Wengine huenda mbali zaidi — kuwa viongozi wa rika au waelimishaji, kuongoza kampeni, kuwalea wengine.",
        "Wengine wanaenda mbali zaidi — kuwa peer leaders ama educators, ku-lead campaigns, ku-mentor wengine.")],
     ]},
    {"type": "sheng", "text": (
     "Angalia hatua ya nane tena. Hiyo ni wewe. Ulianza kizingiti cha kwanza kama mtu mwingine yeyote, na sasa unaendesha kipindi. Ndiyo maana ngazi hii si nadharia.",
     "Angalia hatua ya nane tena. Hiyo ni wewe. Ulianza kizingiti cha kwanza kama mtu mwingine yeyote, na sasa unaendesha kipindi. Ndiyo maana ngazi hii si nadharia.",
     "Angalia stage ya nane tena. Hiyo ni wewe. Ulianza rung ya kwanza kama msee mwingine yeyote, na saa hii una-run session. Ndio maana hii ladder si theory.")},
   ]},

  {"icon": "📡",
   "head": ("Choosing Audience and Channel", "Kuchagua Hadhira na Njia", "Ku-choose Audience na Channel"),
   "blocks": [
    {"type": "p", "text": (
     "<strong>Audience segmentation</strong> means recognising that 'young people' is not one audience. A 12-year-old in a rural school, a 22-year-old boda rider and a young mother out of school need three different messages, delivered three different ways.",
     "<strong>Kugawanya hadhira</strong> maana yake ni kutambua kwamba 'vijana' si hadhira moja. Mtoto wa miaka 12 shule ya vijijini, dereva wa boda wa miaka 22 na mama kijana aliye nje ya shule wanahitaji ujumbe tofauti tatu, unaotolewa kwa njia tatu tofauti.",
     "<strong>Audience segmentation</strong> inamaanisha ku-recognise ati 'vijana' si audience moja. Msee wa 12 kwa rural school, boda rider wa 22 na young mother aliye nje ya shule wanahitaji messages tatu tofauti, zinazotolewa kwa njia tatu tofauti.")},
    {"type": "table",
     "headers": [("Channel", "Njia", "Channel"), ("Best for", "Bora kwa", "Best kwa"), ("Weakness", "Udhaifu", "Weakness")],
     "rows": [
      [("<strong>Mass media</strong> — radio, TV, print", "<strong>Vyombo vya habari</strong> — redio, TV, magazeti", "<strong>Mass media</strong> — radio, TV, print"),
       ("Reaching many people quickly, and shifting what feels normal",
        "Kufikia watu wengi haraka, na kubadilisha kinachoonekana cha kawaida",
        "Ku-reach wasee wengi haraka, na ku-shift kinachoonekana normal"),
       ("One-way; cannot answer a question or respond to a doubt",
        "Njia moja; hauwezi kujibu swali wala kujibu shaka",
        "One-way; haiwezi ku-answer question wala ku-respond kwa doubt")],
      [("<strong>Digital platforms</strong>", "<strong>Majukwaa ya kidijitali</strong>", "<strong>Digital platforms</strong>"),
       ("Reaching young people where they already are, cheaply and repeatedly",
        "Kuwafikia vijana walipo tayari, kwa bei nafuu na mara kwa mara",
        "Ku-reach vijana walipo tayari, cheaply na repeatedly"),
       ("Misinformation travels the same way — see part 2",
        "Taarifa potofu husafiri kwa njia ile ile — angalia sehemu ya 2",
        "Misinformation inasafiri kwa njia ile ile — angalia part 2")],
      [("<strong>Interpersonal communication</strong>", "<strong>Mawasiliano ya ana kwa ana</strong>", "<strong>Interpersonal communication</strong>"),
       ("Moving someone from stage 3 to stage 5 — the rungs where a real person is needed",
        "Kumsogeza mtu kutoka hatua 3 hadi 5 — vizingiti ambapo mtu halisi anahitajika",
        "Ku-move msee kutoka stage 3 hadi 5 — rungs ambapo real person anahitajika"),
       ("Slow, and reaches few people at a time",
        "Polepole, na hufikia watu wachache kwa wakati",
        "Slow, na inafikia wasee wachache kwa wakati")],
     ]},
    {"type": "tip", "title": ("💡 This is what a peer educator is for", "💡 Ndio maana mwelimishaji rika yupo", "💡 Ndio maana peer educator yuko"), "text": (
     " Radio can make a whole county aware of something overnight. It cannot get one frightened girl through a clinic door. Mass media moves stages 1 and 2; <strong>interpersonal communication is what moves stages 3, 4 and 5</strong> — and that is precisely the work you have been trained for.",
     " Redio inaweza kuifanya kaunti nzima ijue jambo usiku mmoja. Haiwezi kumfikisha msichana mmoja aliyeogopa mlangoni mwa kliniki. Vyombo vya habari husogeza hatua 1 na 2; <strong>mawasiliano ya ana kwa ana ndiyo husogeza hatua 3, 4 na 5</strong> — na ndiyo hasa kazi uliyofunzwa.",
     " Radio inaweza kufanya county nzima ijue kitu overnight. Haiwezi kumfikisha dem mmoja aliyeogopa mlangoni mwa clinic. Mass media ina-move stages 1 na 2; <strong>interpersonal communication ndio ina-move stages 3, 4 na 5</strong> — na ndio hasa kazi uliyo-trainiwa.")},
    {"type": "facilitator", "minutes": 12, "text": (
     "Pick one real problem in the group's own community. Ask two questions: which stage is most people stuck at, and is this an SBCC problem or an advocacy problem? Those two answers determine everything else, and groups almost always get the second one wrong at first.",
     "Chagua tatizo moja halisi katika jamii ya kundi. Uliza maswali mawili: watu wengi wamekwama hatua ipi, na je hili ni tatizo la SBCC au la utetezi? Majibu hayo mawili huamua kila kitu kingine, na makundi karibu daima hukosea la pili mwanzoni.",
     "Chagua problem moja real kwa community ya group. Uliza questions mbili: wasee wengi wame-stuck stage ipi, na je hii ni SBCC problem ama advocacy problem? Hizo answers mbili zina-determine kila kitu kingine, na groups karibu daima zina-get ya pili wrong mwanzoni.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "You have run six sessions on HIV testing. Everyone can now explain why testing matters — but almost nobody has actually gone. The nearest testing point opens only on weekday mornings, during school.",
      "Umeendesha vipindi sita kuhusu kupimwa VVU. Sasa kila mtu anaweza kueleza kwa nini kupimwa ni muhimu — lakini karibu hakuna aliyeenda. Kituo cha karibu cha kupima hufunguliwa asubuhi za siku za kazi tu, wakati wa shule.",
      "Ume-run sessions sita kuhusu HIV testing. Saa hii kila msee anaweza ku-explain kwa nini testing ni muhimu — lakini karibu hakuna aliyeenda. Testing point ya karibu inafunguliwa weekday mornings tu, wakati wa shule."),
     "question": ("What kind of problem is this?", "Hili ni tatizo la aina gani?", "Hii ni problem ya aina gani?"),
     "choices": [
      {"kind": "bad",
       "text": ("A knowledge problem — run a seventh session, with better materials",
                "Tatizo la maarifa — endesha kipindi cha saba, kwa vifaa bora",
                "Knowledge problem — run session ya saba, na materials better"),
       "outcome": ("They already know. Module 18 would call this high attendance with no change — a monitoring number hiding an evaluation finding. The barrier is opening hours, and no amount of communication moves an opening hour.",
                   "Tayari wanajua. Moduli 18 ingeliita hili mahudhurio ya juu bila mabadiliko — namba ya ufuatiliaji ikificha matokeo ya tathmini. Kizuizi ni saa za kufunguliwa, na hakuna kiasi cha mawasiliano kinachosogeza saa ya kufunguliwa.",
                   "Tayari wanajua. Module 18 ingei-call hii high attendance bila change — monitoring number ikificha evaluation finding. Barrier ni opening hours, na hakuna kiasi cha communication kina-move opening hour.")},
      {"kind": "good",
       "text": ("An advocacy problem — the barrier is the opening hours, not the understanding",
                "Tatizo la utetezi — kizuizi ni saa za kufunguliwa, si uelewa",
                "Advocacy problem — barrier ni opening hours, si understanding"),
       "outcome": ("You said: 'They know. They can't go, because it's open when they're in class. That's not something a session fixes — that's something we take to the facility in-charge.' You did, with attendance figures from your own register. They added a Saturday clinic. ✅",
                   "Ulisema: 'Wanajua. Hawawezi kwenda, kwa sababu kimefunguliwa wakiwa darasani. Hilo si jambo kipindi linalorekebisha — ni jambo tunalopeleka kwa msimamizi wa kituo.' Ulifanya hivyo, na takwimu za mahudhurio kutoka rejista yako. Waliongeza kliniki ya Jumamosi. ✅",
                   "Ulisema: 'Wanajua. Hawawezi kuenda, kwa sababu iko open wakiwa class. Hiyo si kitu session ina-fix — ni kitu tunapeleka kwa facility in-charge.' Ulifanya hivyo, na attendance figures kutoka register yako. Waliongeza Saturday clinic. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A peer educator plans one message about drug abuse and wants to deliver it identically to a Form One class, a group of out-of-school boda riders, and a parents' meeting.",
      "Mwelimishaji rika anapanga ujumbe mmoja kuhusu matumizi ya dawa za kulevya na anataka kuutoa vivyo hivyo kwa darasa la Kidato cha Kwanza, kundi la madereva wa boda walio nje ya shule, na mkutano wa wazazi.",
      "Peer educator ana-plan message moja kuhusu drug abuse na anataka kui-deliver identically kwa Form One class, group ya boda riders walio nje ya shule, na parents' meeting."),
     "question": ("What is wrong with the plan?", "Nini kibaya na mpango huo?", "Nini kibaya na hiyo plan?"),
     "choices": [
      {"kind": "bad",
       "text": ("Nothing — a consistent message is a strong message",
                "Hakuna — ujumbe thabiti ni ujumbe imara",
                "Hakuna — consistent message ni strong message"),
       "outcome": ("Consistency of facts is good; identical delivery to different audiences is not. 'Reaching different groups' is the first of the seven components precisely because a message tailored to nobody in particular reaches nobody in particular.",
                   "Uthabiti wa ukweli ni mzuri; kutoa kwa namna ile ile kwa hadhira tofauti si vizuri. 'Kufikia makundi tofauti' ni cha kwanza cha vipengele saba hasa kwa sababu ujumbe usiolengwa kwa yeyote hasa haumfikii yeyote hasa.",
                   "Consistency ya facts ni poa; identical delivery kwa audiences tofauti si poa. 'Ku-reach groups tofauti' ni ya kwanza ya components saba hasa kwa sababu message isiyo-tailoriwa kwa msee yeyote specifically hai-reach msee yeyote specifically.")},
      {"kind": "good",
       "text": ("The facts should stay the same, but the framing and channel must change per audience",
                "Ukweli ubaki uleule, lakini mfumo na njia lazima vibadilike kwa kila hadhira",
                "Facts zibaki zile zile, lakini framing na channel lazima zi-change kwa kila audience"),
       "outcome": ("You said: 'Same facts, three different conversations. The Form Ones need refusal skills. The riders need what it does to reaction time and income. The parents need warning signs and where to take someone. One message, delivered three ways.' All three sessions landed. ✅",
                   "Ulisema: 'Ukweli mmoja, mazungumzo matatu tofauti. Wa Kidato cha Kwanza wanahitaji ujuzi wa kukataa. Madereva wanahitaji inavyoathiri kasi ya kuitikia na kipato. Wazazi wanahitaji dalili za onyo na wapi kumpeleka mtu. Ujumbe mmoja, unaotolewa kwa njia tatu.' Vipindi vyote vitatu vilifika. ✅",
                   "Ulisema: 'Facts zile zile, conversations tatu tofauti. Form Ones wanahitaji refusal skills. Riders wanahitaji inavyoathiri reaction time na income. Wazazi wanahitaji warning signs na wapi kumpeleka msee. Message moja, inayotolewa kwa njia tatu.' Sessions zote tatu zili-land. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Social behaviour change is a strategy for enabling young people to make healthy choices.",
      "Mabadiliko ya tabia za kijamii ni mkakati wa kuwawezesha vijana kufanya maamuzi bora ya afya.",
      "Social behaviour change ni strategy ya ku-enable vijana ku-make healthy choices."),
     ("Advocacy targets those who decide; SBCC targets the community. Know which a problem needs.",
      "Utetezi hulenga wanaoamua; SBCC hulenga jamii. Jua tatizo linahitaji lipi.",
      "Advocacy ina-target wanao-decide; SBCC ina-target community. Jua problem inahitaji ipi."),
     ("Behaviour changes through eight stages, and people get stuck at different ones.",
      "Tabia hubadilika kupitia hatua nane, na watu hukwama katika hatua tofauti.",
      "Behaviour ina-change kupitia stages nane, na wasee wana-stuck kwa stages tofauti."),
     ("'Young people' is not one audience — tailor the message to the specific group.",
      "'Vijana' si hadhira moja — rekebisha ujumbe kwa kundi mahususi.",
      "'Vijana' si audience moja — tailor message kwa specific group."),
     ("Mass media moves awareness. Interpersonal communication moves decisions — that is your work.",
      "Vyombo vya habari husogeza uelewa. Mawasiliano ya ana kwa ana husogeza maamuzi — hiyo ni kazi yako.",
      "Mass media ina-move awareness. Interpersonal communication ina-move decisions — hiyo ni kazi yako."),
    ]},
    {"type": "p", "text": (
     "Part 2 covers digital platforms — their uses and risks, staying safe online, and where to report abuse.",
     "Sehemu ya 2 inahusu majukwaa ya kidijitali — matumizi na hatari zake, kuwa salama mtandaoni, na wapi kuripoti unyanyasaji.",
     "Part 2 inacover digital platforms — uses na risks zake, kuwa safe online, na wapi ku-report abuse.")},
   ]},
 ],

 "quiz": [
  {"q": "What is the difference between advocacy and SBCC?",
   "options": ["They are the same thing",
               "Advocacy engages policymakers; SBCC uses communication channels to help communities change behaviour",
               "Advocacy is for adults, SBCC for young people",
               "SBCC is a type of advertising"],
   "answer": "B",
   "explain": "Persuading a hundred young people to seek contraception achieves little if the clinic has none in stock — that second problem needs advocacy."},

  {"q": "Which is the FIRST stage of social behaviour change?",
   "options": ["Decision", "Awareness", "Trial", "Attitude formation"],
   "answer": "B",
   "explain": "Awareness comes through media campaigns, school education or a peer conversation — then interest, then attitude."},

  {"q": "What happens at the attitude formation stage?",
   "options": ["The person tries the new behaviour",
               "Peer norms, cultural beliefs, family values and personal experience shape what they think about it",
               "The behaviour becomes routine",
               "They mentor others"],
   "answer": "B",
   "explain": "This is stage 3, and it is where interpersonal communication matters most — a leaflet cannot shift a peer norm."},

  {"q": "What is the eighth and optional stage?",
   "options": ["Maintenance", "Advocacy — becoming a peer leader or educator, leading campaigns, mentoring others",
               "Adoption", "Relapse"],
   "answer": "B",
   "explain": "Which is precisely what the person completing this curriculum has become — the ladder is not theory."},

  {"q": "Six sessions on HIV testing leave everyone informed but nobody tested, because the clinic only opens on weekday mornings. What kind of problem is this?",
   "options": ["A knowledge problem — run another session",
               "An advocacy problem — the barrier is opening hours, not understanding",
               "A motivation problem",
               "Not a problem at all"],
   "answer": "B",
   "explain": "No amount of communication moves an opening hour. Module 18 would call this high attendance with no change."},

  {"q": "Which are among the seven key components of SBC? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Reaching different groups with tailored messages",
               "Planning with facts and cultural context",
               "Building skills so communities lead the change",
               "Checking progress and adapting",
               "Using a single message for everyone"],
   "answer": ["A", "B", "C", "D"],
   "explain": "A message tailored to nobody in particular reaches nobody in particular."},

  {"q": "What does audience segmentation mean?",
   "options": ["Splitting a session into parts",
               "Recognising that 'young people' is not one audience — different groups need different messages and channels",
               "Separating boys and girls",
               "Dividing a message into chapters"],
   "answer": "B",
   "explain": "A 12-year-old in a rural school, a boda rider and a young mother out of school need three different conversations."},

  {"q": "Which channel is best at moving someone from attitude to trial?",
   "options": ["Radio", "Television", "Interpersonal communication", "Print media"],
   "answer": "C",
   "explain": "Mass media moves stages 1 and 2. Interpersonal communication moves 3, 4 and 5 — which is the peer educator's actual work."},

  {"q": "What is the weakness of mass media as a channel?",
   "options": ["It is expensive",
               "It is one-way — it cannot answer a question or respond to a doubt",
               "It reaches too few people",
               "It is unreliable"],
   "answer": "B",
   "explain": "Radio can make a county aware overnight. It cannot get one frightened girl through a clinic door."},

  {"q": "A peer plans to deliver one identical drug-abuse message to Form Ones, boda riders and parents. What is wrong?",
   "options": ["Nothing — consistency is good",
               "The facts should stay the same, but framing and channel must change per audience",
               "He should only address the students",
               "He should use different facts for each"],
   "answer": "B",
   "explain": "Consistency of facts is good. Identical delivery to different audiences is not — that is why 'reaching different groups' is the first component."},
 ],
}
