# Module 17 (part 2 of 2) — Digital Platforms, Safety and Reporting
# Source: "Adolescent and Young Persons Peer Education — Updated slides", Module 17.
# Trilingual: English / Kiswahili / Sheng.
#
# Final lesson of the 19-module curriculum.

LESSON = {
 "file": "m17b-digital-safety.html",
 "module_code": "M17",
 "module_slug": "advocacy-and-sbcc",
 "lesson_slug": "m17b-digital-safety",
 "module_label": "Peer Educator · M17 · Part 2 of 2",
 "title": "Digital Platforms, Safety and Reporting",
 "icon": "📱",
 "duration": 45,

 "objectives": [
  ("Define digital literacy, credibility, cyber security and cyberbullying",
   "Fafanua ujuzi wa kidijitali, uaminifu, usalama wa mtandao na uonevu mtandaoni",
   "Define digital literacy, credibility, cyber security na cyberbullying"),
  ("Assess the risks and benefits of being digital",
   "Tathmini hatari na faida za kuwa mtandaoni",
   "Assess risks na benefits za kuwa digital"),
  ("Apply online safety practices, and help peers do the same",
   "Tumia mazoea ya usalama mtandaoni, na uwasaidie wenzako kufanya vivyo hivyo",
   "Tumia online safety practices, na usaidie wasee kufanya same"),
  ("Demonstrate the reporting mechanisms available for online harm in Kenya",
   "Onyesha njia za kuripoti madhara ya mtandaoni zilizopo Kenya",
   "Onyesha reporting mechanisms zilizopo kwa online harm Kenya"),
 ],

 "big_question": (
  "<strong>🔍 Big Question:</strong> The same phone that lets a young person reach help at midnight lets a stranger reach them at midnight. How do you teach both truths at once?",
  "<strong>🔍 Swali Kubwa:</strong> Simu ile ile inayomwezesha kijana kufikia msaada usiku wa manane humwezesha mgeni kumfikia usiku wa manane. Unafundishaje ukweli wote wawili kwa wakati mmoja?",
  "<strong>🔍 Big Question:</strong> Phone ile ile inayomwezesha kijana ku-reach msaada midnight inamwezesha stranger kum-reach midnight. Una-teach aje ukweli wote wawili kwa wakati mmoja?"),

 "slides": [

  {"icon": "📖",
   "head": ("The Words You Need", "Maneno Unayohitaji", "Maneno Unayohitaji"),
   "blocks": [
    {"type": "table",
     "headers": [("Term", "Neno", "Term"), ("Meaning", "Maana", "Maana")],
     "rows": [
      [("<strong>Digital literacy</strong>", "<strong>Ujuzi wa kidijitali</strong>", "<strong>Digital literacy</strong>"),
       ("The ability to find, understand and create information using digital tools — smartly and carefully.",
        "Uwezo wa kupata, kuelewa na kuunda taarifa kwa kutumia zana za kidijitali — kwa busara na uangalifu.",
        "Uwezo wa kupata, kuelewa na ku-create information ukitumia digital tools — smartly na carefully.")],
      [("<strong>Credibility</strong>", "<strong>Uaminifu</strong>", "<strong>Credibility</strong>"),
       ("The reliability, believability and trustworthiness of information published by journalists, media outlets and practitioners.",
        "Kutegemewa, kuaminika na uadilifu wa taarifa zinazochapishwa na waandishi wa habari, vyombo vya habari na wataalamu.",
        "Reliability, believability na trustworthiness ya info inayo-publishiwa na journalists, media outlets na practitioners.")],
      [("<strong>Cyber security</strong>", "<strong>Usalama wa mtandao</strong>", "<strong>Cyber security</strong>"),
       ("Protecting computer systems, networks and digital data from theft, damage and unauthorised access.",
        "Kulinda mifumo ya kompyuta, mitandao na data za kidijitali dhidi ya wizi, uharibifu na ufikiaji usioruhusiwa.",
        "Ku-protect computer systems, networks na digital data dhidi ya theft, damage na unauthorised access.")],
      [("<strong>Cyberbullying</strong>", "<strong>Uonevu mtandaoni</strong>", "<strong>Cyberbullying</strong>"),
       ("Using digital devices — phones, social media, messaging apps — to hurt, threaten, embarrass or target another person <strong>on purpose</strong>.",
        "Kutumia vifaa vya kidijitali — simu, mitandao ya kijamii, programu za ujumbe — kumdhuru, kumtishia, kumwaibisha au kumlenga mtu mwingine <strong>kwa makusudi</strong>.",
        "Kutumia digital devices — phones, social media, messaging apps — ku-hurt, ku-threaten, ku-embarrass ama ku-target msee mwingine <strong>kwa makusudi</strong>.")],
      [("<strong>Artificial Intelligence (AI)</strong>", "<strong>Akili Bandia (AI)</strong>", "<strong>Artificial Intelligence (AI)</strong>"),
       ("The simulation of human intelligence in machines programmed to think and learn like humans.",
        "Uigaji wa akili ya binadamu katika mashine zilizoprogramiwa kufikiri na kujifunza kama binadamu.",
        "Simulation ya human intelligence kwa machines zilizo-programiwa kufikiri na kujifunza kama binadamu.")],
     ]},
   ]},

  {"icon": "⚖️",
   "head": ("What Digital Platforms Give, and Cost", "Majukwaa ya Kidijitali Yanatoa Nini, na Yanagharimu Nini", "Digital Platforms Zinatoa Nini, na Zina-cost Nini"),
   "blocks": [
    {"type": "table",
     "headers": [("✅ What they are good for", "✅ Zinafaa kwa nini", "✅ Zinafaa kwa nini"),
                 ("⚠️ What they cost", "⚠️ Zinagharimu nini", "⚠️ Zina-cost nini")],
     "rows": [
      [("Communication — chatting, video calls, staying connected",
        "Mawasiliano — kuzungumza, simu za video, kubaki umeunganishwa",
        "Communication — chatting, video calls, kubaki connected"),
       ("Exposure to cyberbullying and other harms",
        "Kuathiriwa na uonevu mtandaoni na madhara mengine",
        "Exposure kwa cyberbullying na harms zingine")],
      [("Learning — online classes, e-books, tutorials, research",
        "Kujifunza — madarasa mtandaoni, vitabu pepe, mafunzo, utafiti",
        "Kujifunza — online classes, e-books, tutorials, research"),
       ("Unrealistic views of other people's lives — see Module 9",
        "Mitazamo isiyo halisi ya maisha ya wengine — angalia Moduli 9",
        "Unrealistic views za maisha ya wasee wengine — angalia Module 9")],
      [("Information sharing — news and updates in real time",
        "Kushiriki taarifa — habari na masasisho kwa wakati halisi",
        "Ku-share information — news na updates real time"),
       ("A source of <strong>erroneous, damaging and unverified information</strong>",
        "Chanzo cha <strong>taarifa zisizo sahihi, zenye madhara na zisizothibitishwa</strong>",
        "Source ya <strong>erroneous, damaging na unverified information</strong>")],
      [("Networking, business and financial services — mobile banking, payments",
        "Kuunganisha, biashara na huduma za kifedha — benki ya simu, malipo",
        "Networking, business na financial services — mobile banking, payments"),
       ("Can hamper the healthy development of social skills",
        "Inaweza kuzuia ukuaji mzuri wa ujuzi wa kijamii",
        "Inaweza ku-hamper healthy development ya social skills")],
      [("Collaboration — teamwork tools, meetings, file sharing",
        "Ushirikiano — zana za timu, mikutano, kushiriki faili",
        "Collaboration — teamwork tools, meetings, file sharing"),
       ("Provides a platform for <strong>cons and predators seeking children</strong>",
        "Hutoa jukwaa kwa <strong>matapeli na wanaotafuta watoto</strong>",
        "Inatoa platform kwa <strong>cons na predators wanaotafuta watoto</strong>")],
     ]},
    {"type": "tip", "title": ("💡 The answer to the Big Question", "💡 Jibu la Swali Kubwa", "💡 Jibu la Big Question"), "text": (
     " Teach both columns together, never one alone. A peer educator who only lists dangers gets ignored by people who use these tools happily every day; one who only celebrates the benefits leaves them defenceless. <strong>Digital platforms can help or harm depending on how they are used</strong> — that is the whole message, and it is why digital literacy is a skill rather than a warning.",
     " Fundisha safu zote mbili pamoja, kamwe si moja peke yake. Mwelimishaji rika anayeorodhesha hatari tu hupuuzwa na wanaotumia zana hizi kwa furaha kila siku; anayesifia faida tu huwaacha bila ulinzi. <strong>Majukwaa ya kidijitali yanaweza kusaidia au kudhuru kutegemea yanavyotumika</strong> — huo ndio ujumbe wote, na ndiyo maana ujuzi wa kidijitali ni stadi si onyo.",
     " Fundisha columns zote mbili pamoja, kamwe si moja peke yake. Peer educator anaye-list dangers tu ana-ignoriwa na wasee wanaotumia hizi tools happily kila siku; anaye-celebrate benefits tu anawaacha bila protection. <strong>Digital platforms zinaweza kusaidia ama kudhuru kutegemea zinavyotumika</strong> — huo ndio message wote, na ndio maana digital literacy ni skill si warning.")},
   ]},

  {"icon": "🛡️",
   "head": ("Think Smart, Click Safe", "Fikiri kwa Busara, Bonyeza kwa Usalama", "Think Smart, Click Safe"),
   "blocks": [
    {"type": "list", "items": [
     ("<strong>Do not give out personal information</strong> to people or places you do not know",
      "<strong>Usitoe taarifa binafsi</strong> kwa watu au maeneo usiyoyajua",
      "<strong>Usitoe personal information</strong> kwa wasee ama places usizojua"),
     ("<strong>Never meet someone you have only known online</strong> without a parent or guardian's permission",
      "<strong>Usikutane kamwe na mtu uliyemjua mtandaoni tu</strong> bila ruhusa ya mzazi au mlezi",
      "<strong>Usikutane kamwe na msee uliyemjua online tu</strong> bila permission ya mzazi ama guardian"),
     ("<strong>Do not open</strong> emails, messages, files, images or texts from sources you do not trust — they may carry viruses or worse",
      "<strong>Usifungue</strong> barua pepe, ujumbe, faili, picha au maandishi kutoka vyanzo usivyoviamini — vinaweza kubeba virusi au mabaya zaidi",
      "<strong>Usifungue</strong> emails, messages, files, images ama texts kutoka sources usizotrust — zinaweza kubeba viruses ama mabaya zaidi"),
     ("<strong>Always verify information</strong> from trusted sources before you believe it — or forward it",
      "<strong>Daima thibitisha taarifa</strong> kutoka vyanzo vinavyoaminika kabla ya kuiamini — au kuisambaza",
      "<strong>Daima verify information</strong> kutoka trusted sources kabla ui-believe — ama kui-forward"),
     ("<strong>Tell a parent, guardian or trusted adult</strong> when something online worries you",
      "<strong>Mwambie mzazi, mlezi au mtu mzima unayemwamini</strong> kitu cha mtandaoni kikikutia wasiwasi",
      "<strong>Ambia mzazi, guardian ama trusted adult</strong> kitu cha online kikikutia wasiwasi"),
     ("<strong>Remember: online friends are still strangers.</strong>",
      "<strong>Kumbuka: marafiki wa mtandaoni bado ni wageni.</strong>",
      "<strong>Kumbuka: online friends bado ni strangers.</strong>"),
    ]},
    {"type": "table",
     "headers": [("Habits that reduce harm", "Tabia zinazopunguza madhara", "Habits zinazopunguza harm"),
                 ("A positive presence online", "Uwepo chanya mtandaoni", "Positive presence online")],
     "rows": [
      [("Set reasonable limits — a bedtime routine that avoids screens",
        "Weka mipaka ya busara — utaratibu wa kulala usiotumia skrini",
        "Weka reasonable limits — bedtime routine isiyo na screens"),
       ("Post positive comments; be culturally appropriate",
        "Chapisha maoni chanya; kuwa mwenye kuheshimu utamaduni",
        "Post positive comments; kuwa culturally appropriate")],
      [("Know what is appropriate and safe to share and to consume",
        "Jua kilicho sahihi na salama kushiriki na kutumia",
        "Jua kilicho appropriate na safe ku-share na ku-consume"),
       ("Take care what you share; check your privacy settings",
        "Kuwa mwangalifu unachoshiriki; angalia mipangilio yako ya faragha",
        "Kuwa careful unachoshare; check privacy settings zako")],
      [("Encourage face-to-face contact — it builds the skills screens do not",
        "Himiza mawasiliano ya ana kwa ana — hujenga ujuzi ambao skrini haujengi",
        "Encourage face-to-face contact — inajenga skills ambazo screens haziijengi")],
      [("Model responsible use — talk honestly about your own habits",
        "Onyesha matumizi ya uwajibikaji — zungumza kwa ukweli kuhusu tabia zako",
        "Model responsible use — ongea honestly kuhusu habits zako"),
       ("Keep passwords safe; never share personal details; ask before you download",
        "Weka nywila salama; usishiriki taarifa binafsi kamwe; uliza kabla ya kupakua",
        "Keep passwords safe; usishare personal details kamwe; uliza kabla u-download")],
      [("", "", ""),
       ("<strong>Adhere to age restrictions — they exist to keep you safe</strong>",
        "<strong>Fuata vizuizi vya umri — vipo kukuweka salama</strong>",
        "<strong>Follow age restrictions — ziko kuku-keep safe</strong>")],
     ]},
   ]},

  {"icon": "🚨",
   "head": ("Reporting Online Harm in Kenya", "Kuripoti Madhara ya Mtandaoni Kenya", "Ku-report Online Harm Kenya"),
   "blocks": [
    {"type": "p", "text": (
     "This is the most practical slide in the module. Most young people believe nothing can be done about online abuse. These exist specifically so that something can.",
     "Hii ndiyo slaidi yenye manufaa zaidi katika moduli. Vijana wengi wanaamini hakuna kinachoweza kufanyika kuhusu unyanyasaji mtandaoni. Hivi vipo hasa ili kitu kiweze kufanyika.",
     "Hii ndio slide yenye manufaa zaidi kwa module. Vijana wengi wanaamini hakuna kinachoweza kufanyika kuhusu online abuse. Hizi ziko hasa ili kitu kiweze kufanyika.")},
    {"type": "table",
     "headers": [("Where to report", "Wapi kuripoti", "Wapi ku-report"), ("Contact", "Mawasiliano", "Contact")],
     "rows": [
      [("<strong>DCI Fichua</strong> — report offensive or criminal online content, toll free",
        "<strong>DCI Fichua</strong> — ripoti maudhui ya kuudhi au ya kihalifu mtandaoni, bila malipo",
        "<strong>DCI Fichua</strong> — report offensive ama criminal online content, toll free"),
       ("<strong>0800 722 203</strong>", "<strong>0800 722 203</strong>", "<strong>0800 722 203</strong>")],
      [("<strong>National children's helpline</strong> — anyone under 18",
        "<strong>Simu ya kitaifa ya watoto</strong> — yeyote chini ya miaka 18",
        "<strong>National children's helpline</strong> — yeyote chini ya 18"),
       ("<strong>116</strong>", "<strong>116</strong>", "<strong>116</strong>")],
      [("<strong>KE-CIRT</strong> — Kenya Computer Incident Response Team, at the Communications Authority",
        "<strong>KE-CIRT</strong> — Timu ya Kenya ya Kukabiliana na Matukio ya Kompyuta, katika Mamlaka ya Mawasiliano",
        "<strong>KE-CIRT</strong> — Kenya Computer Incident Response Team, kwa Communications Authority"),
       ("ke-cirt.go.ke", "ke-cirt.go.ke", "ke-cirt.go.ke")],
      [("<strong>Internet Watch Foundation</strong> — removing online child sexual abuse material",
        "<strong>Internet Watch Foundation</strong> — kuondoa maudhui ya unyanyasaji wa kingono wa watoto mtandaoni",
        "<strong>Internet Watch Foundation</strong> — kuondoa online child sexual abuse material"),
       ("report.iwf.org.uk/ke", "report.iwf.org.uk/ke", "report.iwf.org.uk/ke")],
      [("<strong>ICMEC</strong> — International Centre for Missing and Exploited Children",
        "<strong>ICMEC</strong> — Kituo cha Kimataifa cha Watoto Waliopotea na Kunyonywa",
        "<strong>ICMEC</strong> — International Centre for Missing and Exploited Children"),
       ("International referral", "Rufaa ya kimataifa", "International referral")],
     ]},
    {"type": "warn", "title": ("⚠️ Report the post, and report the person", "⚠️ Ripoti chapisho, na ripoti mtu", "⚠️ Report post, na report msee"), "text": (
     " Every platform has its own reporting button — use it, because it is fastest. But a platform report is not a referral. If a child is being targeted, that also goes to <strong>116</strong> or <strong>0800 722 203</strong>, and to your supervising adult — exactly as in Module 12. Blocking someone protects one child; reporting them protects the next one.",
     " Kila jukwaa lina kitufe chake cha kuripoti — kitumie, kwa sababu ni cha haraka zaidi. Lakini ripoti ya jukwaa si rufaa. Mtoto akilengwa, hilo pia huenda <strong>116</strong> au <strong>0800 722 203</strong>, na kwa mtu mzima anayekusimamia — kama ilivyo Moduli 12. Kumzuia mtu humlinda mtoto mmoja; kumripoti humlinda anayefuata.",
     " Kila platform ina reporting button yake — itumie, kwa sababu ni fastest. Lakini platform report si referral. Mtoto aki-targetiwa, hiyo pia inaenda <strong>116</strong> ama <strong>0800 722 203</strong>, na kwa msimamizi wako — exactly kama Module 12. Ku-block msee ina-protect mtoto mmoja; kum-report ina-protect anayefuata.")},
    {"type": "facilitator", "minutes": 10, "text": (
     "Have everyone save 116 and 0800 722 203 into their phones now, in the session, before they leave. Then have them find the report button inside whichever app they use most. A number nobody has saved and a button nobody has found are not reporting mechanisms — they are slides.",
     "Waache wote wahifadhi 116 na 0800 722 203 kwenye simu zao sasa, kipindini, kabla hawajaondoka. Kisha waache watafute kitufe cha kuripoti ndani ya programu wanayoitumia zaidi. Nambari ambayo hakuna aliyeihifadhi na kitufe ambacho hakuna aliyekipata si njia za kuripoti — ni slaidi.",
     "Wacha wote wa-save 116 na 0800 722 203 kwa phones zao saa hii, kwa session, kabla waondoke. Kisha wacha watafute report button ndani ya app wanayoitumia zaidi. Number ambayo hakuna msee ame-save na button ambayo hakuna msee ameipata si reporting mechanisms — ni slides.")},
   ]},

  {"icon": "🎭",
   "head": ("Practice — What Would You Do?", "Mazoezi — Ungefanya Nini?", "Practice — Ungefanya Nini?"),
   "blocks": [
    {"type": "p", "text": ("Choose an answer and see what follows.", "Chagua jibu na uone kinachofuata.", "Chagua answer uone kinachofollow.")},
    {"type": "scenario",
     "context": (
      "A 14-year-old girl tells you a man she met on social media has been messaging her for weeks. He is kind, says he understands her, and now wants to meet at a mall on Saturday. She has told nobody.",
      "Msichana wa miaka 14 anakuambia mwanamume aliyemkuta mtandaoni amekuwa akimtumia ujumbe kwa wiki. Ni mkarimu, anasema anamwelewa, na sasa anataka wakutane katika duka kubwa Jumamosi. Hajamwambia mtu.",
      "Dem wa miaka 14 anakuambia mse aliyemkuta kwa social media amekuwa aki-message kwa wiki. Ni mkarimu, anasema anamwelewa, na saa hii anataka wakutane mall Saturday. Hajamwambia msee."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Tell her to block him and say nothing more about it",
                "Mwambie amzuie na asiseme lolote zaidi kuhusu",
                "Mwambie am-block na asiseme kitu zaidi kuhusu"),
       "outcome": ("Blocking protects her from that account. It does nothing about the person, who moves to the next child that afternoon — and grooming patterns like this are precisely what the reporting mechanisms exist for. Module 12's warning signs are all present: gifts of attention, isolation, secrecy, and a request to meet alone.",
                   "Kumzuia kunamlinda dhidi ya akaunti hiyo. Hakufanyi lolote kuhusu mtu, anayehamia kwa mtoto anayefuata alasiri hiyo — na mifumo ya kutongoza kama hii ndiyo hasa njia za kuripoti zilizopo. Dalili za onyo za Moduli 12 zote zipo: zawadi ya umakini, kutengwa, siri, na ombi la kukutana peke yao.",
                   "Ku-block kunamlinda dhidi ya hiyo account. Haifanyi kitu kuhusu msee, anayehamia kwa mtoto anayefuata afternoon hiyo — na grooming patterns kama hii ndio hasa reporting mechanisms ziko. Warning signs za Module 12 zote ziko: gifts za attention, isolation, secrecy, na request ya kukutana peke yao.")},
      {"kind": "good",
       "text": ("Recognise the grooming pattern, escalate to your supervising adult today, and report it",
                "Tambua mchoro wa kutongoza, peleka kwa msimamizi wako leo, na uripoti",
                "Recognise grooming pattern, escalate kwa msimamizi wako leo, na u-report"),
       "outcome": ("You said: 'You haven't done anything wrong. But everything you've just described is on the warning list we learned — someone older, being very kind, wanting to be alone with you, and asking you to keep it quiet. This one I can't keep to myself.' You reported to 116 and told the school. She never met him. ✅",
                   "Ulisema: 'Hukufanya kosa lolote. Lakini kila ulichoeleza kiko kwenye orodha ya onyo tuliyojifunza — mtu mkubwa, akiwa mkarimu sana, akitaka kuwa nawe peke yenu, na akikuomba unyamaze. Hii siwezi kuiweka kwangu.' Uliripoti 116 na ukaiambia shule. Hakukutana naye kamwe. ✅",
                   "Ulisema: 'Haujafanya kosa lolote. Lakini kila ulichoi-describe kiko kwa warning list tuliyojifunza — msee mkubwa, akiwa mkarimu sana, akitaka kuwa na wewe peke yenu, na akikuomba unyamaze. Hii siwezi kui-keep kwangu.' Uli-report 116 na ukaiambia shule. Hakukutana naye kamwe. ✅")},
     ]},
    {"type": "scenario",
     "context": (
      "A message spreads through your school's WhatsApp groups claiming a certain herbal mixture cures HIV. Several peers are sharing it.",
      "Ujumbe unaenea katika makundi ya WhatsApp ya shule yako ukidai mchanganyiko fulani wa mitishamba huponya VVU. Wenzako kadhaa wanausambaza.",
      "Message inaspread kwa WhatsApp groups za shule yako ikidai mixture fulani ya herbs ina-cure HIV. Wasee kadhaa wanai-share."),
     "question": ("What do you do?", "Unafanya nini?", "Unafanya nini?"),
     "choices": [
      {"kind": "bad",
       "text": ("Post a message in the group telling everyone it is false and to stop sharing",
                "Chapisha ujumbe kundini ukiwaambia wote ni uongo na waache kusambaza",
                "Post message kwa group ukiwaambia wote ni uongo na waache ku-share"),
       "outcome": ("A flat contradiction in a group chat usually produces argument rather than correction, and the original message keeps travelling. Worse, it does nothing for the person who has already stopped their ARVs because of it — and that is the actual harm here.",
                   "Kupinga moja kwa moja katika gumzo la kundi kwa kawaida huzua ubishi badala ya kusahihisha, na ujumbe wa awali huendelea kusafiri. Baya zaidi, hakumfanyii lolote aliyeacha ARV zake kwa sababu yake — na hilo ndilo dhara halisi hapa.",
                   "Flat contradiction kwa group chat kwa kawaida ina-produce argument badala ya correction, na original message inaendelea kusafiri. Worse, haifanyi kitu kwa msee aliye-stop ARVs zake kwa sababu yake — na hiyo ndio actual harm hapa.")},
      {"kind": "good",
       "text": ("Correct it with a credible source, and check quietly whether anyone has stopped treatment because of it",
                "Isahihishe kwa chanzo kinachoaminika, na uangalie kwa utulivu kama kuna aliyeacha matibabu kwa sababu yake",
                "I-correct na credible source, na u-check kwa utulivu kama kuna msee aliye-stop treatment kwa sababu yake"),
       "outcome": ("You shared the facility's own information in the group without attacking anyone, then messaged two friends privately. One had genuinely been thinking of stopping his ARVs. That private conversation was the whole point — the group post was never where the harm was. ✅",
                   "Ulishiriki taarifa za kituo chenyewe kundini bila kumshambulia yeyote, kisha ukawatumia marafiki wawili ujumbe faraghani. Mmoja alikuwa kweli anafikiria kuacha ARV zake. Mazungumzo hayo ya faragha ndiyo yalikuwa lengo lote — chapisho la kundi halikuwa mahali dhara lilipokuwa. ✅",
                   "Uli-share info za facility yenyewe kwa group bila ku-attack msee, kisha uka-message friends wawili privately. Mmoja alikuwa kweli anafikiria ku-stop ARVs zake. Hiyo private conversation ndio ilikuwa point yote — group post haikuwa mahali harm ilipokuwa. ✅")},
     ]},
   ]},

  {"icon": "🔑",
   "head": ("Key Messages", "Ujumbe Muhimu", "Key Messages"),
   "blocks": [
    {"type": "list", "items": [
     ("Social behaviour change enables young people to make healthy choices.",
      "Mabadiliko ya tabia za kijamii huwawezesha vijana kufanya maamuzi bora ya afya.",
      "Social behaviour change ina-enable vijana ku-make healthy choices."),
     ("Advocacy empowers young people to speak up about their health needs and influence policy.",
      "Utetezi huwawezesha vijana kusemea mahitaji yao ya afya na kuathiri sera.",
      "Advocacy ina-empower vijana kusemea health needs zao na ku-influence policy."),
     ("Digital literacy is a must-have skill for navigating online life.",
      "Ujuzi wa kidijitali ni stadi ya lazima kwa kuvinjari maisha ya mtandaoni.",
      "Digital literacy ni must-have skill ya ku-navigate online life."),
     ("Digital platforms can help or harm, depending on how they are used.",
      "Majukwaa ya kidijitali yanaweza kusaidia au kudhuru, kutegemea yanavyotumika.",
      "Digital platforms zinaweza kusaidia ama kudhuru, kutegemea zinavyotumika."),
     ("You can report online abuse — child helpline <strong>116</strong>, DCI Fichua <strong>0800 722 203</strong>, or a trusted platform. Speak up and stay safe.",
      "Unaweza kuripoti unyanyasaji mtandaoni — simu ya watoto <strong>116</strong>, DCI Fichua <strong>0800 722 203</strong>, au jukwaa linaloaminika. Sema na ubaki salama.",
      "Unaweza ku-report online abuse — child helpline <strong>116</strong>, DCI Fichua <strong>0800 722 203</strong>, ama trusted platform. Speak up na stay safe."),
    ]},
    {"type": "sheng", "label": "The Last Word", "text": (
     "Umemaliza moduli kumi na tisa. Ulianza kama mtu anayejifunza. Unamaliza kama mtu ambaye wengine watamjia. Hicho ndicho kizingiti cha nane — na tayari umekipanda.",
     "Umemaliza moduli kumi na tisa. Ulianza kama mtu anayejifunza. Unamaliza kama mtu ambaye wengine watamjia. Hicho ndicho kizingiti cha nane — na tayari umekipanda.",
     "Umemaliza modules kumi na tisa. Ulianza kama msee anayejifunza. Unamaliza kama msee ambaye wengine watam-approach. Hiyo ndio stage ya nane — na tayari umei-climb.")},
   ]},
 ],

 "quiz": [
  {"q": "What is digital literacy?",
   "options": ["Owning a smartphone",
               "The ability to find, understand and create information using digital tools, smartly and carefully",
               "Knowing how to code",
               "Having many social media followers"],
   "answer": "B",
   "explain": "It is a skill, not a warning — which is why the curriculum teaches benefits and risks together."},

  {"q": "What defines cyberbullying?",
   "options": ["Any disagreement online",
               "Using digital devices to hurt, threaten, embarrass or target another person on purpose",
               "Receiving too many messages",
               "Posting about yourself"],
   "answer": "B",
   "explain": "The word that matters is 'on purpose' — intent is what separates it from an argument."},

  {"q": "Which number is DCI Fichua, for reporting offensive online content?",
   "options": ["116", "1199", "0800 722 203", "1192"],
   "answer": "C",
   "explain": "116 is the children's helpline, and both are worth saving into a phone during the session itself."},

  {"q": "Which are online safety rules from the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Do not give personal information to people you do not know",
               "Never meet an online contact without a parent or guardian's permission",
               "Do not open files from untrusted sources",
               "Verify information before believing or forwarding it",
               "Accept every friend request to build your network"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Online friends are still strangers — that is stated explicitly in the curriculum."},

  {"q": "A 14-year-old is being messaged by an older man who is very kind, wants to meet alone, and asks her to keep it quiet. What is this?",
   "options": ["A normal friendship",
               "A grooming pattern — every Module 12 warning sign is present",
               "Cyberbullying",
               "Nothing to act on until they meet"],
   "answer": "B",
   "explain": "Gifts of attention, isolation, secrecy and a request to meet alone. This escalates the same day."},

  {"q": "Why is blocking someone not enough in that situation?",
   "options": ["Blocking does not work technically",
               "It protects one child from that account, but the person simply moves to the next child",
               "Blocking is against the rules",
               "It is enough"],
   "answer": "B",
   "explain": "Blocking protects one child; reporting protects the next one."},

  {"q": "Which are risks of digital platforms named in the curriculum? [SELECT ALL THAT APPLY]",
   "type": "msq",
   "options": ["Exposure to cyberbullying",
               "Unrealistic views of other people's lives",
               "Erroneous and unverified information",
               "A platform for cons and predators",
               "Improved face-to-face social skills"],
   "answer": ["A", "B", "C", "D"],
   "explain": "Excessive use can in fact hamper the healthy development of social skills — which is why face-to-face contact is encouraged alongside."},

  {"q": "A false claim that herbs cure HIV spreads in a school WhatsApp group. What is the best response?",
   "options": ["Post a flat contradiction in the group",
               "Correct it with a credible source, and check quietly whether anyone has stopped treatment because of it",
               "Leave the group",
               "Ignore it — nobody believes those"],
   "answer": "B",
   "explain": "The group post was never where the harm was. Someone who has stopped their ARVs because of it is."},

  {"q": "What does the curriculum say about age restrictions on platforms?",
   "options": ["They are optional guidance",
               "Adhere to them — they exist to keep you safe",
               "They only apply outside Kenya",
               "They are set by parents"],
   "answer": "B",
   "explain": "Alongside checking privacy settings, keeping passwords safe and never sharing personal details."},

  {"q": "What is KE-CIRT?",
   "options": ["A children's charity",
               "The Kenya Computer Incident Response Team, at the Communications Authority",
               "A social media platform",
               "A police unit"],
   "answer": "B",
   "explain": "Reachable at ke-cirt.go.ke, alongside DCI Fichua, the 116 helpline, IWF and ICMEC."},
 ],
}
